function dnom = computeNominalAngularCoverage( ...
    direction_count, solid_angle_sr, options)
%COMPUTENOMINALANGULARCOVERAGE Compute normalized nominal angular richness.
%
%   Dnom = (N / Nmax) * (Omega / OmegaMax)
%
% where N is the prescribed number of directions and Omega is the
% prescribed angular support. With OmegaMax = 4*pi, Dnom lies in [0,1]
% when N <= Nmax and Omega <= 4*pi.

arguments
    direction_count
    solid_angle_sr

    options.MaximumDirectionCount (1,1) double = 128
    options.MaximumSolidAngleSr (1,1) double = 4*pi
end

validate_options(options);

direction_count = double(direction_count);
solid_angle_sr = double(solid_angle_sr);

if ~isequal(size(direction_count), size(solid_angle_sr))
    error("reqml:NominalAngularCoverageSizeMismatch", ...
        "Direction count and solid angle must have the same size.");
end

tolerance = 1e-10;

valid = ...
    isfinite(direction_count) & ...
    isfinite(solid_angle_sr) & ...
    direction_count >= 1 & ...
    direction_count <= ...
        options.MaximumDirectionCount + tolerance & ...
    abs(direction_count - round(direction_count)) <= tolerance & ...
    solid_angle_sr >= -tolerance & ...
    solid_angle_sr <= ...
        options.MaximumSolidAngleSr + tolerance;

dnom = NaN(size(direction_count));

bounded_direction_count = min( ...
    options.MaximumDirectionCount, ...
    max(1, round(direction_count)));

bounded_solid_angle_sr = min( ...
    options.MaximumSolidAngleSr, ...
    max(0, solid_angle_sr));

dnom(valid) = ...
    (bounded_direction_count(valid) ./ ...
        options.MaximumDirectionCount) .* ...
    (bounded_solid_angle_sr(valid) ./ ...
        options.MaximumSolidAngleSr);

% Protect against numerical roundoff at the endpoints.
dnom(valid) = min(1, max(0, dnom(valid)));

end


function validate_options(options)

if options.MaximumDirectionCount < 1 || ...
        options.MaximumDirectionCount ~= ...
            fix(options.MaximumDirectionCount)

    error("reqml:InvalidMaximumDirectionCount", ...
        "MaximumDirectionCount must be a positive integer.");
end

if ~isfinite(options.MaximumSolidAngleSr) || ...
        options.MaximumSolidAngleSr <= 0 || ...
        options.MaximumSolidAngleSr > 4*pi

    error("reqml:InvalidMaximumNominalSolidAngle", ...
        ["MaximumSolidAngleSr must be finite, positive, " ...
         "and no greater than 4*pi."]);
end

end
