function report = computePatchCoverage(examples, options)
%COMPUTEPATCHCOVERAGE Compute patch-level adaptive campaign coverage.
%
% The primary coverage plane is:
%
%   patch purity x measured field diffusivity
%
% Local SWS and frequency are tracked as diversity requirements within
% each primary coverage cell.
%
% Usage:
%
%   report = reqml.coverage.computePatchCoverage( ...
%       examples, ...
%       PurityEdges=[0.5 0.6 0.7 0.8 0.9 0.98 1.0], ...
%       DiffusivityEdges=0:0.2:1, ...
%       SwsEdges=1.5:0.5:4.0, ...
%       FrequencyEdges=[199 250 350 450 550 601]);

arguments
    examples table

    options.PurityVariable (1,1) string = ...
        "truth_material_purity"

    options.DiffusivityVariable (1,1) string = ...
        "campaign_angular_entropy"

    options.SwsVariable (1,1) string = ...
        "truth_cs_center_m_s"

    options.FrequencyVariable (1,1) string = ...
        "campaign_frequency_hz"

    options.RunVariable (1,1) string = ...
        "campaign_run_id"

    options.ConditionVariable (1,1) string = ...
        "campaign_design_id"

    options.GeometrySeedVariable (1,1) string = ""

    options.PurityEdges (1,:) double
    options.DiffusivityEdges (1,:) double
    options.SwsEdges (1,:) double
    options.FrequencyEdges (1,:) double

    options.MinimumExamples (1,1) double = 500
    options.MinimumIndependentRuns (1,1) double = 5
    options.MinimumSwsBins (1,1) double = 3
    options.MinimumFrequencyBins (1,1) double = 3
    options.MinimumIndependentConditions (1,1) double = 3
    options.MinimumGeometrySeeds (1,1) double = 0
end

assigned = reqml.coverage.assignCoverageBins( ...
    examples, ...
    PurityVariable=options.PurityVariable, ...
    DiffusivityVariable=options.DiffusivityVariable, ...
    SwsVariable=options.SwsVariable, ...
    FrequencyVariable=options.FrequencyVariable, ...
    PurityEdges=options.PurityEdges, ...
    DiffusivityEdges=options.DiffusivityEdges, ...
    SwsEdges=options.SwsEdges, ...
    FrequencyEdges=options.FrequencyEdges);

summary_arguments = {
    "RunVariable", options.RunVariable
    };

if strlength(options.ConditionVariable) > 0
    summary_arguments(end + 1, :) = { ...
        "ConditionVariable", ...
        options.ConditionVariable};
end

if strlength(options.GeometrySeedVariable) > 0
    summary_arguments(end + 1, :) = { ...
        "GeometrySeedVariable", ...
        options.GeometrySeedVariable};
end

summary_arguments = reshape(summary_arguments.', 1, []);

observed_summary = reqml.coverage.summarizeCoverage( ...
    assigned, ...
    summary_arguments{:});

summary = reqml.coverage.completeCoverageGrid( ...
    observed_summary, ...
    options.PurityEdges, ...
    options.DiffusivityEdges);

deficits = reqml.coverage.findCoverageDeficits( ...
    summary, ...
    MinimumExamples=options.MinimumExamples, ...
    MinimumIndependentRuns= ...
        options.MinimumIndependentRuns, ...
    MinimumSwsBins=options.MinimumSwsBins, ...
    MinimumFrequencyBins= ...
        options.MinimumFrequencyBins, ...
    MinimumIndependentConditions= ...
        options.MinimumIndependentConditions, ...
    MinimumGeometrySeeds= ...
        options.MinimumGeometrySeeds);

report = struct();

report.schema_name = ...
    "reqml_patch_coverage_report";

report.schema_version = "1.0";

report.example_count = height(examples);
report.valid_coverage_example_count = ...
    nnz(assigned.coverage_valid);

report.invalid_coverage_example_count = ...
    height(examples) - ...
    report.valid_coverage_example_count;

report.observed_coverage_cell_count = ...
    height(observed_summary);

report.coverage_cell_count = height(summary);
report.deficient_cell_count = height(deficits);

report.coverage_complete = isempty(deficits);

report.assigned_examples = assigned;
report.observed_summary = observed_summary;
report.summary = summary;
report.deficits = deficits;

report.config = struct();

report.config.purity_variable = ...
    options.PurityVariable;

report.config.diffusivity_variable = ...
    options.DiffusivityVariable;

report.config.sws_variable = ...
    options.SwsVariable;

report.config.frequency_variable = ...
    options.FrequencyVariable;

report.config.run_variable = ...
    options.RunVariable;

report.config.condition_variable = ...
    options.ConditionVariable;

report.config.geometry_seed_variable = ...
    options.GeometrySeedVariable;

report.config.purity_edges = ...
    options.PurityEdges;

report.config.diffusivity_edges = ...
    options.DiffusivityEdges;

report.config.sws_edges = ...
    options.SwsEdges;

report.config.frequency_edges = ...
    options.FrequencyEdges;

report.requirements = struct();

report.requirements.minimum_examples = ...
    options.MinimumExamples;

report.requirements.minimum_independent_runs = ...
    options.MinimumIndependentRuns;

report.requirements.minimum_sws_bins = ...
    options.MinimumSwsBins;

report.requirements.minimum_frequency_bins = ...
    options.MinimumFrequencyBins;

report.requirements.minimum_independent_conditions = ...
    options.MinimumIndependentConditions;

report.requirements.minimum_geometry_seeds = ...
    options.MinimumGeometrySeeds;

end
