function deficits = findCoverageDeficits(summary, options)
%FINDCOVERAGEDEFICITS Identify incomplete 4-D coverage cells.
%
% A cell is defined by:
%
%   SWS bin
%   frequency bin
%   purity bin
%   diffusivity / nominal-angular-coverage bin
%
% Since SWS and frequency are explicit cell dimensions, internal SWS-bin
% and frequency-bin diversity requirements no longer apply.

arguments
    summary table

    options.MinimumExamples (1,1) double = 500
    options.MinimumIndependentRuns (1,1) double = 5

    options.MinimumIndependentConditions ...
        (1,1) double = 0

    options.MinimumGeometrySeeds ...
        (1,1) double = 0
end

validate_nonnegative_integer( ...
    options.MinimumExamples, ...
    "MinimumExamples");

validate_nonnegative_integer( ...
    options.MinimumIndependentRuns, ...
    "MinimumIndependentRuns");

validate_nonnegative_integer( ...
    options.MinimumIndependentConditions, ...
    "MinimumIndependentConditions");

validate_nonnegative_integer( ...
    options.MinimumGeometrySeeds, ...
    "MinimumGeometrySeeds");

required = [
    "sws_bin"
    "frequency_bin"
    "purity_bin"
    "diffusivity_bin"
    "cell_key"
    "sws_label"
    "frequency_label"
    "purity_label"
    "diffusivity_label"
    "example_count"
    "independent_run_count"
    ];

validate_variables(summary, required);

deficits = summary;

deficits.required_example_count = ...
    repmat( ...
        options.MinimumExamples, ...
        height(summary), ...
        1);

deficits.required_independent_run_count = ...
    repmat( ...
        options.MinimumIndependentRuns, ...
        height(summary), ...
        1);

deficits.example_deficit = max( ...
    options.MinimumExamples - ...
        summary.example_count, ...
    0);

deficits.independent_run_deficit = max( ...
    options.MinimumIndependentRuns - ...
        summary.independent_run_count, ...
    0);

deficits.independent_condition_deficit = ...
    zeros(height(summary), 1);

if options.MinimumIndependentConditions > 0
    require_optional_variable( ...
        summary, ...
        "independent_condition_count", ...
        "MinimumIndependentConditions");

    deficits.independent_condition_deficit = max( ...
        options.MinimumIndependentConditions - ...
            summary.independent_condition_count, ...
        0);
end

deficits.geometry_seed_deficit = ...
    zeros(height(summary), 1);

if options.MinimumGeometrySeeds > 0
    require_optional_variable( ...
        summary, ...
        "geometry_seed_count", ...
        "MinimumGeometrySeeds");

    deficits.geometry_seed_deficit = max( ...
        options.MinimumGeometrySeeds - ...
            summary.geometry_seed_count, ...
        0);
end

% Legacy columns retained during migration. They are always zero because
% SWS and frequency are now explicit coverage-cell dimensions.
deficits.required_sws_bin_count = ...
    ones(height(summary), 1);

deficits.required_frequency_bin_count = ...
    ones(height(summary), 1);

deficits.sws_bin_deficit = ...
    zeros(height(summary), 1);

deficits.frequency_bin_deficit = ...
    zeros(height(summary), 1);

deficits.coverage_complete = ...
    deficits.example_deficit == 0 & ...
    deficits.independent_run_deficit == 0 & ...
    deficits.independent_condition_deficit == 0 & ...
    deficits.geometry_seed_deficit == 0;

deficits.deficit_score = ...
    normalized_deficit( ...
        deficits.example_deficit, ...
        options.MinimumExamples) + ...
    normalized_deficit( ...
        deficits.independent_run_deficit, ...
        options.MinimumIndependentRuns) + ...
    normalized_deficit( ...
        deficits.independent_condition_deficit, ...
        options.MinimumIndependentConditions) + ...
    normalized_deficit( ...
        deficits.geometry_seed_deficit, ...
        options.MinimumGeometrySeeds);

deficits = deficits( ...
    ~deficits.coverage_complete, ...
    :);

if ~isempty(deficits)
    deficits = sortrows( ...
        deficits, ...
        [ ...
            "deficit_score"
            "sws_bin"
            "frequency_bin"
            "purity_bin"
            "diffusivity_bin"
        ], ...
        [ ...
            "descend"
            "ascend"
            "ascend"
            "ascend"
            "ascend"
        ]);
end

end


function values = normalized_deficit( ...
        deficit, requirement)

if requirement <= 0
    values = zeros(size(deficit));
else
    values = ...
        double(deficit) ./ ...
        double(requirement);
end

end


function validate_variables( ...
        table_value, required)

available = string( ...
    table_value.Properties.VariableNames);

for variable = required.'
    if ~ismember(variable, available)
        error( ...
            "reqml:MissingCoverageSummaryVariable", ...
            "Coverage summary is missing variable '%s'.", ...
            variable);
    end
end

end


function require_optional_variable( ...
        summary, variable, option_name)

available = string( ...
    summary.Properties.VariableNames);

if ~ismember(variable, available)
    error( ...
        "reqml:MissingCoverageDiversityVariable", ...
        "Coverage option '%s' requires summary variable '%s'.", ...
        option_name, ...
        variable);
end

end


function validate_nonnegative_integer( ...
        value, name)

if ~isfinite(value) || ...
        value < 0 || ...
        value ~= fix(value)

    error( ...
        "reqml:InvalidCoverageRequirement", ...
        "%s must be a nonnegative integer.", ...
        name);
end

end
