function summary = summarizeCoverage(assigned, options)
%SUMMARIZECOVERAGE Summarize coverage over the full 4-D cell grid.
%
% A coverage cell is defined by:
%
%   SWS bin
%   frequency bin
%   purity bin
%   nominal-angular-coverage / diffusivity bin
%
% Patch counts are reported together with independent-run and optional
% independent-condition and geometry-seed counts. Patch count alone must
% not be interpreted as independent coverage.

arguments
    assigned table

    options.RunVariable (1,1) string = ...
        "campaign_run_id"

    options.ConditionVariable (1,1) string = ""

    options.GeometrySeedVariable (1,1) string = ""
end

required = [
    "coverage_sws_bin"
    "coverage_frequency_bin"
    "coverage_purity_bin"
    "coverage_diffusivity_bin"
    "coverage_sws_label"
    "coverage_frequency_label"
    "coverage_purity_label"
    "coverage_diffusivity_label"
    "coverage_valid"
    options.RunVariable
    ];

validate_required_variables(assigned, required);

valid = logical(assigned.coverage_valid);
working = assigned(valid, :);

if isempty(working)
    summary = empty_summary();
    return
end

[group_index, ...
    sws_bin, ...
    frequency_bin, ...
    purity_bin, ...
    diffusivity_bin] = findgroups( ...
        working.coverage_sws_bin, ...
        working.coverage_frequency_bin, ...
        working.coverage_purity_bin, ...
        working.coverage_diffusivity_bin);

example_count = splitapply( ...
    @numel, ...
    working.coverage_purity_bin, ...
    group_index);

independent_run_count = splitapply( ...
    @count_unique_nonmissing, ...
    working.(options.RunVariable), ...
    group_index);

sws_label = splitapply( ...
    @first_string, ...
    working.coverage_sws_label, ...
    group_index);

frequency_label = splitapply( ...
    @first_string, ...
    working.coverage_frequency_label, ...
    group_index);

purity_label = splitapply( ...
    @first_string, ...
    working.coverage_purity_label, ...
    group_index);

diffusivity_label = splitapply( ...
    @first_string, ...
    working.coverage_diffusivity_label, ...
    group_index);

cell_key = compose( ...
    "s%02d_f%02d_p%02d_d%02d", ...
    sws_bin, ...
    frequency_bin, ...
    purity_bin, ...
    diffusivity_bin);

summary = table( ...
    sws_bin, ...
    frequency_bin, ...
    purity_bin, ...
    diffusivity_bin, ...
    cell_key, ...
    sws_label, ...
    frequency_label, ...
    purity_label, ...
    diffusivity_label, ...
    example_count, ...
    independent_run_count);

if strlength(options.ConditionVariable) > 0
    validate_required_variables( ...
        working, ...
        options.ConditionVariable);

    summary.independent_condition_count = splitapply( ...
        @count_unique_nonmissing, ...
        working.(options.ConditionVariable), ...
        group_index);
end

if strlength(options.GeometrySeedVariable) > 0
    validate_required_variables( ...
        working, ...
        options.GeometrySeedVariable);

    summary.geometry_seed_count = splitapply( ...
        @count_unique_nonmissing, ...
        working.(options.GeometrySeedVariable), ...
        group_index);
end

summary = sortrows( ...
    summary, ...
    [ ...
        "sws_bin"
        "frequency_bin"
        "purity_bin"
        "diffusivity_bin"
    ]);

end


function count = count_unique_nonmissing(values)

if isstring(values) || ...
        ischar(values) || ...
        iscellstr(values)

    values = string(values);

    values = values( ...
        ~ismissing(values) & ...
        strlength(values) > 0);
else
    values = double(values);
    values = values(isfinite(values));
end

count = numel(unique(values));

end


function value = first_string(values)

values = string(values);
value = values(1);

end


function validate_required_variables( ...
        table_value, variables)

available = string( ...
    table_value.Properties.VariableNames);

for variable = string(variables).'
    if strlength(variable) == 0
        continue
    end

    if ~ismember(variable, available)
        error( ...
            "reqml:MissingCoverageVariable", ...
            "Coverage table is missing variable '%s'.", ...
            variable);
    end
end

end


function summary = empty_summary()

variable_names = [ ...
    "sws_bin"
    "frequency_bin"
    "purity_bin"
    "diffusivity_bin"
    "cell_key"
    "sws_label"
    "frequency_label"
    "purity_label"
    "diffusivity_label"
    "example_count"
    "independent_run_count"
    ]';

summary = table( ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    VariableNames=variable_names);

end
