function summary = summarizeCoverage(assigned, options)
%SUMMARIZECOVERAGE Summarize patch coverage by purity and diffusivity.
%
% Patch counts are reported together with independent-run and diversity
% counts. Patch count alone must not be interpreted as independent coverage.

arguments
    assigned table

    options.RunVariable (1,1) string = ...
        "campaign_run_id"

    options.ConditionVariable (1,1) string = ""

    options.GeometrySeedVariable (1,1) string = ""
end

required = [
    "coverage_purity_bin"
    "coverage_diffusivity_bin"
    "coverage_sws_bin"
    "coverage_frequency_bin"
    "coverage_valid"
    options.RunVariable
    ];

validate_required_variables(assigned, required);

valid = logical(assigned.coverage_valid);

working = assigned(valid, :);

if isempty(working)
    summary = empty_summary();
    return
end

[group_index, purity_bin, diffusivity_bin] = findgroups( ...
    working.coverage_purity_bin, ...
    working.coverage_diffusivity_bin);

example_count = splitapply( ...
    @numel, ...
    working.coverage_purity_bin, ...
    group_index);

independent_run_count = splitapply( ...
    @count_unique_nonmissing, ...
    working.(options.RunVariable), ...
    group_index);

sws_bin_count = splitapply( ...
    @count_positive_unique, ...
    working.coverage_sws_bin, ...
    group_index);

frequency_bin_count = splitapply( ...
    @count_positive_unique, ...
    working.coverage_frequency_bin, ...
    group_index);

purity_label = splitapply( ...
    @first_string, ...
    working.coverage_purity_label, ...
    group_index);

diffusivity_label = splitapply( ...
    @first_string, ...
    working.coverage_diffusivity_label, ...
    group_index);

summary = table( ...
    purity_bin, ...
    diffusivity_bin, ...
    purity_label, ...
    diffusivity_label, ...
    example_count, ...
    independent_run_count, ...
    sws_bin_count, ...
    frequency_bin_count);

if strlength(options.ConditionVariable) > 0
    validate_required_variables( ...
        working, ...
        options.ConditionVariable);

    summary.independent_condition_count = splitapply( ...
        @count_unique_nonmissing, ...
        working.(options.ConditionVariable), ...
        group_index);
end

if strlength(options.GeometrySeedVariable) > 0
    validate_required_variables( ...
        working, ...
        options.GeometrySeedVariable);

    summary.geometry_seed_count = splitapply( ...
        @count_unique_nonmissing, ...
        working.(options.GeometrySeedVariable), ...
        group_index);
end

summary = sortrows( ...
    summary, ...
    ["purity_bin", "diffusivity_bin"]);

end


function count = count_unique_nonmissing(values)

if isstring(values) || ischar(values) || iscellstr(values)
    values = string(values);
    values = values(~ismissing(values) & strlength(values) > 0);
else
    values = values(isfinite(double(values)));
end

count = numel(unique(values));

end


function count = count_positive_unique(values)

values = double(values);
values = values(isfinite(values) & values > 0);

count = numel(unique(values));

end


function value = first_string(values)

values = string(values);
value = values(1);

end


function validate_required_variables(table_value, variables)

available = string(table_value.Properties.VariableNames);

for variable = string(variables).'
    if strlength(variable) == 0
        continue
    end

    if ~ismember(variable, available)
        error( ...
            "reqml:MissingCoverageVariable", ...
            "Coverage table is missing variable '%s'.", ...
            variable);
    end
end

end


function summary = empty_summary()

summary = table( ...
    zeros(0,1), ...
    zeros(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    VariableNames={ ...
        "purity_bin", ...
        "diffusivity_bin", ...
        "purity_label", ...
        "diffusivity_label", ...
        "example_count", ...
        "independent_run_count", ...
        "sws_bin_count", ...
        "frequency_bin_count"});
end
