function result = fit_oof_regression_model( ...
    X, target, split, folds, model_spec, options)
%FIT_OOF_REGRESSION_MODEL Fit grouped out-of-fold regression predictions.
%
% Training rows receive predictions from a model that excludes their CV
% fold. Validation and test rows receive predictions from the final model
% fitted using every valid training row.

arguments
    X double
    target (:,1) double
    split (1,1) struct
    folds (1,1) struct
    model_spec (1,1) struct

    options.ClipRange (1,2) double = [0, 1]
end

n = size(X, 1);

if numel(target) ~= n || ...
        numel(split.partition) ~= n || ...
        numel(folds.cv_fold) ~= n
    error("reqml:OofTrainingSizeMismatch", ...
        "Predictors, target, split, and folds must have equal row counts.");
end

fold_count = double(folds.fold_count);
cv_fold = double(folds.cv_fold(:));

oof_prediction = nan(n, 1);
fold_models = cell(fold_count, 1);
fold_summary_rows = cell(fold_count, 1);

for fold_index = 1:fold_count
    fold_validation_mask = ...
        split.train_mask & ...
        cv_fold == fold_index;

    fold_train_mask = ...
        split.train_mask & ...
        cv_fold ~= fold_index;

    if ~any(fold_validation_mask)
        error("reqml:EmptyOofFold", ...
            "Training fold %d contains no validation rows.", ...
            fold_index);
    end

    fold_spec = model_spec;
    fold_spec.id = compose( ...
        "%s_oof_fold_%02d", ...
        string(model_spec.id), ...
        fold_index);

    fold_spec.random_seed = ...
        double(model_spec.random_seed) + fold_index;

    fold_model = reqml.training.fit_regression_model( ...
        X, ...
        target, ...
        fold_train_mask, ...
        fold_spec);

    fold_prediction = ...
        reqml.training.predict_regression_model( ...
            fold_model, ...
            X(fold_validation_mask, :), ...
            ClipRange=options.ClipRange);

    oof_prediction(fold_validation_mask) = ...
        fold_prediction;

    fold_models{fold_index} = fold_model;

    fold_summary_rows{fold_index} = table( ...
        fold_index, ...
        nnz(fold_train_mask), ...
        nnz(fold_validation_mask), ...
        mean(abs( ...
            fold_prediction - ...
            target(fold_validation_mask)), ...
            "omitnan"), ...
        sqrt(mean(( ...
            fold_prediction - ...
            target(fold_validation_mask)).^2, ...
            "omitnan")), ...
        VariableNames=[ ...
            "cv_fold", ...
            "training_row_count", ...
            "validation_row_count", ...
            "mae", ...
            "rmse"]);
end

missing_oof = ...
    split.train_mask & ...
    ~isfinite(oof_prediction);

if any(missing_oof)
    error("reqml:MissingOofPrediction", ...
        "%d training rows did not receive OOF predictions.", ...
        nnz(missing_oof));
end

final_model = reqml.training.fit_regression_model( ...
    X, ...
    target, ...
    split.train_mask, ...
    model_spec);

final_prediction = ...
    reqml.training.predict_regression_model( ...
        final_model, ...
        X, ...
        ClipRange=options.ClipRange);

combined_prediction = final_prediction;
combined_prediction(split.train_mask) = ...
    oof_prediction(split.train_mask);

prediction_source = repmat("final_train_model", n, 1);
prediction_source(split.train_mask) = "out_of_fold";

result = struct();
result.schema_name = "reqml_oof_regression_result";
result.schema_version = "1.0";

result.model_id = string(model_spec.id);
result.fold_models = fold_models;
result.final_model = final_model;

result.oof_prediction = oof_prediction;
result.final_prediction = final_prediction;
result.combined_prediction = combined_prediction;
result.prediction_source = prediction_source;

result.fold_summary = vertcat(fold_summary_rows{:});

end
