function report = assess_req_readiness(data, options)
%ASSESS_REQ_READINESS Check whether a loaded 2D field supports REQ analysis.
%
% The operational window length is
%
%   Lwin = WindowWavelengths * CsGuessMPerS / frequency_hz
%
% The number of samples is conservative:
%
%   N = ceil(Lwin / spacing) + 1
%
% Usage:
%   data = reqml.integration.load_wavefield_sample(sample_file);
%   report = reqml.integration.assess_req_readiness(data);
%
% This logic belongs in REQ-ML because cs_guess, wavelength-scaled windows,
% and minimum sliding-window placements are estimator-specific choices.

arguments
    data (1,1) struct

    options.CsGuessMPerS (1,1) double = 3.0

    options.WindowWavelengths (1,1) double = 2.0

    options.MinimumPlacementsPerAxis (1,1) double = 5
end

validate_inputs(data, options);

wavefield = data.wavefield_zx;

Nz = size(wavefield, 1);
Nx = size(wavefield, 2);

dx_m = double(data.dx_m);
dz_m = double(data.dz_m);
frequency_hz = double(data.frequency_hz);

wavelength_guess_m = ...
    options.CsGuessMPerS / frequency_hz;

window_length_m = ...
    options.WindowWavelengths * ...
    wavelength_guess_m;

window_points_x = ...
    ceil(window_length_m / dx_m) + 1;

window_points_z = ...
    ceil(window_length_m / dz_m) + 1;

placements_x = max( ...
    Nx - window_points_x + 1, ...
    0);

placements_z = max( ...
    Nz - window_points_z + 1, ...
    0);

field_finite = all( ...
    isfinite(wavefield), ...
    "all");

field_energy = double(sum( ...
    abs(wavefield).^2, ...
    "all"));

field_nonzero = ...
    isfinite(field_energy) && ...
    field_energy > 0;

checks = repmat( ...
    empty_check(), ...
    0, 1);

add_check( ...
    "finite_wavefield", ...
    field_finite, ...
    double(field_finite), ...
    1, ...
    "The complex wavefield must contain only finite values.");

add_check( ...
    "nonzero_wavefield_energy", ...
    field_nonzero, ...
    field_energy, ...
    0, ...
    "The complex wavefield must contain nonzero energy.");

add_check( ...
    "x_window_fits", ...
    Nx >= window_points_x, ...
    Nx, ...
    window_points_x, ...
    "The REQ window must fit along x.");

add_check( ...
    "z_window_fits", ...
    Nz >= window_points_z, ...
    Nz, ...
    window_points_z, ...
    "The REQ window must fit along z.");

add_check( ...
    "minimum_x_placements", ...
    placements_x >= ...
        options.MinimumPlacementsPerAxis, ...
    placements_x, ...
    options.MinimumPlacementsPerAxis, ...
    "The field must support multiple REQ window positions along x.");

add_check( ...
    "minimum_z_placements", ...
    placements_z >= ...
        options.MinimumPlacementsPerAxis, ...
    placements_z, ...
    options.MinimumPlacementsPerAxis, ...
    "The field must support multiple REQ window positions along z.");

report = struct();

report.valid = all([checks.pass]);
report.checks = checks;

report.parameters = struct();
report.parameters.cs_guess_m_s = ...
    options.CsGuessMPerS;
report.parameters.window_wavelengths = ...
    options.WindowWavelengths;
report.parameters.minimum_placements_per_axis = ...
    options.MinimumPlacementsPerAxis;

report.frequency_hz = frequency_hz;
report.wavelength_guess_m = wavelength_guess_m;
report.window_length_m = window_length_m;

report.window_points_x = window_points_x;
report.window_points_z = window_points_z;

report.sample_points_x = Nx;
report.sample_points_z = Nz;

report.sample_span_x_m = ...
    max(Nx - 1, 0) * dx_m;

report.sample_span_z_m = ...
    max(Nz - 1, 0) * dz_m;

report.placements_x = placements_x;
report.placements_z = placements_z;
report.field_energy = field_energy;

report.summary = sprintf([ ...
    'REQ-ready=%d, sample=%dx%d, span x/z=%.3f/%.3f mm, ', ...
    'window=%.3f mm (%d x %d points), ', ...
    'placements x/z=%d/%d'], ...
    report.valid, ...
    Nz, ...
    Nx, ...
    1e3 * report.sample_span_x_m, ...
    1e3 * report.sample_span_z_m, ...
    1e3 * window_length_m, ...
    window_points_x, ...
    window_points_z, ...
    placements_x, ...
    placements_z);

    function add_check( ...
            name, pass, value, threshold, meaning)

        check = empty_check();

        check.name = string(name);
        check.pass = logical(pass);
        check.value = double(value);
        check.threshold = double(threshold);
        check.meaning = string(meaning);

        checks(end + 1, 1) = check;
    end

end

function validate_inputs(data, options)

required_fields = [
    "wavefield_zx"
    "dx_m"
    "dz_m"
    "frequency_hz"
];

for field_name = required_fields.'
    if ~isfield(data, field_name)
        error("reqml:InvalidReqReadinessInput", ...
            "Loaded sample data is missing field '%s'.", ...
            field_name);
    end
end

if ~isnumeric(data.wavefield_zx) || ...
        ~ismatrix(data.wavefield_zx) || ...
        isempty(data.wavefield_zx)
    error("reqml:InvalidReqReadinessInput", ...
        "wavefield_zx must be a nonempty numeric matrix.");
end

validate_positive_scalar(data.dx_m, "dx_m");
validate_positive_scalar(data.dz_m, "dz_m");
validate_positive_scalar(data.frequency_hz, "frequency_hz");

if options.CsGuessMPerS <= 0
    error("reqml:InvalidReqReadinessParameters", ...
        "CsGuessMPerS must be positive.");
end

if options.WindowWavelengths <= 0
    error("reqml:InvalidReqReadinessParameters", ...
        "WindowWavelengths must be positive.");
end

if options.MinimumPlacementsPerAxis < 1 || ...
        options.MinimumPlacementsPerAxis ~= ...
            fix(options.MinimumPlacementsPerAxis)

    error("reqml:InvalidReqReadinessParameters", ...
        "MinimumPlacementsPerAxis must be a positive integer.");
end

end

function validate_positive_scalar(value, name)

value = double(value);

if ~isscalar(value) || ...
        ~isfinite(value) || ...
        value <= 0
    error("reqml:InvalidReqReadinessInput", ...
        "%s must be a finite positive scalar.", ...
        name);
end

end

function check = empty_check()

check = struct( ...
    "name", "", ...
    "pass", false, ...
    "value", NaN, ...
    "threshold", NaN, ...
    "meaning", "");

end
