function audit = auditAdaptiveCoverage(loop_root, options)
%AUDITADAPTIVECOVERAGE Audit difficult adaptive coverage cells.
%
% Outputs:
%   coverage_cell_history.csv
%   coverage_cell_difficulty.csv
%   coverage_stagnation_summary.csv
%   coverage_difficulty_by_dimension.csv

arguments
    loop_root {mustBeTextScalar}

    options.OutputDirectory {mustBeTextScalar} = ""
    options.RecentWindow (1,1) double = 10
    options.SaveOutputs (1,1) logical = true
end

loop_root = string(loop_root);

history = ...
    reqml.analysis.buildCoverageCellHistory( ...
        loop_root);

final_iteration = max(history.iteration_index);

iteration_pattern = sprintf( ...
    "*_iteration_%03d", ...
    final_iteration);

listing = dir(fullfile( ...
    loop_root, ...
    iteration_pattern));

listing = listing([listing.isdir]);

if numel(listing) ~= 1
    error("reqml:AdaptiveAuditFinalIterationNotFound", ...
        "Could not uniquely locate final iteration %d.", ...
        final_iteration);
end

final_iteration_directory = fullfile( ...
    loop_root, ...
    listing(1).name);

deficits_file = fullfile( ...
    final_iteration_directory, ...
    "coverage_deficits.csv");

if ~isfile(deficits_file)
    error("reqml:AdaptiveAuditFinalDeficitsNotFound", ...
        "Final coverage deficits were not found: %s", ...
        deficits_file);
end

final_deficits = readtable( ...
    deficits_file, ...
    Delimiter=",", ...
    TextType="string");

difficulty = ...
    reqml.analysis.rankDifficultCoverageCells( ...
        history, ...
        final_deficits, ...
        RecentWindow=options.RecentWindow);

stagnation = difficulty( ...
    difficulty.example_count == 0 | ...
    difficulty.recent_example_gain == 0, ...
    :);

dimension_summary = build_dimension_summary( ...
    difficulty);

audit = struct();

audit.schema_name = ...
    "reqml_adaptive_coverage_audit";

audit.schema_version = "1.0";

audit.loop_root = loop_root;
audit.final_iteration = final_iteration;

audit.history = history;
audit.difficulty = difficulty;
audit.stagnation = stagnation;
audit.dimension_summary = dimension_summary;

audit.difficult_cell_count = height(difficulty);
audit.never_observed_cell_count = sum( ...
    difficulty.example_count == 0);

audit.stagnant_cell_count = sum( ...
    difficulty.recent_example_gain == 0);

audit.request_miss_cell_count = sum( ...
    difficulty.total_requested_conditions > 0 & ...
    difficulty.total_requested_cell_hits == 0);

if ~options.SaveOutputs
    audit.paths = struct();
    return
end

output_directory = string(options.OutputDirectory);

if strlength(output_directory) == 0
    output_directory = fullfile( ...
        loop_root, ...
        "analysis");
end

if ~isfolder(output_directory)
    [created, message] = mkdir(output_directory);

    if ~created
        error("reqml:AdaptiveAuditOutputCreateFailed", ...
            "Could not create audit directory '%s': %s", ...
            output_directory, ...
            message);
    end
end

history_file = fullfile( ...
    output_directory, ...
    "coverage_cell_history.csv");

difficulty_file = fullfile( ...
    output_directory, ...
    "coverage_cell_difficulty.csv");

stagnation_file = fullfile( ...
    output_directory, ...
    "coverage_stagnation_summary.csv");

dimension_file = fullfile( ...
    output_directory, ...
    "coverage_difficulty_by_dimension.csv");

writetable(history, history_file);
writetable(difficulty, difficulty_file);
writetable(stagnation, stagnation_file);
writetable(dimension_summary, dimension_file);

audit.paths = struct();
audit.paths.output_directory = output_directory;
audit.paths.history_csv = string(history_file);
audit.paths.difficulty_csv = string(difficulty_file);
audit.paths.stagnation_csv = string(stagnation_file);
audit.paths.dimension_summary_csv = string(dimension_file);

end


function summary = build_dimension_summary(difficulty)

parts = {
    summarize_dimension( ...
        difficulty, ...
        "sws", ...
        "sws_bin", ...
        "sws_label")
    summarize_dimension( ...
        difficulty, ...
        "frequency", ...
        "frequency_bin", ...
        "frequency_label")
    summarize_dimension( ...
        difficulty, ...
        "purity", ...
        "purity_bin", ...
        "purity_label")
    summarize_dimension( ...
        difficulty, ...
        "nominal_angular_coverage", ...
        "diffusivity_bin", ...
        "diffusivity_label")
    };

summary = vertcat(parts{:});

summary = sortrows( ...
    summary, ...
    ["dimension_name", "dimension_bin"]);

end


function summary = summarize_dimension( ...
        difficulty, dimension_name, bin_column, label_column)

[group_index, bins, labels] = findgroups( ...
    difficulty.(bin_column), ...
    difficulty.(label_column));

summary = table();

summary.dimension_name = repmat( ...
    string(dimension_name), ...
    numel(bins), ...
    1);

summary.dimension_bin = double(bins);
summary.dimension_label = string(labels);

summary.difficult_cell_count = splitapply( ...
    @numel, ...
    difficulty.cell_key, ...
    group_index);

summary.never_observed_cell_count = splitapply( ...
    @sum, ...
    difficulty.example_count == 0, ...
    group_index);

summary.stagnant_cell_count = splitapply( ...
    @sum, ...
    difficulty.recent_example_gain == 0, ...
    group_index);

summary.request_miss_cell_count = splitapply( ...
    @sum, ...
    difficulty.total_requested_conditions > 0 & ...
        difficulty.total_requested_cell_hits == 0, ...
    group_index);

summary.mean_difficulty_score = splitapply( ...
    @mean, ...
    difficulty.difficulty_score, ...
    group_index);

summary.median_difficulty_score = splitapply( ...
    @median, ...
    difficulty.difficulty_score, ...
    group_index);

summary.total_example_deficit = splitapply( ...
    @sum, ...
    difficulty.example_deficit, ...
    group_index);

summary.total_run_deficit = splitapply( ...
    @sum, ...
    difficulty.independent_run_deficit, ...
    group_index);

summary.total_condition_deficit = splitapply( ...
    @sum, ...
    difficulty.independent_condition_deficit, ...
    group_index);

end
