function audit = auditFinalAdaptiveCampaign(campaign_root, options)
%AUDITFINALADAPTIVECAMPAIGN Audit production packing and residual actions.

arguments
    campaign_root {mustBeTextScalar}
    options.MaximumIterations (1,1) double = 15
    options.OutputDirectory {mustBeTextScalar} = ""
    options.SaveOutputs (1,1) logical = true
end

campaign_root=string(campaign_root);
base=reqml.analysis.auditDeficitAwarePilot(campaign_root, ...
    MaximumIterations=options.MaximumIterations,SaveOutputs=false);
iterations=reqml.analysis.summarizeAdaptivePilotIterations(campaign_root, ...
    MaximumIterations=options.MaximumIterations);

actions=table(); domains=table(); independence=table();
additional_runs=zeros(height(iterations.iterations),1);
new_condition_runs=zeros(height(iterations.iterations),1);
closed_by_repeats=zeros(height(iterations.iterations),1);
normal_conditions=zeros(height(iterations.iterations),1);
expanded_conditions=zeros(height(iterations.iterations),1);

for row=1:height(iterations.iterations)
    index=double(iterations.iterations.iteration_index(row));
    directory=string(iterations.iterations.iteration_directory(row));
    batch=string(iterations.iterations.batch_directory(row));
    plan_file=fullfile(batch,"adaptive_batch_plan.json");
    state_file=fullfile(directory,"pre_iteration_deficit_state.csv");
    coverage_file=fullfile(directory,"coverage_summary.csv");
    report_file=fullfile(directory,"coverage_report.mat");
    require_files([plan_file,state_file,coverage_file,report_file],index);
    plan=jsondecode(fileread(plan_file));
    state=readtable(state_file,TextType="string");
    coverage=readtable(coverage_file,TextType="string");

    loaded=load(report_file,"coverage_report");
    report=loaded.coverage_report;
    condition_actions=condition_action_rows( ...
        plan,index,state,coverage,report.assigned_examples);
    actions=append_table(actions,condition_actions);
    condition_domains=condition_domain_rows(plan,index);
    domains=append_table(domains,condition_domains);

    if ~isempty(condition_actions)
        repeat=condition_actions.planned_new_condition_count==0;
        additional_runs(row)=sum( ...
            condition_actions.planned_realization_count(repeat));
        new_condition_runs(row)=sum( ...
            condition_actions.planned_realization_count(~repeat));
        closed_by_repeats(row)=sum(repeat & ...
            condition_actions.cell_became_complete);
    end
    if ~isempty(condition_domains)
        expanded_conditions(row)=sum(condition_domains.expansion_required);
        normal_conditions(row)=height(condition_domains)-expanded_conditions(row);
    end

    independence=[independence; independence_row(report,index)]; %#ok<AGROW>
end

center=base.center_selection_summary;
yield=center(:,["iteration_index","selected_center_count", ...
    "analytic_target_center_count","opportunistic_center_count", ...
    "opportunistic_helped_cell_count","mean_centers_per_run", ...
    "mean_opportunistic_centers_per_run"]);
yield.examples_per_run=iterations.progress.example_count ./ ...
    iterations.progress.accumulated_run_count;

progress=base.iteration_progress;
progress.completed_cell_count=500-progress.deficient_cell_count;
progress.examples_per_run=progress.example_count./progress.accumulated_run_count;
progress.additional_realization_run_count=additional_runs;
progress.new_condition_run_count=new_condition_runs;
progress.cells_closed_by_planned_repeats=closed_by_repeats;
progress.normal_domain_condition_count=normal_conditions;
progress.expanded_domain_condition_count=expanded_conditions;

difficulty=reqml.analysis.auditAdaptiveCoverage(campaign_root, ...
    RecentWindow=options.MaximumIterations,SaveOutputs=false);
audit=struct("schema_name","reqml_final_adaptive_campaign_audit", ...
    "schema_version","1.0","iteration_progress",progress, ...
    "center_yield",yield,"residual_deficit_actions",actions, ...
    "domain_expansion_summary",domains,"independence_audit",independence, ...
    "difficulty_by_dimension",difficulty.dimension_summary, ...
    "coverage_audit",difficulty);

if ~options.SaveOutputs, audit.paths=struct(); return, end
output=string(options.OutputDirectory);
if strlength(output)==0, output=fullfile(campaign_root,"analysis"); end
if ~isfolder(output), mkdir(output); end
paths=struct( ...
    "iteration_progress",fullfile(output,"final_iteration_progress.csv"), ...
    "center_yield",fullfile(output,"final_center_yield.csv"), ...
    "residual_actions",fullfile(output,"final_residual_deficit_actions.csv"), ...
    "domain_expansion",fullfile(output,"final_domain_expansion_summary.csv"), ...
    "independence",fullfile(output,"final_independence_audit.csv"), ...
    "difficulty",fullfile(output,"final_difficulty_by_dimension.csv"));
writetable(progress,paths.iteration_progress);
writetable(yield,paths.center_yield);
writetable(actions,paths.residual_actions);
writetable(domains,paths.domain_expansion);
writetable(independence,paths.independence);
writetable(difficulty.dimension_summary,paths.difficulty);
audit.paths=paths;
end


function rows=condition_action_rows(plan,index,state,coverage,assigned)
rows=table();
if ~isfield(plan,"physical_conditions") || isempty(plan.physical_conditions)
    return
end
c=plan.physical_conditions;
assigned_keys=assigned_cell_keys(assigned);
assigned_names=string(assigned.Properties.VariableNames);
for i=1:numel(c)
    q=c(i).requested_coverage;
    key=string(q.requested_cell_key);
    before=find(string(state.cell_key)==key,1);
    after=find(string(coverage.cell_key)==key,1);
    pre=[NaN NaN NaN false]; post=[NaN NaN NaN false];
    if ~isempty(before)
        pre=[double(state.example_count(before)), ...
            double(state.independent_run_count(before)), ...
            double(state.independent_condition_count(before)), ...
            logical(state.coverage_complete(before))];
    end
    if ~isempty(after)
        post=[double(coverage.example_count(after)), ...
            double(coverage.independent_run_count(after)), ...
            double(coverage.independent_condition_count(after)), ...
            false];
        if ~isempty(before)
            post(4)=post(1)>=double(state.required_example_count(before)) && ...
                post(2)>=double(state.required_independent_run_count(before)) && ...
                post(3)>=double( ...
                    state.required_independent_condition_count(before));
        end
    end
    condition_id=string(c(i).condition_id);
    realization_start=double(c(i).realization_start_index);
    realization_end=realization_start+double(c(i).realization_count)-1;
    contribution=false(height(assigned),1);
    if ~isempty(assigned) && all(ismember( ...
            ["campaign_run_id","campaign_condition_id", ...
             "campaign_realization_id"],assigned_names))
        contribution=assigned_keys==key & ...
            string(assigned.campaign_condition_id)==condition_id & ...
            double(assigned.campaign_realization_id)>=realization_start & ...
            double(assigned.campaign_realization_id)<=realization_end;
    end
    actual_examples=sum(contribution);
    actual_runs=numel(unique(string(assigned.campaign_run_id(contribution))));
    actual_conditions=double(actual_examples>0 && ...
        double(q.planned_new_condition_count)>0);
    current=table(index,condition_id,key, ...
        string(q.planned_action),double(q.residual_example_deficit), ...
        double(q.residual_independent_run_deficit), ...
        double(q.residual_independent_condition_deficit), ...
        double(q.planned_realization_count), ...
        double(q.planned_new_condition_count),string(q.reason_for_repeat), ...
        double(q.expected_example_contribution), ...
        double(q.expected_independent_run_contribution), ...
        double(q.expected_independent_condition_contribution), ...
        actual_examples,actual_runs,actual_conditions, ...
        ~pre(4) && post(4),VariableNames=["iteration_index","condition_id", ...
        "requested_cell_key","planned_action","residual_example_deficit", ...
        "residual_independent_run_deficit", ...
        "residual_independent_condition_deficit", ...
        "planned_realization_count","planned_new_condition_count", ...
        "reason_for_repeat","expected_example_contribution", ...
        "expected_independent_run_contribution", ...
        "expected_independent_condition_contribution", ...
        "actual_example_contribution","actual_independent_run_contribution", ...
        "actual_independent_condition_contribution","cell_became_complete"]);
    rows=append_table(rows,current);
end
end


function rows=condition_domain_rows(plan,index)
rows=table();
c=plan.physical_conditions;
for i=1:numel(c)
    g=c(i).geometry_control;
    rows=[rows;table(index,string(c(i).condition_id), ...
        double(g.selected_domain_size_m(:))',logical(g.expansion_required), ...
        double(g.resolved_window_size_pixels), ...
        double(g.maximum_geometrically_packable_center_count), ...
        string(g.packing_strategy),double(g.available_packing_span_pixels), ...
        VariableNames=["iteration_index","condition_id", ...
        "selected_domain_size_m","expansion_required", ...
        "resolved_window_size_pixels", ...
        "maximum_geometrically_packable_center_count", ...
        "packing_strategy","available_packing_span_pixels"])]; %#ok<AGROW>
end
end


function row=independence_row(report,index)
assigned=report.assigned_examples;
summary=report.summary;
run_mismatch=0; condition_mismatch=0;
if ~isempty(assigned)
    keys=compose("s%02d_f%02d_p%02d_d%02d", ...
        assigned.coverage_sws_bin,assigned.coverage_frequency_bin, ...
        assigned.coverage_purity_bin,assigned.coverage_diffusivity_bin);
    for i=1:height(summary)
        mask=keys==string(summary.cell_key(i));
        if ~any(mask), continue, end
        run_mismatch=run_mismatch+(numel(unique( ...
            string(assigned.campaign_run_id(mask))))~= ...
            double(summary.independent_run_count(i)));
        condition_mismatch=condition_mismatch+(numel(unique( ...
            string(assigned.campaign_condition_id(mask))))~= ...
            double(summary.independent_condition_count(i)));
    end
end
row=table(index,height(assigned),run_mismatch,condition_mismatch, ...
    run_mismatch==0 && condition_mismatch==0,VariableNames=[ ...
    "iteration_index","assigned_example_count", ...
    "independent_run_mismatch_cell_count", ...
    "independent_condition_mismatch_cell_count", ...
    "independence_accounting_valid"]);
end


function keys=assigned_cell_keys(assigned)
names=string(assigned.Properties.VariableNames);
required=["coverage_sws_bin","coverage_frequency_bin", ...
    "coverage_purity_bin","coverage_diffusivity_bin"];
if isempty(assigned) || ~all(ismember(required,names))
    keys=strings(height(assigned),1);
    return
end
keys=compose("s%02d_f%02d_p%02d_d%02d", ...
    assigned.coverage_sws_bin,assigned.coverage_frequency_bin, ...
    assigned.coverage_purity_bin,assigned.coverage_diffusivity_bin);
end


function output=append_table(output,value)
if isempty(output), output=value; else, output=[output;value]; end
end
function require_files(files,index)
for file=files
    if ~isfile(file)
        error("reqml:FinalAuditMissingArtifact", ...
            "Iteration %d is missing artifact: %s",index,file);
    end
end
end
