function [campaign, design] = buildAnalyticFiniteApertureCampaign( ...
        config, simulationOutputDirectory)
%BUILDANALYTICFINITEAPERTURECAMPAIGN Build the fixed 12-run diagnostic.

arguments
    config (1,1) struct
    simulationOutputDirectory {mustBeTextScalar}
end

required = ["diagnostic_id","simulation_base_config","frequency_hz", ...
    "M","step_pixels","cs_true_m_s","domain","source_radius_m", ...
    "source_direction_from_center_xyz","directions","sources", ...
    "apertures","noise_snr_db","base_seed", ...
    "geometric_decay_exponent","forces", ...
    "required_simulation_framework_commit"];
missing = required(~isfield(config,cellstr(required)));
if ~isempty(missing)
    error("reqml:InvalidAnalyticFiniteApertureConfig", ...
        "Diagnostic configuration is missing '%s'.",missing(1));
end

csValues = double(config.cs_true_m_s(:));
forces = config.forces;
apertures = config.apertures;
expectedCount = numel(csValues)*numel(forces)*numel(apertures);
if expectedCount ~= 12
    error("reqml:AnalyticFiniteApertureDesignCount", ...
        "The controlled diagnostic must contain exactly 12 runs; found %d.", ...
        expectedCount);
end

centerXYZ = [double(config.domain.Lx_m)/2, ...
    double(config.domain.observation_y_m),double(config.domain.Lz_m)/2];
sourceDirection = unitVector(config.source_direction_from_center_xyz);
sourceRadius = double(config.source_radius_m);
sourceXYZ = centerXYZ+sourceRadius*sourceDirection;
apertureAxis = unitVector(config.sources.aperture_axis_xyz);
spacing = double(config.sources.aperture_node_spacing_m);

runs = repmat(emptyRun(),expectedCount,1);
rows = repmat(emptyDesignRow(),expectedCount,1);
ordinal = 0;
for csIndex = 1:numel(csValues)
    cs = csValues(csIndex);
    seed = double(config.base_seed)+csIndex-1;
    for forceIndex = 1:numel(forces)
        forceDirection = unitVector(forces(forceIndex).direction_xyz);
        forceLabel = lower(string(forces(forceIndex).label));
        for apertureIndex = 1:numel(apertures)
            ordinal = ordinal+1;
            aperture = apertures(apertureIndex);
            apertureLabel = lower(string(aperture.label));
            apertureModel = lower(string(aperture.model));
            span = double(aperture.span_m);
            nodeCount = 1;
            if apertureModel == "line_segment"
                nodeCount = round(span/spacing)+1;
            end
            designId = "cs"+compose("%g",cs)+"_"+forceLabel+"_"+ ...
                apertureLabel;
            overrides = buildOverrides(config,cs,seed,sourceDirection, ...
                forceDirection,apertureModel,span,apertureAxis,spacing, ...
                designId);
            runs(ordinal) = struct("design_id",designId, ...
                "condition_id",designId,"realization_id",1, ...
                "overrides",overrides);
            rows(ordinal) = struct("design_id",designId, ...
                "cs_true_m_s",cs,"force_label",forceLabel, ...
                "force_x",forceDirection(1),"force_y",forceDirection(2), ...
                "force_z",forceDirection(3), ...
                "aperture_label",apertureLabel, ...
                "aperture_model",apertureModel,"aperture_span_m",span, ...
                "aperture_node_count",nodeCount, ...
                "aperture_node_spacing_m",spacing, ...
                "aperture_axis_x",apertureAxis(1), ...
                "aperture_axis_y",apertureAxis(2), ...
                "aperture_axis_z",apertureAxis(3), ...
                "geometric_decay_exponent", ...
                    double(config.geometric_decay_exponent), ...
                "seed",seed,"source_radius_m",sourceRadius, ...
                "expected_source_x_m",sourceXYZ(1), ...
                "expected_source_y_m",sourceXYZ(2), ...
                "expected_source_z_m",sourceXYZ(3), ...
                "radiation_model",string(config.sources.radiation_model), ...
                "frequency_hz",double(config.frequency_hz));
        end
    end
end

design = struct2table(rows);
if numel(unique(design.design_id)) ~= 12
    error("reqml:DuplicateAnalyticFiniteApertureDesignId", ...
        "All 12 diagnostic design IDs must be unique.");
end

campaign = struct("schema_version","1.2","backend","swsynth", ...
    "campaign_name",string(config.diagnostic_id), ...
    "base_config",string(config.simulation_base_config), ...
    "output",struct("directory",string(simulationOutputDirectory)), ...
    "runs",runs);
end

function overrides = buildOverrides(config,cs,seed,sourceDirection, ...
        forceDirection,apertureModel,span,apertureAxis,spacing,designId)
paths = ["scenario";"seed";"domain.Lx_m";"domain.Lz_m"; ...
    "domain.dx_m";"domain.dz_m";"domain.observation_y_m"; ...
    "medium.background_cs_m_s";"wavefield.frequency_hz"; ...
    "propagation.model";"propagation.phase_model"; ...
    "directions.count";"directions.space"; ...
    "directions.sampling_method";"directions.explicit_xyz"; ...
    "directions.require_in_plane";"directions.in_plane_count"; ...
    "sources.radius_range_m";"sources.phase_policy"; ...
    "sources.amplitude_jitter_fraction";"sources.radiation.model"; ...
    "sources.radiation.force_direction_xyz";"sources.aperture.model"; ...
    "sources.aperture.span_m";"sources.aperture.axis_xyz"; ...
    "sources.aperture.node_spacing_m";"polarization.model"; ...
    "amplitude.geometric_decay_exponent";"noise.snr_db"; ...
    "execution.use_parallel"];
values = {designId;seed;double(config.domain.Lx_m); ...
    double(config.domain.Lz_m);double(config.domain.dx_m); ...
    double(config.domain.dz_m);double(config.domain.observation_y_m); ...
    cs;double(config.frequency_hz);"spherical_wave";"local_k_distance"; ...
    double(config.directions.count);string(config.directions.space); ...
    string(config.directions.sampling_method);sourceDirection;false;0; ...
    [double(config.source_radius_m),double(config.source_radius_m)]; ...
    string(config.sources.phase_policy); ...
    double(config.sources.amplitude_jitter_fraction); ...
    string(config.sources.radiation_model);forceDirection;apertureModel; ...
    span;apertureAxis;spacing;"transverse_random"; ...
    double(config.geometric_decay_exponent);double(config.noise_snr_db);false};
overrides = repmat(struct("path","","value",[]),numel(paths),1);
for index = 1:numel(paths)
    overrides(index).path = paths(index);
    overrides(index).value = values{index};
end
end

function value = unitVector(value)
value = double(value(:)');
if numel(value)~=3 || any(~isfinite(value)) || norm(value)<=eps
    error("reqml:InvalidAnalyticFiniteApertureVector", ...
        "Directions must be finite nonzero three-vectors.");
end
value = value/norm(value);
end

function value = emptyRun()
value = struct("design_id","","condition_id","", ...
    "realization_id",1,"overrides",struct([]));
end

function value = emptyDesignRow()
value = struct("design_id","","cs_true_m_s",NaN,"force_label","", ...
    "force_x",NaN,"force_y",NaN,"force_z",NaN, ...
    "aperture_label","","aperture_model","","aperture_span_m",NaN, ...
    "aperture_node_count",NaN,"aperture_node_spacing_m",NaN, ...
    "aperture_axis_x",NaN,"aperture_axis_y",NaN,"aperture_axis_z",NaN, ...
    "geometric_decay_exponent",NaN,"seed",NaN,"source_radius_m",NaN, ...
    "expected_source_x_m",NaN,"expected_source_y_m",NaN, ...
    "expected_source_z_m",NaN,"radiation_model","","frequency_hz",NaN);
end
