function [campaign, design] = buildAnalyticPlaneSphericalCampaign( ...
        config, simulation_output_directory)
%BUILDANALYTICPLANESPHERICALCAMPAIGN Build the fixed 12-run diagnostic.

arguments
    config (1,1) struct
    simulation_output_directory {mustBeTextScalar}
end

required = ["diagnostic_id","simulation_base_config","frequency_hz", ...
    "cs_true_m_s","domain","source_radius_m","orientations", ...
    "directions","sources","noise_snr_db","propagation_conditions"];
missing = required(~isfield(config, cellstr(required)));
if ~isempty(missing)
    error("reqml:InvalidAnalyticPlaneSphericalConfig", ...
        "Diagnostic configuration is missing '%s'.", missing(1));
end

cs_values = double(config.cs_true_m_s(:));
orientations = config.orientations;
conditions = config.propagation_conditions;
expected_count = numel(cs_values)*numel(orientations)*numel(conditions);
if expected_count ~= 12
    error("reqml:AnalyticPlaneSphericalDesignCount", ...
        "The controlled diagnostic must contain exactly 12 runs; found %d.", ...
        expected_count);
end

center_xyz = [double(config.domain.Lx_m)/2, ...
    double(config.domain.observation_y_m), double(config.domain.Lz_m)/2];
radius_m = double(config.source_radius_m);

runs = repmat(empty_run(), expected_count, 1);
rows = repmat(empty_design_row(), expected_count, 1);
ordinal = 0;

for cs_index = 1:numel(cs_values)
    cs = cs_values(cs_index);
    for orientation_index = 1:numel(orientations)
        orientation = orientations(orientation_index);
        d = unit_vector(orientation.center_propagation_direction_xyz);
        for condition_index = 1:numel(conditions)
            ordinal = ordinal + 1;
            condition = conditions(condition_index);
            condition_name = string(condition.name);
            model = string(condition.model);
            if model == "spherical_wave"
                explicit_direction = -d;
                source_xyz = center_xyz + radius_m*explicit_direction;
            else
                explicit_direction = d;
                source_xyz = [NaN NaN NaN];
            end

            design_id = "cs" + compose("%g", cs) + "_" + ...
                string(orientation.name) + "_" + condition_name;
            overrides = build_overrides(config, cs, orientation, ...
                condition, explicit_direction, design_id);
            runs(ordinal) = struct("design_id", design_id, ...
                "condition_id", design_id, "realization_id", 1, ...
                "overrides", overrides);

            rows(ordinal) = struct( ...
                "design_id", design_id, ...
                "cs_true_m_s", cs, ...
                "orientation", string(orientation.name), ...
                "propagation_condition", condition_name, ...
                "propagation_model", model, ...
                "geometric_decay_exponent", ...
                    double(condition.geometric_decay_exponent), ...
                "seed", double(orientation.seed) + 10*(cs_index-1), ...
                "direction_x", d(1), "direction_y", d(2), ...
                "direction_z", d(3), ...
                "explicit_x", explicit_direction(1), ...
                "explicit_y", explicit_direction(2), ...
                "explicit_z", explicit_direction(3), ...
                "source_radius_m", radius_m, ...
                "source_x_m", source_xyz(1), ...
                "source_y_m", source_xyz(2), ...
                "source_z_m", source_xyz(3));
        end
    end
end

design_ids = string({rows.design_id})';
if numel(unique(design_ids)) ~= 12
    error("reqml:DuplicateAnalyticPlaneSphericalDesignId", ...
        "All 12 diagnostic design IDs must be unique.");
end

campaign = struct();
campaign.schema_version = "1.2";
campaign.backend = "swsynth";
campaign.campaign_name = string(config.diagnostic_id);
campaign.base_config = string(config.simulation_base_config);
campaign.output = struct("directory", string(simulation_output_directory));
campaign.runs = runs;
design = struct2table(rows);
end

function overrides = build_overrides(config, cs, orientation, ...
        condition, explicit_direction, design_id)

seed = double(orientation.seed) + 10*(find(double(config.cs_true_m_s)==cs,1)-1);
paths = [ ...
    "scenario"; "seed"; "domain.Lx_m"; "domain.Lz_m"; ...
    "domain.dx_m"; "domain.dz_m"; "domain.observation_y_m"; ...
    "medium.background_cs_m_s"; "wavefield.frequency_hz"; ...
    "propagation.model"; "propagation.phase_model"; ...
    "directions.count"; "directions.space"; ...
    "directions.sampling_method"; "directions.explicit_xyz"; ...
    "directions.require_in_plane"; "directions.in_plane_count"; ...
    "sources.radius_range_m"; "sources.phase_policy"; ...
    "sources.amplitude_jitter_fraction"; "polarization.model"; ...
    "amplitude.geometric_decay_exponent"; "noise.snr_db"; ...
    "execution.use_parallel"];
values = { ...
    design_id; seed; double(config.domain.Lx_m); ...
    double(config.domain.Lz_m); double(config.domain.dx_m); ...
    double(config.domain.dz_m); double(config.domain.observation_y_m); ...
    cs; double(config.frequency_hz); string(condition.model); ...
    string(condition.phase_model); double(config.directions.count); ...
    string(config.directions.space); ...
    string(config.directions.sampling_method); explicit_direction; ...
    true; 0; [double(config.source_radius_m), ...
        double(config.source_radius_m)]; ...
    string(config.sources.phase_policy); ...
    double(config.sources.amplitude_jitter_fraction); ...
    "in_plane_sv"; double(condition.geometric_decay_exponent); ...
    double(config.noise_snr_db); false};
overrides = repmat(struct("path", "", "value", []), numel(paths), 1);
for index = 1:numel(paths)
    overrides(index).path = paths(index);
    overrides(index).value = values{index};
end
end

function value = unit_vector(value)
value = double(value(:)');
if numel(value) ~= 3 || any(~isfinite(value)) || norm(value) <= eps
    error("reqml:InvalidAnalyticPropagationDirection", ...
        "Each requested propagation direction must be a finite 3-vector.");
end
value = value/norm(value);
if abs(value(2)) > 1e-12
    error("reqml:AnalyticDirectionOutsideObservationPlane", ...
        "Diagnostic propagation directions must lie in the x-z plane.");
end
end

function value = empty_run()
value = struct("design_id", "", "condition_id", "", ...
    "realization_id", 1, "overrides", struct([]));
end

function value = empty_design_row()
value = struct("design_id", "", "cs_true_m_s", NaN, ...
    "orientation", "", "propagation_condition", "", ...
    "propagation_model", "", "geometric_decay_exponent", NaN, ...
    "seed", NaN, "direction_x", NaN, "direction_y", NaN, ...
    "direction_z", NaN, "explicit_x", NaN, "explicit_y", NaN, ...
    "explicit_z", NaN, "source_radius_m", NaN, ...
    "source_x_m", NaN, "source_y_m", NaN, "source_z_m", NaN);
end
