function result=freezeV2SplitsFromConfig(config_file,options)
%FREEZEV2SPLITSFROMCONFIG Freeze in-domain and alternating interpolation splits.
arguments
    config_file {mustBeTextScalar}
    options.DatasetPath {mustBeTextScalar} = ""
end
config_file=string(config_file); config=jsondecode(fileread(config_file));
root=string(fileparts(fileparts(fileparts(fileparts(mfilename("fullpath"))))));
output_root=reqml.config.resolveWorkspacePath(string(config.paths.output_root),RepositoryRoot=root);
dataset_path=string(options.DatasetPath); if strlength(dataset_path)==0, dataset_path=fullfile(output_root,"dataset","examples.mat"); end
loaded=load(dataset_path,"examples"); examples=loaded.examples;
design=reqml.homogeneous.materializeCartesianDesign(config); split_root=fullfile(output_root,"splits");
in_domain=reqml.splits.freeze_grouped_training_split(examples, ...
    fullfile(split_root,"in_domain"),DatasetPath=dataset_path, ...
    ConditionColumn="campaign_condition_id",SplitSeed=double(config.splits.in_domain_seed), ...
    FoldSeed=double(config.splits.fold_seed),FoldCount=double(config.splits.fold_count), ...
    TrainFraction=double(config.splits.train_fraction), ...
    ValidationFraction=double(config.splits.validation_fraction), ...
    TestFraction=double(config.splits.test_fraction));
sws=freeze_alternating(examples,design.conditions,"sws",config, ...
    double(config.splits.in_domain_seed)+101,double(config.splits.fold_seed)+101, ...
    dataset_path,fullfile(split_root,"alternating_sws"));
angular=freeze_alternating(examples,design.conditions,"angular",config, ...
    double(config.splits.in_domain_seed)+202,double(config.splits.fold_seed)+202, ...
    dataset_path,fullfile(split_root,"alternating_angular"));
result=struct("in_domain",in_domain,"alternating_sws",sws, ...
    "alternating_angular",angular,"dataset_path",dataset_path);
end

function result=freeze_alternating(examples,conditions,dimension,config,seed,fold_seed,dataset_path,output)
split=reqml.homogeneous.makeV2AlternatingSplit(examples,conditions,dimension,config,Seed=seed);
integrity=reqml.splits.validate_split_integrity(examples,split);
if ~integrity.valid, error("reqml:InvalidV2AlternatingSplit","%s",integrity.summary); end
folds=reqml.splits.make_grouped_training_folds(examples,split, ...
    ConditionColumn="campaign_condition_id",FoldCount=double(config.splits.fold_count),Seed=fold_seed);
fold_integrity=reqml.splits.validate_training_fold_integrity(examples,split,folds);
if ~fold_integrity.valid, error("reqml:InvalidV2AlternatingFolds","%s",fold_integrity.summary); end
paths=reqml.splits.save_training_split_manifest(examples,split,folds,output,DatasetPath=dataset_path);
result=struct("split",split,"folds",folds,"split_integrity",integrity, ...
    "fold_integrity",fold_integrity,"paths",paths);
end
