function result = freezeSplitsFromConfig(config_file, options)
%FREEZESPLITSFROMCONFIG Save in-domain and scientific held-out splits.

arguments
    config_file {mustBeTextScalar}
    options.DatasetPath {mustBeTextScalar} = ""
end

config=jsondecode(fileread(config_file));
root=string(fileparts(fileparts(fileparts(fileparts(mfilename("fullpath"))))));
output_root=resolve_path(string(config.paths.output_root),root);
dataset_path=string(options.DatasetPath);
if strlength(dataset_path)==0
    dataset_path=fullfile(output_root,"dataset","examples.mat");
end
loaded=load(dataset_path,"examples"); examples=loaded.examples;
design=reqml.homogeneous.materializeCartesianDesign(config);
split_root=fullfile(output_root,"splits");

in_domain=reqml.splits.freeze_grouped_training_split( ...
    examples,fullfile(split_root,"in_domain"),DatasetPath=dataset_path, ...
    ConditionColumn="campaign_condition_id", ...
    SplitSeed=double(config.splits.in_domain_seed), ...
    FoldSeed=double(config.splits.fold_seed), ...
    FoldCount=double(config.splits.fold_count), ...
    TrainFraction=double(config.splits.train_fraction), ...
    ValidationFraction=double(config.splits.validation_fraction), ...
    TestFraction=double(config.splits.test_fraction));

held_cs=freeze_held(examples,design.conditions,"cs_m_s", ...
    double(config.splits.held_out_cs_m_s), ...
    double(config.splits.in_domain_seed)+101, ...
    double(config.splits.fold_seed)+101, ...
    double(config.splits.fold_count),dataset_path, ...
    fullfile(split_root,"held_out_cs3"));
held_frequency=freeze_held(examples,design.conditions,"frequency_hz", ...
    double(config.splits.held_out_frequency_hz), ...
    double(config.splits.in_domain_seed)+202, ...
    double(config.splits.fold_seed)+202, ...
    double(config.splits.fold_count),dataset_path, ...
    fullfile(split_root,"held_out_f400"));
result=struct("in_domain",in_domain,"held_out_cs3",held_cs, ...
    "held_out_f400",held_frequency,"dataset_path",dataset_path);
end


function result=freeze_held(examples,conditions,dimension,value,split_seed, ...
        fold_seed,fold_count,dataset_path,output)
split=reqml.homogeneous.makeHeldOutSplit(examples,conditions,dimension,value, ...
    Seed=split_seed);
integrity=reqml.splits.validate_split_integrity(examples,split);
if ~integrity.valid
    error("reqml:InvalidHomogeneousHeldOutSplit","%s",integrity.summary);
end
folds=reqml.splits.make_grouped_training_folds(examples,split, ...
    ConditionColumn="campaign_condition_id",FoldCount=fold_count,Seed=fold_seed);
fold_integrity=reqml.splits.validate_training_fold_integrity( ...
    examples,split,folds);
if ~fold_integrity.valid
    error("reqml:InvalidHomogeneousHeldOutFolds","%s",fold_integrity.summary);
end
paths=reqml.splits.save_training_split_manifest( ...
    examples,split,folds,output,DatasetPath=dataset_path);
result=struct("split",split,"folds",folds,"split_integrity",integrity, ...
    "fold_integrity",fold_integrity,"paths",paths);
end
function value=resolve_path(value,root)
if startsWith(value,"${REPOSITORY_ROOT}/")
    value=fullfile(root,extractAfter(value,"${REPOSITORY_ROOT}/"));
end
end
