function result = runExtremeSmokeTest(config_file)
%RUNEXTREMESMOKETEST Execute and audit two Cartesian design extremes.

arguments
    config_file {mustBeTextScalar}
end

config_file=string(config_file);
config=jsondecode(fileread(config_file));
full=reqml.homogeneous.materializeCartesianDesign(config);
keep=(full.conditions.cs_m_s==1 & full.conditions.frequency_hz==600 & ...
    full.conditions.dx_m==.00025 & full.conditions.field_regime=="single") | ...
    (full.conditions.cs_m_s==4 & full.conditions.frequency_hz==200 & ...
    full.conditions.dx_m==.0005 & full.conditions.field_regime=="diffuse");
design=full;
design.conditions=full.conditions(keep,:);
design.runs=full.runs(ismember(full.runs.condition_id, ...
    design.conditions.condition_id),:);
design.condition_count=height(design.conditions);
design.run_count=height(design.runs);
design.campaign_id=string(config.campaign_id)+"_smoke";

repo_root=string(fileparts(fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))))));
output_root=resolve_path(string(config.paths.output_root),repo_root);
smoke_root=fullfile(output_root,"smoke");
campaign_dir=fullfile(smoke_root,"campaign");
written=reqml.homogeneous.writeCartesianCampaign(config_file, ...
    OutputDirectory=campaign_dir,Design=design, ...
    CampaignId=design.campaign_id);

framework_root=string(config.paths.simulation_framework_root);
framework_src=fullfile(framework_root,"src");
addpath(framework_src);
cleanup=onCleanup(@() rmpath(framework_src));
simulation=simcampaigns.runCampaign(written.paths.campaign_json, ...
    Resume=logical(config.execution.resume_runs), ...
    ContinueOnError=false);
campaign_csv=fullfile(simulation.campaign_directory,"campaign_runs.csv");

feat=reqml.config.default_feature_config("M",2,"cs_guess",3);
dataset=reqml.datasets.build_dataset_from_campaign(campaign_csv,feat, ...
    DatasetId=design.campaign_id,CsGuessMPerS=3,WindowWavelengths=2, ...
    AutomaticHalfWindowStride=true,MinimumStridePixels=double( ...
        config.patch_sampling.minimum_stride_pixels), ...
    MaximumExamplesPerRun=double( ...
        config.patch_sampling.target_patches_per_run), ...
    ExampleSelectionSeedOffset=double( ...
        config.patch_sampling.selection_seed_offset), ...
    UseSampleParfor=logical(config.execution.use_sample_parfor), ...
    OutputDirectory=fullfile(smoke_root,"dataset"));
coverage=reqml.homogeneous.summarizeCoverage(design,campaign_csv, ...
    dataset.sample_summaries,TargetPatchesPerRun=double( ...
        config.patch_sampling.target_patches_per_run));

assert_smoke(dataset,coverage,design);
coverage_dir=fullfile(smoke_root,"coverage");
if ~isfolder(coverage_dir), mkdir(coverage_dir); end
writetable(coverage.runs,fullfile(coverage_dir,"run_coverage.csv"));
writetable(coverage.conditions,fullfile(coverage_dir,"condition_coverage.csv"));
result=struct("design",design,"written_campaign",written, ...
    "simulation",simulation,"dataset",dataset,"coverage",coverage, ...
    "smoke_root",smoke_root);
clear cleanup
end


function assert_smoke(dataset,coverage,design)
if design.condition_count~=2 || design.run_count~=6 || ...
        ~coverage.complete || dataset.example_count~=600
    error("reqml:HomogeneousSmokeCoverageFailed", ...
        "Smoke expected 2 conditions, 6 runs, and 600 selected patches.");
end
examples=dataset.examples;
if any(abs(double(examples.truth_material_purity)-1)>1e-12) || ...
        any(string(examples.campaign_geometry_family)~="homogeneous") || ...
        any(double(examples.REQ_M)~=2) || ...
        any(abs(double(examples.REQ_cs_guess_m_s)-3)>1e-12)
    error("reqml:HomogeneousSmokeInvariantFailed", ...
        "Smoke dataset violated homogeneous or REQ invariants.");
end
end
function value=resolve_path(value,root)
if startsWith(value,"${REPOSITORY_ROOT}/")
    value=fullfile(root,extractAfter(value,"${REPOSITORY_ROOT}/"));
end
end
