function result = runHoldoutGeneralizationStudy(config_file, options)
%RUNHOLDOUTGENERALIZATIONSTUDY Train 16 level and one compositional Q0 holdout.

arguments
    config_file {mustBeTextScalar}
    options.DatasetPath {mustBeTextScalar} = ""
    options.OutputDirectory {mustBeTextScalar} = ""
    options.ExperimentIds (:,1) string = strings(0,1)
end

config_file=string(config_file); config=jsondecode(fileread(config_file));
root=string(fileparts(fileparts(fileparts(fileparts(mfilename("fullpath"))))));
output_root=reqml.config.resolveWorkspacePath( ...
    string(config.paths.output_root),RepositoryRoot=root);
dataset_path=string(options.DatasetPath);
if strlength(dataset_path)==0
    dataset_path=fullfile(output_root,"dataset","examples.mat");
end
output=string(options.OutputDirectory);
if strlength(output)==0, output=fullfile(output_root,"held_out","v1"); end
if ~isfolder(output), mkdir(output); end
loaded=load(dataset_path,"examples"); examples=loaded.examples;
design=reqml.homogeneous.materializeCartesianDesign(config);
registry=reqml.training.q0_predictor_registry();
contract=reqml.training.validate_predictor_contract( ...
    examples,registry.q_spectrum_predictors,registry);
if ~contract.valid, error("reqml:InvalidHoldoutQ0PredictorContract", ...
        "%s",contract.summary); end
[X,predictor_metadata]=reqml.training.build_numeric_predictor_matrix( ...
    examples,registry.q_spectrum_predictors);
q_true=double(examples.q_target_from_center_truth);
specifications=reqml.homogeneous.buildHoldoutSpecifications(config);
if ~isempty(options.ExperimentIds)
    specifications=specifications(ismember(specifications.experiment_id, ...
        options.ExperimentIds),:);
end
summary_rows=cell(height(specifications),1);
for index=1:height(specifications)
    experiment=specifications(index,:);
    fprintf("\n[%d/%d] %s\n",index,height(specifications), ...
        experiment.experiment_id);
    held_mask=make_held_mask(design.conditions,experiment,config);
    split_seed=double(config.generalization.split_seed)+experiment.ordinal;
    split=reqml.homogeneous.makeConditionHoldoutSplit( ...
        examples,design.conditions,held_mask,Seed=split_seed, ...
        ValidationFraction=double(config.generalization.validation_fraction), ...
        HoldoutId=experiment.experiment_id);
    integrity=reqml.splits.validate_split_integrity(examples,split);
    if ~integrity.valid, error("reqml:HoldoutConditionLeakage", ...
            "%s: %s",experiment.experiment_id,integrity.summary); end
    assert_exact_holdout(split,design.conditions,held_mask,experiment);
    model_spec=make_model_spec(config,experiment);
    tic; model=reqml.training.fit_regression_model( ...
        X,q_true,split.train_mask,model_spec); training_seconds=toc;
    q_pred=reqml.training.predict_regression_model(model,X,ClipRange=[.001 .999]);
    q_metrics=reqml.evaluation.evaluate_q_predictions( ...
        q_true,q_pred,split.partition,model_spec.id);
    sws=reqml.evaluation.convert_q_predictions_to_sws(examples,q_pred, ...
        TruthColumn="truth_cs_center_m_s", ...
        FrequencyColumn="campaign_frequency_hz",MappingColumn="req_mapping");
    sws_metrics=reqml.evaluation.evaluate_sws_predictions( ...
        sws,split.partition,model_spec.id);
    predictions=make_predictions(examples,design.conditions,split.partition, ...
        q_true,q_pred,sws,experiment.experiment_id);
    experiment_output=fullfile(output,experiment.family,experiment.experiment_id);
    paths=save_experiment(experiment_output,config_file,dataset_path, ...
        experiment,split,integrity,model,model_spec,predictor_metadata, ...
        registry.q_spectrum_predictors,q_metrics,sws_metrics,predictions, ...
        training_seconds);
    summary_rows{index}=make_summary_row(experiment,split,q_metrics, ...
        sws_metrics,training_seconds,paths);
    fprintf("  test MAPE %.4f%%, bias %.4f%%, %.1f s\n", ...
        summary_rows{index}.sws_mape,summary_rows{index}.sws_bias_percent, ...
        training_seconds);
    clear model q_pred sws predictions split
end
summary=vertcat(summary_rows{:});
summary_file=fullfile(output,"held_out_summary.csv");
writetable(summary,summary_file);
figure_paths=generate_study_figures(summary,output);
write_study_manifest(fullfile(output,"study_manifest.json"), ...
    config_file,dataset_path,specifications,summary,registry.q_spectrum_predictors);
result=struct("summary",summary,"specifications",specifications, ...
    "summary_file",summary_file,"figure_paths",figure_paths, ...
    "output_directory",output);
end


function held=make_held_mask(conditions,experiment,config)
if experiment.family=="compositional"
    held=conditions.cs_m_s==double(config.generalization.compositional_cs_m_s) & ...
        conditions.frequency_hz==double( ...
        config.generalization.compositional_frequency_hz);
elseif experiment.family=="field"
    held=conditions.field_regime==experiment.string_value;
else
    held=double(conditions.(experiment.dimension))==experiment.numeric_value;
end
end
function spec=make_model_spec(config,experiment)
spec=struct("id","homogeneous_q0_holdout_"+experiment.experiment_id, ...
    "type","bagged_trees","num_learning_cycles", ...
    double(config.training.num_learning_cycles),"min_leaf_size", ...
    double(config.training.min_leaf_size),"use_parallel", ...
    logical(config.training.use_parallel),"random_seed", ...
    double(config.generalization.model_seed)+experiment.ordinal);
end
function assert_exact_holdout(split,conditions,held,experiment)
actual=sort(unique(split.condition_id(split.test_mask)));
expected=sort(string(conditions.condition_id(held)));
if ~isequal(actual,expected)
    error("reqml:IncorrectCartesianHoldout", ...
        "%s did not hold out exactly the requested conditions.", ...
        experiment.experiment_id);
end
end


function predictions=make_predictions(examples,conditions,partition, ...
        q_true,q_pred,sws,experiment_id)
[found,location]=ismember(string(examples.campaign_condition_id), ...
    string(conditions.condition_id));
if ~all(found), error("reqml:UnknownHoldoutCondition", ...
        "Examples contain unknown conditions."); end
c=conditions(location,:); n=height(examples);
predictions=table(repmat(experiment_id,n,1),string(examples.example_id), ...
    string(examples.campaign_condition_id),string(examples.campaign_run_id), ...
    string(partition),c.cs_m_s,c.frequency_hz,c.dx_m,c.dz_m,c.field_regime, ...
    q_true,double(q_pred),double(q_pred)-q_true,sws.cs_true_m_s, ...
    sws.cs_pred_m_s,sws.cs_error_m_s,sws.cs_error_percent, ...
    sws.cs_absolute_error_percent,sws.sws_valid, ...
    VariableNames=["experiment_id","example_id","condition_id","run_id", ...
    "partition","cs_m_s","frequency_hz","dx_m","dz_m","field_regime", ...
    "q_true","q_pred","q_error","cs_true_m_s","cs_pred_m_s", ...
    "cs_error_m_s","cs_error_percent","cs_absolute_error_percent", ...
    "sws_valid"]);
end


function paths=save_experiment(output,config_file,dataset_path,experiment, ...
        split,integrity,model,model_spec,predictor_metadata,predictor_names, ...
        q_metrics,sws_metrics,predictions,training_seconds)
if ~isfolder(output), mkdir(output); end
table_dir=fullfile(output,"tables"); if ~isfolder(table_dir), mkdir(table_dir); end
test=predictions(predictions.partition=="test",:);
paths=struct("model",fullfile(output,"model_bundle.mat"), ...
    "split",fullfile(output,"split_assignments.mat"), ...
    "conditions",fullfile(table_dir,"condition_partitions.csv"), ...
    "predictions",fullfile(table_dir,"test_predictions.csv"), ...
    "q_metrics",fullfile(table_dir,"q_metrics.csv"), ...
    "sws_metrics",fullfile(table_dir,"sws_metrics.csv"), ...
    "manifest",fullfile(output,"manifest.json"));
writetable(split.conditions,paths.conditions); writetable(test,paths.predictions);
writetable(q_metrics,paths.q_metrics); writetable(sws_metrics,paths.sws_metrics);
groups=struct();
groups.by_cs="cs_m_s"; groups.by_frequency="frequency_hz";
groups.by_dx="dx_m"; groups.by_field="field_regime";
groups.cs_frequency=["cs_m_s","frequency_hz"];
groups.cs_field=["cs_m_s","field_regime"];
groups.frequency_field=["frequency_hz","field_regime"];
names=fieldnames(groups);
for i=1:numel(names)
    table_value=reqml.homogeneous.summarizeQ0ByGroup( ...
        test,string(groups.(names{i})));
    writetable(table_value,fullfile(table_dir,string(names{i})+".csv"));
end
save(paths.model,"model","model_spec","predictor_names", ...
    "predictor_metadata","-v7.3");
save(paths.split,"split","integrity","-v7.3");
[status,head]=system("git rev-parse HEAD"); if status~=0, head=""; end
manifest=struct("schema_name","reqml_homogeneous_q0_holdout", ...
    "schema_version","1.0","experiment_id",experiment.experiment_id, ...
    "family",experiment.family,"held_out_label",experiment.held_out_label, ...
    "source_config",config_file,"dataset_path",dataset_path, ...
    "model_spec",model_spec,"predictor_names",predictor_names, ...
    "split_seed",split.seed,"partition_summary",split.summary, ...
    "training_seconds",training_seconds,"git_head",strtrim(string(head)), ...
    "created_utc",string(datetime("now","TimeZone","UTC")));
write_json(paths.manifest,manifest);
end


function row=make_summary_row(experiment,split,q_metrics,sws_metrics,seconds,paths)
q=q_metrics(q_metrics.partition=="test",:); s=sws_metrics(sws_metrics.partition=="test",:);
train=split.summary(split.summary.partition=="train",:);
validation=split.summary(split.summary.partition=="validation",:);
test=split.summary(split.summary.partition=="test",:);
row=table(experiment.experiment_id,experiment.family, ...
    experiment.held_out_label,train.condition_count,validation.condition_count, ...
    test.condition_count,train.example_count,validation.example_count, ...
    test.example_count,q.q_mae,q.q_rmse,q.q_bias,q.q_median_ae, ...
    s.sws_mae_m_s,s.sws_rmse_m_s,s.sws_mape,s.sws_median_ape, ...
    s.sws_p90_ape,s.sws_error_gt5_pct,s.sws_error_gt10_pct, ...
    s.sws_error_gt20_pct,s.sws_bias_percent,s.sws_underestimate_pct, ...
    seconds,string(paths.manifest),VariableNames=["experiment_id","family", ...
    "held_out_label","train_condition_count","validation_condition_count", ...
    "test_condition_count","train_example_count","validation_example_count", ...
    "test_example_count","q_mae","q_rmse","q_bias","q_median_ae", ...
    "sws_mae_m_s","sws_rmse_m_s","sws_mape","sws_median_ape", ...
    "sws_p90_ape","sws_error_gt5_pct","sws_error_gt10_pct", ...
    "sws_error_gt20_pct","sws_bias_percent","sws_underestimate_pct", ...
    "training_seconds","manifest_path"]);
end


function paths=generate_study_figures(summary,output)
figure_dir=fullfile(fileparts(fileparts(output)),"figures","held_out_v1");
if ~isfolder(figure_dir), mkdir(figure_dir); end
families=["cs","frequency","dx","field"]; paths=struct();
for i=1:numel(families)
    family=families(i); data=summary(summary.family==family,:);
    path=fullfile(figure_dir,"leave_one_"+family+"_out_mape_bias");
    f=figure("Visible","off","Color","w","Position",[100 100 850 580]);
    x=categorical(data.held_out_label,data.held_out_label);
    bar(x,[data.sws_mape,data.sws_bias_percent]); yline(0,"k:");
    ylabel("Percent"); xlabel("Held-out level");
    legend(["MAPE","Bias"],"Location","best");
    title("Leave-one-"+family+"-out Q0 generalization"); save_figure(f,path);
    paths.(family)=path;
end
selected=["cs_3","f_400","field_intermediate","compositional_cs3_f400"];
for i=1:numel(selected)
    row=summary(summary.experiment_id==selected(i),:);
    if isempty(row), continue; end
    prediction_file=fullfile(fileparts(row.manifest_path),"tables", ...
        "test_predictions.csv"); data=readtable(prediction_file,TextType="string");
    path=fullfile(figure_dir,selected(i)+"_true_vs_predicted");
    f=figure("Visible","off","Color","w","Position",[100 100 720 600]);
    scatter(data.cs_true_m_s,data.cs_pred_m_s,8,data.frequency_hz,"filled", ...
        "MarkerFaceAlpha",.25); hold on; lim=[min([data.cs_true_m_s; ...
        data.cs_pred_m_s]),max([data.cs_true_m_s;data.cs_pred_m_s])];
    plot(lim,lim,"k--"); xlim(lim); ylim(lim); axis square; colorbar;
    xlabel("True SWS (m/s)"); ylabel("Predicted SWS (m/s)");
    title(replace(selected(i),"_"," ")+compose(" (MAPE %.2f%%)",row.sws_mape));
    save_figure(f,path); paths.(char(selected(i)+"_scatter"))=path;
end
paths.cs3_heatmap=holdout_heatmap(summary,"cs_3","frequency_field", ...
    "frequency_hz","field_regime",figure_dir,"held_out_cs3_frequency_field");
paths.f400_heatmap=holdout_heatmap(summary,"f_400","cs_field", ...
    "cs_m_s","field_regime",figure_dir,"held_out_f400_cs_field");
end


function path=holdout_heatmap(summary,id,table_name,y_name,x_name,figure_dir,name)
row=summary(summary.experiment_id==id,:); path=fullfile(figure_dir,name);
if isempty(row), return; end
file=fullfile(fileparts(row.manifest_path),"tables",table_name+".csv");
data=readtable(file,TextType="string"); xv=unique(data.(x_name),"stable");
yv=sort(unique(data.(y_name))); matrix=nan(numel(yv),numel(xv));
for i=1:height(data)
    matrix(yv==data.(y_name)(i),xv==data.(x_name)(i))=data.sws_mape(i);
end
f=figure("Visible","off","Color","w","Position",[100 100 800 600]);
imagesc(matrix); colorbar; xticks(1:numel(xv)); xticklabels(string(xv));
yticks(1:numel(yv)); yticklabels(string(yv)); xlabel(x_name); ylabel(y_name);
title(replace(name,"_"," ")+" MAPE (%)"); save_figure(f,path);
end
function save_figure(f,path)
exportgraphics(f,path+".png","Resolution",300);
exportgraphics(f,path+".pdf","ContentType","vector"); close(f);
end
function write_study_manifest(path,config_file,dataset_path,spec,summary,predictors)
[status,head]=system("git rev-parse HEAD"); if status~=0, head=""; end
manifest=struct("schema_name","reqml_homogeneous_q0_holdout_study", ...
    "schema_version","1.0","source_config",config_file, ...
    "dataset_path",dataset_path,"experiment_count",height(spec), ...
    "specifications",spec,"summary",summary,"predictor_names",predictors, ...
    "git_head",strtrim(string(head)), ...
    "created_utc",string(datetime("now","TimeZone","UTC")));
write_json(path,manifest);
end
function write_json(path,value)
fid=fopen(path,"w"); if fid<0, error("reqml:CannotWriteHoldoutManifest", ...
        "Cannot write %s",path); end
cleanup=onCleanup(@() fclose(fid));
fprintf(fid,"%s\n",jsonencode(value,PrettyPrint=true));
end
