function result = trainQ0FromConfig(config_file, options)
%TRAINQ0FROMCONFIG Train and report controlled homogeneous Q0 only.

arguments
    config_file {mustBeTextScalar}
    options.DatasetPath {mustBeTextScalar} = ""
    options.SplitPath {mustBeTextScalar} = ""
end

config_file=string(config_file);
config=jsondecode(fileread(config_file));
root=string(fileparts(fileparts(fileparts(fileparts(mfilename("fullpath"))))));
output_root=reqml.config.resolveWorkspacePath( ...
    string(config.paths.output_root),RepositoryRoot=root);
dataset_path=string(options.DatasetPath);
if strlength(dataset_path)==0
    dataset_path=fullfile(output_root,"dataset","examples.mat");
end
split_path=string(options.SplitPath);
if strlength(split_path)==0
    split_path=fullfile(output_root,"splits","in_domain", ...
        "training_split_assignments.mat");
end
loaded=load(dataset_path,"examples"); examples=loaded.examples;
frozen=reqml.splits.load_frozen_training_split(examples,split_path);
registry=reqml.training.q0_predictor_registry();
contract=reqml.training.validate_predictor_contract( ...
    examples,registry.q_spectrum_predictors,registry);
if ~contract.valid
    error("reqml:InvalidHomogeneousQ0PredictorContract","%s",contract.summary);
end
[X,predictor_metadata]=reqml.training.build_numeric_predictor_matrix( ...
    examples,registry.q_spectrum_predictors);
q_true=double(examples.q_target_from_center_truth);
spec=struct("id",string(config.training.model_id),"type","bagged_trees", ...
    "num_learning_cycles",double(config.training.num_learning_cycles), ...
    "min_leaf_size",double(config.training.min_leaf_size), ...
    "use_parallel",logical(config.training.use_parallel), ...
    "random_seed",double(config.training.random_seed));
trained=reqml.training.fit_oof_regression_model( ...
    X,q_true,frozen.split,frozen.folds,spec,ClipRange=[.001 .999]);
q_pred=trained.combined_prediction;
q_metrics=reqml.evaluation.evaluate_q_predictions( ...
    q_true,q_pred,frozen.split.partition,string(spec.id));
sws=reqml.evaluation.convert_q_predictions_to_sws(examples,q_pred, ...
    TruthColumn="truth_cs_center_m_s", ...
    FrequencyColumn="campaign_frequency_hz",MappingColumn="req_mapping");
sws_metrics=reqml.evaluation.evaluate_sws_predictions( ...
    sws,frozen.split.partition,string(spec.id));
predictions=build_predictions(examples,frozen.split.partition, ...
    q_true,q_pred,trained.prediction_source,sws,config);

tables=struct();
tables.by_cs=reqml.homogeneous.summarizeQ0ByGroup( ...
    predictions,["partition","cs_m_s"]);
tables.by_frequency=reqml.homogeneous.summarizeQ0ByGroup( ...
    predictions,["partition","frequency_hz"]);
tables.by_dx=reqml.homogeneous.summarizeQ0ByGroup( ...
    predictions,["partition","dx_m"]);
tables.by_field=reqml.homogeneous.summarizeQ0ByGroup( ...
    predictions,["partition","field_regime"]);
tables.cs_frequency=reqml.homogeneous.summarizeQ0ByGroup( ...
    predictions,["partition","cs_m_s","frequency_hz"]);
tables.cs_field=reqml.homogeneous.summarizeQ0ByGroup( ...
    predictions,["partition","cs_m_s","field_regime"]);
tables.frequency_field=reqml.homogeneous.summarizeQ0ByGroup( ...
    predictions,["partition","frequency_hz","field_regime"]);
critical=predictions(predictions.cs_m_s==3 & ...
    predictions.frequency_hz==400 & ismember(predictions.field_regime, ...
    ["single","directional"]),:);
tables.critical_cs3_f400=reqml.homogeneous.summarizeQ0ByGroup( ...
    critical,["partition","field_regime"]);

output=fullfile(output_root,"training","q0_bagged_v1");
paths=save_results(output,examples,predictions,q_metrics,sws_metrics,tables, ...
    trained,registry,predictor_metadata,spec,dataset_path,split_path,config_file);
result=struct("q_metrics",q_metrics,"sws_metrics",sws_metrics, ...
    "stratified",tables,"predictions",predictions,"trained",trained, ...
    "paths",paths,"spec",spec);
end


function predictions=build_predictions(examples,partition,q_true,q_pred, ...
        source,sws,config)
design=reqml.homogeneous.materializeCartesianDesign(config);
[found,location]=ismember(string(examples.campaign_condition_id), ...
    design.conditions.condition_id);
if ~all(found), error("reqml:UnknownHomogeneousTrainingCondition", ...
        "Training examples contain unknown condition IDs."); end
c=design.conditions(location,:);
predictions=table(string(examples.example_id), ...
    string(examples.campaign_condition_id),string(examples.campaign_run_id), ...
    string(partition),string(source),c.cs_m_s,c.frequency_hz,c.dx_m,c.dz_m, ...
    c.field_regime,q_true,q_pred,q_pred-q_true,sws.cs_true_m_s, ...
    sws.cs_pred_m_s,sws.cs_error_m_s,sws.cs_error_percent, ...
    sws.cs_absolute_error_percent,sws.sws_valid, ...
    VariableNames=["example_id","condition_id","run_id","partition", ...
    "prediction_source","cs_m_s","frequency_hz","dx_m","dz_m", ...
    "field_regime","q_true","q_pred","q_error","cs_true_m_s", ...
    "cs_pred_m_s","cs_error_m_s","cs_error_percent", ...
    "cs_absolute_error_percent","sws_valid"]);
end


function paths=save_results(output,examples,predictions,q_metrics,sws_metrics, ...
        tables,trained,registry,predictor_metadata,spec,dataset_path, ...
        split_path,config_file)
if ~isfolder(output), mkdir(output); end
table_dir=fullfile(output,"tables"); plot_dir=fullfile(output,"plots");
if ~isfolder(table_dir), mkdir(table_dir); end
if ~isfolder(plot_dir), mkdir(plot_dir); end
paths=struct();
paths.model_bundle=fullfile(output,"model_bundle.mat");
paths.training_manifest=fullfile(output,"training_manifest.json");
paths.predictions=fullfile(table_dir,"predictions.csv");
paths.q_metrics=fullfile(table_dir,"q_metrics.csv");
paths.sws_metrics=fullfile(table_dir,"sws_metrics.csv");
writetable(predictions,paths.predictions);
writetable(q_metrics,paths.q_metrics); writetable(sws_metrics,paths.sws_metrics);
names=fieldnames(tables);
for i=1:numel(names)
    paths.(names{i})=fullfile(table_dir,string(names{i})+".csv");
    writetable(tables.(names{i}),paths.(names{i}));
end
model=trained.final_model; predictor_names=registry.q_spectrum_predictors;
model_metadata=struct("model_id",string(spec.id),"target_name", ...
    "q_target_from_center_truth","predictor_names",predictor_names, ...
    "predictor_count",predictor_metadata.predictor_count,"spec",spec, ...
    "dataset_path",dataset_path,"split_path",split_path); %#ok<NASGU>
save(paths.model_bundle,"model","model_metadata","predictor_names","-v7.3");
[status,head]=system("git rev-parse HEAD"); if status~=0, head=""; end
manifest=struct("schema_name","reqml_homogeneous_q0_training", ...
    "schema_version","1.0","model_id",string(spec.id), ...
    "target_name","q_target_from_center_truth", ...
    "predictor_names",predictor_names,"model_spec",spec, ...
    "dataset_path",dataset_path,"split_path",split_path, ...
    "source_config",string(config_file),"example_count",height(examples), ...
    "git_head",strtrim(string(head)), ...
    "created_utc",string(datetime("now","TimeZone","UTC")));
write_json(paths.training_manifest,manifest);
paths.cs_frequency_plot=fullfile(plot_dir,"cs_frequency_mape.png");
paths.critical_plot=fullfile(plot_dir,"cs3_f400_field_diagnostic.png");
make_plots(tables,paths);
end


function make_plots(tables,paths)
t=tables.cs_frequency;
t=t(t.partition=="test",:);
cs=sort(unique(t.cs_m_s)); f=sort(unique(t.frequency_hz));
matrix=nan(numel(cs),numel(f));
for i=1:height(t)
    matrix(cs==t.cs_m_s(i),f==t.frequency_hz(i))=t.sws_mape(i);
end
figure("Visible","off"); imagesc(f,cs,matrix); colorbar;
xlabel("Frequency (Hz)"); ylabel("SWS (m/s)"); title("Q0 SWS MAPE (%)");
exportgraphics(gcf,paths.cs_frequency_plot,"Resolution",180); close(gcf);
c=tables.critical_cs3_f400;
c=c(c.partition=="test",:);
figure("Visible","off"); bar(categorical(c.field_regime), ...
    [c.sws_mape,c.sws_bias_percent]); ylabel("Percent");
legend(["MAPE","Bias"],Location="best");
title("cs=3 m/s, f=400 Hz");
exportgraphics(gcf,paths.critical_plot,"Resolution",180); close(gcf);
end


function write_json(path,value)
fid=fopen(path,"w"); if fid<0, error("reqml:CannotWriteQ0Manifest", ...
        "Cannot write %s",path); end
cleanup=onCleanup(@() fclose(fid));
fprintf(fid,"%s\n",jsonencode(value,PrettyPrint=true));
end
