function report = validateDataset(dataset, design, coverage, config)
%VALIDATEDATASET Enforce the controlled homogeneous Q0 training gate.

arguments
    dataset (1,1) struct
    design (1,1) struct
    coverage (1,1) struct
    config (1,1) struct
end

examples=dataset.examples;
checks=table();
checks=add_check(checks,"condition_count", ...
    design.condition_count==240,design.condition_count,240);
checks=add_check(checks,"base_run_count",design.run_count==720, ...
    design.run_count,720);
checks=add_check(checks,"cartesian_cs_values", ...
    isequal(unique(design.conditions.cs_m_s),[1;2;3;4]), ...
    numel(unique(design.conditions.cs_m_s)),4);
checks=add_check(checks,"cartesian_frequency_values", ...
    isequal(unique(design.conditions.frequency_hz),[200;300;400;500;600]), ...
    numel(unique(design.conditions.frequency_hz)),5);
checks=add_check(checks,"cartesian_spacing_values", ...
    isequal(unique(design.conditions.dx_m),[.00025;.0003;.0005]), ...
    numel(unique(design.conditions.dx_m)),3);
expected_fields=sort(["single";"directional";"intermediate";"diffuse"]);
checks=add_check(checks,"cartesian_field_values", ...
    isequal(sort(unique(design.conditions.field_regime)),expected_fields), ...
    numel(unique(design.conditions.field_regime)),4);
checks=add_check(checks,"coverage_complete",coverage.complete, ...
    coverage.completed_condition_count,coverage.condition_count);
checks=add_check(checks,"unique_example_ids", ...
    numel(unique(string(examples.example_id)))==height(examples), ...
    numel(unique(string(examples.example_id))),height(examples));

keys=compose("%s__x%06d_z%06d",string(examples.campaign_run_id), ...
    double(examples.cx),double(examples.cz));
checks=add_check(checks,"unique_run_patch_centers", ...
    numel(unique(keys))==height(examples),numel(unique(keys)),height(examples));
checks=add_check(checks,"homogeneous_geometry_only", ...
    all(string(examples.campaign_geometry_family)=="homogeneous"), ...
    sum(string(examples.campaign_geometry_family)=="homogeneous"),height(examples));
checks=add_check(checks,"purity_is_one", ...
    all(abs(double(examples.truth_material_purity)-1)<=1e-12), ...
    max(abs(double(examples.truth_material_purity)-1)),0);
checks=add_check(checks,"req_M_is_two",all(double(examples.REQ_M)==2), ...
    numel(unique(double(examples.REQ_M))),1);
checks=add_check(checks,"req_cs_guess_is_three", ...
    all(abs(double(examples.REQ_cs_guess_m_s)-3)<=1e-12), ...
    max(abs(double(examples.REQ_cs_guess_m_s)-3)),0);
checks=add_check(checks,"target_valid",all(examples.target_valid), ...
    sum(examples.target_valid),height(examples));

report=struct("schema_name","reqml_homogeneous_dataset_validation", ...
    "schema_version","1.0","checks",checks,"valid",all(checks.pass), ...
    "example_count",height(examples),"condition_count",design.condition_count);
if ~report.valid
    failed=checks.name(~checks.pass);
    error("reqml:HomogeneousCartesianDatasetGateFailed", ...
        "Homogeneous dataset gate failed: %s",strjoin(failed,", "));
end
end


function checks=add_check(checks,name,pass,value,expected)
row=table(string(name),logical(pass),double(value),double(expected), ...
    VariableNames=["name","pass","value","expected"]);
if isempty(checks), checks=row; else, checks=[checks;row]; end
end
