function report = validateDataset(dataset, design, coverage, config)
%VALIDATEDATASET Enforce the controlled homogeneous Q0 training gate.

arguments
    dataset (1,1) struct
    design (1,1) struct
    coverage (1,1) struct
    config (1,1) struct
end

examples=dataset.examples;
expected_cs=sort(double(config.design.cs_m_s(:)));
expected_frequency=sort(double(config.design.frequency_hz(:)));
expected_spacing=sort(double(config.design.spacing_m(:)));
expected_fields=sort(string({config.field_regimes.name})');
expected_condition_count=numel(expected_cs)*numel(expected_frequency)* ...
    numel(expected_spacing)*numel(expected_fields);
expected_run_count=expected_condition_count*double( ...
    config.design.base_realizations_per_condition);
checks=table();
checks=add_check(checks,"condition_count", ...
    design.condition_count==expected_condition_count, ...
    design.condition_count,expected_condition_count);
checks=add_check(checks,"base_run_count",design.run_count==expected_run_count, ...
    design.run_count,expected_run_count);
checks=add_check(checks,"cartesian_cs_values", ...
    isequal(sort(unique(design.conditions.cs_m_s)),expected_cs), ...
    numel(unique(design.conditions.cs_m_s)),numel(expected_cs));
checks=add_check(checks,"cartesian_frequency_values", ...
    isequal(sort(unique(design.conditions.frequency_hz)),expected_frequency), ...
    numel(unique(design.conditions.frequency_hz)),numel(expected_frequency));
checks=add_check(checks,"cartesian_spacing_values", ...
    isequal(sort(unique(design.conditions.dx_m)),expected_spacing), ...
    numel(unique(design.conditions.dx_m)),numel(expected_spacing));
checks=add_check(checks,"cartesian_field_values", ...
    isequal(sort(unique(design.conditions.field_regime)),expected_fields), ...
    numel(unique(design.conditions.field_regime)),numel(expected_fields));
checks=add_check(checks,"planned_extracted_geometry_match", ...
    isfield(coverage,"geometry_match") && coverage.geometry_match, ...
    geometry_mismatch_count(coverage),0);
checks=add_check(checks,"coverage_complete",coverage.complete, ...
    coverage.completed_condition_count,coverage.condition_count);
checks=add_check(checks,"unique_example_ids", ...
    numel(unique(string(examples.example_id)))==height(examples), ...
    numel(unique(string(examples.example_id))),height(examples));

keys=compose("%s__x%06d_z%06d",string(examples.campaign_run_id), ...
    double(examples.cx),double(examples.cz));
checks=add_check(checks,"unique_run_patch_centers", ...
    numel(unique(keys))==height(examples),numel(unique(keys)),height(examples));
checks=add_check(checks,"homogeneous_geometry_only", ...
    all(string(examples.campaign_geometry_family)=="homogeneous"), ...
    sum(string(examples.campaign_geometry_family)=="homogeneous"),height(examples));
checks=add_check(checks,"purity_is_one", ...
    all(abs(double(examples.truth_material_purity)-1)<=1e-12), ...
    max(abs(double(examples.truth_material_purity)-1)),0);
expected_M=double(config.req.M);
expected_cs_guess=double(config.req.cs_guess_m_s);
checks=add_check(checks,"req_M_matches_config", ...
    all(double(examples.REQ_M)==expected_M), ...
    max(abs(double(examples.REQ_M)-expected_M)),0);
checks=add_check(checks,"req_cs_guess_matches_config", ...
    all(abs(double(examples.REQ_cs_guess_m_s)-expected_cs_guess)<=1e-12), ...
    max(abs(double(examples.REQ_cs_guess_m_s)-expected_cs_guess)),0);
checks=add_check(checks,"target_valid",all(examples.target_valid), ...
    sum(examples.target_valid),height(examples));

report=struct("schema_name","reqml_homogeneous_dataset_validation", ...
    "schema_version","1.0","checks",checks,"valid",all(checks.pass), ...
    "example_count",height(examples),"condition_count",design.condition_count);
if ~report.valid
    failed=checks.name(~checks.pass);
    error("reqml:HomogeneousCartesianDatasetGateFailed", ...
        "Homogeneous dataset gate failed: %s",strjoin(failed,", "));
end


function count=geometry_mismatch_count(coverage)
if isfield(coverage,"geometry_mismatch_count")
    count=double(coverage.geometry_mismatch_count);
else
    count=Inf;
end
end
end


function checks=add_check(checks,name,pass,value,expected)
row=table(string(name),logical(pass),double(value),double(expected), ...
    VariableNames=["name","pass","value","expected"]);
if isempty(checks), checks=row; else, checks=[checks;row]; end
end
