function result = advanceAdaptiveIteration( ...
    previous_csv, new_csv_files, ...
    feat_cfg, campaign_config, options)
%ADVANCEADAPTIVEITERATION Accumulate new runs and plan the next iteration.
%
% Workflow:
%
%   previous accumulated campaign CSV
%       + newly executed campaign CSVs
%       -> deduplicated accumulated CSV
%       -> dataset
%       -> coverage
%       -> next adaptive batch

arguments
    previous_csv (1,1) string
    new_csv_files (:,1) string
    feat_cfg (1,1) struct
    campaign_config (1,1) struct

    options.OutputDirectory {mustBeTextScalar}
    options.IterationId (1,1) string
    options.PlannerSeed (1,1) double

    options.PurityEdges (1,:) double
    options.DiffusivityEdges (1,:) double
    options.SwsEdges (1,:) double
    options.FrequencyEdges (1,:) double

    options.MinimumExamples (1,1) double = 500
    options.MinimumIndependentRuns (1,1) double = 5
    options.MinimumSwsBins (1,1) double = 3
    options.MinimumFrequencyBins (1,1) double = 3
    options.MinimumIndependentConditions (1,1) double = 3
    options.MinimumGeometrySeeds (1,1) double = 0

    options.MaximumConditions (1,1) double = 20
    options.RealizationsPerCondition (1,1) double = 2

    options.ParentCoverageReportHash (1,1) string = ""
end

if ~isfile(previous_csv)
    error("reqml:PreviousAdaptiveCampaignCsvNotFound", ...
        "Previous accumulated campaign CSV was not found: %s", ...
        previous_csv);
end

if isempty(new_csv_files)
    error("reqml:EmptyNewAdaptiveCampaignCsvList", ...
        "At least one newly executed campaign CSV is required.");
end

output_directory = string(options.OutputDirectory);

if isfolder(output_directory)
    error("reqml:AdaptiveIterationOutputExists", ...
        "Adaptive iteration output already exists: %s", ...
        output_directory);
end

[created, message] = mkdir(output_directory);

if ~created
    error("reqml:AdaptiveIterationDirectoryCreateFailed", ...
        "Could not create output directory '%s': %s", ...
        output_directory, message);
end

accumulated_csv = fullfile( ...
    output_directory, ...
    "accumulated_campaign_runs.csv");

merge_result = ...
    reqml.campaigns.mergeCampaignRunCsvs( ...
        [previous_csv; new_csv_files], ...
        OutputFile=accumulated_csv);

iteration_result = ...
    reqml.campaigns.runAdaptiveIteration( ...
        accumulated_csv, ...
        feat_cfg, ...
        campaign_config, ...
        OutputDirectory=output_directory, ...
        IterationId=options.IterationId, ...
        PlannerSeed=options.PlannerSeed, ...
        PurityEdges=options.PurityEdges, ...
        DiffusivityEdges=options.DiffusivityEdges, ...
        SwsEdges=options.SwsEdges, ...
        FrequencyEdges=options.FrequencyEdges, ...
        MinimumExamples=options.MinimumExamples, ...
        MinimumIndependentRuns= ...
            options.MinimumIndependentRuns, ...
        MinimumSwsBins=options.MinimumSwsBins, ...
        MinimumFrequencyBins= ...
            options.MinimumFrequencyBins, ...
        MinimumIndependentConditions= ...
            options.MinimumIndependentConditions, ...
        MinimumGeometrySeeds= ...
            options.MinimumGeometrySeeds, ...
        MaximumConditions=options.MaximumConditions, ...
        RealizationsPerCondition= ...
            options.RealizationsPerCondition, ...
        ParentCoverageReportHash= ...
            options.ParentCoverageReportHash);

result = struct();

result.schema_name = ...
    "reqml_adaptive_iteration_advance";

result.schema_version = "1.0";
result.iteration_id = options.IterationId;

result.previous_run_count = ...
    merge_result.input_row_count - ...
    sum(cellfun(@height, read_new_tables(new_csv_files)));

result.new_input_file_count = ...
    numel(new_csv_files);

result.accumulated_run_count = ...
    merge_result.output_row_count;

result.duplicate_run_count = ...
    merge_result.duplicate_row_count;

result.merge = merge_result;
result.iteration = iteration_result;

result.paths = iteration_result.paths;
result.paths.accumulated_campaign_csv = ...
    string(accumulated_csv);

end


function tables = read_new_tables(files)

tables = cell(numel(files), 1);

for index = 1:numel(files)
    tables{index} = readtable( ...
        files(index), ...
        Delimiter=",", ...
        TextType="string");
end

end
