function result = advanceAdaptiveIteration( ...
    previous_csv, new_csv_files, ...
    feat_cfg, campaign_config, options)
%ADVANCEADAPTIVEITERATION Accumulate new runs and plan the next iteration.
%
% Workflow:
%
%   previous accumulated campaign CSV
%       + newly executed campaign CSVs
%       -> deduplicated accumulated CSV
%       -> dataset
%       -> coverage
%       -> next adaptive batch

arguments
    previous_csv (1,1) string
    new_csv_files (:,1) string
    feat_cfg (1,1) struct
    campaign_config (1,1) struct

    options.OutputDirectory {mustBeTextScalar}
    options.IterationId (1,1) string
    options.PlannerSeed (1,1) double

    options.PurityEdges (1,:) double
    options.DiffusivityEdges (1,:) double
    options.SwsEdges (1,:) double
    options.FrequencyEdges (1,:) double

    options.DiscretizationPairsM (:,2) double = ...
        [ ...
        0.0005 0.0005]

    options.MinimumExamples (1,1) double = 500
    options.MinimumIndependentRuns (1,1) double = 5
    options.MinimumSwsBins (1,1) double = 3
    options.MinimumFrequencyBins (1,1) double = 3
    options.MinimumIndependentConditions (1,1) double = 3
    options.MinimumGeometrySeeds (1,1) double = 0

    options.MaximumConditions (1,1) double = 20
    options.RealizationsPerCondition (1,1) double = 2

    options.UseDirectedCenterSelection (1,1) logical = false
    options.CandidateStepPixels (1,1) double = 2
    options.MaximumCentersPerCell (1,1) double = 4
    options.MinimumCenterDistanceFraction (1,1) double = 0.5
    options.MinimumValidFraction (1,1) double = 1
    options.CenterSelectionSeedOffset (1,1) double = 0
    options.CenterSelectionMode (1,1) string = "default"
    options.MaximumCentersPerRun (1,1) double = 12
    options.MaximumCentersPerCellPerRun (1,1) double = 2
    options.MinimumCenterSeparationFraction (1,1) double = 0.75
    options.AnalyticToOpportunisticSeparationFraction (1,1) double = 0.25
    options.DifferentCellSeparationFraction (1,1) double = 0.25
    options.SameCellSeparationFraction (1,1) double = 0.50
    options.UseSampleParfor (1,1) logical = false

    options.ParentCoverageReportHash (1,1) string = ""

    options.ExecutedBatchPlanFile (1,1) string = ""
    options.PreviousDatasetDirectory (1,1) string = ""
    options.PreviousCoverageReportFile (1,1) string = ""

    % Dependency injection for orchestration tests.
    options.RunIterationFunction (1,1) function_handle = ...
        @reqml.campaigns.runAdaptiveIteration
end

has_previous_csv = ...
    strlength(previous_csv) > 0;

if has_previous_csv && ...
        ~isfile(previous_csv)

    error("reqml:PreviousAdaptiveCampaignCsvNotFound", ...
        "Previous accumulated campaign CSV was not found: %s", ...
        previous_csv);
end

if isempty(new_csv_files)
    error("reqml:EmptyNewAdaptiveCampaignCsvList", ...
        "At least one newly executed campaign CSV is required.");
end

output_directory = string(options.OutputDirectory);

if isfolder(output_directory)
    error("reqml:AdaptiveIterationOutputExists", ...
        "Adaptive iteration output already exists: %s", ...
        output_directory);
end

[created, message] = mkdir(output_directory);

if ~created
    error("reqml:AdaptiveIterationDirectoryCreateFailed", ...
        "Could not create output directory '%s': %s", ...
        output_directory, message);
end

accumulated_csv = fullfile( ...
    output_directory, ...
    "accumulated_campaign_runs.csv");

if has_previous_csv
    merge_inputs = ...
        [previous_csv; new_csv_files];
else
    merge_inputs = ...
        new_csv_files;
end

merge_result = ...
    reqml.campaigns.mergeCampaignRunCsvs( ...
        merge_inputs, ...
        OutputFile=accumulated_csv);

iteration_result = ...
    feval( ...
        options.RunIterationFunction, ...
        accumulated_csv, ...
        feat_cfg, ...
        campaign_config, ...
        OutputDirectory=output_directory, ...
        IterationId=options.IterationId, ...
        PlannerSeed=options.PlannerSeed, ...
        PurityEdges=options.PurityEdges, ...
        DiffusivityEdges=options.DiffusivityEdges, ...
        SwsEdges=options.SwsEdges, ...
        FrequencyEdges=options.FrequencyEdges, ...
        DiscretizationPairsM= ...
            options.DiscretizationPairsM, ...
        MinimumExamples=options.MinimumExamples, ...
        MinimumIndependentRuns= ...
            options.MinimumIndependentRuns, ...
        MinimumSwsBins=options.MinimumSwsBins, ...
        MinimumFrequencyBins= ...
            options.MinimumFrequencyBins, ...
        MinimumIndependentConditions= ...
            options.MinimumIndependentConditions, ...
        MinimumGeometrySeeds= ...
            options.MinimumGeometrySeeds, ...
        MaximumConditions=options.MaximumConditions, ...
        RealizationsPerCondition= ...
            options.RealizationsPerCondition, ...
        UseDirectedCenterSelection= ...
            options.UseDirectedCenterSelection, ...
        CandidateStepPixels= ...
            options.CandidateStepPixels, ...
        MaximumCentersPerCell= ...
            options.MaximumCentersPerCell, ...
        MinimumCenterDistanceFraction= ...
            options.MinimumCenterDistanceFraction, ...
        MinimumValidFraction= ...
            options.MinimumValidFraction, ...
        CenterSelectionSeedOffset= ...
            options.CenterSelectionSeedOffset, ...
        CenterSelectionMode=options.CenterSelectionMode, ...
        MaximumCentersPerRun=options.MaximumCentersPerRun, ...
        MaximumCentersPerCellPerRun= ...
            options.MaximumCentersPerCellPerRun, ...
        MinimumCenterSeparationFraction= ...
            options.MinimumCenterSeparationFraction, ...
        AnalyticToOpportunisticSeparationFraction= ...
            options.AnalyticToOpportunisticSeparationFraction, ...
        DifferentCellSeparationFraction= ...
            options.DifferentCellSeparationFraction, ...
        SameCellSeparationFraction=options.SameCellSeparationFraction, ...
        UseSampleParfor= ...
            options.UseSampleParfor, ...
        ParentCoverageReportHash= ...
            options.ParentCoverageReportHash, ...
        ExecutedBatchPlanFile= ...
            options.ExecutedBatchPlanFile, ...
        PreviousDatasetDirectory= ...
            options.PreviousDatasetDirectory, ...
        PreviousCoverageReportFile= ...
            options.PreviousCoverageReportFile);

result = struct();

result.schema_name = ...
    "reqml_adaptive_iteration_advance";

result.schema_version = "1.0";
result.iteration_id = options.IterationId;

if has_previous_csv
    previous_table = readtable( ...
        previous_csv, ...
        Delimiter=",", ...
        TextType="string");

    result.previous_run_count = ...
        height(previous_table);
else
    result.previous_run_count = 0;
end

result.new_input_file_count = ...
    numel(new_csv_files);

result.accumulated_run_count = ...
    merge_result.output_row_count;

result.duplicate_run_count = ...
    merge_result.duplicate_row_count;

result.merge = merge_result;
result.iteration = iteration_result;

result.paths = iteration_result.paths;
result.paths.accumulated_campaign_csv = ...
    string(accumulated_csv);

end
