function result = generateAdaptiveBootstrap( ...
    coverage, campaign_config, options)
%GENERATEADAPTIVEBOOTSTRAP Generate an auditable initial adaptive batch.
%
% Workflow:
%
%   coverage specification
%       -> deterministic bootstrap requests
%       -> backend-neutral physical conditions
%       -> adaptive batch plan and simulation campaigns
%
% This function writes campaign definitions but does not execute them.

arguments
    coverage (1,1) struct
    campaign_config (1,1) struct

    options.OutputDirectory {mustBeTextScalar}
    options.BatchId (1,1) string

    options.PlannerSeed (1,1) double = 1

    options.RealizationsPerCondition (1,1) double = 2

    options.GeometryFamilies (1,:) string = ...
        ["homogeneous", ...
         "bilayer", ...
         "circular_inclusion"]

    options.PurityCycleStride (1,1) double = 1
    options.DiffusivityCycleStride (1,1) double = 2

    options.DomainLxM (1,1) double = 0.05
    options.DomainLzM (1,1) double = 0.05

    options.BackgroundSwsRangeMPerS (1,2) double = ...
        [1.5 4.0]

    options.MinimumContrastMPerS (1,1) double = 0.5

    options.InclusionRadiusRangeM (1,2) double = ...
        [0.004 0.012]

    options.BilayerOffsetRangeM (1,2) double = ...
        [0.015 0.035]

    options.DirectionCounts (1,:) double = ...
        [1 16 32]

    options.InPlaneCounts (1,:) double = ...
        [1 4 8]

    options.SolidAnglesSr (1,:) double = ...
        [0.01 pi 4*pi]

    options.MaximumDirectionCount (1,1) double = 128

    options.MinimumSolidAngleSr (1,1) double = 0.01

    options.MaximumSolidAngleSr (1,1) double = 4*pi
end

validate_options(options);

output_directory = string(options.OutputDirectory);

if isfolder(output_directory)
    existing = dir(output_directory);

    existing_names = string({existing.name});

    existing = existing( ...
        ~ismember(existing_names, [".", ".."]));

    if ~isempty(existing)
        error( ...
            "reqml:AdaptiveBootstrapOutputExists", ...
            "Bootstrap output directory already contains artifacts: %s", ...
            output_directory);
    end
end

requests = ...
    reqml.campaigns.makeBootstrapConditionRequests( ...
        coverage, ...
        BatchId=options.BatchId, ...
        PlannerSeed=options.PlannerSeed, ...
        RealizationsPerCondition= ...
            options.RealizationsPerCondition, ...
        GeometryFamilies=options.GeometryFamilies, ...
        PurityCycleStride= ...
            options.PurityCycleStride, ...
        DiffusivityCycleStride= ...
            options.DiffusivityCycleStride);

physical_conditions = ...
    reqml.campaigns.materializePhysicalConditions( ...
        requests, ...
        DomainLxM=options.DomainLxM, ...
        DomainLzM=options.DomainLzM, ...
        BackgroundSwsRangeMPerS= ...
            options.BackgroundSwsRangeMPerS, ...
        MinimumContrastMPerS= ...
            options.MinimumContrastMPerS, ...
        InclusionRadiusRangeM= ...
            options.InclusionRadiusRangeM, ...
        BilayerOffsetRangeM= ...
            options.BilayerOffsetRangeM, ...
        DirectionCounts=options.DirectionCounts, ...
        InPlaneCounts=options.InPlaneCounts, ...
        SolidAnglesSr=options.SolidAnglesSr, ...
        MaximumDirectionCount= ...
            options.MaximumDirectionCount, ...
        MinimumSolidAngleSr= ...
            options.MinimumSolidAngleSr, ...
        MaximumSolidAngleSr= ...
            options.MaximumSolidAngleSr, ...
        PlannerSeed=options.PlannerSeed);

paths = reqml.campaigns.writeAdaptiveBatch( ...
    physical_conditions, ...
    campaign_config, ...
    OutputDirectory=output_directory, ...
    BatchId=options.BatchId, ...
    PlannerSeed=options.PlannerSeed, ...
    ParentCoverageReportHash="");

run_count = sum(arrayfun( ...
    @(condition) double(condition.realization_count), ...
    physical_conditions));

result = struct();

result.schema_name = ...
    "reqml_adaptive_bootstrap_result";

result.schema_version = "1.0";

result.batch_id = options.BatchId;
result.planner_seed = options.PlannerSeed;

result.request_count = numel(requests);
result.condition_count = numel(physical_conditions);
result.run_count = run_count;

result.requests = requests;
result.physical_conditions = physical_conditions;
result.paths = paths;

end


function validate_options(options)

if strlength(options.BatchId) == 0
    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "BatchId must be non-empty.");
end

validate_nonnegative_integer( ...
    options.PlannerSeed, ...
    "PlannerSeed");

validate_positive_integer( ...
    options.RealizationsPerCondition, ...
    "RealizationsPerCondition");

validate_positive_integer( ...
    options.PurityCycleStride, ...
    "PurityCycleStride");

validate_positive_integer( ...
    options.DiffusivityCycleStride, ...
    "DiffusivityCycleStride");

if options.DomainLxM <= 0 || ...
        options.DomainLzM <= 0

    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "Domain dimensions must be positive.");
end

end


function validate_nonnegative_integer(value, name)

if ~isfinite(value) || ...
        value < 0 || ...
        value ~= fix(value)

    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "%s must be a nonnegative integer.", ...
        name);
end

end


function validate_positive_integer(value, name)

if ~isfinite(value) || ...
        value < 1 || ...
        value ~= fix(value)

    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "%s must be a positive integer.", ...
        name);
end

end
