function requests = makeBootstrapConditionRequests(coverage, options)
%MAKEBOOTSTRAPCONDITIONREQUESTS Create a deterministic 5-D bootstrap design.
%
% The bootstrap creates one condition for every configured:
%
%   SWS bin x frequency bin x spatial-discretization bin
%
% Purity, nominal angular coverage, and geometry family are distributed
% deterministically across those physical blocks. The adaptive loop then
% fills the remaining explicit 5-D coverage cells.
%
% Output requests follow the same contract as:
%
%   reqml.campaigns.mapDeficitsToConditionRequests

arguments
    coverage (1,1) struct

    options.BatchId (1,1) string = ...
        "adaptive_bootstrap"

    options.PlannerSeed (1,1) double = 1

    options.RealizationsPerCondition (1,1) double = 2

    options.GeometryFamilies (1,:) string = ...
        ["homogeneous", ...
         "bilayer", ...
         "circular_inclusion"]

    options.PurityCycleStride (1,1) double = 1

    options.DiffusivityCycleStride (1,1) double = 2
end

validate_coverage(coverage);
validate_options(options);

sws_edges = ...
    double(coverage.sws_edges_m_s(:))';

frequency_edges = ...
    double(coverage.frequency_edges_hz(:))';

purity_edges = ...
    double(coverage.purity_edges(:))';

diffusivity_edges = double( ...
    coverage.nominal_angular_coverage_edges(:))';

discretization_pairs_m = double( ...
    coverage.discretization_pairs_m);

sws_bin_count = numel(sws_edges) - 1;
frequency_bin_count = numel(frequency_edges) - 1;
purity_bin_count = numel(purity_edges) - 1;
diffusivity_bin_count = numel(diffusivity_edges) - 1;
discretization_bin_count = size(discretization_pairs_m, 1);

request_count = ...
    sws_bin_count * ...
    frequency_bin_count * ...
    discretization_bin_count;

requests = repmat( ...
    empty_request(), ...
    request_count, ...
    1);

ordinal = 0;

for sws_bin = 1:sws_bin_count
    for frequency_bin = 1:frequency_bin_count
        for discretization_bin = 1:discretization_bin_count
            ordinal = ordinal + 1;

        purity_bin = cycle_bin( ...
            ordinal, ...
            purity_bin_count, ...
            options.PurityCycleStride);

        diffusivity_bin = cycle_bin( ...
            ordinal, ...
            diffusivity_bin_count, ...
            options.DiffusivityCycleStride);

        geometry_index = ...
            mod(ordinal - 1, ...
                numel(options.GeometryFamilies)) + 1;

        request = empty_request();

        request.condition_id = sprintf( ...
            "%s_s%02d_f%02d_p%02d_d%02d_g%02d_%03d", ...
            options.BatchId, ...
            sws_bin, ...
            frequency_bin, ...
            purity_bin, ...
            diffusivity_bin, ...
            discretization_bin, ...
            ordinal);

        request.priority_rank = ordinal;
        request.deficit_score = 1;

        request.sws_bin = sws_bin;
        request.frequency_bin = frequency_bin;

        request.purity_bin = purity_bin;
        request.purity_range = ...
            bin_range(purity_edges, purity_bin);

        request.diffusivity_bin = ...
            diffusivity_bin;

        request.diffusivity_range = ...
            bin_range( ...
                diffusivity_edges, ...
                diffusivity_bin);

        request.discretization_bin = ...
            discretization_bin;

        request.target_grid_spacing_m = ...
            discretization_pairs_m( ...
                discretization_bin, :);

        request.nominal_angular_coverage_range = ...
            request.diffusivity_range;

        request.geometry_family = ...
            options.GeometryFamilies(geometry_index);

        request.field_regime = ...
            "continuous_dnom";

        request.target_sws_range_m_s = ...
            bin_range(sws_edges, sws_bin);

        request.target_frequency_range_hz = ...
            bin_range( ...
                frequency_edges, ...
                frequency_bin);

        request.realization_count = ...
            options.RealizationsPerCondition;

        request.planner_seed = ...
            options.PlannerSeed;

        request.source_example_deficit = 0;
        request.source_run_deficit = 0;
        request.source_condition_deficit = 0;

        request.requested_cell_key = compose( ...
            "s%02d_f%02d_p%02d_d%02d_g%02d", ...
            sws_bin, frequency_bin, purity_bin, ...
            diffusivity_bin, discretization_bin);
        request.residual_example_deficit = 2*options.RealizationsPerCondition;
        request.residual_independent_run_deficit = ...
            options.RealizationsPerCondition;
        request.residual_independent_condition_deficit = 1;
        request.planned_action = "new_condition";
        request.planned_realization_count = options.RealizationsPerCondition;
        request.planned_new_condition_count = 1;
        request.reason_for_repeat = "bootstrap new physical condition";
        request.expected_example_contribution = ...
            2*options.RealizationsPerCondition;
        request.expected_independent_run_contribution = ...
            options.RealizationsPerCondition;
        request.expected_independent_condition_contribution = 1;
        request.realization_start_index = 1;

        requests(ordinal) = request;
        end
    end
end

end


function bin_index = cycle_bin( ...
        ordinal, bin_count, stride)

bin_index = ...
    mod((ordinal - 1) * stride, bin_count) + 1;

end


function range = bin_range(edges, bin_index)

range = [
    edges(bin_index)
    edges(bin_index + 1)
    ]';

end


function validate_coverage(coverage)

required = [
    "sws_edges_m_s"
    "frequency_edges_hz"
    "purity_edges"
    "nominal_angular_coverage_edges"
    "discretization_pairs_m"
    ];

missing = setdiff( ...
    required, ...
    string(fieldnames(coverage)));

if ~isempty(missing)
    error( ...
        "reqml:InvalidAdaptiveBootstrapCoverage", ...
        "Bootstrap coverage is missing field '%s'.", ...
        missing(1));
end

validate_edges( ...
    coverage.sws_edges_m_s, ...
    "coverage.sws_edges_m_s");

validate_edges( ...
    coverage.frequency_edges_hz, ...
    "coverage.frequency_edges_hz");

validate_edges( ...
    coverage.purity_edges, ...
    "coverage.purity_edges");

validate_edges( ...
    coverage.nominal_angular_coverage_edges, ...
    "coverage.nominal_angular_coverage_edges");

validate_discretization_pairs( ...
    coverage.discretization_pairs_m);

end


function validate_discretization_pairs(pairs_m)

pairs_m = double(pairs_m);

if isempty(pairs_m) || ...
        size(pairs_m, 2) ~= 2 || ...
        any(~isfinite(pairs_m), "all") || ...
        any(pairs_m <= 0, "all")
    error("reqml:InvalidAdaptiveBootstrapCoverage", ...
        "coverage.discretization_pairs_m must be a finite positive N-by-2 matrix.");
end

if size(unique(pairs_m, "rows"), 1) ~= size(pairs_m, 1)
    error("reqml:InvalidAdaptiveBootstrapCoverage", ...
        "coverage.discretization_pairs_m must not contain duplicates.");
end

end


function validate_options(options)

if strlength(options.BatchId) == 0
    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "BatchId must be non-empty.");
end

validate_nonnegative_integer( ...
    options.PlannerSeed, ...
    "PlannerSeed");

validate_positive_integer( ...
    options.RealizationsPerCondition, ...
    "RealizationsPerCondition");

validate_positive_integer( ...
    options.PurityCycleStride, ...
    "PurityCycleStride");

validate_positive_integer( ...
    options.DiffusivityCycleStride, ...
    "DiffusivityCycleStride");

if isempty(options.GeometryFamilies) || ...
        any(strlength(options.GeometryFamilies) == 0)

    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "GeometryFamilies must contain nonempty names.");
end

supported = [
    "homogeneous"
    "bilayer"
    "circular_inclusion"
    ];

if any(~ismember(options.GeometryFamilies, supported))
    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "GeometryFamilies contains an unsupported family.");
end

end


function validate_edges(edges, name)

edges = double(edges(:))';

if numel(edges) < 2 || ...
        any(~isfinite(edges)) || ...
        any(diff(edges) <= 0)

    error( ...
        "reqml:InvalidAdaptiveBootstrapCoverage", ...
        "%s must contain finite increasing values.", ...
        name);
end

end


function validate_nonnegative_integer(value, name)

if ~isfinite(value) || ...
        value < 0 || ...
        value ~= fix(value)

    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "%s must be a nonnegative integer.", ...
        name);
end

end


function validate_positive_integer(value, name)

if ~isfinite(value) || ...
        value < 1 || ...
        value ~= fix(value)

    error( ...
        "reqml:InvalidAdaptiveBootstrapOption", ...
        "%s must be a positive integer.", ...
        name);
end

end


function request = empty_request()

request = struct( ...
    "condition_id", "", ...
    "priority_rank", 0, ...
    "deficit_score", NaN, ...
    "sws_bin", 0, ...
    "frequency_bin", 0, ...
    "purity_bin", 0, ...
    "purity_range", [NaN, NaN], ...
    "diffusivity_bin", 0, ...
    "diffusivity_range", [NaN, NaN], ...
    "discretization_bin", 0, ...
    "target_grid_spacing_m", [NaN, NaN], ...
    "nominal_angular_coverage_range", [NaN, NaN], ...
    "geometry_family", "", ...
    "field_regime", "", ...
    "target_sws_range_m_s", [NaN, NaN], ...
    "target_frequency_range_hz", [NaN, NaN], ...
    "realization_count", 0, ...
    "planner_seed", 0, ...
    "source_example_deficit", 0, ...
    "source_run_deficit", 0, ...
    "source_condition_deficit", 0);
request.requested_cell_key = "";
request.residual_example_deficit = 0;
request.residual_independent_run_deficit = 0;
request.residual_independent_condition_deficit = 0;
request.planned_action = "new_condition";
request.planned_realization_count = 0;
request.planned_new_condition_count = 0;
request.reason_for_repeat = "";
request.expected_example_contribution = 0;
request.expected_independent_run_contribution = 0;
request.expected_independent_condition_contribution = 0;
request.realization_start_index = 1;

end
