function conditions = materializePhysicalConditions(requests, options)
%MATERIALIZEPHYSICALCONDITIONS Convert abstract requests into physical conditions.
%
% This function is backend independent. It does not produce simulator paths
% or campaign overrides.
%
% Each output condition contains:
%
%   condition_id
%   realization_count
%   seed
%   geometry
%   material
%   wavefield
%   requested_coverage

arguments
    requests (:,1) struct

    options.DomainLxM (1,1) double = 0.05
    options.DomainLzM (1,1) double = 0.05

    options.BackgroundSwsRangeMPerS (1,2) double = [1.5 4.0]

    options.MinimumContrastMPerS (1,1) double = 0.5

    options.InclusionRadiusRangeM (1,2) double = [0.004 0.012]

    options.BilayerOffsetRangeM (1,2) double = [0.015 0.035]

    options.DirectionCounts (1,:) double = [1 16 32]

    options.InPlaneCounts (1,:) double = [1 4 8]

    options.SolidAnglesSr (1,:) double = ...
        [0.01 pi 4*pi]

    options.MaximumDirectionCount (1,1) double = 128

    options.MinimumSolidAngleSr (1,1) double = 0.01

    options.MaximumSolidAngleSr (1,1) double = 4*pi

    options.AngularAxisMode (1,1) string = "fixed"
    options.FixedAngularAxisXYZ (1,3) double = [1 0 0]

    options.InPlanePolicy (1,1) string = "legacy_sqrt"
    options.InPlaneFraction (1,1) double = 0.25

    options.TrainingGeometryMode (1,1) string = ...
        "legacy_balanced"

    options.GridSpacingM (1,2) double = [0.0005 0.0005]

    options.PatchWindowWavelengths (1,1) double = 3

    options.CsGuessMPerS (1,1) double = 3.0

    options.SelectedPatchCenterIndicesXZ (1,2) double = ...
        [NaN NaN]

    options.InterfaceOrientation (1,1) string = "x"

    options.MinimumDomainMarginPixels (1,1) double = 0

    options.PackingMode (1,1) string = "geometric_center"
    options.DomainPolicyMode (1,1) string = "fixed"
    options.DefaultDomainSizeM (1,2) double = [0.05 0.05]
    options.ExpandedDomainSizeM (1,2) double = [0.07 0.07]
    options.MinimumPackableCenters (1,1) double = 2
    options.AnalyticToOpportunisticSeparationFraction (1,1) double = 0.25
    options.StableConditionSeedFromId (1,1) logical = false

    options.PlannerSeed (1,1) double = 1
end

validate_options(options);

if isempty(requests)
    conditions = repmat(empty_condition(), 0, 1);
    return
end

conditions = repmat( ...
    empty_condition(), ...
    numel(requests), ...
    1);

for index = 1:numel(requests)
    request = requests(index);

    validate_request(request);

    if options.StableConditionSeedFromId
        condition_seed = deterministic_condition_seed(request.condition_id);
    else
        condition_seed = deterministic_seed(options.PlannerSeed,index);
    end

    stream = RandStream( ...
        "Threefry", ...
        Seed=condition_seed);

    target_sws = sample_requested_value( ...
        stream, ...
        request.target_sws_range_m_s, ...
        options.BackgroundSwsRangeMPerS);

    frequency_hz = sample_requested_value( ...
        stream, ...
        request.target_frequency_range_hz, ...
        [200 600]);

    target_dnom_range = ...
        resolve_target_dnom_range(request);

    field = materialize_field( ...
        stream, ...
        target_dnom_range, ...
        options);

    [material, geometry, geometry_control] = materialize_geometry( ...
        stream, ...
        string(request.geometry_family), ...
        target_sws, ...
        frequency_hz, ...
        double(request.purity_range),request, ...
        options);

    condition = empty_condition();

    condition.condition_id = ...
        string(request.condition_id);

    condition.realization_count = ...
        double(request.realization_count);
    condition.realization_start_index = ...
        resolve_request_scalar(request,"realization_start_index",1);

    condition.seed = condition_seed;

    condition.geometry = geometry;
    condition.material = material;
    condition.geometry_control = geometry_control;

    condition.wavefield.frequency_hz = ...
        frequency_hz;

    condition.wavefield.direction_count = ...
        field.direction_count;

    condition.wavefield.in_plane_count = ...
        field.in_plane_count;

    condition.wavefield.solid_angle_sr = ...
        field.solid_angle_sr;

    condition.wavefield.nominal_angular_coverage = ...
        field.nominal_angular_coverage;

    condition.wavefield.maximum_direction_count = ...
        field.maximum_direction_count;

    condition.wavefield.axis_mode = ...
        field.axis_mode;

    condition.wavefield.axis_xyz = ...
        field.axis_xyz;

    condition.wavefield.axis_angle_rad = ...
        field.axis_angle_rad;

    condition.wavefield.in_plane_policy = ...
        field.in_plane_policy;

    condition.wavefield.in_plane_fraction = ...
        field.in_plane_fraction;

    condition.requested_coverage = struct();

    condition.requested_coverage.sws_bin = ...
        double(request.sws_bin);

    condition.requested_coverage.sws_range_m_s = ...
        double(request.target_sws_range_m_s);

    condition.requested_coverage.frequency_bin = ...
        double(request.frequency_bin);

    condition.requested_coverage.frequency_range_hz = ...
        double(request.target_frequency_range_hz);

    condition.requested_coverage.purity_bin = ...
        double(request.purity_bin);

    condition.requested_coverage.purity_range = ...
        double(request.purity_range);

    condition.requested_coverage.diffusivity_bin = ...
        double(request.diffusivity_bin);

    condition.requested_coverage.diffusivity_range = ...
        double(request.diffusivity_range);

    condition.requested_coverage.nominal_angular_coverage_range = ...
        double(request.diffusivity_range);

    condition.requested_coverage.deficit_score = ...
        double(request.deficit_score);

    metadata_names=["requested_cell_key","residual_example_deficit", ...
        "residual_independent_run_deficit", ...
        "residual_independent_condition_deficit","planned_action", ...
        "planned_realization_count","planned_new_condition_count", ...
        "reason_for_repeat","expected_example_contribution", ...
        "expected_independent_run_contribution", ...
        "expected_independent_condition_contribution"];
    for metadata_name=metadata_names
        if isfield(request,metadata_name)
            condition.requested_coverage.(metadata_name)= ...
                request.(metadata_name);
        end
    end

    conditions(index) = condition;
end

end


function [material, geometry, geometry_control] = materialize_geometry( ...
        stream, family, target_sws, frequency_hz, ...
        requested_purity_range, request, options)

material = struct();
geometry = struct();
geometry_control = empty_geometry_control();

material.background_cs_m_s = target_sws;
material.object_cs_m_s = NaN;

geometry.family = family;
geometry.radius_m = NaN;
geometry.center_xz_m = [NaN NaN];
geometry.normal_angle_rad = NaN;
geometry.offset_m = NaN;

switch family
    case "homogeneous"
        return

    case "bilayer"
        if options.TrainingGeometryMode == "analytic_bilayer"
            [material, geometry, geometry_control] = ...
                materialize_analytic_bilayer( ...
                    stream, target_sws, frequency_hz, ...
                    requested_purity_range,request,options);
        else
            object_sws = sample_contrasting_sws( ...
                stream, ...
                target_sws, ...
                options);

            material.object_cs_m_s = object_sws;

            geometry.normal_angle_rad = ...
                2*pi*rand(stream);

            geometry.offset_m = ...
                materialize_bilayer_offset( ...
                    stream, ...
                    geometry.normal_angle_rad, ...
                    target_sws, ...
                    frequency_hz, ...
                    requested_purity_range, ...
                    options);
        end

    case "circular_inclusion"
        object_sws = sample_contrasting_sws( ...
            stream, ...
            target_sws, ...
            options);

        material.object_cs_m_s = object_sws;

        [center_x, center_z, radius_m] = ...
            optimize_inclusion_geometry( ...
                stream, ...
                requested_purity_range, ...
                target_sws, ...
                frequency_hz, ...
                options);

        geometry.radius_m = radius_m;
        geometry.center_xz_m = [center_x center_z];

    otherwise
        error("reqml:UnsupportedPhysicalGeometryFamily", ...
            "Unsupported geometry family '%s'.", ...
            family);
end

end


function [material, geometry, control] = ...
        materialize_analytic_bilayer( ...
            stream, target_sws, frequency_hz, ...
            requested_purity_range,request,options)

if rand(stream) < 0.5
    dominant_side = "negative";
else
    dominant_side = "positive";
end

contrasting_sws = sample_contrasting_sws( ...
    stream, target_sws, options);

material = struct();

if dominant_side == "negative"
    material.background_cs_m_s = target_sws;
    material.object_cs_m_s = contrasting_sws;
else
    material.background_cs_m_s = contrasting_sws;
    material.object_cs_m_s = target_sws;
end

win_size = round( ...
    options.PatchWindowWavelengths * ...
    options.CsGuessMPerS / frequency_hz / ...
    options.GridSpacingM(1));

win_size = max(3, win_size);

if mod(win_size, 2) == 0
    win_size = win_size + 1;
end

selected_domain=[options.DomainLxM options.DomainLzM];
packing=struct("packing_strategy","geometric_center", ...
    "available_packing_span_pixels",NaN, ...
    "available_packing_span_m",NaN,"expansion_required",false, ...
    "maximum_geometrically_packable_center_count",1);
if options.PackingMode=="packing_aware"
    % Final-mode physical conditions must remain identical when a later
    % realization reuses condition_id. Packing feasibility therefore depends
    % only on the condition geometry, not on the iteration's residual counts.
    require_additional=true;
    packing=reqml.campaigns.computePackingAwareBilayerCenter( ...
        win_size,options.GridSpacingM, ...
        InterfaceOrientation=options.InterfaceOrientation, ...
        MinimumDomainMarginPixels=options.MinimumDomainMarginPixels, ...
        DomainPolicyMode=options.DomainPolicyMode, ...
        DefaultDomainSizeM=options.DefaultDomainSizeM, ...
        ExpandedDomainSizeM=options.ExpandedDomainSizeM, ...
        MinimumPackableCenters=options.MinimumPackableCenters, ...
        AnalyticToOpportunisticSeparationFraction= ...
            options.AnalyticToOpportunisticSeparationFraction, ...
        RequireAdditionalUsefulCenter=require_additional);
    center_indices=packing.selected_patch_center_indices_xz;
    selected_domain=packing.selected_domain_size_m;
else
    center_indices = options.SelectedPatchCenterIndicesXZ;
    if any(~isfinite(center_indices))
        domain_pixels = round(selected_domain./options.GridSpacingM)+1;
        center_indices = round((domain_pixels + 1) / 2);
    end
end

placement = ...
    reqml.campaigns.computeBilayerInterfacePlacement( ...
        requested_purity_range, ...
        [win_size win_size], ...
        options.GridSpacingM, ...
        center_indices, ...
        selected_domain, ...
        InterfaceOrientation=options.InterfaceOrientation, ...
        DominantMaterialSide=dominant_side, ...
        MinimumDomainMarginPixels= ...
            options.MinimumDomainMarginPixels);

geometry = struct();
geometry.family = "bilayer";
geometry.radius_m = NaN;
geometry.center_xz_m = [NaN NaN];
geometry.normal_angle_rad = placement.normal_angle_rad;
geometry.offset_m = placement.interface_position_m;

control = empty_geometry_control();
control.geometry_control_mode = placement.geometry_control_mode;
control.requested_purity_lower = requested_purity_range(1);
control.requested_purity_upper = requested_purity_range(2);
control.target_purity = placement.target_purity;
control.predicted_discrete_purity = ...
    placement.predicted_discrete_purity;
control.interface_offset_pixels = ...
    placement.interface_offset_pixels;
control.interface_offset_m = placement.interface_offset_m;
control.interface_position_m = placement.interface_position_m;
control.selected_patch_center_indices_xz = ...
    placement.selected_patch_center_indices_xz;
control.selected_patch_center_m = ...
    placement.selected_patch_center_m;
control.dominant_material_side = ...
    placement.dominant_material_side;
control.interface_orientation = ...
    placement.interface_orientation;
control.patch_size_pixels = placement.patch_size_pixels;
control.grid_spacing_m = placement.grid_spacing_m;
control.domain_size_m = placement.domain_size_m;
control.selected_domain_size_m = selected_domain;
control.expansion_required = logical(packing.expansion_required);
control.resolved_window_size_pixels = win_size;
control.maximum_geometrically_packable_center_count = ...
    packing.maximum_geometrically_packable_center_count;
control.packing_strategy = string(packing.packing_strategy);
control.available_packing_span_pixels = packing.available_packing_span_pixels;
control.available_packing_span_m = packing.available_packing_span_m;
control.feasibility_diagnostics = placement.diagnostics;

end


function offset_m = materialize_bilayer_offset( ...
        stream, normal_angle_rad, target_sws, frequency_hz, ...
        requested_purity_range, options)

domain_center = [
    options.DomainLxM / 2
    options.DomainLzM / 2
    ];

normal = [
    cos(normal_angle_rad)
    sin(normal_angle_rad)
    ];

center_projection_m = dot(normal, domain_center);

purity_range = double(requested_purity_range);

if numel(purity_range) ~= 2 || ...
        any(~isfinite(purity_range))

    purity_midpoint = 0.75;
else
    purity_midpoint = mean(purity_range);
end

purity_midpoint = min(max(purity_midpoint, 0.5), 1.0);

window_length_m = ...
    2 * target_sws / frequency_hz;

% Approximate the interface distance required to obtain the requested
% central-material fraction in a wavelength-scaled local patch.
interface_distance_m = ...
    (purity_midpoint - 0.5) * window_length_m;

side = 1;

if rand(stream) < 0.5
    side = -1;
end

offset_m = ...
    center_projection_m + ...
    side * interface_distance_m;

end



function [center_x, center_z, radius_m] = ...
    optimize_inclusion_geometry( ...
        stream, ...
        requested_purity_range, ...
        target_sws, ...
        frequency_hz, ...
        options)
%OPTIMIZE_INCLUSION_GEOMETRY Preserve unbiased inclusion sampling.
%
% Purity targeting is handled by selecting patch centers from the truth
% material map. Geometry remains independently randomized.

radius_m = sample_uniform( ...
    stream, ...
    options.InclusionRadiusRangeM);

margin_x = radius_m;
margin_z = radius_m;

center_x = sample_uniform( ...
    stream, ...
    [margin_x, options.DomainLxM - margin_x]);

center_z = sample_uniform( ...
    stream, ...
    [margin_z, options.DomainLzM - margin_z]);

end

function range = resolve_target_dnom_range(request)


if isfield(request, ...
        "nominal_angular_coverage_range")

    range = double( ...
        request.nominal_angular_coverage_range);
else
    % Backwards compatibility for older adaptive plans.
    range = double(request.diffusivity_range);
end

if numel(range) ~= 2 || ...
        any(~isfinite(range)) || ...
        range(1) < 0 || ...
        range(2) > 1 || ...
        range(2) < range(1)

    error("reqml:InvalidNominalAngularCoverageRange", ...
        ["nominal_angular_coverage_range must be " ...
         "ordered and contained in [0,1]."]);
end

end


function field = materialize_field( ...
        stream, target_dnom_range, options)

axis_mode = options.AngularAxisMode;
in_plane_policy = options.InPlanePolicy;


field = ...
    reqml.campaigns.materializeNominalAngularField( ...
        stream, ...
        target_dnom_range, ...
        MaximumDirectionCount= ...
            options.MaximumDirectionCount, ...
        MinimumSolidAngleSr= ...
            options.MinimumSolidAngleSr, ...
        MaximumSolidAngleSr= ...
            options.MaximumSolidAngleSr, ...
        AxisMode=axis_mode, ...
        FixedAxisXYZ=options.FixedAngularAxisXYZ, ...
        InPlanePolicy=in_plane_policy, ...
        InPlaneFraction=options.InPlaneFraction);

end


function value = sample_requested_value( ...
        stream, requested_range, fallback_range)

requested_range = double(requested_range);

if numel(requested_range) ~= 2 || ...
        any(~isfinite(requested_range))
    range = fallback_range;
else
    range = requested_range;
end

value = sample_uniform(stream, range);

end


function value = sample_contrasting_sws( ...
        stream, center_sws, options)

allowed = options.BackgroundSwsRangeMPerS;

candidate_ranges = [
    allowed(1), center_sws - options.MinimumContrastMPerS
    center_sws + options.MinimumContrastMPerS, allowed(2)
    ];

valid = candidate_ranges(:,2) > candidate_ranges(:,1);

if ~any(valid)
    error("reqml:CannotMaterializeSwsContrast", ...
        "Could not generate a contrasting material SWS.");
end

candidate_ranges = candidate_ranges(valid, :);

selection = randi( ...
    stream, ...
    size(candidate_ranges, 1));

value = sample_uniform( ...
    stream, ...
    candidate_ranges(selection, :));

end


function value = sample_uniform(stream, range)

range = double(range);

if numel(range) ~= 2 || ...
        any(~isfinite(range)) || ...
        range(2) < range(1)

    error("reqml:InvalidPhysicalSamplingRange", ...
        "Sampling ranges must contain two finite ordered values.");
end

if range(1) == range(2)
    value = range(1);
else
    value = range(1) + ...
        (range(2) - range(1)) * rand(stream);
end

end


function seed = deterministic_seed(planner_seed, ordinal)

seed = mod( ...
    double(planner_seed) * 1000003 + ...
    double(ordinal) * 9176, ...
    2^31 - 1);

seed = max(1, floor(seed));

end


function seed = deterministic_condition_seed(condition_id)
values=double(char(string(condition_id)));
weights=mod(1:numel(values),97)+1;
seed=mod(sum(values.*weights)*1000003,2^31-1);
seed=max(1,floor(seed));
end


function value = resolve_request_scalar(request,name,default_value)
if isfield(request,name)
    value=double(request.(name));
else
    value=default_value;
end
end


function validate_request(request)

required = [
    "condition_id"
    "realization_count"
    "geometry_family"
    "field_regime"
    "sws_bin"
    "frequency_bin"
    "target_sws_range_m_s"
    "target_frequency_range_hz"
    "purity_bin"
    "purity_range"
    "diffusivity_bin"
    "diffusivity_range"
    "deficit_score"
    ];

missing = setdiff( ...
    required, ...
    string(fieldnames(request)));

if ~isempty(missing)
    error("reqml:InvalidPhysicalConditionRequest", ...
        "Condition request is missing field '%s'.", ...
        missing(1));
end

end


function validate_options(options)

if ~ismember(options.TrainingGeometryMode, ...
        ["legacy_balanced", "analytic_bilayer"])
    error("reqml:InvalidTrainingGeometryMode", ...
        "TrainingGeometryMode must be legacy_balanced or analytic_bilayer.");
end

if any(~isfinite(options.GridSpacingM)) || ...
        any(options.GridSpacingM <= 0) || ...
        options.PatchWindowWavelengths <= 0 || ...
        options.CsGuessMPerS <= 0
    error("reqml:InvalidAnalyticBilayerConfiguration", ...
        "Analytic bilayer grid and REQ window parameters must be positive.");
end

if any(isfinite(options.SelectedPatchCenterIndicesXZ)) && ...
        (any(~isfinite(options.SelectedPatchCenterIndicesXZ)) || ...
         any(options.SelectedPatchCenterIndicesXZ < 1) || ...
         any(options.SelectedPatchCenterIndicesXZ ~= ...
            fix(options.SelectedPatchCenterIndicesXZ)))
    error("reqml:InvalidAnalyticBilayerConfiguration", ...
        "SelectedPatchCenterIndicesXZ must contain two positive integers.");
end

validate_range( ...
    options.BackgroundSwsRangeMPerS, ...
    "BackgroundSwsRangeMPerS");

validate_range( ...
    options.InclusionRadiusRangeM, ...
    "InclusionRadiusRangeM");

validate_range( ...
    options.BilayerOffsetRangeM, ...
    "BilayerOffsetRangeM");

if options.DomainLxM <= 0 || options.DomainLzM <= 0
    error("reqml:InvalidPhysicalMaterializerOption", ...
        "Domain dimensions must be positive.");
end

if options.MinimumContrastMPerS <= 0
    error("reqml:InvalidPhysicalMaterializerOption", ...
        "MinimumContrastMPerS must be positive.");
end

if numel(options.DirectionCounts) ~= ...
        numel(options.InPlaneCounts) || ...
        numel(options.DirectionCounts) ~= ...
        numel(options.SolidAnglesSr)

    error("reqml:InvalidPhysicalMaterializerOption", ...
        ["DirectionCounts, InPlaneCounts, and SolidAnglesSr " ...
         "must have equal lengths."]);
end

if any(options.DirectionCounts < 1) || ...
        any(options.DirectionCounts ~= fix(options.DirectionCounts))

    error("reqml:InvalidPhysicalMaterializerOption", ...
        "DirectionCounts must contain positive integers.");
end

if any(options.InPlaneCounts < 0) || ...
        any(options.InPlaneCounts ~= fix(options.InPlaneCounts)) || ...
        any(options.InPlaneCounts > options.DirectionCounts)

    error("reqml:InvalidPhysicalMaterializerOption", ...
        "InPlaneCounts must be valid nonnegative integers.");
end

if options.MaximumDirectionCount < 1 || ...
        options.MaximumDirectionCount ~= ...
            fix(options.MaximumDirectionCount)

    error("reqml:InvalidPhysicalMaterializerOption", ...
        "MaximumDirectionCount must be a positive integer.");
end

if options.MinimumSolidAngleSr <= 0 || ...
        options.MaximumSolidAngleSr > 4*pi || ...
        options.MaximumSolidAngleSr <= ...
            options.MinimumSolidAngleSr

    error("reqml:InvalidPhysicalMaterializerOption", ...
        ["Nominal solid-angle limits must satisfy " ...
         "0 < minimum < maximum <= 4*pi."]);
end

end


function validate_range(range, name)

if numel(range) ~= 2 || ...
        any(~isfinite(range)) || ...
        range(2) <= range(1)

    error("reqml:InvalidPhysicalMaterializerOption", ...
        "%s must contain two finite increasing values.", ...
        name);
end

end


function condition = empty_condition()

condition = struct();

condition.condition_id = "";
condition.realization_count = 0;
condition.realization_start_index = 1;
condition.seed = 0;

condition.geometry = struct( ...
    "family", "", ...
    "radius_m", NaN, ...
    "center_xz_m", [NaN NaN], ...
    "normal_angle_rad", NaN, ...
    "offset_m", NaN);

condition.geometry_control = empty_geometry_control();

condition.material = struct( ...
    "background_cs_m_s", NaN, ...
    "object_cs_m_s", NaN);

condition.wavefield = struct( ...
    "frequency_hz", NaN, ...
    "direction_count", NaN, ...
    "in_plane_count", NaN, ...
    "solid_angle_sr", NaN, ...
    "nominal_angular_coverage", NaN, ...
    "maximum_direction_count", NaN);

condition.requested_coverage = struct( ...
    "purity_bin", 0, ...
    "purity_range", [NaN NaN], ...
    "diffusivity_bin", 0, ...
    "diffusivity_range", [NaN NaN], ...
    "nominal_angular_coverage_range", [NaN NaN], ...
    "deficit_score", NaN);
condition.requested_coverage.requested_cell_key = "";
condition.requested_coverage.residual_example_deficit = 0;
condition.requested_coverage.residual_independent_run_deficit = 0;
condition.requested_coverage.residual_independent_condition_deficit = 0;
condition.requested_coverage.planned_action = "new_condition";
condition.requested_coverage.planned_realization_count = 0;
condition.requested_coverage.planned_new_condition_count = 0;
condition.requested_coverage.reason_for_repeat = "";
condition.requested_coverage.expected_example_contribution = 0;
condition.requested_coverage.expected_independent_run_contribution = 0;
condition.requested_coverage.expected_independent_condition_contribution = 0;

end


function control = empty_geometry_control()

control = struct( ...
    "geometry_control_mode", "legacy", ...
    "requested_purity_lower", NaN, ...
    "requested_purity_upper", NaN, ...
    "target_purity", NaN, ...
    "predicted_discrete_purity", NaN, ...
    "interface_offset_pixels", NaN, ...
    "interface_offset_m", NaN, ...
    "interface_position_m", NaN, ...
    "selected_patch_center_indices_xz", [NaN NaN], ...
    "selected_patch_center_m", [NaN NaN], ...
    "dominant_material_side", "", ...
    "interface_orientation", "", ...
    "patch_size_pixels", [NaN NaN], ...
    "grid_spacing_m", [NaN NaN], ...
    "domain_size_m", [NaN NaN], ...
    "selected_domain_size_m", [NaN NaN], ...
    "expansion_required", false, ...
    "resolved_window_size_pixels", NaN, ...
    "maximum_geometrically_packable_center_count", NaN, ...
    "packing_strategy", "", ...
    "available_packing_span_pixels", NaN, ...
    "available_packing_span_m", NaN, ...
    "feasibility_diagnostics", struct());

end
