function runs = physicalConditionToSwsynthRuns(condition)
%PHYSICALCONDITIONTOSWSYNTHRUNS Convert one physical condition to swsynth runs.
%
% This is the only adaptive-planning function that knows swsynth override
% paths. Each realization receives a deterministic simulation seed.

arguments
    condition (1,1) struct
end

validate_condition(condition);

realization_count = double(condition.realization_count);

runs = repmat(struct( ...
    "condition_id", "", ...
    "realization_id", 0, ...
    "design_id", "", ...
    "overrides", struct([])), ...
    realization_count, ...
    1);

for realization_id = 1:realization_count
    simulation_seed = realization_seed( ...
        condition.seed, ...
        realization_id);

    runs(realization_id).condition_id = ...
        string(condition.condition_id);

    runs(realization_id).realization_id = ...
        realization_id;

    runs(realization_id).design_id = sprintf( ...
        "%s_r%03d", ...
        string(condition.condition_id), ...
        realization_id);

    runs(realization_id).overrides = ...
        build_overrides( ...
            condition, ...
            simulation_seed);
end

end


function overrides = build_overrides(condition, simulation_seed)

overrides = repmat(struct( ...
    "path", "", ...
    "value", []), ...
    0, 1);

overrides(end + 1) = make_override( ...
    "seed", ...
    simulation_seed);

overrides(end + 1) = make_override( ...
    "wavefield.frequency_hz", ...
    condition.wavefield.frequency_hz);

overrides(end + 1) = make_override( ...
    "directions.count", ...
    condition.wavefield.direction_count);

overrides(end + 1) = make_override( ...
    "directions.sampling_method", ...
    "fibonacci");

overrides(end + 1) = make_override( ...
    "directions.in_plane_count", ...
    condition.wavefield.in_plane_count);

overrides(end + 1) = make_override( ...
    "directions.support.solid_angle_sr", ...
    condition.wavefield.solid_angle_sr);

overrides(end + 1) = make_override( ...
    "medium.background_cs_m_s", ...
    condition.material.background_cs_m_s);

family = string(condition.geometry.family);

switch family
    case "homogeneous"
        return

    case "bilayer"
        overrides(end + 1) = make_override( ...
            "medium.objects[1].cs_m_s", ...
            condition.material.object_cs_m_s);

        overrides(end + 1) = make_override( ...
            "medium.objects[1].normal_angle_rad", ...
            condition.geometry.normal_angle_rad);

        overrides(end + 1) = make_override( ...
            "medium.objects[1].offset_m", ...
            condition.geometry.offset_m);

    case "circular_inclusion"
        overrides(end + 1) = make_override( ...
            "medium.objects[1].cs_m_s", ...
            condition.material.object_cs_m_s);

        overrides(end + 1) = make_override( ...
            "medium.objects[1].radius_m", ...
            condition.geometry.radius_m);

        overrides(end + 1) = make_override( ...
            "medium.objects[1].center_xz_m", ...
            condition.geometry.center_xz_m);

    otherwise
        error("reqml:UnsupportedSwsynthGeometryFamily", ...
            "Unsupported swsynth geometry family '%s'.", ...
            family);
end

end


function override = make_override(path_value, value)

override = struct();
override.path = string(path_value);
override.value = value;

end


function seed = realization_seed(condition_seed, realization_id)

seed = mod( ...
    double(condition_seed) + ...
    double(realization_id - 1) * 104729, ...
    2^31 - 1);

seed = max(1, floor(seed));

end


function validate_condition(condition)

required = [
    "condition_id"
    "realization_count"
    "seed"
    "geometry"
    "material"
    "wavefield"
    ];

missing = setdiff( ...
    required, ...
    string(fieldnames(condition)));

if ~isempty(missing)
    error("reqml:InvalidSwsynthPhysicalCondition", ...
        "Physical condition is missing field '%s'.", ...
        missing(1));
end

if strlength(string(condition.condition_id)) == 0
    error("reqml:InvalidSwsynthPhysicalCondition", ...
        "condition_id must be non-empty.");
end

realization_count = double(condition.realization_count);

if ~isscalar(realization_count) || ...
        ~isfinite(realization_count) || ...
        realization_count < 1 || ...
        realization_count ~= fix(realization_count)

    error("reqml:InvalidSwsynthPhysicalCondition", ...
        "realization_count must be a positive integer.");
end

validate_positive_scalar(condition.seed, "seed");

validate_positive_scalar( ...
    condition.wavefield.frequency_hz, ...
    "wavefield.frequency_hz");

validate_positive_integer( ...
    condition.wavefield.direction_count, ...
    "wavefield.direction_count");

validate_nonnegative_integer( ...
    condition.wavefield.in_plane_count, ...
    "wavefield.in_plane_count");

if condition.wavefield.in_plane_count > ...
        condition.wavefield.direction_count

    error("reqml:InvalidSwsynthPhysicalCondition", ...
        "in_plane_count cannot exceed direction_count.");
end

validate_positive_scalar( ...
    condition.wavefield.solid_angle_sr, ...
    "wavefield.solid_angle_sr");

validate_positive_scalar( ...
    condition.material.background_cs_m_s, ...
    "material.background_cs_m_s");

family = string(condition.geometry.family);

if ~ismember(family, ...
        ["homogeneous", "bilayer", "circular_inclusion"])

    error("reqml:UnsupportedSwsynthGeometryFamily", ...
        "Unsupported swsynth geometry family '%s'.", ...
        family);
end

if family ~= "homogeneous"
    validate_positive_scalar( ...
        condition.material.object_cs_m_s, ...
        "material.object_cs_m_s");
end

end


function validate_positive_scalar(value, name)

value = double(value);

if ~isscalar(value) || ...
        ~isfinite(value) || ...
        value <= 0

    error("reqml:InvalidSwsynthPhysicalCondition", ...
        "%s must be a finite positive scalar.", ...
        name);
end

end


function validate_positive_integer(value, name)

validate_positive_scalar(value, name);

if value ~= fix(value)
    error("reqml:InvalidSwsynthPhysicalCondition", ...
        "%s must be an integer.", ...
        name);
end

end


function validate_nonnegative_integer(value, name)

value = double(value);

if ~isscalar(value) || ...
        ~isfinite(value) || ...
        value < 0 || ...
        value ~= fix(value)

    error("reqml:InvalidSwsynthPhysicalCondition", ...
        "%s must be a nonnegative integer.", ...
        name);
end

end
