function result = planNextAdaptiveBatch( ...
    coverage_report, campaign_config, options)
%PLANNEXTADAPTIVEBATCH Plan and write the next adaptive simulation batch.
%
% Workflow:
%
%   coverage report
%       -> condition requests
%       -> backend-neutral physical conditions
%       -> swsynth campaign artifacts
%
% This function does not execute simulations.

arguments
    coverage_report (1,1) struct
    campaign_config (1,1) struct

    options.OutputDirectory {mustBeTextScalar}
    options.BatchId (1,1) string
    options.PlannerSeed (1,1) double

    options.ParentCoverageReportHash (1,1) string = ""

    options.MaximumConditions (1,1) double = 20
    options.RealizationsPerCondition (1,1) double = 2

    options.DomainLxM (1,1) double = 0.05
    options.DomainLzM (1,1) double = 0.05

    options.BackgroundSwsRangeMPerS (1,2) double = ...
        [1.5 4.0]

    options.MinimumContrastMPerS (1,1) double = 0.5

    options.InclusionRadiusRangeM (1,2) double = ...
        [0.004 0.012]

    options.BilayerOffsetRangeM (1,2) double = ...
        [0.015 0.035]

    options.DirectionCounts (1,:) double = ...
        [4 16 32]

    options.InPlaneCounts (1,:) double = ...
        [2 4 8]

    options.SolidAnglesSr (1,:) double = ...
        [0.5 pi 4*pi]
end

requests = ...
    reqml.campaigns.mapDeficitsToConditionRequests( ...
        coverage_report, ...
        MaximumConditions=options.MaximumConditions, ...
        RealizationsPerCondition= ...
            options.RealizationsPerCondition, ...
        PlannerSeed=options.PlannerSeed);

if isempty(requests)
    result = struct();

    result.schema_name = ...
        "reqml_adaptive_batch_planning_result";

    result.schema_version = "1.0";
    result.batch_required = false;
    result.coverage_complete = true;

    result.request_count = 0;
    result.condition_count = 0;
    result.run_count = 0;

    result.requests = requests;
    result.selected_requests = requests;
    result.physical_conditions = struct.empty;
    result.paths = struct();

    return
end

selected_requests = ...
    reqml.campaigns.selectGeometryFamilies( ...
        requests, ...
        coverage_report.assigned_examples, ...
        PlannerSeed=options.PlannerSeed);

physical_conditions = ...
    reqml.campaigns.materializePhysicalConditions( ...
        selected_requests, ...
        DomainLxM=options.DomainLxM, ...
        DomainLzM=options.DomainLzM, ...
        BackgroundSwsRangeMPerS= ...
            options.BackgroundSwsRangeMPerS, ...
        MinimumContrastMPerS= ...
            options.MinimumContrastMPerS, ...
        InclusionRadiusRangeM= ...
            options.InclusionRadiusRangeM, ...
        BilayerOffsetRangeM= ...
            options.BilayerOffsetRangeM, ...
        DirectionCounts=options.DirectionCounts, ...
        InPlaneCounts=options.InPlaneCounts, ...
        SolidAnglesSr=options.SolidAnglesSr, ...
        PlannerSeed=options.PlannerSeed);

paths = reqml.campaigns.writeAdaptiveBatch( ...
    physical_conditions, ...
    campaign_config, ...
    OutputDirectory=options.OutputDirectory, ...
    BatchId=options.BatchId, ...
    PlannerSeed=options.PlannerSeed, ...
    ParentCoverageReportHash= ...
        options.ParentCoverageReportHash);

run_count = sum(arrayfun( ...
    @(condition) double(condition.realization_count), ...
    physical_conditions));

result = struct();

result.schema_name = ...
    "reqml_adaptive_batch_planning_result";

result.schema_version = "1.0";

result.batch_required = true;
result.coverage_complete = false;

result.request_count = numel(requests);
result.condition_count = numel(physical_conditions);
result.run_count = run_count;

result.requests = requests;
result.selected_requests = selected_requests;
result.physical_conditions = physical_conditions;
result.paths = paths;

end
