function result = runAdaptiveCampaignFromConfig( ...
    config_file, options)
%RUNADAPTIVECAMPAIGNFROMCONFIG Run an adaptive campaign from JSON.
%
% The JSON config defines:
%
%   input/output paths
%   simulation framework path
%   base simulation configs
%   coverage bins and requirements
%   planning limits
%   loop execution and resume behavior

arguments
    config_file {mustBeTextScalar}

    % Dependency injection for unit tests.
    options.RunLoopFunction (1,1) function_handle = ...
        @reqml.campaigns.runAdaptiveCampaignLoop
end

config_file = string(config_file);

if ~isfile(config_file)
    error("reqml:AdaptiveCampaignConfigNotFound", ...
        "Adaptive campaign config was not found: %s", ...
        config_file);
end

try
    config = jsondecode(fileread(config_file));
catch exception
    error("reqml:InvalidAdaptiveCampaignConfigJson", ...
        "Could not decode adaptive campaign config '%s': %s", ...
        config_file, ...
        exception.message);
end

validate_config(config);

config_directory = string( ...
    fileparts(char(config_file)));

repository_root = resolve_repository_root();

resolved = resolve_config_paths( ...
    config, ...
    config_directory, ...
    repository_root);

feature_config = ...
    reqml.config.default_feature_config();

campaign_config = build_campaign_config( ...
    config, ...
    resolved);

coverage = config.coverage;
requirements = config.requirements;
planning = config.planning;
execution = config.execution;

result = feval( ...
    options.RunLoopFunction, ...
    resolved.previous_campaign_csv, ...
    resolved.initial_batch_directory, ...
    feature_config, ...
    campaign_config, ...
    resolved.simulation_framework_root, ...
    OutputRoot=resolved.output_root, ...
    CampaignId=string(config.campaign_id), ...
    MaximumIterations= ...
        double(execution.maximum_iterations), ...
    PlannerSeed=double(execution.planner_seed), ...
    PurityEdges=double(coverage.purity_edges(:))', ...
    DiffusivityEdges=double( ...
        coverage. ...
            nominal_angular_coverage_edges(:))', ...
    SwsEdges=double(coverage.sws_edges_m_s(:))', ...
    FrequencyEdges=double( ...
        coverage.frequency_edges_hz(:))', ...
    MinimumExamples=double( ...
        requirements.minimum_examples), ...
    MinimumIndependentRuns=double( ...
        requirements.minimum_independent_runs), ...
    MinimumSwsBins=double( ...
        requirements.minimum_sws_bins), ...
    MinimumFrequencyBins=double( ...
        requirements.minimum_frequency_bins), ...
    MinimumIndependentConditions=double( ...
        requirements. ...
            minimum_independent_conditions), ...
    MinimumGeometrySeeds=double( ...
        requirements.minimum_geometry_seeds), ...
    MaximumConditions=double( ...
        planning.maximum_conditions), ...
    RealizationsPerCondition=double( ...
        planning.realizations_per_condition), ...
    Resume=logical(execution.resume_runs), ...
    ContinueOnError=logical( ...
        execution.continue_on_error), ...
    ResumeExistingLoop=logical( ...
        execution.resume_existing_loop));

result.config_file = config_file;
result.resolved_config = resolved;

end


function validate_config(config)

required_top_level = [
    "schema_name"
    "schema_version"
    "campaign_id"
    "paths"
    "simulation"
    "coverage"
    "requirements"
    "planning"
    "execution"
    ];

validate_struct_fields( ...
    config, ...
    required_top_level, ...
    "root");

if string(config.schema_name) ~= ...
        "reqml_adaptive_campaign_config"

    error("reqml:InvalidAdaptiveCampaignConfigSchema", ...
        "Unsupported config schema '%s'.", ...
        string(config.schema_name));
end

if string(config.schema_version) ~= "1.0"
    error("reqml:InvalidAdaptiveCampaignConfigSchema", ...
        "Unsupported config schema version '%s'.", ...
        string(config.schema_version));
end

validate_nonempty_text( ...
    config.campaign_id, ...
    "campaign_id");

validate_struct_fields( ...
    config.paths, ...
    [
        "previous_campaign_csv"
        "initial_batch_directory"
        "output_root"
        "simulation_framework_root"
    ], ...
    "paths");

validate_struct_fields( ...
    config.simulation, ...
    [
        "backend"
        "output_directory"
        "base_config_mapping"
    ], ...
    "simulation");

validate_struct_fields( ...
    config.simulation.base_config_mapping, ...
    [
        "homogeneous"
        "bilayer"
        "circular_inclusion"
    ], ...
    "simulation.base_config_mapping");

validate_struct_fields( ...
    config.coverage, ...
    [
        "purity_edges"
        "nominal_angular_coverage_edges"
        "sws_edges_m_s"
        "frequency_edges_hz"
    ], ...
    "coverage");

validate_struct_fields( ...
    config.requirements, ...
    [
        "minimum_examples"
        "minimum_independent_runs"
        "minimum_independent_conditions"
        "minimum_sws_bins"
        "minimum_frequency_bins"
        "minimum_geometry_seeds"
    ], ...
    "requirements");

validate_struct_fields( ...
    config.planning, ...
    [
        "maximum_conditions"
        "realizations_per_condition"
    ], ...
    "planning");

validate_struct_fields( ...
    config.execution, ...
    [
        "maximum_iterations"
        "planner_seed"
        "resume_runs"
        "continue_on_error"
        "resume_existing_loop"
    ], ...
    "execution");

validate_edges( ...
    config.coverage.purity_edges, ...
    "coverage.purity_edges", ...
    [0 1]);

validate_edges( ...
    config.coverage. ...
        nominal_angular_coverage_edges, ...
    "coverage.nominal_angular_coverage_edges", ...
    [0 1]);

validate_edges( ...
    config.coverage.sws_edges_m_s, ...
    "coverage.sws_edges_m_s", ...
    [0 Inf]);

validate_edges( ...
    config.coverage.frequency_edges_hz, ...
    "coverage.frequency_edges_hz", ...
    [0 Inf]);

validate_nonnegative_integer( ...
    config.requirements.minimum_examples, ...
    "requirements.minimum_examples");

validate_nonnegative_integer( ...
    config.requirements.minimum_independent_runs, ...
    "requirements.minimum_independent_runs");

validate_nonnegative_integer( ...
    config.requirements. ...
        minimum_independent_conditions, ...
    "requirements.minimum_independent_conditions");

validate_nonnegative_integer( ...
    config.requirements.minimum_sws_bins, ...
    "requirements.minimum_sws_bins");

validate_nonnegative_integer( ...
    config.requirements.minimum_frequency_bins, ...
    "requirements.minimum_frequency_bins");

validate_nonnegative_integer( ...
    config.requirements.minimum_geometry_seeds, ...
    "requirements.minimum_geometry_seeds");

validate_positive_integer( ...
    config.planning.maximum_conditions, ...
    "planning.maximum_conditions");

validate_positive_integer( ...
    config.planning.realizations_per_condition, ...
    "planning.realizations_per_condition");

validate_positive_integer( ...
    config.execution.maximum_iterations, ...
    "execution.maximum_iterations");

validate_nonnegative_integer( ...
    config.execution.planner_seed, ...
    "execution.planner_seed");

end


function resolved = resolve_config_paths( ...
        config, config_directory, repository_root)

resolved = struct();

resolved.previous_campaign_csv = ...
    resolve_path( ...
        config.paths.previous_campaign_csv, ...
        config_directory, ...
        repository_root);

resolved.initial_batch_directory = ...
    resolve_path( ...
        config.paths.initial_batch_directory, ...
        config_directory, ...
        repository_root);

resolved.output_root = ...
    resolve_path( ...
        config.paths.output_root, ...
        config_directory, ...
        repository_root);

resolved.simulation_framework_root = ...
    resolve_path( ...
        config.paths.simulation_framework_root, ...
        config_directory, ...
        repository_root);

resolved.simulation_output_directory = ...
    resolve_path( ...
        config.simulation.output_directory, ...
        config_directory, ...
        repository_root);

mapping = ...
    config.simulation.base_config_mapping;

resolved.base_config_mapping = struct();

resolved.base_config_mapping.homogeneous = ...
    resolve_path( ...
        mapping.homogeneous, ...
        config_directory, ...
        repository_root);

resolved.base_config_mapping.bilayer = ...
    resolve_path( ...
        mapping.bilayer, ...
        config_directory, ...
        repository_root);

resolved.base_config_mapping.circular_inclusion = ...
    resolve_path( ...
        mapping.circular_inclusion, ...
        config_directory, ...
        repository_root);

end


function campaign = build_campaign_config( ...
        config, resolved)

campaign = struct();

campaign.backend = ...
    string(config.simulation.backend);

campaign.campaign_name = ...
    string(config.campaign_id);

campaign.base_config_mapping = struct( ...
    "homogeneous", ...
        resolved.base_config_mapping.homogeneous, ...
    "bilayer", ...
        resolved.base_config_mapping.bilayer, ...
    "circular_inclusion", ...
        resolved.base_config_mapping. ...
            circular_inclusion);

campaign.output = struct( ...
    "directory", ...
    resolved.simulation_output_directory);

end


function value = resolve_path( ...
        raw_value, config_directory, repository_root)

value = string(raw_value);

if strlength(value) == 0
    error("reqml:EmptyAdaptiveCampaignConfigPath", ...
        "Adaptive campaign config contains an empty path.");
end

if startsWith(value, "${REPOSITORY_ROOT}/")
    value = fullfile( ...
        repository_root, ...
        extractAfter(value, ...
            "${REPOSITORY_ROOT}/"));

elseif value == "${REPOSITORY_ROOT}"
    value = repository_root;

elseif startsWith(value, "${CONFIG_DIRECTORY}/")
    value = fullfile( ...
        config_directory, ...
        extractAfter(value, ...
            "${CONFIG_DIRECTORY}/"));

elseif value == "${CONFIG_DIRECTORY}"
    value = config_directory;

elseif ~is_absolute_path(value)
    value = fullfile( ...
        config_directory, ...
        value);
end

value = string( ...
    char(java.io.File(char(value)).getCanonicalPath()));

end


function tf = is_absolute_path(path_value)

path_value = char(path_value);

if ispc
    tf = ~isempty(regexp( ...
        path_value, ...
        '^[A-Za-z]:[\\/]', ...
        'once')) || ...
        startsWith(path_value, "\\");
else
    tf = startsWith(path_value, "/");
end

end


function root = resolve_repository_root()

function_path = string(mfilename("fullpath"));

root = string(fileparts(fileparts(fileparts( ...
    fileparts(char(function_path))))));

end


function validate_struct_fields(value, required, context)

if ~isstruct(value) || ~isscalar(value)
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config field '%s' must be a scalar object.", ...
        context);
end

missing = setdiff( ...
    required, ...
    string(fieldnames(value)));

if ~isempty(missing)
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config object '%s' is missing field '%s'.", ...
        context, ...
        missing(1));
end

end


function validate_nonempty_text(value, name)

if strlength(string(value)) == 0
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config field '%s' must be non-empty.", ...
        name);
end

end


function validate_edges(value, name, bounds)

value = double(value(:));

if numel(value) < 2 || ...
        any(~isfinite(value)) || ...
        any(diff(value) <= 0) || ...
        value(1) < bounds(1) || ...
        value(end) > bounds(2)

    error("reqml:InvalidAdaptiveCampaignConfig", ...
        ["Config field '%s' must contain at least two " ...
         "strictly increasing values within [%g,%g]."], ...
        name, ...
        bounds(1), ...
        bounds(2));
end

end


function validate_positive_integer(value, name)

value = double(value);

if ~isscalar(value) || ...
        ~isfinite(value) || ...
        value < 1 || ...
        value ~= fix(value)

    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config field '%s' must be a positive integer.", ...
        name);
end

end


function validate_nonnegative_integer(value, name)

value = double(value);

if ~isscalar(value) || ...
        ~isfinite(value) || ...
        value < 0 || ...
        value ~= fix(value)

    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config field '%s' must be a nonnegative integer.", ...
        name);
end

end
