function result = runAdaptiveCampaignLoop( ...
    previous_csv, initial_batch_directory, ...
    feat_cfg, campaign_config, ...
    simulation_framework_root, options)
%RUNADAPTIVECAMPAIGNLOOP Execute and advance an adaptive campaign.
%
% Workflow:
%
%   existing accumulated CSV
%       + initial planned simulation batch
%       -> execute simulations
%       -> merge campaign CSVs
%       -> rebuild dataset
%       -> recompute coverage
%       -> plan next batch
%       -> repeat until complete or iteration limit
%
% The initial batch must already contain:
%
%   adaptive_batch_plan.json
%   simulation_campaign_*.json

arguments
    previous_csv (1,1) string
    initial_batch_directory {mustBeTextScalar}
    feat_cfg (1,1) struct
    campaign_config (1,1) struct
    simulation_framework_root {mustBeTextScalar}

    options.OutputRoot {mustBeTextScalar}
    options.CampaignId (1,1) string

    options.MaximumIterations (1,1) double = 10
    options.PlannerSeed (1,1) double = 1

    options.PurityEdges (1,:) double
    options.DiffusivityEdges (1,:) double
    options.SwsEdges (1,:) double
    options.FrequencyEdges (1,:) double

    options.MinimumExamples (1,1) double = 500
    options.MinimumIndependentRuns (1,1) double = 5
    options.MinimumSwsBins (1,1) double = 3
    options.MinimumFrequencyBins (1,1) double = 3
    options.MinimumIndependentConditions (1,1) double = 3
    options.MinimumGeometrySeeds (1,1) double = 0

    options.MaximumConditions (1,1) double = 20
    options.RealizationsPerCondition (1,1) double = 2

    options.Resume (1,1) logical = true
    options.ContinueOnError (1,1) logical = false

    options.ResumeExistingLoop (1,1) logical = false

    % Dependency injection allows orchestration tests without running
    % real simulations or rebuilding full datasets.
    options.ExecuteBatchFunction (1,1) function_handle = ...
        @reqml.campaigns.executeAdaptiveBatch

    options.AdvanceIterationFunction (1,1) function_handle = ...
        @reqml.campaigns.advanceAdaptiveIteration
end

output_root = string(options.OutputRoot);

validate_inputs( ...
    previous_csv, ...
    initial_batch_directory, ...
    output_root, ...
    options);

records = repmat( ...
    empty_iteration_record(), ...
    options.MaximumIterations, ...
    1);

completed_iteration_count = 0;
start_iteration_index = 1;

current_csv = previous_csv;
current_batch_directory = ...
    string(initial_batch_directory);

stop_reason = "maximum_iterations_reached";
coverage_complete = false;

if options.ResumeExistingLoop
    state = ...
        reqml.campaigns.loadAdaptiveLoopState( ...
            output_root);

    if state.campaign_id ~= options.CampaignId
        error("reqml:AdaptiveLoopCampaignIdMismatch", ...
            ["Persisted campaign ID '%s' does not match " ...
             "requested campaign ID '%s'."], ...
            state.campaign_id, ...
            options.CampaignId);
    end

    existing_records = ...
        iteration_table_to_records( ...
            state.iterations);

    completed_iteration_count = ...
        state.completed_iteration_count;

    if completed_iteration_count > ...
            options.MaximumIterations

        error("reqml:AdaptiveLoopIterationLimitTooSmall", ...
            ["Persisted loop already contains %d iterations, " ...
             "but MaximumIterations is %d."], ...
            completed_iteration_count, ...
            options.MaximumIterations);
    end

    if completed_iteration_count > 0
        records(1:completed_iteration_count) = ...
            existing_records;
    end

    coverage_complete = ...
        state.coverage_complete;

    if coverage_complete
        result = result_from_loaded_state( ...
            state, ...
            records(1:completed_iteration_count), ...
            options.MaximumIterations);

        return
    end

    if completed_iteration_count >= ...
            options.MaximumIterations

        error("reqml:AdaptiveLoopIterationLimitReached", ...
            ["The persisted loop is incomplete, but it has " ...
             "already reached MaximumIterations=%d."], ...
            options.MaximumIterations);
    end

    current_csv = ...
        state.final_accumulated_campaign_csv;

    current_batch_directory = ...
        state.next_batch_directory;

    start_iteration_index = ...
        completed_iteration_count + 1;
else
    if ~isfolder(output_root)
        [created, message] = mkdir(output_root);

        if ~created
            error("reqml:AdaptiveLoopOutputCreateFailed", ...
                "Could not create output root '%s': %s", ...
                output_root, message);
        end
    end

    summary_path = fullfile( ...
        output_root, ...
        "adaptive_loop_summary.json");

    iterations_path = fullfile( ...
        output_root, ...
        "adaptive_loop_iterations.csv");

    if isfile(summary_path) || isfile(iterations_path)
        error("reqml:AdaptiveLoopOutputAlreadyInitialized", ...
            ["Adaptive loop state already exists in '%s'. " ...
             "Use ResumeExistingLoop=true to continue it."], ...
            output_root);
    end
end

for iteration_index = ...
        start_iteration_index:options.MaximumIterations
    iteration_id = sprintf( ...
        "%s_iteration_%03d", ...
        options.CampaignId, ...
        iteration_index);

    iteration_directory = fullfile( ...
        output_root, ...
        iteration_id);

    executed_plan_file = fullfile( ...
        current_batch_directory, ...
        "adaptive_batch_plan.json");

    if ~isfile(executed_plan_file)
        error("reqml:AdaptiveBatchPlanNotFound", ...
            "Adaptive batch plan was not found: %s", ...
            executed_plan_file);
    end

    fprintf( ...
        "\n============================================================\n");
    fprintf( ...
        "Adaptive iteration %d of %d\n", ...
        iteration_index, ...
        options.MaximumIterations);
    fprintf("Batch: %s\n", current_batch_directory);

    execution = feval( ...
        options.ExecuteBatchFunction, ...
        current_batch_directory, ...
        simulation_framework_root, ...
        Resume=options.Resume, ...
        ContinueOnError=options.ContinueOnError);

    next_campaign_config = campaign_config;

    next_campaign_config.campaign_name = sprintf( ...
        "%s_simulation_%03d", ...
        options.CampaignId, ...
        iteration_index + 1);

    iteration_seed = ...
        options.PlannerSeed + iteration_index - 1;

    advanced = feval( ...
        options.AdvanceIterationFunction, ...
        current_csv, ...
        execution.campaign_csv_files, ...
        feat_cfg, ...
        next_campaign_config, ...
        OutputDirectory=iteration_directory, ...
        IterationId=iteration_id, ...
        PlannerSeed=iteration_seed, ...
        PurityEdges=options.PurityEdges, ...
        DiffusivityEdges=options.DiffusivityEdges, ...
        SwsEdges=options.SwsEdges, ...
        FrequencyEdges=options.FrequencyEdges, ...
        MinimumExamples=options.MinimumExamples, ...
        MinimumIndependentRuns= ...
            options.MinimumIndependentRuns, ...
        MinimumSwsBins=options.MinimumSwsBins, ...
        MinimumFrequencyBins= ...
            options.MinimumFrequencyBins, ...
        MinimumIndependentConditions= ...
            options.MinimumIndependentConditions, ...
        MinimumGeometrySeeds= ...
            options.MinimumGeometrySeeds, ...
        MaximumConditions=options.MaximumConditions, ...
        RealizationsPerCondition= ...
            options.RealizationsPerCondition, ...
        ParentCoverageReportHash= ...
            string(iteration_index - 1), ...
        ExecutedBatchPlanFile= ...
            executed_plan_file);

    record = empty_iteration_record();

    record.iteration_index = iteration_index;
    record.iteration_id = iteration_id;
    record.batch_directory = current_batch_directory;
    record.iteration_directory = string(iteration_directory);

    record.executed_campaign_count = ...
        double(execution.campaign_count);

    record.executed_run_count = ...
        double(execution.run_count);

    record.accumulated_run_count = ...
        double(advanced.accumulated_run_count);

    record.example_count = ...
        double(advanced.iteration.example_count);

    record.observed_coverage_cell_count = ...
        double( ...
            advanced.iteration. ...
                observed_coverage_cell_count);

    record.deficient_cell_count = ...
        double(advanced.iteration.deficient_cell_count);

    record.coverage_complete = ...
        logical(advanced.iteration.coverage_complete);

    record.next_batch_required = ...
        logical( ...
            advanced.iteration.planning.batch_required);

    record.accumulated_campaign_csv = ...
        string( ...
            advanced.paths. ...
                accumulated_campaign_csv);

    records(iteration_index) = record;
    completed_iteration_count = iteration_index;

    fprintf( ...
        "Executed runs: %d\n", ...
        record.executed_run_count);

    fprintf( ...
        "Accumulated runs: %d\n", ...
        record.accumulated_run_count);

    fprintf( ...
        "Examples: %d\n", ...
        record.example_count);

    fprintf( ...
        "Observed cells: %d\n", ...
        record.observed_coverage_cell_count);

    fprintf( ...
        "Deficient cells: %d\n", ...
        record.deficient_cell_count);

    coverage_complete = ...
        record.coverage_complete;

    completed_records = ...
        records(1:completed_iteration_count);

    if coverage_complete
        stop_reason = "coverage_complete";

        checkpoint = build_loop_result( ...
            options.CampaignId, ...
            completed_records, ...
            options.MaximumIterations, ...
            stop_reason, ...
            coverage_complete);

        persist_loop_result( ...
            checkpoint, ...
            output_root);

        break
    end

    if ~record.next_batch_required
        stop_reason = "no_next_batch_required";

        checkpoint = build_loop_result( ...
            options.CampaignId, ...
            completed_records, ...
            options.MaximumIterations, ...
            stop_reason, ...
            coverage_complete);

        persist_loop_result( ...
            checkpoint, ...
            output_root);

        break
    end

    next_batch_directory = fullfile( ...
        iteration_directory, ...
        "next_batch");

    if ~isfolder(next_batch_directory)
        error("reqml:AdaptiveNextBatchNotFound", ...
            ["Planner reported that another batch was required, " ...
             "but the next_batch directory was not created: %s"], ...
            next_batch_directory);
    end

    current_csv = ...
        record.accumulated_campaign_csv;

    current_batch_directory = ...
        string(next_batch_directory);

    checkpoint = build_loop_result( ...
        options.CampaignId, ...
        completed_records, ...
        options.MaximumIterations, ...
        "in_progress", ...
        false);

    persist_loop_result( ...
        checkpoint, ...
        output_root);
end

records = records(1:completed_iteration_count);

result = build_loop_result( ...
    options.CampaignId, ...
    records, ...
    options.MaximumIterations, ...
    stop_reason, ...
    coverage_complete);

result.paths = persist_loop_result( ...
    result, ...
    output_root);

end


function result = build_loop_result( ...
        campaign_id, records, maximum_iterations, ...
        stop_reason, coverage_complete)

result = struct();

result.schema_name = ...
    "reqml_adaptive_campaign_loop";

result.schema_version = "1.0";
result.campaign_id = string(campaign_id);

result.completed_iteration_count = ...
    numel(records);

result.maximum_iterations = ...
    maximum_iterations;

result.stop_reason = string(stop_reason);

result.coverage_complete = ...
    logical(coverage_complete);

result.iterations = records;

if ~isempty(records)
    result.final_accumulated_campaign_csv = ...
        records(end).accumulated_campaign_csv;

    result.final_iteration_directory = ...
        records(end).iteration_directory;

    result.final_deficient_cell_count = ...
        records(end).deficient_cell_count;
else
    result.final_accumulated_campaign_csv = "";
    result.final_iteration_directory = "";
    result.final_deficient_cell_count = NaN;
end

end


function paths = persist_loop_result(result, output_root)

summary_path = fullfile( ...
    output_root, ...
    "adaptive_loop_summary.json");

iterations_path = fullfile( ...
    output_root, ...
    "adaptive_loop_iterations.csv");

write_json_atomically( ...
    summary_path, ...
    result);

iteration_table = ...
    iteration_records_to_table( ...
        result.iterations);

writetable( ...
    iteration_table, ...
    iterations_path);

paths = struct();

paths.summary_json = ...
    string(summary_path);

paths.iterations_csv = ...
    string(iterations_path);

end


function iteration_table = ...
        iteration_records_to_table(records)

if isempty(records)
    iteration_table = table();
    return
end

records = records(:);
row_count = numel(records);

iteration_table = table();

iteration_table.iteration_index = reshape( ...
    [records.iteration_index], ...
    row_count, ...
    1);

iteration_table.iteration_id = reshape( ...
    string({records.iteration_id}), ...
    row_count, ...
    1);

iteration_table.batch_directory = reshape( ...
    string({records.batch_directory}), ...
    row_count, ...
    1);

iteration_table.iteration_directory = reshape( ...
    string({records.iteration_directory}), ...
    row_count, ...
    1);

iteration_table.executed_campaign_count = reshape( ...
    [records.executed_campaign_count], ...
    row_count, ...
    1);

iteration_table.executed_run_count = reshape( ...
    [records.executed_run_count], ...
    row_count, ...
    1);

iteration_table.accumulated_run_count = reshape( ...
    [records.accumulated_run_count], ...
    row_count, ...
    1);

iteration_table.example_count = reshape( ...
    [records.example_count], ...
    row_count, ...
    1);

iteration_table.observed_coverage_cell_count = reshape( ...
    [records.observed_coverage_cell_count], ...
    row_count, ...
    1);

iteration_table.deficient_cell_count = reshape( ...
    [records.deficient_cell_count], ...
    row_count, ...
    1);

iteration_table.coverage_complete = reshape( ...
    logical([records.coverage_complete]), ...
    row_count, ...
    1);

iteration_table.next_batch_required = reshape( ...
    logical([records.next_batch_required]), ...
    row_count, ...
    1);

iteration_table.accumulated_campaign_csv = reshape( ...
    string({records.accumulated_campaign_csv}), ...
    row_count, ...
    1);

end


function write_json_atomically(path_value, value)

temporary_path = ...
    string(path_value) + ".tmp";

if isfile(temporary_path)
    delete(temporary_path);
end

file_id = fopen(temporary_path, "w");

if file_id < 0
    error("reqml:AdaptiveLoopSummaryWriteFailed", ...
        "Could not create temporary file '%s'.", ...
        temporary_path);
end

cleanup = onCleanup(@() fclose(file_id));

fprintf(file_id, "%s", ...
    jsonencode(value, PrettyPrint=true));

clear cleanup

[moved, message] = movefile( ...
    temporary_path, ...
    path_value, ...
    "f");

if ~moved
    if isfile(temporary_path)
        delete(temporary_path);
    end

    error("reqml:AdaptiveLoopSummaryWriteFailed", ...
        "Could not publish loop summary '%s': %s", ...
        path_value, ...
        message);
end

end


function validate_inputs( ...
        previous_csv, initial_batch_directory, ...
        output_root, options)

if strlength(options.CampaignId) == 0
    error("reqml:InvalidAdaptiveLoopCampaignId", ...
        "CampaignId must be non-empty.");
end

if options.MaximumIterations < 1 || ...
        options.MaximumIterations ~= ...
            fix(options.MaximumIterations)

    error("reqml:InvalidAdaptiveLoopIterationLimit", ...
        "MaximumIterations must be a positive integer.");
end

if options.ResumeExistingLoop
    if ~isfolder(output_root)
        error("reqml:AdaptiveLoopOutputNotFound", ...
            ["Cannot resume because the adaptive loop output " ...
             "directory was not found: %s"], ...
            output_root);
    end

    return
end

if ~isfile(previous_csv)
    error("reqml:AdaptiveLoopPreviousCsvNotFound", ...
        "Previous accumulated CSV was not found: %s", ...
        previous_csv);
end

if ~isfolder(initial_batch_directory)
    error("reqml:AdaptiveLoopInitialBatchNotFound", ...
        "Initial batch directory was not found: %s", ...
        initial_batch_directory);
end

end


function records = iteration_table_to_records(table_value)

row_count = height(table_value);

records = repmat( ...
    empty_iteration_record(), ...
    row_count, ...
    1);

for index = 1:row_count
    record = empty_iteration_record();

    record.iteration_index = double( ...
        table_value.("iteration_index")(index));

    record.iteration_id = string( ...
        table_value.("iteration_id")(index));

    record.batch_directory = string( ...
        table_value.("batch_directory")(index));

    record.iteration_directory = string( ...
        table_value.("iteration_directory")(index));

    record.executed_campaign_count = double( ...
        table_value.("executed_campaign_count")(index));

    record.executed_run_count = double( ...
        table_value.("executed_run_count")(index));

    record.accumulated_run_count = double( ...
        table_value.("accumulated_run_count")(index));

    record.example_count = double( ...
        table_value.("example_count")(index));

    record.observed_coverage_cell_count = double( ...
        table_value.("observed_coverage_cell_count")(index));

    record.deficient_cell_count = double( ...
        table_value.("deficient_cell_count")(index));

    record.coverage_complete = logical( ...
        table_value.("coverage_complete")(index));

    record.next_batch_required = logical( ...
        table_value.("next_batch_required")(index));

    record.accumulated_campaign_csv = string( ...
        table_value.("accumulated_campaign_csv")(index));

    records(index) = record;
end

end


function result = result_from_loaded_state( ...
        state, records, maximum_iterations)

result = struct();

result.schema_name = ...
    "reqml_adaptive_campaign_loop";

result.schema_version = "1.0";
result.campaign_id = state.campaign_id;

result.completed_iteration_count = ...
    state.completed_iteration_count;

result.maximum_iterations = ...
    maximum_iterations;

result.stop_reason = ...
    state.stop_reason;

result.coverage_complete = ...
    state.coverage_complete;

result.iterations = records;

result.final_accumulated_campaign_csv = ...
    state.final_accumulated_campaign_csv;

result.final_iteration_directory = ...
    state.final_iteration_directory;

result.final_deficient_cell_count = ...
    double( ...
        state.iterations. ...
            ("deficient_cell_count")(end));

result.paths = state.paths;

end


function record = empty_iteration_record()

record = struct();

record.iteration_index = 0;
record.iteration_id = "";
record.batch_directory = "";
record.iteration_directory = "";

record.executed_campaign_count = 0;
record.executed_run_count = 0;
record.accumulated_run_count = 0;
record.example_count = 0;

record.observed_coverage_cell_count = 0;
record.deficient_cell_count = 0;

record.coverage_complete = false;
record.next_batch_required = false;

record.accumulated_campaign_csv = "";

end
