function result = runAdaptiveCampaignFromConfig( ...
    config_file, options)
%RUNADAPTIVECAMPAIGNFROMCONFIG Run an adaptive campaign from JSON.
%
% The JSON config defines:
%
%   input/output paths
%   simulation framework path
%   base simulation configs
%   coverage bins and requirements
%   planning limits
%   loop execution and resume behavior

arguments
    config_file {mustBeTextScalar}

    % Dependency injection for unit tests.
    options.RunLoopFunction (1,1) function_handle = ...
        @reqml.campaigns.runAdaptiveCampaignLoop

    options.GenerateBootstrapFunction (1,1) function_handle = ...
        @reqml.campaigns.generateAdaptiveBootstrap
end

config_file = string(config_file);

if ~isfile(config_file)
    error("reqml:AdaptiveCampaignConfigNotFound", ...
        "Adaptive campaign config was not found: %s", ...
        config_file);
end

try
    config = jsondecode(fileread(config_file));
catch exception
    error("reqml:InvalidAdaptiveCampaignConfigJson", ...
        "Could not decode adaptive campaign config '%s': %s", ...
        config_file, ...
        exception.message);
end

validate_config(config);

config_directory = string( ...
    fileparts(char(config_file)));

repository_root = resolve_repository_root();

resolved = resolve_config_paths( ...
    config, ...
    config_directory, ...
    repository_root);

feature_config = ...
    reqml.config.default_feature_config();

campaign_config = build_campaign_config( ...
    config, ...
    resolved, ...
    feature_config);

coverage = config.coverage;
requirements = config.requirements;
planning = config.planning;
execution = config.execution;

directed_center_selection = ...
    resolve_directed_center_selection(config);
campaign_config.center_selection_mode = ...
    string(directed_center_selection.mode);
campaign_config.center_selection_policy = directed_center_selection;
if isfield(config,"domain_policy")
    campaign_config.domain_policy = config.domain_policy;
end
validate_center_selection_geometry_mode( ...
    directed_center_selection, planning);

[previous_campaign_csv, ...
    initial_batch_directory, ...
    resume_existing_loop, ...
    bootstrap_result] = ...
    prepare_initial_state( ...
        config, ...
        resolved, ...
        campaign_config, ...
        options.GenerateBootstrapFunction);

result = feval( ...
    options.RunLoopFunction, ...
    previous_campaign_csv, ...
    initial_batch_directory, ...
    feature_config, ...
    campaign_config, ...
    resolved.simulation_framework_root, ...
    OutputRoot=resolved.output_root, ...
    CampaignId=string(config.campaign_id), ...
    MaximumIterations= ...
        double(execution.maximum_iterations), ...
    PlannerSeed=double(execution.planner_seed), ...
    PurityEdges=double(coverage.purity_edges(:))', ...
    DiffusivityEdges=double( ...
        coverage. ...
            nominal_angular_coverage_edges(:))', ...
    SwsEdges=double(coverage.sws_edges_m_s(:))', ...
    FrequencyEdges=double( ...
        coverage.frequency_edges_hz(:))', ...
    MinimumExamples=double( ...
        requirements.minimum_examples), ...
    MinimumIndependentRuns=double( ...
        requirements.minimum_independent_runs), ...
    MinimumSwsBins=double( ...
        requirements.minimum_sws_bins), ...
    MinimumFrequencyBins=double( ...
        requirements.minimum_frequency_bins), ...
    MinimumIndependentConditions=double( ...
        requirements. ...
            minimum_independent_conditions), ...
    MinimumGeometrySeeds=double( ...
        requirements.minimum_geometry_seeds), ...
    MaximumConditions=double( ...
        planning.maximum_conditions), ...
    RealizationsPerCondition=double( ...
        planning.realizations_per_condition), ...
    UseDirectedCenterSelection=logical( ...
        directed_center_selection.enabled), ...
    CandidateStepPixels=double( ...
        directed_center_selection.candidate_step_pixels), ...
    MaximumCentersPerCell=double( ...
        directed_center_selection.maximum_centers_per_cell), ...
    MinimumCenterDistanceFraction=double( ...
        directed_center_selection. ...
            minimum_center_distance_fraction), ...
    MinimumValidFraction=double( ...
        directed_center_selection.minimum_valid_fraction), ...
    CenterSelectionSeedOffset=double( ...
        directed_center_selection.seed_offset), ...
    CenterSelectionMode=string(directed_center_selection.mode), ...
    MaximumCentersPerRun=double( ...
        directed_center_selection.maximum_centers_per_run), ...
    MaximumCentersPerCellPerRun=double( ...
        directed_center_selection.maximum_centers_per_cell_per_run), ...
    MinimumCenterSeparationFraction=double( ...
        directed_center_selection.minimum_center_separation_fraction), ...
    AnalyticToOpportunisticSeparationFraction=double( ...
        directed_center_selection.analytic_to_opportunistic_separation_fraction), ...
    DifferentCellSeparationFraction=double( ...
        directed_center_selection.different_cell_separation_fraction), ...
    SameCellSeparationFraction=double( ...
        directed_center_selection.same_cell_separation_fraction), ...
    UseSampleParfor=get_logical_field( ...
        execution, ...
        "use_sample_parfor", ...
        false), ...
    Resume=logical(execution.resume_runs), ...
    ContinueOnError=logical( ...
        execution.continue_on_error), ...
    ResumeExistingLoop=resume_existing_loop);

result.config_file = config_file;
result.resolved_config = resolved;
result.bootstrap = bootstrap_result;

end


function value = get_logical_field( ...
        source, field_name, default_value)

if isfield(source, field_name)
    value = logical(source.(field_name));
else
    value = logical(default_value);
end

end


function [previous_csv, initial_batch_directory, ...
        resume_existing_loop, bootstrap_result] = ...
        prepare_initial_state( ...
            config, resolved, campaign_config, ...
            generate_bootstrap_function)

schema_version = string(config.schema_version);

bootstrap_result = struct();

if schema_version == "1.0"
    previous_csv = ...
        resolved.previous_campaign_csv;

    initial_batch_directory = ...
        resolved.initial_batch_directory;

    resume_existing_loop = logical( ...
        config.execution.resume_existing_loop);

    return
end

summary_file = fullfile( ...
    resolved.output_root, ...
    "adaptive_loop_summary.json");

resume_requested = logical( ...
    config.execution.resume_existing_loop);

if resume_requested && isfile(summary_file)
    previous_csv = "";
    initial_batch_directory = "";
    resume_existing_loop = true;
    return
end

previous_csv = "";
initial_batch_directory = ...
    resolved.bootstrap_output_directory;

resume_existing_loop = false;

bootstrap = config.bootstrap;

bootstrap_result = feval( ...
    generate_bootstrap_function, ...
    config.coverage, ...
    campaign_config, ...
    OutputDirectory= ...
        initial_batch_directory, ...
    BatchId=string(bootstrap.batch_id), ...
    PlannerSeed=double( ...
        bootstrap.planner_seed), ...
    RealizationsPerCondition=double( ...
        bootstrap. ...
            realizations_per_condition), ...
    GeometryFamilies=string( ...
        bootstrap.geometry_families(:))', ...
    PurityCycleStride=double( ...
        bootstrap.purity_cycle_stride), ...
    DiffusivityCycleStride=double( ...
        bootstrap.diffusivity_cycle_stride));

end


function selection = ...
        resolve_directed_center_selection(config)

selection = struct();
selection.enabled = false;
selection.candidate_step_pixels = 2;
selection.maximum_centers_per_cell = 4;
selection.minimum_center_distance_fraction = 0.5;
selection.minimum_valid_fraction = 1;
selection.seed_offset = 0;
selection.mode = "default";
selection.maximum_centers_per_run = 12;
selection.maximum_centers_per_cell_per_run = 2;
selection.minimum_center_separation_fraction = 0.75;
selection.analytic_to_opportunistic_separation_fraction = 0.25;
selection.different_cell_separation_fraction = 0.25;
selection.same_cell_separation_fraction = 0.50;

if isfield(config, "center_selection")
    requested = config.center_selection;
    names = string(fieldnames(selection));
    for index = 1:numel(names)
        name = names(index);
        if isfield(requested, name)
            selection.(name) = requested.(name);
        end
    end
    selection.enabled = selection.mode == "legacy_directed";
    validate_center_selection(selection);
    return
end

if ~isfield(config, "directed_center_selection")
    return
end

requested = config.directed_center_selection;
names = string(fieldnames(selection));

for index = 1:numel(names)
    name = names(index);

    if isfield(requested, name)
        selection.(name) = requested.(name);
    end
end

if selection.enabled
    selection.mode = "legacy_directed";
end

end


function validate_center_selection(selection)
allowed = ["default","legacy_directed", ...
    "analytic_exact_center", ...
    "analytic_target_plus_deficit_aware_centers", ...
    "analytic_deficit_aware_final"];
if ~ismember(string(selection.mode),allowed)
    error("reqml:InvalidCenterSelectionMode", ...
        "Unsupported center_selection.mode '%s'.",string(selection.mode));
end
if selection.maximum_centers_per_run < 1 || ...
        selection.maximum_centers_per_cell_per_run < 1 || ...
        selection.minimum_center_separation_fraction < 0 || ...
        selection.analytic_to_opportunistic_separation_fraction < 0 || ...
        selection.different_cell_separation_fraction < 0 || ...
        selection.same_cell_separation_fraction < 0
    error("reqml:InvalidCenterSelectionConfig", ...
        "Hybrid center-selection quotas and separation must be valid.");
end

end


function validate_center_selection_geometry_mode(selection, planning)

if ~ismember(string(selection.mode), ...
        ["analytic_target_plus_deficit_aware_centers", ...
         "analytic_deficit_aware_final"])
    return
end

if ~isfield(planning,"training_geometry_mode") || ...
        string(planning.training_geometry_mode) ~= "analytic_bilayer"
    error("reqml:HybridCentersRequireAnalyticBilayer", ...
        "Hybrid deficit-aware centers require planning.training_geometry_mode='analytic_bilayer'.");
end

end


function validate_config(config)

required_top_level = [
    "schema_name"
    "schema_version"
    "campaign_id"
    "paths"
    "simulation"
    "coverage"
    "requirements"
    "planning"
    "execution"
    ];

validate_struct_fields( ...
    config, ...
    required_top_level, ...
    "root");

if string(config.schema_name) ~= ...
        "reqml_adaptive_campaign_config"

    error("reqml:InvalidAdaptiveCampaignConfigSchema", ...
        "Unsupported config schema '%s'.", ...
        string(config.schema_name));
end

schema_version = string(config.schema_version);

if ~ismember(schema_version, ["1.0", "1.1"])
    error("reqml:InvalidAdaptiveCampaignConfigSchema", ...
        "Unsupported config schema version '%s'.", ...
        schema_version);
end

validate_nonempty_text( ...
    config.campaign_id, ...
    "campaign_id");

if schema_version == "1.0"
    required_paths = [
        "previous_campaign_csv"
        "initial_batch_directory"
        "output_root"
        "simulation_framework_root"
        ];
else
    required_paths = [
        "output_root"
        "simulation_framework_root"
        ];
end

validate_struct_fields( ...
    config.paths, ...
    required_paths, ...
    "paths");

if schema_version == "1.1"
    validate_struct_fields( ...
        config, ...
        "bootstrap", ...
        "root");

    validate_struct_fields( ...
        config.bootstrap, ...
        [
            "output_subdirectory"
            "batch_id"
            "planner_seed"
            "realizations_per_condition"
            "geometry_families"
            "purity_cycle_stride"
            "diffusivity_cycle_stride"
        ], ...
        "bootstrap");

    validate_nonempty_text( ...
        config.bootstrap.output_subdirectory, ...
        "bootstrap.output_subdirectory");

    validate_nonempty_text( ...
        config.bootstrap.batch_id, ...
        "bootstrap.batch_id");

    validate_nonnegative_integer( ...
        config.bootstrap.planner_seed, ...
        "bootstrap.planner_seed");

    validate_positive_integer( ...
        config.bootstrap.realizations_per_condition, ...
        "bootstrap.realizations_per_condition");

    validate_positive_integer( ...
        config.bootstrap.purity_cycle_stride, ...
        "bootstrap.purity_cycle_stride");

    validate_positive_integer( ...
        config.bootstrap.diffusivity_cycle_stride, ...
        "bootstrap.diffusivity_cycle_stride");
end

validate_struct_fields( ...
    config.simulation, ...
    [
        "backend"
        "output_directory"
        "base_config_mapping"
    ], ...
    "simulation");

validate_struct_fields( ...
    config.simulation.base_config_mapping, ...
    [
        "homogeneous"
        "bilayer"
        "circular_inclusion"
    ], ...
    "simulation.base_config_mapping");

validate_struct_fields( ...
    config.coverage, ...
    [
        "purity_edges"
        "nominal_angular_coverage_edges"
        "sws_edges_m_s"
        "frequency_edges_hz"
    ], ...
    "coverage");


if isfield(config, "directed_center_selection")
    validate_directed_center_selection_config( ...
        config.directed_center_selection);
end

if isfield(config,"domain_policy")
    validate_struct_fields(config.domain_policy,["mode","default_size_m", ...
        "expanded_size_m","minimum_packable_centers"],"domain_policy");
    if string(config.domain_policy.mode)~="adaptive_for_center_packing"
        error("reqml:InvalidDomainPolicyMode", ...
            "domain_policy.mode must be adaptive_for_center_packing.");
    end
    default_size=double(config.domain_policy.default_size_m(:))';
    expanded_size=double(config.domain_policy.expanded_size_m(:))';
    if numel(default_size)~=2 || numel(expanded_size)~=2 || ...
            any(~isfinite(default_size)) || any(~isfinite(expanded_size)) || ...
            any(default_size<=0) || any(expanded_size<default_size)
        error("reqml:InvalidDomainPolicySize", ...
            ["domain_policy sizes must contain two positive dimensions, " ...
             "and expanded_size_m must not be smaller than default_size_m."]);
    end
    validate_positive_integer( ...
        config.domain_policy.minimum_packable_centers, ...
        "domain_policy.minimum_packable_centers");
end

validate_struct_fields( ...
    config.requirements, ...
    [
        "minimum_examples"
        "minimum_independent_runs"
        "minimum_independent_conditions"
        "minimum_sws_bins"
        "minimum_frequency_bins"
        "minimum_geometry_seeds"
    ], ...
    "requirements");

validate_struct_fields( ...
    config.planning, ...
    [
        "maximum_conditions"
        "realizations_per_condition"
    ], ...
    "planning");

validate_struct_fields( ...
    config.execution, ...
    [
        "maximum_iterations"
        "planner_seed"
        "resume_runs"
        "continue_on_error"
        "resume_existing_loop"
    ], ...
    "execution");

validate_edges( ...
    config.coverage.purity_edges, ...
    "coverage.purity_edges", ...
    [0 1]);

validate_edges( ...
    config.coverage. ...
        nominal_angular_coverage_edges, ...
    "coverage.nominal_angular_coverage_edges", ...
    [0 1]);

validate_edges( ...
    config.coverage.sws_edges_m_s, ...
    "coverage.sws_edges_m_s", ...
    [0 Inf]);

validate_edges( ...
    config.coverage.frequency_edges_hz, ...
    "coverage.frequency_edges_hz", ...
    [0 Inf]);

validate_nonnegative_integer( ...
    config.requirements.minimum_examples, ...
    "requirements.minimum_examples");

validate_nonnegative_integer( ...
    config.requirements.minimum_independent_runs, ...
    "requirements.minimum_independent_runs");

validate_nonnegative_integer( ...
    config.requirements. ...
        minimum_independent_conditions, ...
    "requirements.minimum_independent_conditions");

validate_nonnegative_integer( ...
    config.requirements.minimum_sws_bins, ...
    "requirements.minimum_sws_bins");

validate_nonnegative_integer( ...
    config.requirements.minimum_frequency_bins, ...
    "requirements.minimum_frequency_bins");

validate_nonnegative_integer( ...
    config.requirements.minimum_geometry_seeds, ...
    "requirements.minimum_geometry_seeds");

validate_positive_integer( ...
    config.planning.maximum_conditions, ...
    "planning.maximum_conditions");

validate_positive_integer( ...
    config.planning.realizations_per_condition, ...
    "planning.realizations_per_condition");

if isfield(config.planning, "training_geometry_mode")
    mode = string(config.planning.training_geometry_mode);

    if ~isscalar(mode) || ...
            ~ismember(mode, ["legacy_balanced", "analytic_bilayer"])
        error("reqml:InvalidAdaptiveCampaignConfig", ...
            "planning.training_geometry_mode must be legacy_balanced or analytic_bilayer.");
    end
end

validate_positive_integer( ...
    config.execution.maximum_iterations, ...
    "execution.maximum_iterations");

validate_nonnegative_integer( ...
    config.execution.planner_seed, ...
    "execution.planner_seed");

end


function resolved = resolve_config_paths( ...
        config, config_directory, repository_root)

resolved = struct();

schema_version = string(config.schema_version);

if schema_version == "1.0"
    resolved.previous_campaign_csv = ...
        resolve_path( ...
            config.paths.previous_campaign_csv, ...
            config_directory, ...
            repository_root);

    resolved.initial_batch_directory = ...
        resolve_path( ...
            config.paths.initial_batch_directory, ...
            config_directory, ...
            repository_root);
else
    resolved.previous_campaign_csv = "";
    resolved.initial_batch_directory = "";
end

resolved.output_root = ...
    resolve_path( ...
        config.paths.output_root, ...
        config_directory, ...
        repository_root);

resolved.simulation_framework_root = ...
    resolve_path( ...
        config.paths.simulation_framework_root, ...
        config_directory, ...
        repository_root);


if schema_version == "1.1"
    resolved.bootstrap_output_directory = ...
        fullfile( ...
            resolved.output_root, ...
            string(config.bootstrap. ...
                output_subdirectory));
else
    resolved.bootstrap_output_directory = "";
end

resolved.simulation_output_directory = ...
    resolve_path( ...
        config.simulation.output_directory, ...
        config_directory, ...
        repository_root);

mapping = ...
    config.simulation.base_config_mapping;

resolved.base_config_mapping = struct();

resolved.base_config_mapping.homogeneous = ...
    resolve_path( ...
        mapping.homogeneous, ...
        config_directory, ...
        repository_root);

resolved.base_config_mapping.bilayer = ...
    resolve_path( ...
        mapping.bilayer, ...
        config_directory, ...
        repository_root);

resolved.base_config_mapping.circular_inclusion = ...
    resolve_path( ...
        mapping.circular_inclusion, ...
        config_directory, ...
        repository_root);

end


function campaign = build_campaign_config( ...
        config, resolved, feature_config)

campaign = struct();

campaign.backend = ...
    string(config.simulation.backend);

campaign.campaign_name = ...
    string(config.campaign_id);

campaign.base_config_mapping = struct( ...
    "homogeneous", ...
        resolved.base_config_mapping.homogeneous, ...
    "bilayer", ...
        resolved.base_config_mapping.bilayer, ...
    "circular_inclusion", ...
        resolved.base_config_mapping. ...
            circular_inclusion);

campaign.output = struct( ...
    "directory", ...
    resolved.simulation_output_directory);

campaign.training_geometry_mode = ...
    resolve_training_geometry_mode(config);

if campaign.training_geometry_mode == "analytic_bilayer"
    campaign.analytic_bilayer = ...
        build_analytic_bilayer_config( ...
            resolved.base_config_mapping.bilayer, ...
            feature_config);
end

end


function mode = resolve_training_geometry_mode(config)

if isfield(config.planning, "training_geometry_mode")
    mode = string(config.planning.training_geometry_mode);
else
    mode = "legacy_balanced";
end

end


function analytic = build_analytic_bilayer_config( ...
        bilayer_base_config_path, feature_config)

if ~isfile(bilayer_base_config_path)
    error("reqml:AnalyticBilayerBaseConfigNotFound", ...
        "Analytic bilayer base configuration was not found: %s", ...
        bilayer_base_config_path);
end

base = jsondecode(fileread(bilayer_base_config_path));

required_domain_fields = [ ...
    "Lx_m"
    "Lz_m"
    "dx_m"
    "dz_m"
    ];

if ~isfield(base, "domain") || ...
        any(~isfield(base.domain, required_domain_fields))
    error("reqml:InvalidAnalyticBilayerBaseConfig", ...
        "Bilayer base configuration must define Lx_m, Lz_m, dx_m, and dz_m.");
end

domain_size_m = [ ...
    double(base.domain.Lx_m), ...
    double(base.domain.Lz_m)];
grid_spacing_m = [ ...
    double(base.domain.dx_m), ...
    double(base.domain.dz_m)];
domain_size_pixels = ...
    round(domain_size_m ./ grid_spacing_m) + 1;

analytic = struct();
analytic.domain_size_m = domain_size_m;
analytic.grid_spacing_m = grid_spacing_m;
analytic.patch_window_wavelengths = ...
    double(feature_config.M);
analytic.cs_guess_m_s = ...
    double(feature_config.cs_guess);
analytic.selected_patch_center_indices_xz = ...
    round((domain_size_pixels + 1) / 2);
analytic.interface_orientation = "x";
analytic.minimum_domain_margin_pixels = 0;

end


function value = resolve_path( ...
        raw_value, config_directory, repository_root)

value = string(raw_value);

if strlength(value) == 0
    error("reqml:EmptyAdaptiveCampaignConfigPath", ...
        "Adaptive campaign config contains an empty path.");
end

if startsWith(value, "${REPOSITORY_ROOT}/")
    value = fullfile( ...
        repository_root, ...
        extractAfter(value, ...
            "${REPOSITORY_ROOT}/"));

elseif value == "${REPOSITORY_ROOT}"
    value = repository_root;

elseif startsWith(value, "${CONFIG_DIRECTORY}/")
    value = fullfile( ...
        config_directory, ...
        extractAfter(value, ...
            "${CONFIG_DIRECTORY}/"));

elseif value == "${CONFIG_DIRECTORY}"
    value = config_directory;

elseif ~is_absolute_path(value)
    value = fullfile( ...
        config_directory, ...
        value);
end

value = string( ...
    char(java.io.File(char(value)).getCanonicalPath()));

end


function tf = is_absolute_path(path_value)

path_value = char(path_value);

if ispc
    tf = ~isempty(regexp( ...
        path_value, ...
        '^[A-Za-z]:[\\/]', ...
        'once')) || ...
        startsWith(path_value, "\\");
else
    tf = startsWith(path_value, "/");
end

end


function root = resolve_repository_root()

function_path = string(mfilename("fullpath"));

root = string(fileparts(fileparts(fileparts( ...
    fileparts(char(function_path))))));

end


function validate_directed_center_selection_config( ...
        selection)

validate_struct_fields( ...
    selection, ...
    [
        "enabled"
        "candidate_step_pixels"
        "maximum_centers_per_cell"
        "minimum_center_distance_fraction"
        "minimum_valid_fraction"
        "seed_offset"
    ], ...
    "directed_center_selection");

if ~islogical(selection.enabled) || ...
        ~isscalar(selection.enabled)
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        ["Config field 'directed_center_selection.enabled' " ...
         "must be logical."]);
end

validate_positive_integer( ...
    selection.candidate_step_pixels, ...
    "directed_center_selection.candidate_step_pixels");

validate_positive_integer( ...
    selection.maximum_centers_per_cell, ...
    "directed_center_selection.maximum_centers_per_cell");

distance_fraction = double( ...
    selection.minimum_center_distance_fraction);

if ~isscalar(distance_fraction) || ...
        ~isfinite(distance_fraction) || ...
        distance_fraction < 0
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        ["Config field 'directed_center_selection." ...
         "minimum_center_distance_fraction' must be " ...
         "a finite nonnegative scalar."]);
end

valid_fraction = double( ...
    selection.minimum_valid_fraction);

if ~isscalar(valid_fraction) || ...
        ~isfinite(valid_fraction) || ...
        valid_fraction < 0 || ...
        valid_fraction > 1
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        ["Config field 'directed_center_selection." ...
         "minimum_valid_fraction' must lie in [0,1]."]);
end

validate_nonnegative_integer( ...
    selection.seed_offset, ...
    "directed_center_selection.seed_offset");

end


function validate_struct_fields(value, required, context)

if ~isstruct(value) || ~isscalar(value)
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config field '%s' must be a scalar object.", ...
        context);
end

missing = setdiff( ...
    required, ...
    string(fieldnames(value)));

if ~isempty(missing)
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config object '%s' is missing field '%s'.", ...
        context, ...
        missing(1));
end

end


function validate_nonempty_text(value, name)

if strlength(string(value)) == 0
    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config field '%s' must be non-empty.", ...
        name);
end

end


function validate_edges(value, name, bounds)

value = double(value(:));

if numel(value) < 2 || ...
        any(~isfinite(value)) || ...
        any(diff(value) <= 0) || ...
        value(1) < bounds(1) || ...
        value(end) > bounds(2)

    error("reqml:InvalidAdaptiveCampaignConfig", ...
        ["Config field '%s' must contain at least two " ...
         "strictly increasing values within [%g,%g]."], ...
        name, ...
        bounds(1), ...
        bounds(2));
end

end


function validate_positive_integer(value, name)

value = double(value);

if ~isscalar(value) || ...
        ~isfinite(value) || ...
        value < 1 || ...
        value ~= fix(value)

    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config field '%s' must be a positive integer.", ...
        name);
end

end


function validate_nonnegative_integer(value, name)

value = double(value);

if ~isscalar(value) || ...
        ~isfinite(value) || ...
        value < 0 || ...
        value ~= fix(value)

    error("reqml:InvalidAdaptiveCampaignConfig", ...
        "Config field '%s' must be a nonnegative integer.", ...
        name);
end

end
