function result = runAdaptiveDatasetPipelineFromConfig( ...
    config_file, options)
%RUNADAPTIVEDATASETPIPELINEFROMCONFIG
% Run an adaptive campaign and prepare a balanced training dataset.
%
% The campaign remains responsible for simulation, coverage, planning,
% persistence, and resume. This wrapper performs postprocessing only after
% coverage is complete.

arguments
    config_file {mustBeTextScalar}

    options.TrainingOutputDirectory {mustBeTextScalar}

    options.MaximumConditionsPerCell (1,1) double = Inf

    options.MaximumRunsPerConditionPerCell ...
        (1,1) double = Inf

    options.MaximumPatchesPerRunPerCell ...
        (1,1) double = Inf

    options.TrainingRandomSeed (1,1) double = 1

    options.RunCampaignFunction (1,1) function_handle = ...
        @reqml.campaigns.runAdaptiveCampaignFromConfig

    options.BalanceFunction (1,1) function_handle = ...
        @reqml.datasets.makeBalancedTrainingSelection
end

config_file = string(config_file);
training_output_directory = ...
    string(options.TrainingOutputDirectory);

campaign_result = feval( ...
    options.RunCampaignFunction, ...
    config_file);

if ~campaign_result.coverage_complete
    error("reqml:AdaptiveDatasetCoverageIncomplete", ...
        ["Adaptive campaign did not reach complete coverage. " ...
         "Remaining deficient cells: %d."], ...
        campaign_result.final_deficient_cell_count);
end

if strlength( ...
        campaign_result.final_iteration_directory) == 0

    error("reqml:AdaptiveDatasetFinalIterationMissing", ...
        "Adaptive campaign returned no final iteration directory.");
end

examples_file = fullfile( ...
    campaign_result.final_iteration_directory, ...
    "dataset", ...
    "examples.mat");

if ~isfile(examples_file)
    error("reqml:AdaptiveDatasetExamplesNotFound", ...
        "Final examples file was not found: %s", ...
        examples_file);
end

config = jsondecode(fileread(config_file));

coverage = config.coverage;

loaded = load(examples_file);

if ~isfield(loaded, "examples") || ...
        ~istable(loaded.examples)

    error("reqml:InvalidAdaptiveDatasetExamples", ...
        "Final examples MAT file must contain table variable 'examples'.");
end

balance_result = feval( ...
    options.BalanceFunction, ...
    loaded.examples, ...
    PurityEdges=double( ...
        coverage.purity_edges(:))', ...
    NominalAngularCoverageEdges=double( ...
        coverage. ...
            nominal_angular_coverage_edges(:))', ...
    SwsEdges=double( ...
        coverage.sws_edges_m_s(:))', ...
    FrequencyEdges=double( ...
        coverage.frequency_edges_hz(:))', ...
    MaximumConditionsPerCell= ...
        options.MaximumConditionsPerCell, ...
    MaximumRunsPerConditionPerCell= ...
        options.MaximumRunsPerConditionPerCell, ...
    MaximumPatchesPerRunPerCell= ...
        options.MaximumPatchesPerRunPerCell, ...
    RandomSeed=options.TrainingRandomSeed, ...
    OutputDirectory=training_output_directory, ...
    SaveOutputs=true);

result = struct();

result.schema_name = ...
    "reqml_adaptive_dataset_pipeline";

result.schema_version = "1.0";

result.config_file = config_file;

result.campaign = campaign_result;
result.training_balance = balance_result;

result.paths = struct();

result.paths.final_examples_file = ...
    string(examples_file);

result.paths.balanced_examples_file = ...
    balance_result.paths.examples_mat;

result.paths.training_balance_summary = ...
    balance_result.paths.summary_csv;

end
