function report = runAnalyticBilayerSmokeTest(config_file)
%RUNANALYTICBILAYERSMOKETEST Run a controlled requested-cell hit audit.

arguments
    config_file {mustBeTextScalar}
end

config_file = string(config_file);

if ~isfile(config_file)
    error("reqml:AnalyticBilayerSmokeConfigNotFound", ...
        "Smoke-test configuration was not found: %s", config_file);
end

config = jsondecode(fileread(config_file));
repository_root = fileparts(fileparts(fileparts(fileparts( ...
    mfilename("fullpath")))));
output_directory = resolve_repository_path( ...
    config.output_directory, repository_root);

if ~isfolder(output_directory)
    mkdir(output_directory);
end

campaign_config = struct();
campaign_config.backend = "swsynth";
campaign_config.campaign_name = string(config.campaign_id);
campaign_config.training_geometry_mode = "analytic_bilayer";
campaign_config.base_config_mapping = config.simulation.base_config_mapping;
campaign_config.output = struct( ...
    "directory", string(config.simulation.output_directory));
campaign_config.analytic_bilayer = config.geometry_control;

angular_policy = resolve_angular_field_policy(config);

requests = normalize_requests(config.requests);

physical_conditions = ...
    reqml.campaigns.materializePhysicalConditions( ...
        requests, ...
        DomainLxM=config.geometry_control.domain_size_m(1), ...
        DomainLzM=config.geometry_control.domain_size_m(2), ...
        TrainingGeometryMode="analytic_bilayer", ...
        GridSpacingM=config.geometry_control.grid_spacing_m, ...
        PatchWindowWavelengths= ...
            config.geometry_control.patch_window_wavelengths, ...
        CsGuessMPerS=config.geometry_control.cs_guess_m_s, ...
        SelectedPatchCenterIndicesXZ= ...
            config.geometry_control. ...
                selected_patch_center_indices_xz, ...
        InterfaceOrientation=string( ...
            config.geometry_control.interface_orientation), ...
        MinimumDomainMarginPixels=double( ...
            config.geometry_control. ...
                minimum_domain_margin_pixels), ...
        AngularAxisMode=angular_policy.axis_mode, ...
        InPlanePolicy=angular_policy.in_plane_policy, ...
        InPlaneFraction=angular_policy.in_plane_fraction, ...
        PlannerSeed=double(config.planner_seed));

angular_audit = audit_angular_fields( ...
    physical_conditions, angular_policy);

if ~angular_audit.acceptance_met
    error("reqml:AngularFieldSmokeAuditFailed", ...
        "Angular field audit failed before simulation execution.");
end

batch_directory = fullfile(output_directory, "batch");
paths = reqml.campaigns.writeAdaptiveBatch( ...
    physical_conditions, campaign_config, ...
    OutputDirectory=batch_directory, ...
    BatchId=string(config.campaign_id), ...
    PlannerSeed=double(config.planner_seed));

execution = reqml.campaigns.executeAdaptiveBatch( ...
    batch_directory, ...
    string(config.simulation_framework_root), ...
    Resume=true, ContinueOnError=false);

combined_csv = fullfile(output_directory, "campaign_runs.csv");
reqml.campaigns.mergeCampaignRunCsvs( ...
    execution.campaign_csv_files, ...
    OutputFile=combined_csv);

feature_config = reqml.config.default_feature_config( ...
    "M", config.geometry_control.patch_window_wavelengths, ...
    "cs_guess", config.geometry_control.cs_guess_m_s);

dataset = reqml.datasets.build_dataset_from_campaign( ...
    combined_csv, feature_config, ...
    DatasetId=string(config.campaign_id), ...
    CsGuessMPerS=config.geometry_control.cs_guess_m_s, ...
    AdaptiveBatchPlanFile=paths.plan, ...
    OutputDirectory=fullfile(output_directory, "dataset"), ...
    SaveOutputs=true);

coverage = config.coverage;

coverage_report = reqml.coverage.computePatchCoverage( ...
    dataset.examples, ...
    FieldCoverageMode="nominal", ...
    PurityEdges=double(coverage.purity_edges(:))', ...
    DiffusivityEdges=double( ...
        coverage.nominal_angular_coverage_edges(:))', ...
    SwsEdges=double(coverage.sws_edges_m_s(:))', ...
    FrequencyEdges=double(coverage.frequency_edges_hz(:))', ...
    MinimumExamples=1, ...
    MinimumIndependentRuns=1, ...
    MinimumIndependentConditions=1, ...
    MinimumSwsBins=0, ...
    MinimumFrequencyBins=0, ...
    MinimumGeometrySeeds=0);

condition_summary = ...
    reqml.coverage.summarizeRequestedVsAchieved( ...
        coverage_report.assigned_examples, paths.plan);

condition_count = height(condition_summary);
patch_count = sum(condition_summary.patch_count);
requested_cell_hit_count = sum( ...
    condition_summary.requested_cell_hit);
requested_cell_hit_rate = ...
    requested_cell_hit_count / max(1, condition_count);

summary_csv = fullfile( ...
    output_directory, "analytic_bilayer_smoke_summary.csv");
writetable(condition_summary, summary_csv);

report = struct();
report.schema_name = "reqml_analytic_bilayer_smoke_report";
report.schema_version = "1.0";
report.campaign_id = string(config.campaign_id);
report.condition_count = condition_count;
report.patch_count = patch_count;
report.requested_cell_hit_count = requested_cell_hit_count;
report.requested_cell_hit_rate = requested_cell_hit_rate;
report.acceptance_target = double(config.acceptance_target);
report.acceptance_met = ...
    requested_cell_hit_rate >= report.acceptance_target;
report.requested_purity_range = unique( ...
    [condition_summary.requested_purity_lower, ...
     condition_summary.requested_purity_upper], "rows");
report.predicted_discrete_purity_range = [ ...
    min(condition_summary.predicted_discrete_purity), ...
    max(condition_summary.predicted_discrete_purity)];
report.achieved_purity_median = median( ...
    condition_summary.purity_median, "omitnan");
report.achieved_purity_range = [ ...
    min(condition_summary.purity_min, [], "omitnan"), ...
    max(condition_summary.purity_max, [], "omitnan")];
report.condition_summary_csv = string(summary_csv);
report.batch_plan = paths.plan;
report.combined_campaign_csv = string(combined_csv);
report.dataset_directory = string(dataset.paths.output_directory);
report.generated_simulation_output_directory = ...
    string(config.simulation.output_directory);
report.angular_field = angular_policy;
report.angular_audit = angular_audit;

report_path = fullfile( ...
    output_directory, "analytic_bilayer_smoke_report.json");
write_json(report_path, report);
report.report_path = string(report_path);
report.condition_summary = condition_summary;

end



function policy = resolve_angular_field_policy(config)

policy = struct( ...
    "axis_mode", "fixed", ...
    "in_plane_policy", "legacy_sqrt", ...
    "in_plane_fraction", 0.25);

if ~isfield(config, "angular_field")
    return
end

angular = config.angular_field;

if isfield(angular, "axis_mode")
    policy.axis_mode = string(angular.axis_mode);
end

if isfield(angular, "in_plane_policy")
    policy.in_plane_policy = string(angular.in_plane_policy);
end

if isfield(angular, "in_plane_fraction")
    policy.in_plane_fraction = ...
        double(angular.in_plane_fraction);
end

end


function audit = audit_angular_fields(conditions, policy)

condition_count = numel(conditions);

axes_xyz = zeros(condition_count, 3);
direction_counts = zeros(condition_count, 1);
in_plane_counts = zeros(condition_count, 1);
expected_in_plane_counts = zeros(condition_count, 1);

for index = 1:condition_count
    field = conditions(index).wavefield;

    axes_xyz(index, :) = double(field.axis_xyz);
    direction_counts(index) = double(field.direction_count);
    in_plane_counts(index) = double(field.in_plane_count);

    if policy.in_plane_policy == "fixed_fraction"
        expected_in_plane_counts(index) = min( ...
            direction_counts(index), ...
            max(1, round( ...
                policy.in_plane_fraction * ...
                direction_counts(index))));
    else
        expected_in_plane_counts(index) = min( ...
            direction_counts(index), ...
            max(1, round(sqrt(direction_counts(index)))));
    end
end

axis_norms = vecnorm(axes_xyz, 2, 2);
unique_axes = unique(round(axes_xyz, 12), "rows");

audit = struct();
audit.condition_count = condition_count;
audit.axes_xyz = axes_xyz;
audit.direction_counts = direction_counts;
audit.in_plane_counts = in_plane_counts;
audit.expected_in_plane_counts = expected_in_plane_counts;
audit.maximum_axis_norm_error = ...
    max(abs(axis_norms - 1));
audit.maximum_out_of_plane_component = ...
    max(abs(axes_xyz(:, 2)));
audit.unique_axis_count = size(unique_axes, 1);
audit.reproducible_policy = true;
audit.in_plane_count_match = ...
    all(in_plane_counts == expected_in_plane_counts);

if policy.axis_mode == "seeded_uniform_in_plane"
    audit.axis_diversity_met = ...
        condition_count <= 1 || ...
        audit.unique_axis_count > 1;
else
    audit.axis_diversity_met = true;
end

audit.acceptance_met = ...
    audit.maximum_axis_norm_error <= 1e-12 && ...
    audit.maximum_out_of_plane_component <= 1e-12 && ...
    audit.in_plane_count_match && ...
    audit.axis_diversity_met;

end



function requests = normalize_requests(raw)

requests = raw(:);

for index = 1:numel(requests)
    requests(index).condition_id = string(requests(index).condition_id);
    requests(index).geometry_family = "bilayer";
    requests(index).field_regime = "continuous_dnom";
    requests(index).realization_count = ...
        double(requests(index).realization_count);
    requests(index).deficit_score = 1;
    requests(index).diffusivity_range = ...
        double(requests(index).nominal_angular_coverage_range(:))';
end

end


function value = resolve_repository_path(raw, repository_root)

value = string(raw);

if startsWith(value, "${REPOSITORY_ROOT}/")
    value = fullfile(repository_root, ...
        extractAfter(value, "${REPOSITORY_ROOT}/"));
end

end


function write_json(path_value, value)

text = jsonencode(value, PrettyPrint=true);
file_id = fopen(path_value, "w");

if file_id < 0
    error("reqml:AnalyticBilayerSmokeWriteFailed", ...
        "Could not open smoke report for writing: %s", path_value);
end


cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, "%s\n", text);
clear cleanup

end
