repository_root = "/Users/sara/local/req-ml";
legacy_root = "/tmp/reqml_legacy_reference";

cd(repository_root);
addpath(repository_root);
addpath(legacy_root);

root_dir = setup_reqml(); %#ok<NASGU>

% =========================================================================
% Diagnostic configuration
% =========================================================================

target_cs_m_s = 3.0;
target_frequency_hz = 600;
direction_counts = [1, 4, 8, 32, 128];

fixed_q = 0.55;
step_x = 1;
step_z = 1;

output_directory = fullfile( ...
    repository_root, ...
    "outputs", ...
    "diagnostics", ...
    "step1_direction_comparison");

if ~isfolder(output_directory)
    mkdir(output_directory);
end

% =========================================================================
% Parallel pool
% =========================================================================

pool = gcp("nocreate");

if isempty(pool)
    pool = parpool("threads");
end

fprintf("Parallel workers: %d\n", pool.NumWorkers);

% =========================================================================
% Load dataset metadata and locate matching runs
% =========================================================================

dataset_path = fullfile( ...
    repository_root, ...
    "outputs", ...
    "datasets", ...
    "homogeneous_projected3d_control", ...
    "examples.mat");

loaded = load(dataset_path, "examples");
all_examples = loaded.examples;

run_metadata = unique( ...
    all_examples(:, [ ...
        "campaign_run_id", ...
        "campaign_sample_file", ...
        "campaign_frequency_hz", ...
        "campaign_background_cs_m_s", ...
        "campaign_direction_count"]), ...
    "rows");

selected_runs = table();

for direction_index = 1:numel(direction_counts)
    direction_count = direction_counts(direction_index);

    match = ...
        abs(run_metadata.campaign_background_cs_m_s - target_cs_m_s) ...
            < 1e-12 & ...
        run_metadata.campaign_frequency_hz == target_frequency_hz & ...
        run_metadata.campaign_direction_count == direction_count;

    candidates = run_metadata(match, :);

    if isempty(candidates)
        warning( ...
            "No run found for cs=%.1f, f=%g Hz, Ndir=%g.", ...
            target_cs_m_s, ...
            target_frequency_hz, ...
            direction_count);
        continue
    end

    % Deterministic choice when more than one seed/run is available.
    candidates = sortrows(candidates, "campaign_run_id");
    selected_runs = [selected_runs; candidates(1, :)]; %#ok<AGROW>
end

if isempty(selected_runs)
    error("No matching runs were found.");
end

fprintf("\nSelected runs:\n");
disp(selected_runs(:, [ ...
    "campaign_run_id", ...
    "campaign_frequency_hz", ...
    "campaign_background_cs_m_s", ...
    "campaign_direction_count"]));

% =========================================================================
% Load the frozen bagged_full model
% =========================================================================

model_file = fullfile( ...
    repository_root, ...
    "outputs", ...
    "baselines", ...
    "homogeneous_control", ...
    "baseline_models.mat");

if ~isfile(model_file)
    error( ...
        "reqml:MissingFrozenBaseline", ...
        "Frozen baseline model file not found: %s", ...
        model_file);
end

fprintf("\nLoading frozen bagged_full model:\n%s\n", model_file);

bagged_model = reqml.training.load_frozen_model( ...
    model_file, ...
    "bagged_full");

predictor_names = string(bagged_model.predictor_names(:));

fprintf("Frozen model loaded successfully.\n");
fprintf("Model ID     : %s\n", bagged_model.model_id);
fprintf("Model type   : %s\n", bagged_model.model_type);
fprintf("Training rows: %d\n", bagged_model.training_row_count);
fprintf("Predictors   : %d\n", numel(predictor_names));
fprintf("Random seed  : %d\n", bagged_model.random_seed);

% =========================================================================
% Evaluate every selected condition at step = 1 pixel
% =========================================================================

number_of_runs = height(selected_runs);

diagnostic_records = repmat(struct( ...
    "campaign_run_id", "", ...
    "frequency_hz", NaN, ...
    "true_cs_m_s", NaN, ...
    "direction_count", NaN, ...
    "legacy_patch_count", NaN, ...
    "bagged_patch_count", NaN, ...
    "legacy_mean_m_s", NaN, ...
    "legacy_std_m_s", NaN, ...
    "legacy_mape", NaN, ...
    "bagged_mean_m_s", NaN, ...
    "bagged_std_m_s", NaN, ...
    "bagged_mape", NaN, ...
    "bagged_bias_percent", NaN), ...
    number_of_runs, ...
    1);

for run_index = 1:number_of_runs
    run_row = selected_runs(run_index, :);

    run_id = string(run_row.campaign_run_id);
    sample_path = string(run_row.campaign_sample_file);

    fprintf("\n============================================\n");
    fprintf("Run %d / %d: %s\n", ...
        run_index, number_of_runs, run_id);
    fprintf("Ndir: %g\n", run_row.campaign_direction_count);
    fprintf("============================================\n");

    data = reqml.integration.load_wavefield_sample(sample_path);

    cfg = struct();
    cfg.dx = double(data.dx_m);
    cfg.dz = double(data.dz_m);
    cfg.f0 = double(data.frequency_hz);
    cfg.cs_bg = double(run_row.campaign_background_cs_m_s);
    cfg.WaveModel = "wavefield_sample";

    feat_cfg = reqml.config.default_feature_config( ...
        "M", 2, ...
        "cs_guess", 3.0, ...
        "gamma_win", 1.0, ...
        "pad_factor", 1, ...
        "smooth_sigma_2d", 1.0);

    % ---------------------------------------------------------------------
    % Legacy fixed-q map
    % ---------------------------------------------------------------------

    legacy_timer = tic;

    [cs_legacy, ~, ~, x_legacy, z_legacy] = ...
        REQ_estimator_new( ...
            data.wavefield_zx, ...
            cfg.dx, ...
            cfg.dz, ...
            cfg.f0, ...
            3.0, ...
            "M", 2, ...
            "StepX", step_x, ...
            "StepZ", step_z, ...
            "Gamma", 1.0, ...
            "PadFactor", 1, ...
            "Nbins", "auto", ...
            "SmoothSigma", 1.0, ...
            "QuantE", fixed_q, ...
            "EdgeMode", "valid", ...
            "UseParfor", true);

    fprintf("Legacy elapsed: %.1f s\n", toc(legacy_timer));

    legacy_error_percent = ...
        100 * (cs_legacy - cfg.cs_bg) / cfg.cs_bg;

    % ---------------------------------------------------------------------
    % Step-1 feature extraction
    % ---------------------------------------------------------------------

    extraction_timer = tic;

    extraction = reqml.datasets.extract_examples_from_sample( ...
        data, ...
        feat_cfg, ...
        DatasetId="step1_direction_diagnostic", ...
        SampleId=run_id, ...
        StepX=step_x, ...
        StepZ=step_z, ...
        StoreReqCurves=false, ...
        UseWindowParfor=true);

    step1_examples = extraction.examples;
    row_count = height(step1_examples);

    fprintf("Feature extraction elapsed: %.1f s\n", ...
        toc(extraction_timer));
    fprintf("Step-1 patches: %d\n", row_count);

    % ---------------------------------------------------------------------
    % Supply campaign-level predictors absent from extraction output
    % ---------------------------------------------------------------------

    available_names = ...
        string(step1_examples.Properties.VariableNames);

    missing_predictors = ...
        setdiff(predictor_names, available_names);

    source_rows = all_examples( ...
        all_examples.campaign_run_id == run_id, ...
        :);

    source_row = source_rows(1, :);

    for predictor_index = 1:numel(missing_predictors)
        variable_name = missing_predictors(predictor_index);

        if ~ismember( ...
                variable_name, ...
                string(source_row.Properties.VariableNames))
            error( ...
                "Cannot supply predictor '%s' for run '%s'.", ...
                variable_name, ...
                run_id);
        end

        source_value = source_row.(char(variable_name));

        if ~(isnumeric(source_value) || islogical(source_value)) || ...
                ~isscalar(source_value)
            error( ...
                "Predictor '%s' is not a scalar numeric value.", ...
                variable_name);
        end

        step1_examples.(char(variable_name)) = ...
            repmat(source_value, row_count, 1);
    end

    step1_examples.campaign_frequency_hz = ...
        repmat(cfg.f0, row_count, 1);

    step1_examples.campaign_background_cs_m_s = ...
        repmat(cfg.cs_bg, row_count, 1);

    step1_examples.campaign_direction_count = ...
        repmat( ...
            double(run_row.campaign_direction_count), ...
            row_count, ...
            1);

    step1_examples.campaign_run_id = ...
        repmat(run_id, row_count, 1);

    % ---------------------------------------------------------------------
    % Bagged prediction and q -> k -> SWS conversion
    % ---------------------------------------------------------------------

    [X_step1, ~] = ...
        reqml.training.build_numeric_predictor_matrix( ...
            step1_examples, ...
            predictor_names);

    q_bagged = ...
        reqml.training.predict_regression_model( ...
            bagged_model, ...
            X_step1);

    sws_bagged = ...
        reqml.evaluation.convert_q_predictions_to_sws( ...
            step1_examples, ...
            q_bagged);

    x_bagged = unique( ...
        double(step1_examples.x_center_m), ...
        "sorted");

    z_bagged = unique( ...
        double(step1_examples.z_center_m), ...
        "sorted");

    nx_bagged = numel(x_bagged);
    nz_bagged = numel(z_bagged);

    [~, x_index] = ismember( ...
        double(step1_examples.x_center_m), ...
        x_bagged);

    [~, z_index] = ismember( ...
        double(step1_examples.z_center_m), ...
        z_bagged);

    linear_index = sub2ind( ...
        [nz_bagged, nx_bagged], ...
        z_index, ...
        x_index);

    cs_bagged = nan(nz_bagged, nx_bagged);
    cs_bagged(linear_index) = sws_bagged.cs_pred_m_s;

    bagged_error_percent = nan(nz_bagged, nx_bagged);
    bagged_error_percent(linear_index) = ...
        sws_bagged.cs_error_percent;

    % ---------------------------------------------------------------------
    % Save side-by-side figure for this run
    % ---------------------------------------------------------------------

    common_limits = [
        min([cs_legacy(:); cs_bagged(:)], [], "omitnan")
        max([cs_legacy(:); cs_bagged(:)], [], "omitnan")
        ];

    figure_handle = figure( ...
        Name="Step-1 direction comparison", ...
        Position=[100, 100, 1600, 700]);

    tiledlayout(1, 2, ...
        TileSpacing="compact", ...
        Padding="compact");

    nexttile;

    imagesc( ...
        1e3*x_legacy, ...
        1e3*z_legacy, ...
        cs_legacy);

    axis image;
    axis xy;
    colorbar;
    clim(common_limits);

    xlabel("x (mm)");
    ylabel("z (mm)");
    title(sprintf("Legacy fixed q = %.2f", fixed_q));

    nexttile;

    imagesc( ...
        1e3*x_bagged, ...
        1e3*z_bagged, ...
        cs_bagged);

    axis image;
    axis xy;
    colorbar;
    clim(common_limits);

    xlabel("x (mm)");
    ylabel("z (mm)");
    title("Bagged full");

    sgtitle(sprintf( ...
        "%s | %.0f Hz | c_s = %.1f m/s | N_{dir} = %g", ...
        run_id, ...
        cfg.f0, ...
        cfg.cs_bg, ...
        double(run_row.campaign_direction_count)), ...
        Interpreter="none");

    figure_path = fullfile( ...
        output_directory, ...
        sprintf( ...
            "step1_ndir_%03d_%s.png", ...
            round(run_row.campaign_direction_count), ...
            run_id));

    exportgraphics( ...
        figure_handle, ...
        figure_path, ...
        Resolution=200);

    close(figure_handle);

    % ---------------------------------------------------------------------
    % Record metrics
    % ---------------------------------------------------------------------

    diagnostic_records(run_index).campaign_run_id = run_id;
    diagnostic_records(run_index).frequency_hz = cfg.f0;
    diagnostic_records(run_index).true_cs_m_s = cfg.cs_bg;
    diagnostic_records(run_index).direction_count = ...
        double(run_row.campaign_direction_count);

    diagnostic_records(run_index).legacy_patch_count = ...
        numel(cs_legacy);

    diagnostic_records(run_index).bagged_patch_count = ...
        numel(cs_bagged);

    diagnostic_records(run_index).legacy_mean_m_s = ...
        mean(cs_legacy, "all", "omitnan");

    diagnostic_records(run_index).legacy_std_m_s = ...
        std(cs_legacy, 0, "all", "omitnan");

    diagnostic_records(run_index).legacy_mape = ...
        mean(abs(legacy_error_percent), "all", "omitnan");

    diagnostic_records(run_index).bagged_mean_m_s = ...
        mean(cs_bagged, "all", "omitnan");

    diagnostic_records(run_index).bagged_std_m_s = ...
        std(cs_bagged, 0, "all", "omitnan");

    diagnostic_records(run_index).bagged_mape = ...
        mean(abs(bagged_error_percent), "all", "omitnan");

    diagnostic_records(run_index).bagged_bias_percent = ...
        mean(bagged_error_percent, "all", "omitnan");
end

% =========================================================================
% Save and print summary
% =========================================================================

diagnostic_summary = struct2table(diagnostic_records);
diagnostic_summary = sortrows( ...
    diagnostic_summary, ...
    "direction_count");

summary_path = fullfile( ...
    output_directory, ...
    "step1_direction_summary.csv");

writetable(diagnostic_summary, summary_path);

fprintf("\n============================================\n");
fprintf("STEP-1 DIRECTION COMPARISON COMPLETED\n");
fprintf("============================================\n");

disp(diagnostic_summary);

fprintf("Summary saved to:\n%s\n", summary_path);
