%RUN_ALL Run all public REQ Q0 examples.

example_root = fileparts(mfilename("fullpath"));
reqml_root = fileparts(example_root);
run(fullfile(reqml_root,"setup_reqml.m"));

fprintf("\n=== REQ Q0 public examples ===\n");

fprintf("\n[1/2] Homogeneous\n");
homogeneous = reqml.examples.runExample( ...
    "homogeneous", ...
    Cs=2.0, ...
    FrequencyHz=400, ...
    FieldRegime="directional", ...
    M=2, ...
    StepPixels=4, ...
    Verbose=true, ...
    SaveFigure=true, ...
    ShowFigure=false);

fprintf("\n[2/2] Inclusion\n");
inclusion = reqml.examples.runExample( ...
    "inclusion", ...
    CsBackground=2.0, ...
    CsInclusion=3.0, ...
    InclusionRadiusMm=15, ...
    FrequencyHz=400, ...
    FieldRegime="directional", ...
    M=2, ...
    StepPixels=4, ...
    Verbose=true, ...
    SaveFigure=true, ...
    ShowFigure=false);

release_examples = struct( ...
    "homogeneous",homogeneous, ...
    "inclusion",inclusion);

fprintf("\nREQ Q0 public example smoke test completed.\n");
