% Circular inclusion wavefield -> REQ Q0 SWS map.

example_dir = fileparts(mfilename("fullpath"));
reqml_root = fileparts(fileparts(example_dir));
run(fullfile(reqml_root,"setup_reqml.m"));

example = reqml.examples.runExample( ...
    "inclusion", ...
    CsBackground=2.0, ...
    CsInclusion=3.0, ...
    InclusionRadiusMm=15, ...
    FrequencyHz=400, ...
    FieldRegime="directional", ...
    M=2, ...
    StepPixels=4, ...
    Verbose=true, ...
    SaveFigure=true, ...
    ShowFigure=true);

result = example.result;
