function result = freeze_grouped_training_split( ...
    examples, output_directory, options)
%FREEZE_GROUPED_TRAINING_SPLIT Create and persist one immutable split.

arguments
    examples table
    output_directory (1,1) string

    options.DatasetPath (1,1) string = ""

    options.ConditionColumn (1,1) string = ...
        "campaign_condition_id"

    options.RunColumn (1,1) string = ...
        "campaign_run_id"

    options.SplitSeed (1,1) double = 4101
    options.FoldSeed (1,1) double = 5101

    options.TrainFraction (1,1) double = 0.70
    options.ValidationFraction (1,1) double = 0.15
    options.TestFraction (1,1) double = 0.15

    options.FoldCount (1,1) double = 5
end

split = reqml.splits.make_grouped_condition_split( ...
    examples, ...
    GroupColumns=options.ConditionColumn, ...
    RunColumn=options.RunColumn, ...
    Seed=options.SplitSeed, ...
    TrainFraction=options.TrainFraction, ...
    ValidationFraction=options.ValidationFraction, ...
    TestFraction=options.TestFraction);

split_report = reqml.splits.validate_split_integrity( ...
    examples, ...
    split);

if ~split_report.valid
    error("reqml:InvalidFrozenTrainingSplit", ...
        "Grouped split failed integrity validation: %s", ...
        split_report.summary);
end

folds = reqml.splits.make_grouped_training_folds( ...
    examples, ...
    split, ...
    ConditionColumn=options.ConditionColumn, ...
    FoldCount=options.FoldCount, ...
    Seed=options.FoldSeed);

fold_report = ...
    reqml.splits.validate_training_fold_integrity( ...
        examples, ...
        split, ...
        folds);

if ~fold_report.valid
    error("reqml:InvalidFrozenTrainingFolds", ...
        "Training folds failed integrity validation: %s", ...
        fold_report.summary);
end

paths = reqml.splits.save_training_split_manifest( ...
    examples, ...
    split, ...
    folds, ...
    output_directory, ...
    DatasetPath=options.DatasetPath);

result = struct();
result.schema_name = "reqml_frozen_training_split_result";
result.schema_version = "1.0";

result.split = split;
result.folds = folds;
result.split_integrity = split_report;
result.fold_integrity = fold_report;
result.paths = paths;

end
