function report = validate_training_fold_integrity( ...
    examples, split, folds)
%VALIDATE_TRAINING_FOLD_INTEGRITY Validate grouped train-only CV folds.

arguments
    examples table
    split (1,1) struct
    folds (1,1) struct
end

if ~isfield(folds, "cv_fold") || ...
        ~isfield(folds, "fold_count") || ...
        ~isfield(folds, "condition_column")
    error("reqml:InvalidTrainingFolds", ...
        "Training folds are missing required fields.");
end

n = height(examples);
cv_fold = double(folds.cv_fold(:));

if numel(cv_fold) ~= n
    error("reqml:TrainingFoldSizeMismatch", ...
        "Fold row count does not match example count.");
end

condition_id = string( ...
    examples.(char(folds.condition_column)));

train_only = ...
    all(cv_fold(split.train_mask) >= 1) && ...
    all(cv_fold(~split.train_mask) == 0);

valid_fold_ids = all(ismember( ...
    unique(cv_fold(split.train_mask)), ...
    (1:folds.fold_count)'));

all_folds_present = isequal( ...
    unique(cv_fold(split.train_mask)), ...
    (1:folds.fold_count)');

condition_overlap = false;
run_overlap = false;

train_conditions = unique( ...
    condition_id(split.train_mask));

for index = 1:numel(train_conditions)
    values = unique(cv_fold( ...
        split.train_mask & ...
        condition_id == train_conditions(index)));

    if numel(values) ~= 1
        condition_overlap = true;
        break
    end
end

train_runs = unique(string( ...
    examples.campaign_run_id(split.train_mask)));

for index = 1:numel(train_runs)
    values = unique(cv_fold( ...
        split.train_mask & ...
        string(examples.campaign_run_id) == train_runs(index)));

    if numel(values) ~= 1
        run_overlap = true;
        break
    end
end

report = struct();
report.schema_name = ...
    "reqml_training_fold_integrity_report";
report.schema_version = "1.0";

report.train_only = train_only;
report.valid_fold_ids = valid_fold_ids;
report.all_folds_present = all_folds_present;
report.condition_overlap = condition_overlap;
report.run_overlap = run_overlap;

report.valid = ...
    train_only && ...
    valid_fold_ids && ...
    all_folds_present && ...
    ~condition_overlap && ...
    ~run_overlap;

if report.valid
    report.summary = "Training fold integrity valid.";
else
    report.summary = compose( ...
        ["Training folds invalid: train_only=%d, " ...
         "valid_ids=%d, all_present=%d, " ...
         "condition_overlap=%d, run_overlap=%d."], ...
        train_only, ...
        valid_fold_ids, ...
        all_folds_present, ...
        condition_overlap, ...
        run_overlap);
end

end
