function summary = summarize_sws_by_run(predictions, options)
%SUMMARIZE_SWS_BY_RUN Compute one spatial SWS summary per campaign run.
%
% Each campaign_run_id represents one reconstructed local SWS map. Metrics
% are first computed across patches within each run so every map contributes
% one row independently of its number of patches.

arguments
    predictions table

    options.ModelId (1,1) string = "bagged_full"
    options.Partition (1,1) string = "test"
end

required = [
    "model_id"
    "partition"
    "campaign_run_id"
    "campaign_frequency_hz"
    "campaign_background_cs_m_s"
    "campaign_direction_count"
    "cs_true_m_s"
    "cs_pred_m_s"
    "cs_error_m_s"
    "cs_error_percent"
    "cs_absolute_error_percent"
    "sws_valid"
    ];

missing = setdiff( ...
    required, ...
    string(predictions.Properties.VariableNames));

if ~isempty(missing)
    error("reqml:MissingRunDiagnosticVariable", ...
        "Prediction table is missing variables: %s", ...
        strjoin(missing, ", "));
end

mask = ...
    string(predictions.model_id) == options.ModelId & ...
    string(predictions.partition) == options.Partition & ...
    logical(predictions.sws_valid);

data = predictions(mask, :);

if isempty(data)
    error("reqml:EmptyRunDiagnosticSelection", ...
        "No valid rows matched model '%s' and partition '%s'.", ...
        options.ModelId, ...
        options.Partition);
end

group_columns = [
    "campaign_run_id"
    "campaign_frequency_hz"
    "campaign_background_cs_m_s"
    "campaign_direction_count"
    ];

[group_id, group_values] = ...
    findgroups(data(:, group_columns));

patch_count = splitapply( ...
    @numel, ...
    data.cs_pred_m_s, ...
    group_id);

cs_true_mean_m_s = splitapply( ...
    @(x) mean(x, "omitnan"), ...
    data.cs_true_m_s, ...
    group_id);

cs_pred_mean_m_s = splitapply( ...
    @(x) mean(x, "omitnan"), ...
    data.cs_pred_m_s, ...
    group_id);

cs_pred_median_m_s = splitapply( ...
    @(x) median(x, "omitnan"), ...
    data.cs_pred_m_s, ...
    group_id);

cs_pred_std_m_s = splitapply( ...
    @(x) std(x, 0, "omitnan"), ...
    data.cs_pred_m_s, ...
    group_id);

cs_pred_min_m_s = splitapply( ...
    @min, ...
    data.cs_pred_m_s, ...
    group_id);

cs_pred_max_m_s = splitapply( ...
    @max, ...
    data.cs_pred_m_s, ...
    group_id);

sws_mae_m_s = splitapply( ...
    @(x) mean(abs(x), "omitnan"), ...
    data.cs_error_m_s, ...
    group_id);

sws_rmse_m_s = splitapply( ...
    @(x) sqrt(mean(x.^2, "omitnan")), ...
    data.cs_error_m_s, ...
    group_id);

sws_bias_m_s = splitapply( ...
    @(x) mean(x, "omitnan"), ...
    data.cs_error_m_s, ...
    group_id);

sws_median_ape = splitapply( ...
    @(x) median(x, "omitnan"), ...
    data.cs_absolute_error_percent, ...
    group_id);

sws_mape = splitapply( ...
    @(x) mean(x, "omitnan"), ...
    data.cs_absolute_error_percent, ...
    group_id);

sws_bias_percent = splitapply( ...
    @(x) mean(x, "omitnan"), ...
    data.cs_error_percent, ...
    group_id);

sws_p90_ape = splitapply( ...
    @(x) prctile(x, 90), ...
    data.cs_absolute_error_percent, ...
    group_id);

sws_p95_ape = splitapply( ...
    @(x) prctile(x, 95), ...
    data.cs_absolute_error_percent, ...
    group_id);

sws_max_ape = splitapply( ...
    @max, ...
    data.cs_absolute_error_percent, ...
    group_id);

summary = group_values;

summary.patch_count = patch_count;
summary.cs_true_mean_m_s = cs_true_mean_m_s;
summary.cs_pred_mean_m_s = cs_pred_mean_m_s;
summary.cs_pred_median_m_s = cs_pred_median_m_s;
summary.cs_pred_std_m_s = cs_pred_std_m_s;
summary.cs_pred_min_m_s = cs_pred_min_m_s;
summary.cs_pred_max_m_s = cs_pred_max_m_s;

summary.sws_mae_m_s = sws_mae_m_s;
summary.sws_rmse_m_s = sws_rmse_m_s;
summary.sws_bias_m_s = sws_bias_m_s;
summary.sws_median_ape = sws_median_ape;
summary.sws_mape = sws_mape;
summary.sws_bias_percent = sws_bias_percent;
summary.sws_p90_ape = sws_p90_ape;
summary.sws_p95_ape = sws_p95_ape;
summary.sws_max_ape = sws_max_ape;

summary = sortrows( ...
    summary, ...
    "sws_mape", ...
    "descend");

end
