function summary = summarize_sws_by_group( ...
    predictions, group_columns, options)
%SUMMARIZE_SWS_BY_GROUP Summarize SWS performance by experimental groups.

arguments
    predictions table
    group_columns (:,1) string

    options.Partition (1,1) string = "test"
    options.ModelId (1,1) string = ""
end

required = [
    "model_id"
    "partition"
    "cs_true_m_s"
    "cs_pred_m_s"
    "cs_error_m_s"
    "cs_error_percent"
    "cs_absolute_error_percent"
    "sws_valid"
    ];

missing = setdiff( ...
    [required; group_columns], ...
    string(predictions.Properties.VariableNames));

if ~isempty(missing)
    error("reqml:MissingDiagnosticVariable", ...
        "Prediction table is missing variables: %s", ...
        strjoin(missing, ", "));
end

mask = ...
    string(predictions.partition) == options.Partition & ...
    logical(predictions.sws_valid);

if strlength(options.ModelId) > 0
    mask = mask & ...
        string(predictions.model_id) == options.ModelId;
end

data = predictions(mask, :);

if isempty(data)
    error("reqml:EmptyDiagnosticSelection", ...
        "No valid rows matched model '%s' and partition '%s'.", ...
        options.ModelId, options.Partition);
end

[group_id, group_values] = findgroups(data(:, group_columns));

row_count = splitapply(@numel, data.cs_true_m_s, group_id);

sws_mae_m_s = splitapply( ...
    @(x) mean(abs(x), "omitnan"), ...
    data.cs_error_m_s, ...
    group_id);

sws_rmse_m_s = splitapply( ...
    @(x) sqrt(mean(x.^2, "omitnan")), ...
    data.cs_error_m_s, ...
    group_id);

sws_bias_m_s = splitapply( ...
    @(x) mean(x, "omitnan"), ...
    data.cs_error_m_s, ...
    group_id);

sws_median_ape = splitapply( ...
    @(x) median(x, "omitnan"), ...
    data.cs_absolute_error_percent, ...
    group_id);

sws_mape = splitapply( ...
    @(x) mean(x, "omitnan"), ...
    data.cs_absolute_error_percent, ...
    group_id);

sws_bias_percent = splitapply( ...
    @(x) mean(x, "omitnan"), ...
    data.cs_error_percent, ...
    group_id);

sws_p90_ape = splitapply( ...
    @(x) prctile(x, 90), ...
    data.cs_absolute_error_percent, ...
    group_id);

sws_p95_ape = splitapply( ...
    @(x) prctile(x, 95), ...
    data.cs_absolute_error_percent, ...
    group_id);

sws_max_ape = splitapply( ...
    @max, ...
    data.cs_absolute_error_percent, ...
    group_id);

summary = group_values;
summary.row_count = row_count;
summary.sws_mae_m_s = sws_mae_m_s;
summary.sws_rmse_m_s = sws_rmse_m_s;
summary.sws_bias_m_s = sws_bias_m_s;
summary.sws_median_ape = sws_median_ape;
summary.sws_mape = sws_mape;
summary.sws_bias_percent = sws_bias_percent;
summary.sws_p90_ape = sws_p90_ape;
summary.sws_p95_ape = sws_p95_ape;
summary.sws_max_ape = sws_max_ape;

summary = sortrows( ...
    summary, ...
    "sws_mape", ...
    "descend");

end
