function examples = attach_theory_baseline( ...
    examples, run, feat_cfg, mapping)
%ATTACH_THEORY_BASELINE Add run-level discrete-theory diagnostics.
%
% The theory values are computed from the effective REQ configuration and
% repeated across all patches belonging to the same campaign run.

arguments
    examples table
    run table
    feat_cfg (1,1) struct
    mapping (:,1) struct
end

if height(run) ~= 1
    error("reqml:InvalidTheoryCampaignRun", ...
        "Theory attachment requires exactly one campaign run.");
end

required_columns = [
    "GRID_dx_m"
    "GRID_dz_m"
    "REQ_cs_guess_m_s"
    "REQ_M"
    "REQ_Nbins_effective"
    ];

missing = setdiff( ...
    required_columns, ...
    string(examples.Properties.VariableNames));

if ~isempty(missing)
    error("reqml:MissingTheoryConfiguration", ...
        "Examples are missing theory inputs: %s", ...
        strjoin(missing, ", "));
end

field_class = ...
    reqml.theory.resolve_field_class( ...
        double(run.direction_count), ...
        mapping);

dx = require_constant_column(examples, "GRID_dx_m");
dz = require_constant_column(examples, "GRID_dz_m");
cs_guess = require_constant_column( ...
    examples, "REQ_cs_guess_m_s");
M = require_constant_column(examples, "REQ_M");
Nbins = require_constant_column( ...
    examples, "REQ_Nbins_effective");

frequency_hz = double(run.frequency_hz);

gamma = get_numeric_config_field( ...
    feat_cfg, "gamma_win", 1);

pad_factor = get_numeric_config_field( ...
    feat_cfg, "pad_factor", 1);

smooth_sigma = get_numeric_config_field( ...
    feat_cfg, "smooth_sigma_2d", 1);

single_wave = ...
    reqml.theory.q_theory_REQ_discrete_shearUZ( ...
        dx, ...
        dz, ...
        frequency_hz, ...
        cs_guess, ...
        M=M, ...
        Gamma=gamma, ...
        PadFactor=pad_factor, ...
        Nbins=Nbins, ...
        SmoothSigma=smooth_sigma, ...
        FieldType="SingleWave", ...
        TheoryMode="S2D", ...
        Plot=false);

diffuse_3d = ...
    reqml.theory.q_theory_REQ_discrete_shearUZ( ...
        dx, ...
        dz, ...
        frequency_hz, ...
        cs_guess, ...
        M=M, ...
        Gamma=gamma, ...
        PadFactor=pad_factor, ...
        Nbins=Nbins, ...
        SmoothSigma=smooth_sigma, ...
        FieldType="Diffuse3D", ...
        TheoryMode="S2D", ...
        Plot=false);

switch field_class
    case "SingleWave"
        selected_q = ...
            single_wave.q_theory_discrete;

    case "PartialDiffuse3D"
        selected_q = 0.5 * ( ...
            single_wave.q_theory_discrete + ...
            diffuse_3d.q_theory_discrete);

    case "Diffuse3D"
        selected_q = ...
            diffuse_3d.q_theory_discrete;

    otherwise
        error("reqml:InvalidTheoryFieldClass", ...
            "Unsupported theory class '%s'.", ...
            field_class);
end

theory_valid = ...
    single_wave.valid && ...
    diffuse_3d.valid && ...
    isfinite(selected_q) && ...
    selected_q >= 0 && ...
    selected_q <= 1;

n = height(examples);

examples.theory_field_class = ...
    repmat(field_class, n, 1);

examples.q_theory_single_wave_discrete = ...
    repmat(single_wave.q_theory_discrete, n, 1);

examples.q_theory_diffuse3d_discrete = ...
    repmat(diffuse_3d.q_theory_discrete, n, 1);

examples.q_theory_discrete = ...
    repmat(selected_q, n, 1);

examples.q_theory_valid = ...
    repmat(theory_valid, n, 1);

end

function value = require_constant_column(examples, name)

values = double(examples.(name));
values = unique(values(isfinite(values)));

if numel(values) ~= 1
    error("reqml:NonconstantRunTheoryConfiguration", ...
        "Theory input '%s' must have one finite value per run.", ...
        name);
end

value = values(1);

end

function value = get_numeric_config_field( ...
    config, name, default_value)

if isfield(config, name)
    value = double(config.(name));
else
    value = default_value;
end

if ~isscalar(value) || ~isfinite(value)
    error("reqml:InvalidTheoryConfiguration", ...
        "Theory configuration '%s' must be a finite scalar.", ...
        name);
end

end
