function result = makeBalancedTrainingSelection( ...
    examples, options)
%MAKEBALANCEDTRAININGSELECTION Hierarchical training-data balance.
%
% Hierarchy:
%
%   coverage cell
%       -> physical condition
%           -> simulation run
%               -> patch
%
% All rows are retained. The function appends:
%
%   selected_for_training
%   training_weight
%
% Selected examples receive weights such that:
%
%   equal total weight per selected coverage cell
%   equal total weight per condition within a cell
%   equal total weight per run within a condition
%   equal weight per selected patch within a run

arguments
    examples table

    options.PurityEdges (1,:) double
    options.NominalAngularCoverageEdges (1,:) double
    options.SwsEdges (1,:) double
    options.FrequencyEdges (1,:) double

    options.DiscretizationPairsM (:,2) double = ...
        [0.0005 0.0005]

    options.MaximumConditionsPerCell (1,1) double = Inf

    options.MaximumRunsPerConditionPerCell ...
        (1,1) double = Inf

    options.MaximumPatchesPerRunPerCell ...
        (1,1) double = Inf

    options.RandomSeed (1,1) double = 1

    options.OutputDirectory {mustBeTextScalar} = ""
    options.SaveOutputs (1,1) logical = false
end

validate_options(options);

assigned = reqml.coverage.assignCoverageBins( ...
    examples, ...
    FieldCoverageMode="nominal", ...
    PurityEdges=options.PurityEdges, ...
    DiffusivityEdges= ...
        options.NominalAngularCoverageEdges, ...
    SwsEdges=options.SwsEdges, ...
    FrequencyEdges=options.FrequencyEdges, ...
    DiscretizationPairsM= ...
        options.DiscretizationPairsM);

validate_required_variables(assigned);

row_count = height(assigned);

selected = false(row_count, 1);
training_weight = zeros(row_count, 1);

valid = logical(assigned.coverage_valid);

cell_keys = make_cell_keys(assigned);

condition_ids = string( ...
    assigned.campaign_condition_id);

run_ids = string( ...
    assigned.campaign_run_id);

stream = RandStream( ...
    "Threefry", ...
    Seed=options.RandomSeed);

valid_cells = unique( ...
    cell_keys(valid), ...
    "stable");

valid_cells(valid_cells == "") = [];

for cell_index = 1:numel(valid_cells)
    cell_key = valid_cells(cell_index);

    cell_rows = find( ...
        valid & cell_keys == cell_key);

    cell_conditions = unique( ...
        condition_ids(cell_rows), ...
        "stable");

    cell_conditions = sample_values( ...
        cell_conditions, ...
        options.MaximumConditionsPerCell, ...
        stream);

    for condition_index = 1:numel(cell_conditions)
        condition_id = ...
            cell_conditions(condition_index);

        condition_rows = cell_rows( ...
            condition_ids(cell_rows) == condition_id);

        condition_runs = unique( ...
            run_ids(condition_rows), ...
            "stable");

        condition_runs = sample_values( ...
            condition_runs, ...
            options.MaximumRunsPerConditionPerCell, ...
            stream);

        for run_index = 1:numel(condition_runs)
            run_id = condition_runs(run_index);

            run_rows = condition_rows( ...
                run_ids(condition_rows) == run_id);

            run_rows = sample_indices( ...
                run_rows, ...
                options.MaximumPatchesPerRunPerCell, ...
                stream);

            selected(run_rows) = true;
        end
    end
end

training_weight = assign_hierarchical_weights( ...
    assigned, ...
    selected, ...
    cell_keys, ...
    condition_ids, ...
    run_ids);

assigned.selected_for_training = selected;
assigned.training_weight = training_weight;

cell_summary = summarize_cells( ...
    assigned, ...
    cell_keys);

frequency_summary = summarize_numeric_bins( ...
    assigned, ...
    options.FrequencyEdges, ...
    "campaign_frequency_hz", ...
    "frequency");

sws_summary = summarize_numeric_bins( ...
    assigned, ...
    options.SwsEdges, ...
    "truth_cs_center_m_s", ...
    "sws");

condition_summary = summarize_conditions(assigned);

result = struct();

result.schema_name = ...
    "reqml_hierarchical_training_balance";

result.schema_version = "1.0";

result.random_seed = options.RandomSeed;

result.example_count = row_count;
result.valid_example_count = nnz(valid);
result.selected_example_count = nnz(selected);

result.selected_condition_count = ...
    numel(unique(condition_ids(selected)));

result.selected_run_count = ...
    numel(unique(run_ids(selected)));

result.coverage_cell_count = ...
    height(cell_summary);

result.examples = assigned;

result.cell_summary = cell_summary;
result.frequency_summary = frequency_summary;
result.sws_summary = sws_summary;
result.condition_summary = condition_summary;

% Backward-compatible alias.
result.summary = cell_summary;

result.paths = empty_paths();

if options.SaveOutputs
    result.paths = save_outputs( ...
        result, ...
        options.OutputDirectory);
end

end


function selected_values = sample_values( ...
        values, maximum_count, stream)

values = values(:);

if isempty(values) || ...
        isinf(maximum_count) || ...
        numel(values) <= maximum_count

    selected_values = values;
    return
end

order = randperm(stream, numel(values));

selected_values = ...
    values(order(1:maximum_count));

end


function selected_rows = sample_indices( ...
        rows, maximum_count, stream)

rows = rows(:);

if isempty(rows) || ...
        isinf(maximum_count) || ...
        numel(rows) <= maximum_count

    selected_rows = rows;
    return
end

order = randperm(stream, numel(rows));

selected_rows = ...
    rows(order(1:maximum_count));

end


function weights = assign_hierarchical_weights( ...
        assigned, selected, ...
        cell_keys, condition_ids, run_ids)

weights = zeros(height(assigned), 1);

selected_cells = unique( ...
    cell_keys(selected), ...
    "stable");

selected_cells(selected_cells == "") = [];

cell_count = numel(selected_cells);

if cell_count == 0
    return
end

for cell_index = 1:cell_count
    cell_key = selected_cells(cell_index);

    cell_rows = find( ...
        selected & cell_keys == cell_key);

    cell_conditions = unique( ...
        condition_ids(cell_rows), ...
        "stable");

    condition_count = numel(cell_conditions);

    for condition_index = 1:condition_count
        condition_id = ...
            cell_conditions(condition_index);

        condition_rows = cell_rows( ...
            condition_ids(cell_rows) == condition_id);

        condition_runs = unique( ...
            run_ids(condition_rows), ...
            "stable");

        run_count = numel(condition_runs);

        for run_index = 1:run_count
            run_id = condition_runs(run_index);

            run_rows = condition_rows( ...
                run_ids(condition_rows) == run_id);

            patch_count = numel(run_rows);

            row_weight = ...
                1 / ...
                (cell_count * ...
                 condition_count * ...
                 run_count * ...
                 patch_count);

            weights(run_rows) = row_weight;
        end
    end
end

positive = weights > 0;

if any(positive)
    weights(positive) = ...
        weights(positive) / ...
        mean(weights(positive));
end

end


function summary = summarize_cells( ...
        assigned, cell_keys)

valid = logical(assigned.coverage_valid);

keys = unique( ...
    cell_keys(valid), ...
    "stable");

keys(keys == "") = [];

summary = table();

for index = 1:numel(keys)
    key = keys(index);

    rows = find( ...
        valid & cell_keys == key);

    selected_rows = rows( ...
        assigned.selected_for_training(rows));

    first = rows(1);

    new_row = table( ...
        assigned.coverage_sws_bin(first), ...
        assigned.coverage_frequency_bin(first), ...
        assigned.coverage_purity_bin(first), ...
        assigned.coverage_diffusivity_bin(first), ...
        string(assigned.coverage_sws_label(first)), ...
        string(assigned.coverage_frequency_label(first)), ...
        string(assigned.coverage_purity_label(first)), ...
        string(assigned.coverage_diffusivity_label(first)), ...
        numel(rows), ...
        nnz(assigned.selected_for_training(rows)), ...
        count_unique(assigned, rows, ...
            "campaign_condition_id"), ...
        count_unique(assigned, selected_rows, ...
            "campaign_condition_id"), ...
        count_unique(assigned, rows, ...
            "campaign_run_id"), ...
        count_unique(assigned, selected_rows, ...
            "campaign_run_id"), ...
        sum(assigned.training_weight(rows)), ...
        VariableNames={ ...
            'sws_bin', ...
            'frequency_bin', ...
            'purity_bin', ...
            'dnom_bin', ...
            'sws_label', ...
            'frequency_label', ...
            'purity_label', ...
            'dnom_label', ...
            'available_example_count', ...
            'selected_example_count', ...
            'available_condition_count', ...
            'selected_condition_count', ...
            'available_run_count', ...
            'selected_run_count', ...
            'training_weight_sum' ...
            });

    summary = [summary; new_row]; %#ok<AGROW>
end

summary = sortrows( ...
    summary, ...
    [ ...
        "sws_bin"
        "frequency_bin"
        "purity_bin"
        "dnom_bin"
    ]);

end


function summary = summarize_numeric_bins( ...
        assigned, edges, variable_name, prefix)

values = double(assigned.(variable_name));

bin_index = discretize(values, edges);

condition_ids = string( ...
    assigned.campaign_condition_id);

run_ids = string( ...
    assigned.campaign_run_id);

selected = logical( ...
    assigned.selected_for_training);

bin_count = numel(edges) - 1;

summary = table();

for index = 1:bin_count
    available_mask = ...
        bin_index == index;

    selected_mask = ...
        available_mask & selected;

    if index < bin_count
        label = sprintf( ...
            "[%g,%g)", ...
            edges(index), ...
            edges(index+1));
    else
        label = sprintf( ...
            "[%g,%g]", ...
            edges(index), ...
            edges(index+1));
    end

    variable_names = [ ...
        string(prefix) + "_bin"
        string(prefix) + "_label"
        string(prefix) + "_lower"
        string(prefix) + "_upper"
        "available_example_count"
        "selected_example_count"
        "available_condition_count"
        "selected_condition_count"
        "available_run_count"
        "selected_run_count"
        "training_weight_sum"
        ]';

    new_row = table( ...
        index, ...
        string(label), ...
        edges(index), ...
        edges(index+1), ...
        nnz(available_mask), ...
        nnz(selected_mask), ...
        numel(unique(condition_ids(available_mask))), ...
        numel(unique(condition_ids(selected_mask))), ...
        numel(unique(run_ids(available_mask))), ...
        numel(unique(run_ids(selected_mask))), ...
        sum(assigned.training_weight(selected_mask)), ...
        VariableNames=variable_names);

    summary = [summary; new_row]; %#ok<AGROW>
end

end


function summary = summarize_conditions(assigned)

condition_ids = string( ...
    assigned.campaign_condition_id);

run_ids = string( ...
    assigned.campaign_run_id);

selected = logical( ...
    assigned.selected_for_training);

conditions = unique( ...
    condition_ids, ...
    "stable");

summary = table();

for index = 1:numel(conditions)
    condition_id = conditions(index);

    rows = condition_ids == condition_id;

    selected_rows = rows & selected;

    new_row = table( ...
        condition_id, ...
        string(assigned. ...
            campaign_geometry_family(find(rows,1))), ...
        nnz(rows), ...
        nnz(selected_rows), ...
        numel(unique(run_ids(rows))), ...
        numel(unique(run_ids(selected_rows))), ...
        sum(assigned.training_weight(selected_rows)), ...
        VariableNames={ ...
            'condition_id', ...
            'geometry_family', ...
            'available_example_count', ...
            'selected_example_count', ...
            'available_run_count', ...
            'selected_run_count', ...
            'training_weight_sum' ...
            });

    summary = [summary; new_row]; %#ok<AGROW>
end

end


function count = count_unique( ...
        assigned, rows, variable_name)

if isempty(rows)
    count = 0;
    return
end

count = numel(unique( ...
    string(assigned.(variable_name)(rows))));

end


function keys = make_cell_keys(assigned)

keys = strings(height(assigned), 1);

valid = logical(assigned.coverage_valid);

keys(valid) = compose( ...
    "s%02d_f%02d_p%02d_d%02d", ...
    assigned.coverage_sws_bin(valid), ...
    assigned.coverage_frequency_bin(valid), ...
    assigned.coverage_purity_bin(valid), ...
    assigned.coverage_diffusivity_bin(valid));

end


function validate_required_variables(examples)

required = [
    "coverage_valid"
    "coverage_purity_bin"
    "coverage_diffusivity_bin"
    "coverage_purity_label"
    "coverage_diffusivity_label"
    "campaign_condition_id"
    "campaign_run_id"
    "campaign_geometry_family"
    "campaign_frequency_hz"
    "truth_cs_center_m_s"
    ];

missing = setdiff( ...
    required, ...
    string(examples.Properties.VariableNames));

if ~isempty(missing)
    error("reqml:MissingBalancedTrainingVariable", ...
        "Balanced training requires variable '%s'.", ...
        missing(1));
end

end


function validate_options(options)

validate_limit( ...
    options.MaximumConditionsPerCell, ...
    "MaximumConditionsPerCell");

validate_limit( ...
    options.MaximumRunsPerConditionPerCell, ...
    "MaximumRunsPerConditionPerCell");

validate_limit( ...
    options.MaximumPatchesPerRunPerCell, ...
    "MaximumPatchesPerRunPerCell");

if ~isfinite(options.RandomSeed) || ...
        options.RandomSeed < 0 || ...
        options.RandomSeed ~= fix(options.RandomSeed)

    error("reqml:InvalidBalancedTrainingOption", ...
        "RandomSeed must be a nonnegative integer.");
end

end


function validate_limit(value, name)

if ~(isinf(value) || ...
        (isfinite(value) && ...
         value >= 1 && ...
         value == fix(value)))

    error("reqml:InvalidBalancedTrainingOption", ...
        "%s must be a positive integer or Inf.", ...
        name);
end

end


function paths = save_outputs( ...
        result, output_directory)

output_directory = string(output_directory);

if strlength(output_directory) == 0
    error("reqml:MissingBalancedTrainingOutputDirectory", ...
        ["OutputDirectory is required when " ...
         "SaveOutputs=true."]);
end

if isfolder(output_directory)
    error("reqml:BalancedTrainingOutputExists", ...
        "Output directory already exists: %s", ...
        output_directory);
end

[created, message] = mkdir(output_directory);

if ~created
    error("reqml:BalancedTrainingOutputCreateFailed", ...
        "Could not create output directory '%s': %s", ...
        output_directory, ...
        message);
end

examples = result.examples; %#ok<NASGU>

examples_path = fullfile( ...
    output_directory, ...
    "examples_with_training_selection.mat");

cell_summary_path = fullfile( ...
    output_directory, ...
    "training_balance_by_cell.csv");

frequency_summary_path = fullfile( ...
    output_directory, ...
    "training_balance_by_frequency.csv");

sws_summary_path = fullfile( ...
    output_directory, ...
    "training_balance_by_sws.csv");

condition_summary_path = fullfile( ...
    output_directory, ...
    "training_balance_by_condition.csv");

report_path = fullfile( ...
    output_directory, ...
    "training_balance_report.json");

frequency_plot_path = fullfile( ...
    output_directory, ...
    "training_balance_frequency.png");

sws_plot_path = fullfile( ...
    output_directory, ...
    "training_balance_sws.png");

cell_plot_path = fullfile( ...
    output_directory, ...
    "training_balance_cells.png");

save(examples_path, "examples", "-v7.3");

writetable( ...
    result.cell_summary, ...
    cell_summary_path);

writetable( ...
    result.frequency_summary, ...
    frequency_summary_path);

writetable( ...
    result.sws_summary, ...
    sws_summary_path);

writetable( ...
    result.condition_summary, ...
    condition_summary_path);

make_before_after_plot( ...
    result.frequency_summary, ...
    "frequency_label", ...
    "Frequency bin", ...
    "Training balance by frequency", ...
    frequency_plot_path);

make_before_after_plot( ...
    result.sws_summary, ...
    "sws_label", ...
    "SWS bin [m/s]", ...
    "Training balance by SWS", ...
    sws_plot_path);

make_cell_plot( ...
    result.cell_summary, ...
    cell_plot_path);

report = struct();

report.schema_name = ...
    result.schema_name;

report.schema_version = ...
    result.schema_version;

report.random_seed = ...
    result.random_seed;

report.example_count = ...
    result.example_count;

report.selected_example_count = ...
    result.selected_example_count;

report.selected_condition_count = ...
    result.selected_condition_count;

report.selected_run_count = ...
    result.selected_run_count;

report.coverage_cell_count = ...
    result.coverage_cell_count;

write_json(report_path, report);

paths = struct();

paths.examples_mat = string(examples_path);

% Backward-compatible alias.
paths.summary_csv = string(cell_summary_path);

paths.cell_summary_csv = ...
    string(cell_summary_path);

paths.frequency_summary_csv = ...
    string(frequency_summary_path);

paths.sws_summary_csv = ...
    string(sws_summary_path);

paths.condition_summary_csv = ...
    string(condition_summary_path);

paths.report_json = ...
    string(report_path);

paths.frequency_plot = ...
    string(frequency_plot_path);

paths.sws_plot = ...
    string(sws_plot_path);

paths.cell_plot = ...
    string(cell_plot_path);

end


function make_before_after_plot( ...
        summary, label_variable, ...
        x_label, title_text, output_path)

figure_handle = figure(Visible="off");

values = [
    summary.available_example_count, ...
    summary.selected_example_count
    ];

bar(categorical(summary.(label_variable)), values);

xlabel(x_label);
ylabel("Example count");
title(title_text);

legend( ...
    ["Available", "Selected"], ...
    Location="best");

grid on;

exportgraphics( ...
    figure_handle, ...
    output_path, ...
    Resolution=180);

close(figure_handle);

end


function make_cell_plot(summary, output_path)

labels = compose( ...
    "S%d-F%d-P%d-D%d", ...
    summary.sws_bin, ...
    summary.frequency_bin, ...
    summary.purity_bin, ...
    summary.dnom_bin);

figure_handle = figure(Visible="off");

values = [
    summary.available_example_count, ...
    summary.selected_example_count
    ];

bar(categorical(labels), values);

xlabel("Coverage cell");
ylabel("Example count");
title("Training balance by coverage cell");

legend( ...
    ["Available", "Selected"], ...
    Location="best");

grid on;

exportgraphics( ...
    figure_handle, ...
    output_path, ...
    Resolution=180);

close(figure_handle);

end


function write_json(path_value, value)

file_id = fopen(path_value, "w");

if file_id < 0
    error("reqml:BalancedTrainingReportWriteFailed", ...
        "Could not create report file: %s", ...
        path_value);
end

cleanup = onCleanup(@() fclose(file_id));

fprintf(file_id, "%s", ...
    jsonencode(value, PrettyPrint=true));

clear cleanup

end


function paths = empty_paths()

paths = struct();

paths.examples_mat = "";
paths.summary_csv = "";
paths.cell_summary_csv = "";
paths.frequency_summary_csv = "";
paths.sws_summary_csv = "";
paths.condition_summary_csv = "";
paths.report_json = "";
paths.frequency_plot = "";
paths.sws_plot = "";
paths.cell_plot = "";

end
