function [summary,radial_curve,angular_curve] = analyzeQ0RegionSpectrum(data,ux_data,q0,region,options)
%ANALYZEQ0REGIONSPECTRUM Reuse the Q0/REQ spectrum at a truth-fixed region.

arguments
    data (1,1) struct
    ux_data (1,1) struct
    q0 (1,1) struct
    region (1,1) struct
    options.SourcePosition {mustBeTextScalar}
    options.InterfaceZM (1,1) double = 0.019
    options.M (1,1) double = 2
    options.CsGuess (1,1) double = 3
end
[~,ix]=min(abs(q0.x_mm-1e3*region.x_m));
[~,iz]=min(abs(q0.z_mm-1e3*region.z_m));
cx=q0.x_idx(ix); cz=q0.z_idx(iz); qpred=q0.q_map(iz,ix);
physical=struct('dx',data.dx_m,'dz',data.dz_m,'f0',data.frequency_hz, ...
    'cs_bg',options.CsGuess);
fc=reqml.config.default_feature_config(M=options.M,cs_guess=options.CsGuess);
d=reqml.estimators.req_estimator_map(data.wavefield_zx,physical,fc, ...
    CenterIndices=[cx cz],QuantileMode='fixed',FixedQuantile=qpred, ...
    ReturnFeatures=true,ReturnFeatureTable=true,StoreReqCurves=true);
curve=d.req_curves{1}; feat=d.features{1};
spectrum=max(curve.Ssm,0); spectrum=spectrum./(sum(spectrum,'all')+eps);
rad=reqml.features.extract_radial_features(spectrum,curve.KR,fc);
ang=reqml.features.extract_angular_features(spectrum,curve.TH,curve.KR,rad,fc);
material=data.truth.material_id_zx(cz,cx); truth=data.truth.cs_m_s_zx(cz,cx);
h=floor(d.win_size/2); zidx=cz-h:cz+h; xidx=cx-h:cx+h;
mask=data.truth.material_id_zx(zidx,xidx); purity=mean(mask(:)==material);
local_uz=data.wavefield_zx(zidx,xidx); local_ux=ux_data.wavefield_zx(zidx,xidx);
ratio=rms(abs(local_ux),'all')/max(rms(abs(local_uz),'all'),eps);
centroid=sum(rad.k_cent_plot.*rad.Prad_plot)/(sum(rad.Prad_plot)+eps);
bandwidth=sqrt(sum(rad.Prad_plot.*(rad.k_cent_plot-centroid).^2)/ ...
    (sum(rad.Prad_plot)+eps));
[~,peak_index]=max(rad.Prad_plot); peak_k=rad.k_cent_plot(peak_index);
peak_count=count_peaks(rad.Prad_plot);
distance_mm=1e3*(data.axes.z_m(cz)-options.InterfaceZM);
effective_bins=exp(feat.ang_entropy*log(numel(ang.Pang)));
summary=table(string(options.SourcePosition),string(region.name),cx,cz, ...
    data.axes.x_m(cx),data.axes.z_m(cz),qpred,d.k_map(1),d.cs_map(1), ...
    truth,d.cs_map(1)-truth,100*(d.cs_map(1)-truth)/truth,material, ...
    purity,distance_mm,ratio,peak_k,centroid,bandwidth,peak_count, ...
    feat.radial_entropy,feat.width_75_25_rel,feat.width_90_10_rel, ...
    feat.ang_entropy,feat.circ_var,feat.dom_dir_frac, ...
    feat.window_max_frac,effective_bins, ...
    'VariableNames',{'source_position','region','cx','cz','x_m','z_m', ...
    'q_pred','k_q','estimate_m_s','truth_m_s','signed_error_m_s', ...
    'relative_error_percent','material_id','window_purity', ...
    'signed_distance_to_interface_mm','local_Ux_Uz_rms_ratio', ...
    'dominant_peak_k_rad_m','spectral_centroid_k_rad_m', ...
    'spectral_bandwidth_k_rad_m','prominent_peak_count', ...
    'radial_entropy','width_75_25_rel','width_90_10_rel','ang_entropy', ...
    'circ_var','dom_dir_frac','window_max_frac','effective_angular_bins'});
n=numel(rad.k_cent_plot);
radial_curve=table(repmat(string(options.SourcePosition),n,1), ...
    repmat(string(region.name),n,1),rad.k_cent_plot(:),rad.Prad_plot(:), ...
    rad.Frad_plot(:),repmat(qpred,n,1),repmat(d.k_map(1),n,1), ...
    'VariableNames',{'source_position','region','k_rad_m', ...
    'normalized_energy','cumulative_energy','q_pred','k_q'});
n=numel(ang.th_deg);
angular_curve=table(repmat(string(options.SourcePosition),n,1), ...
    repmat(string(region.name),n,1),ang.th_deg(:),ang.Pang(:), ...
    'VariableNames',{'source_position','region','theta_deg','normalized_energy'});
end

function n=count_peaks(y)
y=movmean(double(y(:)),3); threshold=.2*max(y); n=0;
for i=2:numel(y)-1
    if y(i)>y(i-1) && y(i)>=y(i+1) && y(i)>=threshold, n=n+1; end
end
end
