function comparison = compareSourceSummaries(summary)
%COMPARESOURCESUMMARIES Pair SOURCE-Z and SOURCE-X metrics at equal support.
arguments
    summary table
end
keys=unique(summary(:,{'condition','estimator','M','center_material_id'}), ...
    'rows','stable');
rows=cell(height(keys),1); keep=false(height(keys),1);
for i=1:height(keys)
    match=summary.condition==keys.condition(i) & ...
        summary.estimator==keys.estimator(i) & summary.M==keys.M(i) & ...
        summary.center_material_id==keys.center_material_id(i);
    z=summary(match&summary.source_polarization=="Z",:);
    x=summary(match&summary.source_polarization=="X",:);
    if isempty(z) || isempty(x), continue; end
    keep(i)=true;
    rows{i}=table(keys.condition(i),keys.estimator(i),keys.M(i), ...
        keys.center_material_id(i),z.N(1),x.N(1), ...
        z.median_estimate_m_s(1),x.median_estimate_m_s(1), ...
        z.std_estimate_m_s(1),x.std_estimate_m_s(1), ...
        z.MAPE_percent(1),x.MAPE_percent(1), ...
        x.MAPE_percent(1)-z.MAPE_percent(1), ...
        z.bias_m_s(1),x.bias_m_s(1),x.bias_m_s(1)-z.bias_m_s(1), ...
        'VariableNames',{'condition','estimator','M','center_material_id', ...
        'N_source_z','N_source_x','median_source_z_m_s','median_source_x_m_s', ...
        'std_source_z_m_s','std_source_x_m_s','MAPE_source_z_percent', ...
        'MAPE_source_x_percent','delta_MAPE_x_minus_z_percent_points', ...
        'bias_source_z_m_s','bias_source_x_m_s','delta_bias_x_minus_z_m_s'});
end
if ~any(keep), comparison=table(); else, comparison=vertcat(rows{keep}); end
end
