function result = freeze_scientific_5d_training_split()
%FREEZE_SCIENTIFIC_5D_TRAINING_SPLIT Freeze the final scientific split.

repo_root = fileparts(fileparts(mfilename("fullpath")));

dataset_path = fullfile( ...
    repo_root, ...
    "outputs", ...
    "adaptive_scientific_5d", ...
    "reqml_adaptive_scientific_5d_final", ...
    "reqml_adaptive_scientific_5d_final_iteration_050", ...
    "dataset", ...
    "examples.mat");

output_directory = fullfile( ...
    repo_root, ...
    "outputs", ...
    "scientific_5d_training", ...
    "split_v1");

if ~isfile(dataset_path)
    error("reqml:Scientific5DDatasetNotFound", ...
        "Scientific dataset was not found: %s", ...
        dataset_path);
end

if isfolder(output_directory)
    existing = dir(fullfile(output_directory, "*"));

    existing = existing(~ismember( ...
        string({existing.name}), ...
        [".", ".."]));

    if ~isempty(existing)
        error("reqml:FrozenSplitAlreadyExists", ...
            ["Frozen split output already exists. Delete it only " ...
             "if intentionally creating a new split version: %s"], ...
            output_directory);
    end
end

loaded = load(dataset_path, "examples");
examples = loaded.examples;

result = reqml.splits.freeze_grouped_training_split( ...
    examples, ...
    output_directory, ...
    DatasetPath=dataset_path, ...
    ConditionColumn="campaign_condition_id", ...
    RunColumn="campaign_run_id", ...
    SplitSeed=4101, ...
    FoldSeed=5101, ...
    TrainFraction=0.70, ...
    ValidationFraction=0.15, ...
    TestFraction=0.15, ...
    FoldCount=5);

disp("===== PARTITION SUMMARY =====");
disp(result.split.summary);

disp("===== TRAINING FOLD SUMMARY =====");
disp(result.folds.summary);

fprintf("Frozen split: %s\n", output_directory);

end
