function result = train_scientific_5d_purity_model()
%TRAIN_SCIENTIFIC_5D_PURITY_MODEL Train the scientific purity regressor.
%
% Training examples receive grouped out-of-fold predictions.
% Validation and test examples receive predictions from the final model
% trained using the complete training partition.

repo_root = fileparts(fileparts(mfilename("fullpath")));

dataset_path = fullfile( ...
    repo_root, ...
    "outputs", ...
    "adaptive_scientific_5d", ...
    "reqml_adaptive_scientific_5d_final", ...
    "reqml_adaptive_scientific_5d_final_iteration_050", ...
    "dataset", ...
    "examples.mat");

split_path = fullfile( ...
    repo_root, ...
    "outputs", ...
    "scientific_5d_training", ...
    "split_v1", ...
    "training_split_assignments.mat");

output_directory = fullfile( ...
    repo_root, ...
    "outputs", ...
    "scientific_5d_training", ...
    "purity_model_v1");

validate_input_paths(dataset_path, split_path);
prepare_output_directory(output_directory);

loaded = load(dataset_path, "examples");
examples = loaded.examples;

frozen = reqml.splits.load_frozen_training_split( ...
    examples, ...
    split_path);

split = frozen.split;
folds = frozen.folds;

registry = ...
    reqml.training.scientific_5d_predictor_registry();

contract_report = ...
    reqml.training.validate_predictor_contract( ...
        examples, ...
        registry.purity_predictors, ...
        registry);

if ~contract_report.valid
    error("reqml:InvalidPurityPredictorContract", ...
        "%s", contract_report.summary);
end

[X, predictor_metadata] = ...
    reqml.training.build_numeric_predictor_matrix( ...
        examples, ...
        registry.purity_predictors);

target_name = registry.targets.purity;
purity_true = double(examples.(char(target_name)));

if any(~isfinite(purity_true))
    error("reqml:NonFinitePurityTarget", ...
        "Purity target contains %d non-finite rows.", ...
        nnz(~isfinite(purity_true)));
end

if any(purity_true < 0 | purity_true > 1)
    error("reqml:PurityTargetOutsideUnitInterval", ...
        "Purity target contains values outside [0,1].");
end

model_spec = struct( ...
    "id", "purity_bagged_v1", ...
    "type", "bagged_trees", ...
    "num_learning_cycles", 160, ...
    "min_leaf_size", 8, ...
    "use_parallel", false, ...
    "random_seed", 6101);

fprintf("\n===== SCIENTIFIC PURITY TRAINING =====\n");
fprintf("Examples: %d\n", height(examples));
fprintf("Predictors: %d\n", predictor_metadata.predictor_count);
fprintf("Train examples: %d\n", nnz(split.train_mask));
fprintf("Validation examples: %d\n", nnz(split.validation_mask));
fprintf("Test examples: %d\n", nnz(split.test_mask));
fprintf("Trees: %d | MinLeafSize: %d\n", ...
    model_spec.num_learning_cycles, ...
    model_spec.min_leaf_size);

oof_result = reqml.training.fit_oof_regression_model( ...
    X, ...
    purity_true, ...
    split, ...
    folds, ...
    model_spec, ...
    ClipRange=[0, 1]);

predicted_patch_purity = ...
    oof_result.combined_prediction;

metrics = ...
    reqml.evaluation.evaluate_purity_predictions( ...
        purity_true, ...
        predicted_patch_purity, ...
        split.partition, ...
        string(model_spec.id));

predictions = build_prediction_table( ...
    examples, ...
    frozen.assignment, ...
    purity_true, ...
    predicted_patch_purity, ...
    oof_result.prediction_source);

paths = save_outputs( ...
    output_directory, ...
    predictions, ...
    metrics, ...
    oof_result, ...
    registry, ...
    predictor_metadata, ...
    model_spec, ...
    dataset_path, ...
    split_path);

fprintf("\n===== PURITY METRICS =====\n");
disp(metrics);

fprintf("\n===== OOF FOLD SUMMARY =====\n");
disp(oof_result.fold_summary);

fprintf("Saved purity model outputs: %s\n", output_directory);

result = struct();
result.schema_name = ...
    "reqml_scientific_5d_purity_training";
result.schema_version = "1.0";

result.metrics = metrics;
result.fold_summary = oof_result.fold_summary;
result.predictions = predictions;
result.model = oof_result.final_model;
result.paths = paths;

end

function predictions = build_prediction_table( ...
    examples, ...
    assignment, ...
    purity_true, ...
    purity_pred, ...
    prediction_source)

predictions = table();

predictions.example_id = string(examples.example_id);
predictions.campaign_condition_id = ...
    string(examples.campaign_condition_id);
predictions.campaign_run_id = ...
    string(examples.campaign_run_id);

predictions.partition = string(assignment.partition);
predictions.cv_fold = double(assignment.cv_fold);

predictions.campaign_frequency_hz = ...
    double(examples.campaign_frequency_hz);

predictions.truth_cs_center_m_s = ...
    double(examples.truth_cs_center_m_s);

predictions.truth_material_purity = ...
    double(purity_true);

predictions.predicted_patch_purity = ...
    double(purity_pred);

predictions.purity_error = ...
    predictions.predicted_patch_purity - ...
    predictions.truth_material_purity;

predictions.purity_absolute_error = ...
    abs(predictions.purity_error);

predictions.prediction_source = ...
    string(prediction_source);

optional_names = [
    "achieved_purity_bin"
    "achieved_sws_bin"
    "achieved_frequency_bin"
    "achieved_dnom_bin"
    "achieved_discretization_bin"
    "center_selection_role"
    ];

available = string(examples.Properties.VariableNames);

for index = 1:numel(optional_names)
    name = optional_names(index);

    if ismember(name, available)
        predictions.(char(name)) = ...
            examples.(char(name));
    end
end

end

function paths = save_outputs( ...
    output_directory, ...
    predictions, ...
    metrics, ...
    oof_result, ...
    registry, ...
    predictor_metadata, ...
    model_spec, ...
    dataset_path, ...
    split_path)

table_directory = fullfile(output_directory, "tables");
model_directory = fullfile(output_directory, "models");

mkdir(table_directory);
mkdir(model_directory);

paths = struct();

paths.predictions_csv = fullfile( ...
    table_directory, ...
    "purity_predictions.csv");

paths.metrics_csv = fullfile( ...
    table_directory, ...
    "purity_metrics.csv");

paths.fold_summary_csv = fullfile( ...
    table_directory, ...
    "purity_oof_fold_summary.csv");

paths.model_mat = fullfile( ...
    model_directory, ...
    "purity_model_bundle.mat");

paths.manifest_json = fullfile( ...
    output_directory, ...
    "purity_training_manifest.json");

writetable(predictions, paths.predictions_csv);
writetable(metrics, paths.metrics_csv);
writetable(oof_result.fold_summary, paths.fold_summary_csv);

purity_model_bundle = struct();
purity_model_bundle.schema_name = ...
    "reqml_purity_model_bundle";
purity_model_bundle.schema_version = "1.0";

purity_model_bundle.final_model = ...
    oof_result.final_model;

purity_model_bundle.fold_models = ...
    oof_result.fold_models;

purity_model_bundle.predictor_names = ...
    registry.purity_predictors;

purity_model_bundle.target_name = ...
    registry.targets.purity;

purity_model_bundle.model_spec = model_spec;
purity_model_bundle.predictor_metadata = predictor_metadata;

save( ...
    paths.model_mat, ...
    "purity_model_bundle", ...
    "-v7.3");

manifest = struct();
manifest.schema_name = ...
    "reqml_purity_training_manifest";
manifest.schema_version = "1.0";

manifest.dataset_path = char(dataset_path);
manifest.split_path = char(split_path);

manifest.model_spec = model_spec;
manifest.target_name = char(registry.targets.purity);
manifest.predictor_names = ...
    cellstr(registry.purity_predictors);

manifest.example_count = height(predictions);
manifest.train_count = nnz(predictions.partition == "train");
manifest.validation_count = ...
    nnz(predictions.partition == "validation");
manifest.test_count = nnz(predictions.partition == "test");

manifest.metrics = table2struct(metrics);
manifest.fold_summary = ...
    table2struct(oof_result.fold_summary);

write_json(paths.manifest_json, manifest);

end

function validate_input_paths(dataset_path, split_path)

if ~isfile(dataset_path)
    error("reqml:Scientific5DDatasetNotFound", ...
        "Scientific dataset was not found: %s", ...
        dataset_path);
end

if ~isfile(split_path)
    error("reqml:FrozenSplitNotFound", ...
        "Frozen training split was not found: %s", ...
        split_path);
end

end

function prepare_output_directory(output_directory)

if ~isfolder(output_directory)
    mkdir(output_directory);
    return
end

existing = dir(fullfile(output_directory, "**", "*"));
existing = existing(~[existing.isdir]);

if ~isempty(existing)
    error("reqml:PurityTrainingOutputAlreadyExists", ...
        ["Purity output already contains files. Delete it only " ...
         "when intentionally rerunning version v1: %s"], ...
        output_directory);
end

end

function write_json(path, value)

text = jsonencode(value, PrettyPrint=true);

file_id = fopen(path, "w");

if file_id < 0
    error("reqml:CannotWriteJson", ...
        "Could not open JSON file for writing: %s", path);
end

cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, "%s\n", text);

end
