function result = train_scientific_5d_quantile_models()
%TRAIN_SCIENTIFIC_5D_QUANTILE_MODELS Train Q0 and QP quantile models.
%
% Models:
%   q_spectrum:
%       observable spectral/context predictors -> q target
%
%   q_spectrum_plus_purity:
%       observable spectral/context predictors
%       + out-of-fold predicted purity -> q target
%
% Train predictions are grouped out-of-fold. Validation and test
% predictions use final models trained only on the complete train split.

repo_root = fileparts(fileparts(mfilename("fullpath")));

dataset_path = fullfile( ...
    repo_root, ...
    "outputs", ...
    "adaptive_scientific_5d", ...
    "reqml_adaptive_scientific_5d_final", ...
    "reqml_adaptive_scientific_5d_final_iteration_050", ...
    "dataset", ...
    "examples.mat");

split_path = fullfile( ...
    repo_root, ...
    "outputs", ...
    "scientific_5d_training", ...
    "split_v1", ...
    "training_split_assignments.mat");

purity_prediction_path = fullfile( ...
    repo_root, ...
    "outputs", ...
    "scientific_5d_training", ...
    "purity_model_v1", ...
    "tables", ...
    "purity_predictions.csv");

output_directory = fullfile( ...
    repo_root, ...
    "outputs", ...
    "scientific_5d_training", ...
    "quantile_models_v1");

validate_input_paths( ...
    dataset_path, ...
    split_path, ...
    purity_prediction_path);

prepare_output_directory(output_directory);

loaded = load(dataset_path, "examples");
examples = loaded.examples;

frozen = reqml.splits.load_frozen_training_split( ...
    examples, ...
    split_path);

split = frozen.split;
folds = frozen.folds;

registry = ...
    reqml.training.scientific_5d_predictor_registry();

q_contract = reqml.training.validate_predictor_contract( ...
    examples, ...
    registry.q_spectrum_predictors, ...
    registry);

if ~q_contract.valid
    error("reqml:InvalidQuantilePredictorContract", ...
        "%s", q_contract.summary);
end

predicted_patch_purity = load_aligned_purity_predictions( ...
    examples, ...
    purity_prediction_path, ...
    split.partition);

examples_with_purity = examples;
examples_with_purity.predicted_patch_purity = ...
    predicted_patch_purity;

qp_contract = reqml.training.validate_predictor_contract( ...
    examples_with_purity, ...
    registry.q_composition_predictors, ...
    registry);

if ~qp_contract.valid
    error("reqml:InvalidCompositionQuantilePredictorContract", ...
        "%s", qp_contract.summary);
end

[X_q0, q0_predictor_metadata] = ...
    reqml.training.build_numeric_predictor_matrix( ...
        examples, ...
        registry.q_spectrum_predictors);

[X_qp, qp_predictor_metadata] = ...
    reqml.training.build_numeric_predictor_matrix( ...
        examples_with_purity, ...
        registry.q_composition_predictors);

q_true = double( ...
    examples.q_target_from_center_truth);

validate_q_target(q_true);

common_spec = struct( ...
    "type", "bagged_trees", ...
    "num_learning_cycles", 160, ...
    "min_leaf_size", 8, ...
    "use_parallel", false);

q0_spec = common_spec;
q0_spec.id = "q_spectrum_bagged_v1";
q0_spec.random_seed = 7101;

qp_spec = common_spec;
qp_spec.id = "q_spectrum_plus_purity_bagged_v1";
qp_spec.random_seed = 7201;

fprintf("\n===== SCIENTIFIC QUANTILE TRAINING =====\n");
fprintf("Examples: %d\n", height(examples));
fprintf("Train: %d | Validation: %d | Test: %d\n", ...
    nnz(split.train_mask), ...
    nnz(split.validation_mask), ...
    nnz(split.test_mask));

fprintf("Q0 predictors: %d\n", ...
    q0_predictor_metadata.predictor_count);

fprintf("QP predictors: %d\n", ...
    qp_predictor_metadata.predictor_count);

fprintf("\nTraining Q0...\n");

q0_result = reqml.training.fit_oof_regression_model( ...
    X_q0, ...
    q_true, ...
    split, ...
    folds, ...
    q0_spec, ...
    ClipRange=[0.001, 0.999]);

fprintf("Training QP...\n");

qp_result = reqml.training.fit_oof_regression_model( ...
    X_qp, ...
    q_true, ...
    split, ...
    folds, ...
    qp_spec, ...
    ClipRange=[0.001, 0.999]);

q0_evaluation = evaluate_one_model( ...
    examples, ...
    q_true, ...
    q0_result.combined_prediction, ...
    split.partition, ...
    string(q0_spec.id));

qp_evaluation = evaluate_one_model( ...
    examples, ...
    q_true, ...
    qp_result.combined_prediction, ...
    split.partition, ...
    string(qp_spec.id));

q_metrics = [
    q0_evaluation.q_metrics
    qp_evaluation.q_metrics
    ];

sws_metrics = [
    q0_evaluation.sws_metrics
    qp_evaluation.sws_metrics
    ];

predictions = [
    build_prediction_table( ...
        examples, ...
        frozen.assignment, ...
        predicted_patch_purity, ...
        q_true, ...
        q0_result, ...
        q0_evaluation.sws, ...
        string(q0_spec.id))
    build_prediction_table( ...
        examples, ...
        frozen.assignment, ...
        predicted_patch_purity, ...
        q_true, ...
        qp_result, ...
        qp_evaluation.sws, ...
        string(qp_spec.id))
    ];

stratified_metrics = build_stratified_metrics( ...
    predictions);

comparison = build_validation_test_comparison( ...
    q_metrics, ...
    sws_metrics);

paths = save_outputs( ...
    output_directory, ...
    predictions, ...
    q_metrics, ...
    sws_metrics, ...
    stratified_metrics, ...
    comparison, ...
    q0_result, ...
    qp_result, ...
    registry, ...
    q0_predictor_metadata, ...
    qp_predictor_metadata, ...
    q0_spec, ...
    qp_spec, ...
    dataset_path, ...
    split_path, ...
    purity_prediction_path);

fprintf("\n===== Q METRICS =====\n");
disp(q_metrics);

fprintf("\n===== SWS METRICS =====\n");
disp(sws_metrics);

fprintf("\n===== MODEL COMPARISON =====\n");
disp(comparison);

fprintf("Saved quantile outputs: %s\n", output_directory);

result = struct();
result.schema_name = ...
    "reqml_scientific_5d_quantile_training";
result.schema_version = "1.0";

result.q_metrics = q_metrics;
result.sws_metrics = sws_metrics;
result.comparison = comparison;
result.stratified_metrics = stratified_metrics;
result.predictions = predictions;
result.paths = paths;

end

function evaluation = evaluate_one_model( ...
    examples, q_true, q_pred, partition, model_id)

q_metrics = reqml.evaluation.evaluate_q_predictions( ...
    q_true, ...
    q_pred, ...
    partition, ...
    model_id);

sws = reqml.evaluation.convert_q_predictions_to_sws( ...
    examples, ...
    q_pred, ...
    TruthColumn="truth_cs_center_m_s", ...
    FrequencyColumn="campaign_frequency_hz", ...
    MappingColumn="req_mapping");

sws_metrics = reqml.evaluation.evaluate_sws_predictions( ...
    sws, ...
    partition, ...
    model_id);

evaluation = struct();
evaluation.q_metrics = q_metrics;
evaluation.sws = sws;
evaluation.sws_metrics = sws_metrics;

end

function purity = load_aligned_purity_predictions( ...
    examples, prediction_path, expected_partition)

T = readtable( ...
    prediction_path, ...
    TextType="string", ...
    VariableNamingRule="preserve");

required = [
    "example_id"
    "partition"
    "predicted_patch_purity"
    ];

missing = setdiff( ...
    required, ...
    string(T.Properties.VariableNames));

if ~isempty(missing)
    error("reqml:InvalidPurityPredictionFile", ...
        "Purity prediction file is missing: %s", ...
        strjoin(missing, ", "));
end

current_id = string(examples.example_id);
stored_id = string(T.example_id);

if numel(unique(stored_id)) ~= height(T)
    error("reqml:DuplicatePurityPredictionExampleId", ...
        "Purity predictions contain duplicate example IDs.");
end

[found, index] = ismember(current_id, stored_id);

if any(~found) || height(T) ~= height(examples)
    error("reqml:PurityPredictionDatasetMismatch", ...
        "Purity predictions do not match the scientific dataset.");
end

ordered = T(index, :);

if any(string(ordered.partition) ~= expected_partition)
    error("reqml:PurityPredictionPartitionMismatch", ...
        "Purity predictions were generated using a different split.");
end

purity = double(ordered.predicted_patch_purity);

if any(~isfinite(purity)) || ...
        any(purity < 0 | purity > 1)
    error("reqml:InvalidPredictedPurity", ...
        "Predicted purity must be finite and within [0,1].");
end

end

function predictions = build_prediction_table( ...
    examples, ...
    assignment, ...
    predicted_purity, ...
    q_true, ...
    model_result, ...
    sws, ...
    model_id)

n = height(examples);

predictions = table();

predictions.model_id = repmat(model_id, n, 1);
predictions.example_id = string(examples.example_id);

predictions.campaign_condition_id = ...
    string(examples.campaign_condition_id);

predictions.campaign_run_id = ...
    string(examples.campaign_run_id);

predictions.partition = string(assignment.partition);
predictions.cv_fold = double(assignment.cv_fold);

predictions.prediction_source = ...
    string(model_result.prediction_source);

predictions.campaign_frequency_hz = ...
    double(examples.campaign_frequency_hz);

predictions.truth_cs_center_m_s = ...
    double(examples.truth_cs_center_m_s);

predictions.truth_material_purity = ...
    double(examples.truth_material_purity);

predictions.predicted_patch_purity = ...
    double(predicted_purity);

predictions.q_true = double(q_true);
predictions.q_pred = ...
    double(model_result.combined_prediction);

predictions.q_error = ...
    predictions.q_pred - predictions.q_true;

predictions.q_absolute_error = ...
    abs(predictions.q_error);

predictions.k_pred_rad_m = sws.k_pred_rad_m;
predictions.cs_true_m_s = sws.cs_true_m_s;
predictions.cs_pred_m_s = sws.cs_pred_m_s;
predictions.cs_error_m_s = sws.cs_error_m_s;
predictions.cs_error_percent = sws.cs_error_percent;

predictions.cs_absolute_error_percent = ...
    sws.cs_absolute_error_percent;

predictions.sws_valid = sws.sws_valid;

optional_names = [
    "achieved_sws_bin"
    "achieved_frequency_bin"
    "achieved_purity_bin"
    "achieved_dnom_bin"
    "achieved_discretization_bin"
    "center_selection_role"
    "GRID_dx_m"
    "GRID_dz_m"
    ];

available = string(examples.Properties.VariableNames);

for index = 1:numel(optional_names)
    name = optional_names(index);

    if ismember(name, available)
        predictions.(char(name)) = ...
            examples.(char(name));
    end
end

end

function stratified = build_stratified_metrics(predictions)

group_candidates = [
    "achieved_sws_bin"
    "achieved_frequency_bin"
    "achieved_purity_bin"
    "achieved_dnom_bin"
    "achieved_discretization_bin"
    "center_selection_role"
    ];

available = string(predictions.Properties.VariableNames);

group_variables = group_candidates( ...
    ismember(group_candidates, available));

blocks = cell(numel(group_variables), 1);

for variable_index = 1:numel(group_variables)
    group_name = group_variables(variable_index);

    group_values = string( ...
        predictions.(char(group_name)));

    grouping_table = table( ...
        string(predictions.model_id), ...
        string(predictions.partition), ...
        group_values, ...
        VariableNames=[ ...
            "model_id", ...
            "partition", ...
            "stratification_value"]);

    [group_id, group_table] = findgroups(grouping_table);

    row_count = splitapply( ...
        @numel, ...
        predictions.q_true, ...
        group_id);

    q_mae = splitapply( ...
        @(x) mean(x, "omitnan"), ...
        predictions.q_absolute_error, ...
        group_id);

    q_bias = splitapply( ...
        @(x) mean(x, "omitnan"), ...
        predictions.q_error, ...
        group_id);

    sws_mape = splitapply( ...
        @(x) mean(x, "omitnan"), ...
        predictions.cs_absolute_error_percent, ...
        group_id);

    sws_bias_percent = splitapply( ...
        @(x) mean(x, "omitnan"), ...
        predictions.cs_error_percent, ...
        group_id);

    sws_p90_ape = splitapply( ...
        @(x) prctile(x, 90), ...
        predictions.cs_absolute_error_percent, ...
        group_id);

    sws_error_gt10_pct = splitapply( ...
        @(x) 100 * mean(x > 10), ...
        predictions.cs_absolute_error_percent, ...
        group_id);

    sws_error_gt20_pct = splitapply( ...
        @(x) 100 * mean(x > 20), ...
        predictions.cs_absolute_error_percent, ...
        group_id);

    block = group_table;

    block.stratification_variable = ...
        repmat(group_name, height(block), 1);

    block = movevars( ...
        block, ...
        "stratification_variable", ...
        "Before", ...
        "stratification_value");

    block.row_count = row_count;
    block.q_mae = q_mae;
    block.q_bias = q_bias;
    block.sws_mape = sws_mape;
    block.sws_bias_percent = sws_bias_percent;
    block.sws_p90_ape = sws_p90_ape;
    block.sws_error_gt10_pct = sws_error_gt10_pct;
    block.sws_error_gt20_pct = sws_error_gt20_pct;

    blocks{variable_index} = block;
end

if isempty(blocks)
    stratified = table();
else
    stratified = vertcat(blocks{:});
end

end

function comparison = build_validation_test_comparison( ...
    q_metrics, sws_metrics)

partitions = ["validation"; "test"];
rows = cell(numel(partitions), 1);

for index = 1:numel(partitions)
    partition_name = partitions(index);

    Q = q_metrics(q_metrics.partition == partition_name, :);
    S = sws_metrics(sws_metrics.partition == partition_name, :);

    q0_q = Q(Q.baseline_id == "q_spectrum_bagged_v1", :);
    qp_q = Q(Q.baseline_id == ...
        "q_spectrum_plus_purity_bagged_v1", :);

    q0_s = S(S.model_id == "q_spectrum_bagged_v1", :);
    qp_s = S(S.model_id == ...
        "q_spectrum_plus_purity_bagged_v1", :);

    rows{index} = table( ...
        partition_name, ...
        q0_q.q_mae, ...
        qp_q.q_mae, ...
        100*(q0_q.q_mae - qp_q.q_mae) / q0_q.q_mae, ...
        q0_s.sws_mape, ...
        qp_s.sws_mape, ...
        q0_s.sws_mape - qp_s.sws_mape, ...
        q0_s.sws_error_gt10_pct, ...
        qp_s.sws_error_gt10_pct, ...
        q0_s.sws_error_gt20_pct, ...
        qp_s.sws_error_gt20_pct, ...
        'VariableNames', [ ...
            "partition", ...
            "q0_q_mae", ...
            "qp_q_mae", ...
            "q_mae_relative_improvement_pct", ...
            "q0_sws_mape", ...
            "qp_sws_mape", ...
            "sws_mape_absolute_improvement", ...
            "q0_error_gt10_pct", ...
            "qp_error_gt10_pct", ...
            "q0_error_gt20_pct", ...
            "qp_error_gt20_pct"]);
end

comparison = vertcat(rows{:});

end

function paths = save_outputs( ...
    output_directory, ...
    predictions, ...
    q_metrics, ...
    sws_metrics, ...
    stratified_metrics, ...
    comparison, ...
    q0_result, ...
    qp_result, ...
    registry, ...
    q0_predictor_metadata, ...
    qp_predictor_metadata, ...
    q0_spec, ...
    qp_spec, ...
    dataset_path, ...
    split_path, ...
    purity_prediction_path)

table_directory = fullfile(output_directory, "tables");
model_directory = fullfile(output_directory, "models");

mkdir(table_directory);
mkdir(model_directory);

paths = struct();

paths.predictions_csv = fullfile( ...
    table_directory, ...
    "quantile_predictions.csv");

paths.q_metrics_csv = fullfile( ...
    table_directory, ...
    "q_metrics.csv");

paths.sws_metrics_csv = fullfile( ...
    table_directory, ...
    "sws_metrics.csv");

paths.stratified_metrics_csv = fullfile( ...
    table_directory, ...
    "stratified_metrics.csv");

paths.comparison_csv = fullfile( ...
    table_directory, ...
    "model_comparison.csv");

paths.q0_fold_summary_csv = fullfile( ...
    table_directory, ...
    "q0_oof_fold_summary.csv");

paths.qp_fold_summary_csv = fullfile( ...
    table_directory, ...
    "qp_oof_fold_summary.csv");

paths.model_bundle_mat = fullfile( ...
    model_directory, ...
    "quantile_model_bundle.mat");

paths.manifest_json = fullfile( ...
    output_directory, ...
    "quantile_training_manifest.json");

writetable(predictions, paths.predictions_csv);
writetable(q_metrics, paths.q_metrics_csv);
writetable(sws_metrics, paths.sws_metrics_csv);
writetable(stratified_metrics, paths.stratified_metrics_csv);
writetable(comparison, paths.comparison_csv);

writetable( ...
    q0_result.fold_summary, ...
    paths.q0_fold_summary_csv);

writetable( ...
    qp_result.fold_summary, ...
    paths.qp_fold_summary_csv);

quantile_model_bundle = struct();
quantile_model_bundle.schema_name = ...
    "reqml_quantile_model_bundle";
quantile_model_bundle.schema_version = "1.0";

quantile_model_bundle.q0_model = q0_result.final_model;
quantile_model_bundle.qp_model = qp_result.final_model;

quantile_model_bundle.q0_predictor_names = ...
    registry.q_spectrum_predictors;

quantile_model_bundle.qp_predictor_names = ...
    registry.q_composition_predictors;

quantile_model_bundle.target_name = ...
    registry.targets.quantile;

quantile_model_bundle.q0_model_spec = q0_spec;
quantile_model_bundle.qp_model_spec = qp_spec;

quantile_model_bundle.q0_predictor_metadata = ...
    q0_predictor_metadata;

quantile_model_bundle.qp_predictor_metadata = ...
    qp_predictor_metadata;

save( ...
    paths.model_bundle_mat, ...
    "quantile_model_bundle", ...
    "-v7.3");

manifest = struct();
manifest.schema_name = ...
    "reqml_quantile_training_manifest";
manifest.schema_version = "1.0";

manifest.dataset_path = char(dataset_path);
manifest.split_path = char(split_path);

manifest.purity_prediction_path = ...
    char(purity_prediction_path);

manifest.target_name = ...
    char(registry.targets.quantile);

manifest.q0_model_spec = q0_spec;
manifest.qp_model_spec = qp_spec;

manifest.q0_predictor_names = ...
    cellstr(registry.q_spectrum_predictors);

manifest.qp_predictor_names = ...
    cellstr(registry.q_composition_predictors);

manifest.q_metrics = table2struct(q_metrics);
manifest.sws_metrics = table2struct(sws_metrics);
manifest.model_comparison = table2struct(comparison);

write_json(paths.manifest_json, manifest);

end

function validate_q_target(q_true)

if any(~isfinite(q_true))
    error("reqml:NonFiniteQuantileTarget", ...
        "Quantile target contains non-finite rows.");
end

if any(q_true < 0 | q_true > 1)
    error("reqml:QuantileTargetOutsideUnitInterval", ...
        "Quantile target contains values outside [0,1].");
end

end

function validate_input_paths( ...
    dataset_path, split_path, purity_prediction_path)

paths = [
    dataset_path
    split_path
    purity_prediction_path
    ];

for index = 1:numel(paths)
    if ~isfile(paths(index))
        error("reqml:TrainingInputNotFound", ...
            "Required training input was not found: %s", ...
            paths(index));
    end
end

end

function prepare_output_directory(output_directory)

if ~isfolder(output_directory)
    mkdir(output_directory);
    return
end

existing = dir(fullfile(output_directory, "**", "*"));
existing = existing(~[existing.isdir]);

if ~isempty(existing)
    error("reqml:QuantileTrainingOutputAlreadyExists", ...
        ["Quantile output already contains files. Delete it only " ...
         "when intentionally rerunning version v1: %s"], ...
        output_directory);
end

end

function write_json(path, value)

text = jsonencode(value, PrettyPrint=true);

file_id = fopen(path, "w");

if file_id < 0
    error("reqml:CannotWriteJson", ...
        "Could not open JSON file for writing: %s", path);
end

cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, "%s\n", text);

end
