function tests = test_write_adaptive_batch
%TEST_WRITE_ADAPTIVE_BATCH Test adaptive batch artifacts.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testWritesPhysicalPlanAndCompatibleCampaign(testCase)

output_directory = string(tempname);

cleanup = onCleanup(@() cleanup_directory( ...
    output_directory));

physical_condition = make_physical_condition();

campaign_config = struct();

campaign_config.backend = "swsynth";
campaign_config.campaign_name = ...
    "reqml_adaptive_batch_001";

campaign_config.base_config = ...
    "configs/swsynth/scientific/" + ...
    "reqml_eikonal_training_v1/" + ...
    "circular_inclusion_base.json";

paths = reqml.campaigns.writeAdaptiveBatch( ...
    physical_condition, ...
    campaign_config, ...
    OutputDirectory=output_directory, ...
    BatchId="batch_001", ...
    PlannerSeed=17001, ...
    ParentCoverageReportHash="coverage_hash");

verifyTrue(testCase, isfile(paths.plan));

verifyTrue(testCase, ...
    isfile(paths.simulation_campaign));

plan = jsondecode(fileread(paths.plan));

campaign = jsondecode(fileread( ...
    paths.simulation_campaign));

verifyEqual(testCase, ...
    string(plan.schema_name), ...
    "reqml_adaptive_batch_plan");

verifyEqual(testCase, ...
    string(plan.schema_version), ...
    "1.1");

verifyEqual(testCase, plan.condition_count, 1);
verifyEqual(testCase, plan.run_count, 2);

verifyEqual(testCase, ...
    string(plan.physical_conditions.condition_id), ...
    "cond_000001");

verifyEqual(testCase, ...
    string(plan.runs(1).condition_id), ...
    "cond_000001");

verifyEqual(testCase, ...
    plan.runs(2).realization_id, ...
    2);

verifyEqual(testCase, ...
    string(campaign.schema_version), ...
    "1.2");

verifyEqual(testCase, ...
    string(campaign.backend), ...
    "swsynth");

verifyEqual(testCase, ...
    string(campaign.runs(1).design_id), ...
    "cond_000001_r001");

verifyFalse(testCase, ...
    isfield(campaign.runs, "condition_id"));

paths_first = string({campaign.runs(1).overrides.path})';

verifyTrue(testCase, ...
    ismember("medium.objects[1].radius_m", ...
        paths_first));

verifyTrue(testCase, ...
    ismember("directions.support.solid_angle_sr", ...
        paths_first));

verifyTrue(testCase, ...
    ismember("seed", paths_first));

clear cleanup

end


function testRejectsUnsupportedBackend(testCase)

physical_condition = make_physical_condition();

campaign_config = struct();

campaign_config.backend = "kwsim";
campaign_config.campaign_name = "invalid_backend";
campaign_config.base_config = "config.json";

verifyError(testCase, ...
    @() reqml.campaigns.writeAdaptiveBatch( ...
        physical_condition, ...
        campaign_config, ...
        OutputDirectory=string(tempname), ...
        BatchId="batch_001", ...
        PlannerSeed=1), ...
    "reqml:UnsupportedAdaptiveCampaignBackend");

end


function physical_condition = make_physical_condition()

physical_condition = struct();

physical_condition.condition_id = "cond_000001";
physical_condition.realization_count = 2;
physical_condition.seed = 12345;

physical_condition.geometry = struct( ...
    "family", "circular_inclusion", ...
    "radius_m", 0.008, ...
    "center_xz_m", [0.02 0.03], ...
    "normal_angle_rad", NaN, ...
    "offset_m", NaN);

physical_condition.material = struct( ...
    "background_cs_m_s", 2.0, ...
    "object_cs_m_s", 3.0);

physical_condition.wavefield = struct( ...
    "frequency_hz", 400, ...
    "direction_count", 16, ...
    "in_plane_count", 4, ...
    "solid_angle_sr", pi);

physical_condition.requested_coverage = struct( ...
    "purity_bin", 2, ...
    "purity_range", [0.7 0.9], ...
    "diffusivity_bin", 2, ...
    "diffusivity_range", [0.4 0.7], ...
    "deficit_score", 1.5);

end


function cleanup_directory(directory)

if isfolder(directory)
    rmdir(directory, "s");
end

end
