function tests = test_select_coverage_centers

tests = functiontests(localfunctions);

end


function testSelectsMultipleCellsFromOneSimulation(testCase)

truth = make_bilayer_truth();

requested = table( ...
    [1; 1; 2; 2], ...
    [1; 1; 1; 1], ...
    [1; 3; 1; 3], ...
    [1; 1; 1; 1], ...
    [1; 1; 1; 1], ...
    [4; 4; 4; 4], ...
    VariableNames=[ ...
        "sws_bin", ...
        "frequency_bin", ...
        "purity_bin", ...
        "diffusivity_bin", ...
        "discretization_bin", ...
        "needed_example_count"]);

selection = reqml.datasets.selectCoverageCenters( ...
    truth, ...
    5, ...
    requested, ...
    PurityEdges=[0.5 0.7 0.9 1.0001], ...
    DiffusivityEdges=[0 1], ...
    SwsEdges=[1.5 3.0 4.5], ...
    FrequencyEdges=[400 600], ...
    FrequencyHz=500, ...
    DiffusivityValue=0.5, ...
    CandidateStepPixels=1, ...
    MaximumPerCell=4, ...
    MinimumCenterDistancePixels=0, ...
    RandomSeed=17);

verifyGreaterThan(testCase, height(selection), 0);

verifyTrue(testCase, all( ...
    ismember(selection.coverage_sws_bin, [1; 2])));

verifyTrue(testCase, all( ...
    ismember(selection.coverage_purity_bin, [1; 3])));

verifyEqual(testCase, ...
    selection.coverage_cell_key, ...
    selection.selection_target_cell_key);

verifyLessThanOrEqual(testCase, ...
    max(groupcounts( ...
        selection.selection_target_cell_key)), ...
    4);

verifyEqual(testCase, ...
    size(unique(selection{:, ["cx", "cz"]}, "rows"), 1), ...
    height(selection));

end


function testHonorsSpatialSeparation(testCase)

truth = make_bilayer_truth();

requested = table( ...
    1, ...
    1, ...
    3, ...
    1, ...
    1, ...
    20, ...
    VariableNames=[ ...
        "sws_bin", ...
        "frequency_bin", ...
        "purity_bin", ...
        "diffusivity_bin", ...
        "discretization_bin", ...
        "needed_example_count"]);

minimum_distance = 5;

selection = reqml.datasets.selectCoverageCenters( ...
    truth, ...
    5, ...
    requested, ...
    PurityEdges=[0.5 0.7 0.9 1.0001], ...
    DiffusivityEdges=[0 1], ...
    SwsEdges=[1.5 3.0 4.5], ...
    FrequencyEdges=[400 600], ...
    FrequencyHz=500, ...
    DiffusivityValue=0.5, ...
    CandidateStepPixels=1, ...
    MaximumPerCell=20, ...
    MinimumCenterDistancePixels=minimum_distance, ...
    RandomSeed=21);

centers = selection{:, ["cx", "cz"]};

for first = 1:size(centers, 1)
    for second = (first + 1):size(centers, 1)
        distance = hypot( ...
            centers(first, 1) - centers(second, 1), ...
            centers(first, 2) - centers(second, 2));

        verifyGreaterThanOrEqual( ...
            testCase, ...
            distance, ...
            minimum_distance);
    end
end

end


function testSelectionIsReproducible(testCase)

truth = make_bilayer_truth();

requested = table( ...
    [1; 2], ...
    [1; 1], ...
    [1; 1], ...
    [1; 1], ...
    [1; 1], ...
    [5; 5], ...
    VariableNames=[ ...
        "sws_bin", ...
        "frequency_bin", ...
        "purity_bin", ...
        "diffusivity_bin", ...
        "discretization_bin", ...
        "needed_example_count"]);

arguments = { ...
    "PurityEdges", [0.5 0.7 0.9 1.0001], ...
    "DiffusivityEdges", [0 1], ...
    "SwsEdges", [1.5 3.0 4.5], ...
    "FrequencyEdges", [400 600], ...
    "FrequencyHz", 500, ...
    "DiffusivityValue", 0.5, ...
    "CandidateStepPixels", 1, ...
    "MaximumPerCell", 5, ...
    "RandomSeed", 123};

first = reqml.datasets.selectCoverageCenters( ...
    truth, 5, requested, arguments{:});

second = reqml.datasets.selectCoverageCenters( ...
    truth, 5, requested, arguments{:});

verifyEqual(testCase, first, second);

end


function truth = make_bilayer_truth()

nz = 31;
nx = 31;

material = ones(nz, nx, "uint16");
material(:, 17:end) = 2;

cs = 2 * ones(nz, nx);
cs(:, 17:end) = 4;

truth = struct();
truth.material_id_zx = material;
truth.cs_m_s_zx = cs;
truth.valid_mask_zx = true(nz, nx);

end
