function tests = test_make_bootstrap_condition_requests
%TEST_MAKE_BOOTSTRAP_CONDITION_REQUESTS

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testCreatesOneRequestPerSwsFrequencyDiscretizationBlock(testCase)

coverage = make_scientific_coverage();

requests = ...
    reqml.campaigns.makeBootstrapConditionRequests( ...
        coverage, ...
        BatchId="bootstrap_test", ...
        PlannerSeed=42001, ...
        RealizationsPerCondition=2);

verifyEqual(testCase, numel(requests), 75);

blocks = [
    [requests.sws_bin]', ...
    [requests.frequency_bin]', ...
    [requests.discretization_bin]'
    ];

verifyEqual(testCase, ...
    size(unique(blocks, "rows"), 1), ...
    75);

verifyEqual(testCase, ...
    unique([requests.sws_bin]'), ...
    (1:5)');

verifyEqual(testCase, ...
    unique([requests.frequency_bin]'), ...
    (1:5)');

verifyEqual(testCase, ...
    unique([requests.discretization_bin]'), ...
    (1:3)');

verifyEqual(testCase, ...
    [requests.realization_count]', ...
    repmat(2, 75, 1));

verifyEqual(testCase, ...
    [requests.planner_seed]', ...
    repmat(42001, 75, 1));

end


function testCreatesUniqueFiveDimensionalIdentifiers(testCase)

coverage = make_scientific_coverage();

requests = ...
    reqml.campaigns.makeBootstrapConditionRequests( ...
        coverage, ...
        BatchId="bootstrap_test", ...
        PlannerSeed=42001);

condition_ids = string({requests.condition_id})';
cell_keys = string({requests.requested_cell_key})';

verifyEqual(testCase, ...
    numel(unique(condition_ids)), ...
    75);

verifyEqual(testCase, ...
    numel(unique(cell_keys)), ...
    75);

verifyTrue(testCase, ...
    all(contains(condition_ids, "_g")));

verifyTrue(testCase, ...
    all(contains(cell_keys, "_g")));

end


function testUsesExactConfiguredPhysicalRanges(testCase)

coverage = make_scientific_coverage();

requests = ...
    reqml.campaigns.makeBootstrapConditionRequests( ...
        coverage, ...
        BatchId="bootstrap_test");

sws_edges = coverage.sws_edges_m_s;
frequency_edges = coverage.frequency_edges_hz;
purity_edges = coverage.purity_edges;

dnom_edges = ...
    coverage.nominal_angular_coverage_edges;

for index = 1:numel(requests)
    request = requests(index);

    verifyEqual(testCase, ...
        request.target_sws_range_m_s, ...
        sws_edges( ...
            request.sws_bin: ...
            request.sws_bin + 1));

    verifyEqual(testCase, ...
        request.target_frequency_range_hz, ...
        frequency_edges( ...
            request.frequency_bin: ...
            request.frequency_bin + 1));

    verifyEqual(testCase, ...
        request.purity_range, ...
        purity_edges( ...
            request.purity_bin: ...
            request.purity_bin + 1));

    verifyEqual(testCase, ...
        request.diffusivity_range, ...
        dnom_edges( ...
            request.diffusivity_bin: ...
            request.diffusivity_bin + 1));

    verifyEqual(testCase, ...
        request.target_grid_spacing_m, ...
        coverage.discretization_pairs_m( ...
            request.discretization_bin, :), ...
        AbsTol=1e-15);

    verifyEqual(testCase, ...
        request.nominal_angular_coverage_range, ...
        request.diffusivity_range);

    verifyEqual(testCase, ...
        request.requested_cell_key, ...
        compose( ...
            "s%02d_f%02d_p%02d_d%02d_g%02d", ...
            request.sws_bin, ...
            request.frequency_bin, ...
            request.purity_bin, ...
            request.diffusivity_bin, ...
            request.discretization_bin));
end

end


function testDistributionIsDeterministic(testCase)

coverage = make_scientific_coverage();

a = reqml.campaigns.makeBootstrapConditionRequests( ...
    coverage, ...
    BatchId="bootstrap_test", ...
    PlannerSeed=42001);

b = reqml.campaigns.makeBootstrapConditionRequests( ...
    coverage, ...
    BatchId="bootstrap_test", ...
    PlannerSeed=42001);

verifyEqual(testCase, a, b);

expected_geometry = repmat( ...
    [ ...
        "homogeneous"
        "bilayer"
        "circular_inclusion"
    ], ...
    25, ...
    1);

expected_geometry = expected_geometry(1:75);

verifyEqual(testCase, ...
    string({a.geometry_family})', ...
    expected_geometry);

end


function testRequestsCanBeMaterialized(testCase)

coverage = make_scientific_coverage();

requests = ...
    reqml.campaigns.makeBootstrapConditionRequests( ...
        coverage, ...
        BatchId="bootstrap_test", ...
        PlannerSeed=42001);

conditions = ...
    reqml.campaigns.materializePhysicalConditions( ...
        requests, ...
        PlannerSeed=42001);

verifyEqual(testCase, numel(conditions), 75);

verifyTrue(testCase, ...
    all([conditions.realization_count]' == 2));

verifyEqual(testCase, ...
    string({conditions.condition_id})', ...
    string({requests.condition_id})');

end


function coverage = make_scientific_coverage()

coverage = struct();

coverage.sws_edges_m_s = ...
    [1.5 2.0 2.5 3.0 3.5 4.0];

coverage.frequency_edges_hz = ...
    [199 250 350 450 550 601];

coverage.purity_edges = ...
    [0.5 0.7 0.9 0.98 1.0];

coverage.nominal_angular_coverage_edges = ...
    [0 0.01 0.05 0.20 0.50 1.0];

coverage.discretization_pairs_m = [
    0.25e-3 0.25e-3
    0.40e-3 0.40e-3
    0.50e-3 0.50e-3
    ];

end
