function tests = test_grouped_training_folds
%TEST_GROUPED_TRAINING_FOLDS Test deterministic train-only grouped folds.

tests = functiontests(localfunctions);

end

function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end

function testKeepsConditionsAndRunsWithinOneFold(testCase)

examples = make_examples();

split = reqml.splits.make_grouped_condition_split( ...
    examples, ...
    GroupColumns="campaign_condition_id", ...
    Seed=4101, ...
    TrainFraction=0.70, ...
    ValidationFraction=0.15, ...
    TestFraction=0.15);

folds = reqml.splits.make_grouped_training_folds( ...
    examples, ...
    split, ...
    ConditionColumn="campaign_condition_id", ...
    FoldCount=5, ...
    Seed=5101);

report = reqml.splits.validate_training_fold_integrity( ...
    examples, ...
    split, ...
    folds);

verifyTrue(testCase, report.valid);
verifyFalse(testCase, report.condition_overlap);
verifyFalse(testCase, report.run_overlap);

verifyEqual(testCase, ...
    unique(folds.cv_fold(split.train_mask)), ...
    (1:5)');

verifyEqual(testCase, ...
    unique(folds.cv_fold(~split.train_mask)), ...
    0);

end

function testIsDeterministic(testCase)

examples = make_examples();

split = reqml.splits.make_grouped_condition_split( ...
    examples, ...
    GroupColumns="campaign_condition_id", ...
    Seed=4101, ...
    TrainFraction=0.70, ...
    ValidationFraction=0.15, ...
    TestFraction=0.15);

a = reqml.splits.make_grouped_training_folds( ...
    examples, split, Seed=5101);

b = reqml.splits.make_grouped_training_folds( ...
    examples, split, Seed=5101);

verifyEqual(testCase, a.cv_fold, b.cv_fold);
verifyEqual(testCase, a.conditions, b.conditions);

end

function examples = make_examples()

condition_count = 20;
runs_per_condition = 2;
examples_per_run = 3;

n = ...
    condition_count * ...
    runs_per_condition * ...
    examples_per_run;

campaign_condition_id = strings(n, 1);
campaign_run_id = strings(n, 1);
campaign_background_cs_m_s = zeros(n, 1);
campaign_frequency_hz = zeros(n, 1);
campaign_direction_count = zeros(n, 1);

row = 0;

for condition_index = 1:condition_count
    condition_id = compose( ...
        "condition_%03d", ...
        condition_index);

    for run_index = 1:runs_per_condition
        run_id = compose( ...
            "%s_run_%02d", ...
            condition_id, ...
            run_index);

        for example_index = 1:examples_per_run
            row = row + 1;

            campaign_condition_id(row) = condition_id;
            campaign_run_id(row) = run_id;

            campaign_background_cs_m_s(row) = ...
                1.5 + 0.1 * mod(condition_index, 5);

            campaign_frequency_hz(row) = ...
                200 + 100 * mod(condition_index, 5);

            campaign_direction_count(row) = ...
                1 + mod(condition_index, 8);
        end
    end
end

examples = table( ...
    campaign_condition_id, ...
    campaign_run_id, ...
    campaign_background_cs_m_s, ...
    campaign_frequency_hz, ...
    campaign_direction_count);

end
