function tests = test_oof_regression_training
%TEST_OOF_REGRESSION_TRAINING Test grouped OOF regression.

tests = functiontests(localfunctions);

end

function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end

function testProducesCompleteTrainOnlyOofPredictions(testCase)

rng(101);

condition_count = 30;
rows_per_condition = 4;
n = condition_count * rows_per_condition;

condition_number = repelem((1:condition_count)', rows_per_condition);
X = [
    condition_number / condition_count, ...
    randn(n, 1)
    ];

target = min(max( ...
    0.55 + 0.30*X(:,1) + 0.03*X(:,2), ...
    0), 1);

examples = make_examples( ...
    condition_number, ...
    rows_per_condition);

split = reqml.splits.make_grouped_condition_split( ...
    examples, ...
    GroupColumns="campaign_condition_id", ...
    Seed=4101, ...
    TrainFraction=0.70, ...
    ValidationFraction=0.15, ...
    TestFraction=0.15);

folds = reqml.splits.make_grouped_training_folds( ...
    examples, ...
    split, ...
    ConditionColumn="campaign_condition_id", ...
    FoldCount=5, ...
    Seed=5101);

spec = struct( ...
    "id", "purity_bagged", ...
    "type", "bagged_trees", ...
    "num_learning_cycles", 20, ...
    "min_leaf_size", 4, ...
    "use_parallel", false, ...
    "random_seed", 6101);

result = reqml.training.fit_oof_regression_model( ...
    X, target, split, folds, spec, ...
    ClipRange=[0, 1]);

verifyTrue(testCase, ...
    all(isfinite(result.combined_prediction)));

verifyTrue(testCase, ...
    all(isfinite( ...
        result.oof_prediction(split.train_mask))));

verifyTrue(testCase, ...
    all(isnan( ...
        result.oof_prediction(~split.train_mask))));

verifyEqual(testCase, ...
    unique(result.prediction_source(split.train_mask)), ...
    "out_of_fold");

verifyEqual(testCase, ...
    unique(result.prediction_source(~split.train_mask)), ...
    "final_train_model");

verifyEqual(testCase, ...
    height(result.fold_summary), ...
    5);

end

function testIsDeterministic(testCase)

rng(202);

n = 120;
X = randn(n, 3);
target = min(max(0.7 + 0.04*X(:,1), 0), 1);

condition_number = repelem((1:30)', 4);
examples = make_examples(condition_number, 4);

split = reqml.splits.make_grouped_condition_split( ...
    examples, ...
    GroupColumns="campaign_condition_id", ...
    Seed=4101, ...
    TrainFraction=0.70, ...
    ValidationFraction=0.15, ...
    TestFraction=0.15);

folds = reqml.splits.make_grouped_training_folds( ...
    examples, split, Seed=5101);

spec = struct( ...
    "id", "purity_bagged", ...
    "type", "bagged_trees", ...
    "num_learning_cycles", 15, ...
    "min_leaf_size", 5, ...
    "use_parallel", false, ...
    "random_seed", 6101);

a = reqml.training.fit_oof_regression_model( ...
    X, target, split, folds, spec, ...
    ClipRange=[0, 1]);

b = reqml.training.fit_oof_regression_model( ...
    X, target, split, folds, spec, ...
    ClipRange=[0, 1]);

verifyEqual(testCase, ...
    a.combined_prediction, ...
    b.combined_prediction, ...
    AbsTol=0);

end

function examples = make_examples( ...
    condition_number, rows_per_condition)

n = numel(condition_number);

campaign_condition_id = compose( ...
    "condition_%03d", ...
    condition_number);

run_number = repelem( ...
    (1:ceil(n / rows_per_condition))', ...
    rows_per_condition);

run_number = run_number(1:n);

campaign_run_id = compose( ...
    "run_%03d", ...
    run_number);

examples = table( ...
    string(campaign_condition_id), ...
    string(campaign_run_id), ...
    VariableNames=[ ...
        "campaign_condition_id", ...
        "campaign_run_id"]);

end
