function tests = test_run_adaptive_campaign_loop
%TEST_RUN_ADAPTIVE_CAMPAIGN_LOOP Test adaptive loop orchestration.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testRunsUntilCoverageIsComplete(testCase)

root = string(tempname);

previous_csv = fullfile(root, "previous.csv");
initial_batch = fullfile(root, "initial_batch");
output_root = fullfile(root, "iterations");
framework_root = fullfile(root, "framework");

mkdir(root);
mkdir(initial_batch);
mkdir(framework_root);

write_table(previous_csv);
write_plan(initial_batch);

cleanup = onCleanup(@() cleanup_root(root));

feat_cfg = struct();
campaign_config = struct();
campaign_config.campaign_name = "test_campaign";

result = reqml.campaigns.runAdaptiveCampaignLoop( ...
    previous_csv, ...
    initial_batch, ...
    feat_cfg, ...
    campaign_config, ...
    framework_root, ...
    OutputRoot=output_root, ...
    CampaignId="loop_test", ...
    MaximumIterations=3, ...
    PlannerSeed=100, ...
    PurityEdges=[0.5 0.7 1.0], ...
    DiffusivityEdges=[0 0.5 1.0], ...
    SwsEdges=[1.5 3.0 4.0], ...
    FrequencyEdges=[199 400 601], ...
    ExecuteBatchFunction=@fake_execute, ...
    AdvanceIterationFunction=@fake_advance);

verifyTrue(testCase, result.coverage_complete);

verifyEqual(testCase, ...
    result.stop_reason, ...
    "coverage_complete");

verifyEqual(testCase, ...
    result.completed_iteration_count, ...
    2);

verifyEqual(testCase, ...
    [result.iterations.deficient_cell_count]', ...
    [1; 0]);

verifyEqual(testCase, ...
    [result.iterations.executed_run_count]', ...
    [2; 2]);

verifyTrue(testCase, ...
    isfile(result.paths.summary_json));

verifyTrue(testCase, ...
    isfile(result.paths.iterations_csv));

summary = jsondecode( ...
    fileread(result.paths.summary_json));

verifyEqual(testCase, ...
    string(summary.stop_reason), ...
    "coverage_complete");

verifyTrue(testCase, ...
    logical(summary.coverage_complete));

iteration_table = readtable( ...
    result.paths.iterations_csv, ...
    Delimiter=",", ...
    TextType="string", ...
    VariableNamingRule="preserve");

verifyEqual(testCase, ...
    height(iteration_table), ...
    2);

variable_names = ...
    string(iteration_table.Properties.VariableNames);

verifyTrue(testCase, ...
    ismember("deficient_cell_count", variable_names));

verifyEqual(testCase, ...
    iteration_table.("deficient_cell_count"), ...
    [1; 0]);

clear cleanup

end


function testResumesPersistedIncompleteLoop(testCase)

root = string(tempname);

previous_csv = fullfile(root, "previous.csv");
initial_batch = fullfile(root, "initial_batch");
output_root = fullfile(root, "iterations");
framework_root = fullfile(root, "framework");

mkdir(root);
mkdir(initial_batch);
mkdir(framework_root);

write_table(previous_csv);
write_plan(initial_batch);

cleanup = onCleanup(@() cleanup_root(root));

feat_cfg = struct();

campaign_config = struct();
campaign_config.campaign_name = "resume_test";

first = reqml.campaigns.runAdaptiveCampaignLoop( ...
    previous_csv, ...
    initial_batch, ...
    feat_cfg, ...
    campaign_config, ...
    framework_root, ...
    OutputRoot=output_root, ...
    CampaignId="resume_test", ...
    MaximumIterations=1, ...
    PlannerSeed=200, ...
    PurityEdges=[0.5 0.7 1.0], ...
    DiffusivityEdges=[0 0.5 1.0], ...
    SwsEdges=[1.5 3.0 4.0], ...
    FrequencyEdges=[199 400 601], ...
    ExecuteBatchFunction=@fake_execute, ...
    AdvanceIterationFunction=@fake_advance);

verifyFalse(testCase, first.coverage_complete);

verifyEqual(testCase, ...
    first.completed_iteration_count, ...
    1);

second = reqml.campaigns.runAdaptiveCampaignLoop( ...
    previous_csv, ...
    initial_batch, ...
    feat_cfg, ...
    campaign_config, ...
    framework_root, ...
    OutputRoot=output_root, ...
    CampaignId="resume_test", ...
    MaximumIterations=3, ...
    PlannerSeed=200, ...
    PurityEdges=[0.5 0.7 1.0], ...
    DiffusivityEdges=[0 0.5 1.0], ...
    SwsEdges=[1.5 3.0 4.0], ...
    FrequencyEdges=[199 400 601], ...
    ResumeExistingLoop=true, ...
    ExecuteBatchFunction=@fake_execute, ...
    AdvanceIterationFunction=@fake_advance);

verifyTrue(testCase, second.coverage_complete);

verifyEqual(testCase, ...
    second.stop_reason, ...
    "coverage_complete");

verifyEqual(testCase, ...
    second.completed_iteration_count, ...
    2);

verifyEqual(testCase, ...
    [second.iterations.iteration_index]', ...
    [1; 2]);

verifyEqual(testCase, ...
    [second.iterations.deficient_cell_count]', ...
    [1; 0]);

iteration_table = readtable( ...
    second.paths.iterations_csv, ...
    Delimiter=",", ...
    TextType="string", ...
    VariableNamingRule="preserve");

verifyEqual(testCase, ...
    height(iteration_table), ...
    2);

clear cleanup

end


function testCheckpointsBeforeLaterIterationFailure(testCase)

root = string(tempname);

previous_csv = fullfile(root, "previous.csv");
initial_batch = fullfile(root, "initial_batch");
output_root = fullfile(root, "iterations");
framework_root = fullfile(root, "framework");

mkdir(root);
mkdir(initial_batch);
mkdir(framework_root);

write_table(previous_csv);
write_plan(initial_batch);

cleanup = onCleanup(@() cleanup_root(root));

feat_cfg = struct();

campaign_config = struct();
campaign_config.campaign_name = ...
    "checkpoint_failure_test";

verifyError(testCase, ...
    @() reqml.campaigns.runAdaptiveCampaignLoop( ...
        previous_csv, ...
        initial_batch, ...
        feat_cfg, ...
        campaign_config, ...
        framework_root, ...
        OutputRoot=output_root, ...
        CampaignId="checkpoint_failure_test", ...
        MaximumIterations=3, ...
        PlannerSeed=300, ...
        PurityEdges=[0.5 0.7 1.0], ...
        DiffusivityEdges=[0 0.5 1.0], ...
        SwsEdges=[1.5 3.0 4.0], ...
        FrequencyEdges=[199 400 601], ...
        ExecuteBatchFunction=@fail_on_second_execute, ...
        AdvanceIterationFunction=@fake_advance), ...
    "reqml:IntentionalAdaptiveLoopTestFailure");

state = ...
    reqml.campaigns.loadAdaptiveLoopState( ...
        output_root);

verifyEqual(testCase, ...
    state.completed_iteration_count, ...
    1);

verifyFalse(testCase, ...
    state.coverage_complete);

verifyEqual(testCase, ...
    state.stop_reason, ...
    "in_progress");

verifyEqual(testCase, ...
    state.final_accumulated_campaign_csv, ...
    string(fullfile( ...
        output_root, ...
        "checkpoint_failure_test_iteration_001", ...
        "accumulated_campaign_runs.csv")));

verifyTrue(testCase, ...
    isfolder(state.next_batch_directory));

clear cleanup

end


function execution = fail_on_second_execute( ...
        batch_directory, framework_root, options)

arguments
    batch_directory
    framework_root

    options.Resume (1,1) logical = true
    options.ContinueOnError (1,1) logical = false
end

persistent call_count

if isempty(call_count)
    call_count = 0;
end

call_count = call_count + 1;

if call_count == 2
    call_count = 0;

    error("reqml:IntentionalAdaptiveLoopTestFailure", ...
        "Intentional failure after the first persisted iteration.");
end

execution = fake_execute( ...
    batch_directory, ...
    framework_root, ...
    Resume=options.Resume, ...
    ContinueOnError=options.ContinueOnError);

end


function execution = fake_execute( ...
        batch_directory, simulation_framework_root, options) %#ok<INUSD>

arguments
    batch_directory
    simulation_framework_root

    options.Resume (1,1) logical = true
    options.ContinueOnError (1,1) logical = false
end

csv_path = fullfile( ...
    batch_directory, ...
    "campaign_runs.csv");

write_table(csv_path);

execution = struct();

execution.campaign_count = 1;
execution.run_count = 2;
execution.completed_count = 2;
execution.skipped_count = 0;
execution.failed_count = 0;
execution.success = true;
execution.campaign_csv_files = string(csv_path);

end


function result = fake_advance( ...
        previous_csv, new_csv_files, ...
        feat_cfg, campaign_config, options) %#ok<INUSD>

arguments
    previous_csv
    new_csv_files
    feat_cfg
    campaign_config

    options.OutputDirectory
    options.IterationId
    options.PlannerSeed

    options.PurityEdges
    options.DiffusivityEdges
    options.SwsEdges
    options.FrequencyEdges

    options.MinimumExamples = 500
    options.MinimumIndependentRuns = 5
    options.MinimumSwsBins = 3
    options.MinimumFrequencyBins = 3
    options.MinimumIndependentConditions = 3
    options.MinimumGeometrySeeds = 0

    options.MaximumConditions = 20
    options.RealizationsPerCondition = 2

    options.UseDirectedCenterSelection (1,1) logical = false
    options.CandidateStepPixels (1,1) double = 2
    options.MaximumCentersPerCell (1,1) double = 4
    options.MinimumCenterDistanceFraction (1,1) double = 0.5
    options.MinimumValidFraction (1,1) double = 1
    options.CenterSelectionSeedOffset (1,1) double = 0

    options.ParentCoverageReportHash = ""
    options.ExecutedBatchPlanFile = ""
    options.PreviousDatasetDirectory (1,1) string = ""
end

iteration_directory = ...
    string(options.OutputDirectory);

mkdir(iteration_directory);

dataset_directory = fullfile( ...
    iteration_directory, ...
    "dataset");

[created, message] = mkdir(dataset_directory);

if ~created && ~isfolder(dataset_directory)
    error("reqml:TestDatasetDirectoryCreateFailed", ...
        "Could not create fake dataset directory '%s': %s", ...
        dataset_directory, message);
end

iteration_token = extractAfter( ...
    string(options.IterationId), ...
    "_iteration_");

iteration_number = str2double(iteration_token);

assert( ...
    isfinite(iteration_number) && ...
    iteration_number >= 1 && ...
    iteration_number == fix(iteration_number));

accumulated_csv = fullfile( ...
    iteration_directory, ...
    "accumulated_campaign_runs.csv");

write_table(accumulated_csv);

is_complete = iteration_number >= 2;

if ~is_complete
    next_batch = fullfile( ...
        iteration_directory, ...
        "next_batch");

    mkdir(next_batch);
    write_plan(next_batch);
end

iteration = struct();

iteration.example_count = ...
    10 * iteration_number;

iteration.observed_coverage_cell_count = ...
    2 + iteration_number;

iteration.deficient_cell_count = ...
    double(~is_complete);

iteration.coverage_complete = is_complete;

iteration.planning = struct();
iteration.planning.batch_required = ~is_complete;

result = struct();

result.accumulated_run_count = ...
    2 * iteration_number;

result.iteration = iteration;

result.paths = struct();

result.paths.accumulated_campaign_csv = ...
    string(accumulated_csv);

end


function write_plan(directory)

path_value = fullfile( ...
    directory, ...
    "adaptive_batch_plan.json");

file_id = fopen(path_value, "w");
assert(file_id >= 0);

cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, "{}");

clear cleanup

end


function write_table(path_value)

value = table( ...
    [1; 2], ...
    VariableNames="ordinal");

writetable(value, path_value);

end


function cleanup_root(root)

if isfolder(root)
    rmdir(root, "s");
end

end
