function tests = test_compute_patch_coverage
%TEST_COMPUTE_PATCH_COVERAGE Test the complete coverage workflow.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testComputesCompleteCoverageReport(testCase)

examples = make_examples();

report = reqml.coverage.computePatchCoverage( ...
    examples, ...
    PurityEdges=[0.5 0.7 0.9 1.0], ...
    DiffusivityEdges=[0 0.4 0.7 1.0], ...
    SwsEdges=[1.5 2.5 3.5 4.1], ...
    FrequencyEdges=[199 350 450 550 601], ...
    MinimumExamples=2, ...
    MinimumIndependentRuns=2, ...
    MinimumSwsBins=2, ...
    MinimumFrequencyBins=2, ...
    MinimumIndependentConditions=2);

verifyEqual(testCase, ...
    report.schema_name, ...
    "reqml_patch_coverage_report");

verifyEqual(testCase, report.example_count, 6);

verifyEqual(testCase, ...
    report.valid_coverage_example_count, ...
    6);

verifyEqual(testCase, ...
    report.observed_coverage_cell_count, ...
    6);

verifyEqual(testCase, ...
    report.coverage_cell_count, ...
    108);

verifyEqual(testCase, ...
    report.deficient_cell_count, ...
    108);

verifyFalse(testCase, report.coverage_complete);

verifyEqual(testCase, ...
    report.observed_summary.example_count, ...
    ones(6,1));

verifyEqual(testCase, ...
    report.observed_summary.independent_condition_count, ...
    ones(6,1));

verifyEqual(testCase, ...
    nnz(report.summary.example_count > 0), ...
    6);

verifyEqual(testCase, ...
    nnz(report.summary.example_count == 0), ...
    102);

end


function testReportsCoverageDeficits(testCase)

examples = make_examples();

report = reqml.coverage.computePatchCoverage( ...
    examples, ...
    PurityEdges=[0.5 0.7 0.9 1.0], ...
    DiffusivityEdges=[0 0.4 0.7 1.0], ...
    SwsEdges=[1.5 2.5 3.5 4.1], ...
    FrequencyEdges=[199 350 450 550 601], ...
    MinimumExamples=3, ...
    MinimumIndependentRuns=3, ...
    MinimumSwsBins=2, ...
    MinimumFrequencyBins=2, ...
    MinimumIndependentConditions=3);

verifyFalse(testCase, report.coverage_complete);

verifyEqual(testCase, ...
    report.deficient_cell_count, ...
    108);

observed = report.deficits.example_count > 0;
unobserved = report.deficits.example_count == 0;

verifyEqual(testCase, nnz(observed), 6);
verifyEqual(testCase, nnz(unobserved), 102);



end


function testTracksOutOfRangeExamples(testCase)

examples = make_examples();
examples.truth_material_purity(1) = 0.25;

report = reqml.coverage.computePatchCoverage( ...
    examples, ...
    PurityEdges=[0.5 0.7 0.9 1.0], ...
    DiffusivityEdges=[0 0.4 0.7 1.0], ...
    SwsEdges=[1.5 2.5 3.5 4.1], ...
    FrequencyEdges=[199 350 450 550 601], ...
    MinimumExamples=1, ...
    MinimumIndependentRuns=1, ...
    MinimumSwsBins=1, ...
    MinimumFrequencyBins=1, ...
    MinimumIndependentConditions=1);

verifyEqual(testCase, ...
    report.valid_coverage_example_count, ...
    5);

verifyEqual(testCase, ...
    report.invalid_coverage_example_count, ...
    1);

verifyFalse(testCase, ...
    report.assigned_examples.coverage_valid(1));

end


function examples = make_examples()

examples = table();

examples.truth_material_purity = ...
    [0.55; 0.60; 0.75; 0.80; 0.95; 1.00];

examples.campaign_angular_entropy = ...
    [0.20; 0.25; 0.50; 0.55; 0.85; 0.90];

examples.truth_cs_center_m_s = ...
    [1.8; 2.8; 2.2; 3.2; 3.0; 4.0];

examples.campaign_frequency_hz = ...
    [200; 400; 300; 500; 400; 600];

examples.campaign_run_id = ...
    ["run_1"; "run_2"; ...
     "run_3"; "run_4"; ...
     "run_5"; "run_6"];

examples.campaign_design_id = ...
    ["design_1"; "design_2"; ...
     "design_3"; "design_4"; ...
     "design_5"; "design_6"];

end


function testUnobservedCellsAreReportedAsDeficits(testCase)

examples = make_examples();

report = reqml.coverage.computePatchCoverage( ...
    examples, ...
    PurityEdges=[0.5 0.7 0.9 1.0], ...
    DiffusivityEdges=[0 0.4 0.7 1.0], ...
    SwsEdges=[1.5 2.5 3.5 4.1], ...
    FrequencyEdges=[199 350 450 550 601], ...
    MinimumExamples=1, ...
    MinimumIndependentRuns=1, ...
    MinimumSwsBins=1, ...
    MinimumFrequencyBins=1, ...
    MinimumIndependentConditions=1);

verifyEqual(testCase, ...
    report.coverage_cell_count, ...
    108);

verifyEqual(testCase, ...
    report.observed_coverage_cell_count, ...
    6);

verifyEqual(testCase, ...
    report.deficient_cell_count, ...
    102);

verifyTrue(testCase, ...
    all(report.deficits.example_count == 0));

verifyTrue(testCase, ...
    all(report.deficits.example_deficit == 1));

end
