function tests = test_materialize_nominal_angular_field
%TEST_MATERIALIZE_NOMINAL_ANGULAR_FIELD Test Dnom materialization.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testReproducesSampledCoverage(testCase)

stream = RandStream("Threefry", Seed=4101);

field = reqml.campaigns.materializeNominalAngularField( ...
    stream, ...
    [0.20 0.40], ...
    MaximumDirectionCount=128);

reconstructed = ...
    (field.direction_count / 128) * ...
    (field.solid_angle_sr / (4*pi));

verifyEqual(testCase, ...
    reconstructed, ...
    field.nominal_angular_coverage, ...
    AbsTol=1e-12);

verifyGreaterThanOrEqual(testCase, ...
    field.nominal_angular_coverage, ...
    0.20);

verifyLessThanOrEqual(testCase, ...
    field.nominal_angular_coverage, ...
    0.40);

verifyGreaterThanOrEqual(testCase, ...
    field.direction_count, ...
    ceil(field.nominal_angular_coverage * 128));

verifyLessThanOrEqual(testCase, ...
    field.solid_angle_sr, ...
    4*pi);

end


function testMaterializationIsReproducible(testCase)

a = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=5201), ...
    [0.05 0.25]);

b = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=5201), ...
    [0.05 0.25]);

verifyEqual(testCase, a, b);

end


function testMaximumCoverageRequiresMaximumConfiguration(testCase)

field = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=6301), ...
    [1 1], ...
    MaximumDirectionCount=128);

verifyEqual(testCase, field.direction_count, 128);
verifyEqual(testCase, field.solid_angle_sr, 4*pi, ...
    AbsTol=1e-12);
verifyEqual(testCase, ...
    field.nominal_angular_coverage, ...
    1, ...
    AbsTol=1e-12);

end


function testAllowsVeryDirectionalFields(testCase)

field = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=7401), ...
    [0 0.01], ...
    MaximumDirectionCount=128, ...
    MinimumSolidAngleSr=0.01);

verifyGreaterThan(testCase, ...
    field.nominal_angular_coverage, ...
    0);

verifyLessThanOrEqual(testCase, ...
    field.nominal_angular_coverage, ...
    0.01);

verifyGreaterThanOrEqual(testCase, ...
    field.solid_angle_sr, ...
    0.01);

end


function testMaterializesVeryLowDnomWithoutClamping(testCase)

stream = RandStream( ...
    "Threefry", ...
    Seed=42001);

target_range = [0, 0.01];

field = ...
    reqml.campaigns.materializeNominalAngularField( ...
        stream, ...
        target_range, ...
        MaximumDirectionCount=128, ...
        MinimumSolidAngleSr=0.01, ...
        MaximumSolidAngleSr=4*pi);

achieved = ...
    (field.direction_count / ...
        field.maximum_direction_count) * ...
    (field.solid_angle_sr / (4*pi));

verifyGreaterThanOrEqual(testCase, ...
    achieved, ...
    target_range(1));

verifyLessThanOrEqual(testCase, ...
    achieved, ...
    target_range(2));

verifyGreaterThanOrEqual(testCase, ...
    field.solid_angle_sr, ...
    0.01);

verifyLessThanOrEqual(testCase, ...
    field.solid_angle_sr, ...
    4*pi);

verifyEqual(testCase, ...
    field.nominal_angular_coverage, ...
    achieved, ...
    AbsTol=1e-12);

end


function testLowDnomAlwaysUsesFeasibleDirectionCount(testCase)

target_range = [0, 0.01];

for seed = 1:100
    field = ...
        reqml.campaigns.materializeNominalAngularField( ...
            RandStream("Threefry", Seed=seed), ...
            target_range, ...
            MaximumDirectionCount=128, ...
            MinimumSolidAngleSr=0.01, ...
            MaximumSolidAngleSr=4*pi);

    reconstructed = ...
        (field.direction_count / ...
            field.maximum_direction_count) * ...
        (field.solid_angle_sr / ...
            field.maximum_solid_angle_sr);

    verifyEqual(testCase, ...
        reconstructed, ...
        field.nominal_angular_coverage, ...
        AbsTol=1e-12);

    verifyGreaterThanOrEqual(testCase, ...
        field.solid_angle_sr, ...
        0.01);

    verifyLessThanOrEqual(testCase, ...
        field.solid_angle_sr, ...
        4*pi);

    verifyGreaterThanOrEqual(testCase, ...
        field.nominal_angular_coverage, ...
        target_range(1));

    verifyLessThanOrEqual(testCase, ...
        field.nominal_angular_coverage, ...
        target_range(2));
end

end



function testSeededInPlaneAxisIsReproducible(testCase)

a = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=1234), ...
    [0.2 0.2], ...
    AxisMode="seeded_uniform_in_plane", ...
    InPlanePolicy="fixed_fraction", ...
    InPlaneFraction=0.25);

b = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=1234), ...
    [0.2 0.2], ...
    AxisMode="seeded_uniform_in_plane", ...
    InPlanePolicy="fixed_fraction", ...
    InPlaneFraction=0.25);

verifyEqual(testCase, a.axis_xyz, b.axis_xyz, AbsTol=1e-12);
verifyEqual(testCase, a.axis_angle_rad, b.axis_angle_rad, AbsTol=1e-12);
verifyEqual(testCase, a.axis_mode, "seeded_uniform_in_plane");
verifyEqual(testCase, a.in_plane_policy, "fixed_fraction");
verifyEqual(testCase, a.axis_xyz(2), 0, AbsTol=1e-12);
verifyEqual(testCase, norm(a.axis_xyz), 1, AbsTol=1e-12);

end


function testDifferentSeedsChangeAngularAxis(testCase)

a = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=1234), ...
    [0.2 0.2], ...
    AxisMode="seeded_uniform_in_plane");

b = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=5678), ...
    [0.2 0.2], ...
    AxisMode="seeded_uniform_in_plane");

verifyGreaterThan(testCase, norm(a.axis_xyz - b.axis_xyz), 1e-6);
verifyEqual(testCase, a.axis_xyz(2), 0, AbsTol=1e-12);
verifyEqual(testCase, b.axis_xyz(2), 0, AbsTol=1e-12);

end


function testFixedFractionControlsInPlaneCount(testCase)

field = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=9101), ...
    [0.3 0.3], ...
    InPlanePolicy="fixed_fraction", ...
    InPlaneFraction=0.25);

expected = min( ...
    field.direction_count, ...
    max(1, round(0.25 * field.direction_count)));

verifyEqual(testCase, field.in_plane_count, expected);
verifyEqual(testCase, field.in_plane_fraction, 0.25);

end


function testLegacyAngularDefaultsRemainAvailable(testCase)

field = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=9201), ...
    [0.3 0.3]);

verifyEqual(testCase, field.axis_mode, "fixed");
verifyEqual(testCase, field.axis_xyz, [1 0 0], AbsTol=1e-12);
verifyEqual(testCase, field.in_plane_policy, "legacy_sqrt");
verifyEqual(testCase, ...
    field.in_plane_count, ...
    min(field.direction_count, ...
        max(1, round(sqrt(field.direction_count)))));

end



function testRejectsInvalidRange(testCase)

verifyError(testCase, ...
    @() reqml.campaigns.materializeNominalAngularField( ...
        RandStream("Threefry", Seed=1), ...
        [-0.1 0.5]), ...
    "reqml:InvalidNominalAngularCoverageRange");

end
