function tests = test_run_adaptive_campaign_from_config
%TEST_RUN_ADAPTIVE_CAMPAIGN_FROM_CONFIG Test JSON campaign runner.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testLoadsAndTranslatesConfig(testCase)

root = string(tempname);
mkdir(root);

cleanup = onCleanup(@() cleanup_root(root));

previous_csv = fullfile(root, "previous.csv");
initial_batch = fullfile(root, "initial_batch");
framework_root = fullfile(root, "framework");
simulation_output = fullfile(root, "simulation_output");

mkdir(initial_batch);
mkdir(framework_root);
mkdir(simulation_output);

writetable( ...
    table([1;2], VariableNames="ordinal"), ...
    previous_csv);

base_directory = fullfile(root, "base_configs");
mkdir(base_directory);

families = [
    "homogeneous"
    "bilayer"
    "circular_inclusion"
    ];

for family = families'
    write_text( ...
        fullfile(base_directory, family + ".json"), ...
        "{}");
end

config = make_config( ...
    previous_csv, ...
    initial_batch, ...
    framework_root, ...
    simulation_output, ...
    base_directory);

config_file = fullfile(root, "config.json");

write_text( ...
    config_file, ...
    jsonencode(config, PrettyPrint=true));

result = ...
    reqml.campaigns.runAdaptiveCampaignFromConfig( ...
        config_file, ...
        RunLoopFunction=@fake_loop);

verifyEqual(testCase, ...
    result.campaign_id, ...
    "json_test");

verifyEqual(testCase, ...
    result.maximum_iterations, ...
    4);

verifyEqual(testCase, ...
    result.minimum_examples, ...
    25);

verifyEqual(testCase, ...
    result.diffusivity_edges, ...
    [0 0.1 0.5 1]);

verifyTrue(testCase, ...
    result.resume_existing_loop);

verifyEqual(testCase, ...
    string(result.campaign_config.backend), ...
    "swsynth");

verifyEqual(testCase, ...
    string(result.config_file), ...
    string(config_file));

clear cleanup

end


function result = fake_loop( ...
        previous_csv, initial_batch, ...
        feat_cfg, campaign_config, ...
        framework_root, options) %#ok<INUSD>

arguments
    previous_csv
    initial_batch
    feat_cfg
    campaign_config
    framework_root

    options.OutputRoot
    options.CampaignId
    options.MaximumIterations
    options.PlannerSeed

    options.PurityEdges
    options.DiffusivityEdges
    options.SwsEdges
    options.FrequencyEdges

    options.MinimumExamples
    options.MinimumIndependentRuns
    options.MinimumSwsBins
    options.MinimumFrequencyBins
    options.MinimumIndependentConditions
    options.MinimumGeometrySeeds

    options.MaximumConditions
    options.RealizationsPerCondition

    options.UseDirectedCenterSelection (1,1) logical = false
    options.CandidateStepPixels (1,1) double = 2
    options.MaximumCentersPerCell (1,1) double = 4
    options.MinimumCenterDistanceFraction (1,1) double = 0.5
    options.MinimumValidFraction (1,1) double = 1
    options.CenterSelectionSeedOffset (1,1) double = 0
    options.CenterSelectionMode (1,1) string = "default"
    options.MaximumCentersPerRun (1,1) double = 12
    options.MaximumCentersPerCellPerRun (1,1) double = 2
    options.MinimumCenterSeparationFraction (1,1) double = 0.75
    options.UseSampleParfor (1,1) logical = false

    options.Resume
    options.ContinueOnError
    options.ResumeExistingLoop
end

result = struct();

result.campaign_id = string(options.CampaignId);

result.maximum_iterations = ...
    options.MaximumIterations;

result.minimum_examples = ...
    options.MinimumExamples;

result.diffusivity_edges = ...
    options.DiffusivityEdges;

result.resume_existing_loop = ...
    options.ResumeExistingLoop;

result.use_sample_parfor = ...
    options.UseSampleParfor;

result.campaign_config = ...
    campaign_config;

end


function testSchema11GeneratesBootstrapAndStartsCleanLoop(testCase)

root = string(testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture).Folder);

framework_root = fullfile(root, "framework");
mkdir(fullfile(framework_root, "src"));

simulation_output = fullfile(root, "simulation_output");
mkdir(simulation_output);

base_directory = fullfile(root, "base_configs");
mkdir(base_directory);

write_text( ...
    fullfile(base_directory, "homogeneous.json"), ...
    "{}");

write_text( ...
    fullfile(base_directory, "bilayer.json"), ...
    '{"domain":{"Lx_m":0.05,"Lz_m":0.05,"dx_m":0.0005,"dz_m":0.0005}}');

write_text( ...
    fullfile(base_directory, ...
        "circular_inclusion.json"), ...
    "{}");

config = make_schema_11_config( ...
    root, ...
    framework_root, ...
    simulation_output, ...
    base_directory);

config_path = fullfile( ...
    root, ...
    "adaptive_schema_11.json");

write_text( ...
    config_path, ...
    jsonencode(config, PrettyPrint=true));

result = ...
    reqml.campaigns.runAdaptiveCampaignFromConfig( ...
        config_path, ...
        GenerateBootstrapFunction= ...
            @fake_generate_bootstrap, ...
        RunLoopFunction=@fake_schema_11_loop);

verifyEqual(testCase, ...
    result.campaign_id, ...
    "json_test_4d");

verifyEqual(testCase, ...
    result.previous_csv, ...
    "");

verifyEqual(testCase, ...
    result.initial_batch_directory, ...
    fullfile( ...
        config.paths.output_root, ...
        config.bootstrap.output_subdirectory));

verifyFalse(testCase, ...
    result.resume_existing_loop);

verifyTrue(testCase, ...
    isfield(result, "bootstrap"));

verifyEqual(testCase, ...
    result.bootstrap.schema_name, ...
    "fake_bootstrap");

verifyEqual(testCase, ...
    result.bootstrap.batch_id, ...
    string(config.bootstrap.batch_id));

verifyEqual(testCase, ...
    result.bootstrap.condition_count, ...
    25);

verifyEqual(testCase, ...
    result.bootstrap.run_count, ...
    50);

verifyEqual(testCase, result.center_selection_mode, ...
    "analytic_target_plus_deficit_aware_centers");

end


function result = fake_generate_bootstrap( ...
        coverage, campaign_config, varargin)

options = parse_name_value_arguments(varargin);

output_directory = ...
    string(options.OutputDirectory);

if ~isfolder(output_directory)
    mkdir(output_directory);
end

write_text( ...
    fullfile( ...
        output_directory, ...
        "adaptive_batch_plan.json"), ...
    "{}");

result = struct();

result.schema_name = "fake_bootstrap";
result.batch_id = string(options.BatchId);
result.planner_seed = double(options.PlannerSeed);
result.condition_count = 25;
result.run_count = 50;

result.coverage = coverage;
result.campaign_config = campaign_config;

result.paths = struct( ...
    "plan", ...
    fullfile( ...
        output_directory, ...
        "adaptive_batch_plan.json"));

end


function result = fake_schema_11_loop( ...
        previous_csv, initial_batch_directory, ...
        ~, campaign_config, ~, varargin)

options = parse_name_value_arguments(varargin);

result = struct();

result.campaign_id = ...
    string(options.CampaignId);

result.previous_csv = ...
    string(previous_csv);

result.initial_batch_directory = ...
    string(initial_batch_directory);

result.resume_existing_loop = ...
    logical(options.ResumeExistingLoop);

result.maximum_iterations = ...
    double(options.MaximumIterations);

result.center_selection_mode = string(options.CenterSelectionMode);

result.campaign_config = ...
    campaign_config;

end


function config = make_schema_11_config( ...
        root, framework_root, ...
        simulation_output, base_directory)

config = struct();

config.schema_name = ...
    "reqml_adaptive_campaign_config";

config.schema_version = "1.1";
config.campaign_id = "json_test_4d";

config.paths = struct( ...
    "output_root", ...
        fullfile(root, "loop_output"), ...
    "simulation_framework_root", ...
        framework_root);

config.bootstrap = struct( ...
    "output_subdirectory", ...
        "initial_batch", ...
    "batch_id", ...
        "json_test_4d_bootstrap", ...
    "planner_seed", ...
        42001, ...
    "realizations_per_condition", ...
        2, ...
    "geometry_families", ...
        [ ...
            "homogeneous"
            "bilayer"
            "circular_inclusion"
        ], ...
    "purity_cycle_stride", ...
        1, ...
    "diffusivity_cycle_stride", ...
        2);

config.simulation = struct();

config.simulation.backend = "swsynth";

config.simulation.output_directory = ...
    simulation_output;

config.simulation.base_config_mapping = struct( ...
    "homogeneous", ...
        fullfile(base_directory, "homogeneous.json"), ...
    "bilayer", ...
        fullfile(base_directory, "bilayer.json"), ...
    "circular_inclusion", ...
        fullfile(base_directory, ...
            "circular_inclusion.json"));

config.coverage = struct( ...
    "purity_edges", ...
        [0.5 0.7 0.9 0.98 1.0], ...
    "nominal_angular_coverage_edges", ...
        [0 0.01 0.05 0.2 0.5 1.0], ...
    "sws_edges_m_s", ...
        [1.5 2.0 2.5 3.0 3.5 4.0], ...
    "frequency_edges_hz", ...
        [199 250 350 450 550 601]);

config.requirements = struct( ...
    "minimum_examples", 4, ...
    "minimum_independent_runs", 2, ...
    "minimum_independent_conditions", 1, ...
    "minimum_sws_bins", 0, ...
    "minimum_frequency_bins", 0, ...
    "minimum_geometry_seeds", 0);

config.planning = struct( ...
    "maximum_conditions", 12, ...
    "realizations_per_condition", 2, ...
    "training_geometry_mode", "analytic_bilayer");

config.execution = struct( ...
    "maximum_iterations", 100, ...
    "planner_seed", 43001, ...
    "resume_runs", true, ...
    "continue_on_error", false, ...
    "resume_existing_loop", true);

config.center_selection = struct( ...
    "mode", "analytic_target_plus_deficit_aware_centers", ...
    "candidate_step_pixels", 2, ...
    "maximum_centers_per_run", 12, ...
    "maximum_centers_per_cell_per_run", 2, ...
    "minimum_center_separation_fraction", 0.75, ...
    "minimum_valid_fraction", 1, ...
    "seed_offset", 0);

end


function options = parse_name_value_arguments(arguments)

if mod(numel(arguments), 2) ~= 0
    error( ...
        "reqml:InvalidTestNameValueArguments", ...
        "Expected name-value pairs.");
end

options = struct();

for index = 1:2:numel(arguments)
    name = string(arguments{index});
    options.(name) = arguments{index + 1};
end

end


function config = make_config( ...
        previous_csv, initial_batch, ...
        framework_root, simulation_output, ...
        base_directory)

config = struct();

config.schema_name = ...
    "reqml_adaptive_campaign_config";

config.schema_version = "1.0";
config.campaign_id = "json_test";

config.paths = struct( ...
    "previous_campaign_csv", previous_csv, ...
    "initial_batch_directory", initial_batch, ...
    "output_root", fullfile( ...
        fileparts(previous_csv), "loop_output"), ...
    "simulation_framework_root", framework_root);

config.simulation = struct();

config.simulation.backend = "swsynth";

config.simulation.output_directory = ...
    simulation_output;

config.simulation.base_config_mapping = struct( ...
    "homogeneous", ...
        fullfile(base_directory, "homogeneous.json"), ...
    "bilayer", ...
        fullfile(base_directory, "bilayer.json"), ...
    "circular_inclusion", ...
        fullfile(base_directory, ...
            "circular_inclusion.json"));

config.coverage = struct( ...
    "purity_edges", ...
        [0.5 0.7 0.9 1.0], ...
    "nominal_angular_coverage_edges", ...
        [0 0.1 0.5 1.0], ...
    "sws_edges_m_s", ...
        [1.5 2.5 4.0], ...
    "frequency_edges_hz", ...
        [199 400 601]);

config.requirements = struct( ...
    "minimum_examples", 25, ...
    "minimum_independent_runs", 2, ...
    "minimum_independent_conditions", 2, ...
    "minimum_sws_bins", 2, ...
    "minimum_frequency_bins", 2, ...
    "minimum_geometry_seeds", 0);

config.planning = struct( ...
    "maximum_conditions", 8, ...
    "realizations_per_condition", 2);

config.execution = struct( ...
    "maximum_iterations", 4, ...
    "planner_seed", 40001, ...
    "resume_runs", true, ...
    "continue_on_error", false, ...
    "resume_existing_loop", true);

end


function write_text(path_value, content)

file_id = fopen(path_value, "w");
assert(file_id >= 0);

cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, "%s", content);
clear cleanup

end


function cleanup_root(root)

if isfolder(root)
    rmdir(root, "s");
end

end
