function tests = test_make_bootstrap_condition_requests
%TEST_MAKE_BOOTSTRAP_CONDITION_REQUESTS

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testCreatesOneRequestPerSwsFrequencyBlock(testCase)

coverage = make_scientific_coverage();

requests = ...
    reqml.campaigns.makeBootstrapConditionRequests( ...
        coverage, ...
        BatchId="bootstrap_test", ...
        PlannerSeed=42001, ...
        RealizationsPerCondition=2);

verifyEqual(testCase, numel(requests), 25);

pairs = [
    [requests.sws_bin]', ...
    [requests.frequency_bin]'
    ];

verifyEqual(testCase, ...
    size(unique(pairs, "rows"), 1), ...
    25);

verifyEqual(testCase, ...
    unique([requests.sws_bin]'), ...
    (1:5)');

verifyEqual(testCase, ...
    unique([requests.frequency_bin]'), ...
    (1:5)');

verifyEqual(testCase, ...
    [requests.realization_count]', ...
    repmat(2, 25, 1));

verifyEqual(testCase, ...
    [requests.planner_seed]', ...
    repmat(42001, 25, 1));

end


function testUsesExactConfiguredPhysicalRanges(testCase)

coverage = make_scientific_coverage();

requests = ...
    reqml.campaigns.makeBootstrapConditionRequests( ...
        coverage, ...
        BatchId="bootstrap_test");

sws_edges = coverage.sws_edges_m_s;
frequency_edges = coverage.frequency_edges_hz;
purity_edges = coverage.purity_edges;

dnom_edges = ...
    coverage.nominal_angular_coverage_edges;

for index = 1:numel(requests)
    request = requests(index);

    verifyEqual(testCase, ...
        request.target_sws_range_m_s, ...
        sws_edges( ...
            request.sws_bin: ...
            request.sws_bin + 1));

    verifyEqual(testCase, ...
        request.target_frequency_range_hz, ...
        frequency_edges( ...
            request.frequency_bin: ...
            request.frequency_bin + 1));

    verifyEqual(testCase, ...
        request.purity_range, ...
        purity_edges( ...
            request.purity_bin: ...
            request.purity_bin + 1));

    verifyEqual(testCase, ...
        request.diffusivity_range, ...
        dnom_edges( ...
            request.diffusivity_bin: ...
            request.diffusivity_bin + 1));

    verifyEqual(testCase, ...
        request.nominal_angular_coverage_range, ...
        request.diffusivity_range);
end

end


function testDistributionIsDeterministic(testCase)

coverage = make_scientific_coverage();

a = reqml.campaigns.makeBootstrapConditionRequests( ...
    coverage, ...
    BatchId="bootstrap_test", ...
    PlannerSeed=42001);

b = reqml.campaigns.makeBootstrapConditionRequests( ...
    coverage, ...
    BatchId="bootstrap_test", ...
    PlannerSeed=42001);

verifyEqual(testCase, a, b);

expected_geometry = repmat( ...
    [ ...
        "homogeneous"
        "bilayer"
        "circular_inclusion"
    ], ...
    9, ...
    1);

expected_geometry = expected_geometry(1:25);

verifyEqual(testCase, ...
    string({a.geometry_family})', ...
    expected_geometry);

end


function testRequestsCanBeMaterialized(testCase)

coverage = make_scientific_coverage();

requests = ...
    reqml.campaigns.makeBootstrapConditionRequests( ...
        coverage, ...
        BatchId="bootstrap_test", ...
        PlannerSeed=42001);

conditions = ...
    reqml.campaigns.materializePhysicalConditions( ...
        requests, ...
        PlannerSeed=42001);

verifyEqual(testCase, numel(conditions), 25);

verifyTrue(testCase, ...
    all([conditions.realization_count]' == 2));

verifyEqual(testCase, ...
    string({conditions.condition_id})', ...
    string({requests.condition_id})');

end


function coverage = make_scientific_coverage()

coverage = struct();

coverage.sws_edges_m_s = ...
    [1.5 2.0 2.5 3.0 3.5 4.0];

coverage.frequency_edges_hz = ...
    [199 250 350 450 550 601];

coverage.purity_edges = ...
    [0.5 0.7 0.9 0.98 1.0];

coverage.nominal_angular_coverage_edges = ...
    [0 0.01 0.05 0.20 0.50 1.0];

end
