function tests = test_find_coverage_deficits
%TEST_FIND_COVERAGE_DEFICITS Test coverage stopping requirements.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testReturnsOnlyIncompleteCells(testCase)

summary = make_summary();

deficits = reqml.coverage.findCoverageDeficits( ...
    summary, ...
    MinimumExamples=100, ...
    MinimumIndependentRuns=5, ...
    MinimumSwsBins=3, ...
    MinimumFrequencyBins=3);

verifyEqual(testCase, height(deficits), 2);

verifyEqual(testCase, ...
    deficits.purity_bin, ...
    [2; 3]);

verifyEqual(testCase, ...
    deficits.example_deficit, ...
    [60; 0]);

verifyEqual(testCase, ...
    deficits.independent_run_deficit, ...
    [3; 1]);

verifyEqual(testCase, ...
    deficits.sws_bin_deficit, ...
    [2; 0]);

verifyEqual(testCase, ...
    deficits.frequency_bin_deficit, ...
    [2; 0]);

verifyFalse(testCase, any(deficits.coverage_complete));

end


function testReturnsEmptyWhenCoverageIsComplete(testCase)

summary = make_summary();

deficits = reqml.coverage.findCoverageDeficits( ...
    summary, ...
    MinimumExamples=20, ...
    MinimumIndependentRuns=2, ...
    MinimumSwsBins=1, ...
    MinimumFrequencyBins=1);

verifyEqual(testCase, height(deficits), 0);

end


function testRequiresOptionalDiversityColumns(testCase)

summary = make_summary();

verifyError(testCase, ...
    @() reqml.coverage.findCoverageDeficits( ...
        summary, ...
        MinimumIndependentConditions=2), ...
    "reqml:MissingCoverageDiversityVariable");

verifyError(testCase, ...
    @() reqml.coverage.findCoverageDeficits( ...
        summary, ...
        MinimumGeometrySeeds=2), ...
    "reqml:MissingCoverageDiversityVariable");

end


function testUsesOptionalDiversityColumns(testCase)

summary = make_summary();

summary.independent_condition_count = [6; 1; 4];
summary.geometry_seed_count = [5; 1; 2];

deficits = reqml.coverage.findCoverageDeficits( ...
    summary, ...
    MinimumExamples=20, ...
    MinimumIndependentRuns=2, ...
    MinimumSwsBins=1, ...
    MinimumFrequencyBins=1, ...
    MinimumIndependentConditions=3, ...
    MinimumGeometrySeeds=3);

verifyEqual(testCase, height(deficits), 2);

verifyEqual(testCase, ...
    deficits.purity_bin, ...
    [2; 3]);

verifyEqual(testCase, ...
    deficits.independent_condition_deficit, ...
    [2; 0]);

verifyEqual(testCase, ...
    deficits.geometry_seed_deficit, ...
    [2; 1]);

end


function summary = make_summary()

summary = table();

summary.purity_bin = [1; 2; 3];
summary.diffusivity_bin = [1; 2; 3];

summary.purity_label = ...
    ["[0.5,0.7)"; "[0.7,0.9)"; "[0.9,1]"];

summary.diffusivity_label = ...
    ["[0,0.4)"; "[0.4,0.7)"; "[0.7,1]"];

summary.example_count = [120; 40; 150];
summary.independent_run_count = [6; 2; 4];
summary.sws_bin_count = [4; 1; 3];
summary.frequency_bin_count = [4; 1; 3];

end
