function tests = test_advance_adaptive_iteration_bootstrap
%TEST_ADVANCE_ADAPTIVE_ITERATION_BOOTSTRAP

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testAcceptsEmptyPreviousCsvForBootstrap(testCase)

root = string(testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture).Folder);

new_csv_a = fullfile(root, "campaign_a.csv");
new_csv_b = fullfile(root, "campaign_b.csv");

write_campaign_csv( ...
    new_csv_a, ...
    ["run_a_1"; "run_a_2"], ...
    ["condition_a"; "condition_a"]);

write_campaign_csv( ...
    new_csv_b, ...
    ["run_b_1"; "run_b_2"], ...
    ["condition_b"; "condition_b"]);

feat_cfg = struct();
campaign_config = struct();

result = ...
    reqml.campaigns.advanceAdaptiveIteration( ...
        "", ...
        [new_csv_a; new_csv_b], ...
        feat_cfg, ...
        campaign_config, ...
        OutputDirectory=fullfile(root, "iteration_001"), ...
        IterationId="bootstrap_iteration_001", ...
        PlannerSeed=101, ...
        PurityEdges=[0.5 0.7 1.0], ...
        DiffusivityEdges=[0 0.5 1.0], ...
        SwsEdges=[1.5 2.5 4.0], ...
        FrequencyEdges=[199 400 601], ...
        MinimumExamples=1, ...
        MinimumIndependentRuns=1, ...
        MinimumIndependentConditions=1, ...
        MaximumConditions=1, ...
        RealizationsPerCondition=1, ...
        RunIterationFunction=@fake_run_iteration);

verifyEqual(testCase, ...
    result.previous_run_count, ...
    0);

verifyEqual(testCase, ...
    result.new_input_file_count, ...
    2);

verifyEqual(testCase, ...
    result.accumulated_run_count, ...
    4);

verifyEqual(testCase, ...
    result.duplicate_run_count, ...
    0);

verifyTrue(testCase, ...
    isfile(result.paths.accumulated_campaign_csv));

accumulated = readtable( ...
    result.paths.accumulated_campaign_csv, ...
    Delimiter=",", ...
    TextType="string");

verifyEqual(testCase, ...
    string(accumulated.run_id), ...
    ["run_a_1"; "run_a_2"; "run_b_1"; "run_b_2"]);

end


function result = fake_run_iteration( ...
        accumulated_csv, ~, ~, varargin)

options = parse_name_value_arguments(varargin);

result = struct();

result.schema_name = ...
    "fake_adaptive_iteration";

result.iteration_id = ...
    string(options.IterationId);

result.example_count = 4;
result.observed_coverage_cell_count = 4;
result.deficient_cell_count = 1;
result.coverage_complete = false;

result.planning = struct( ...
    "batch_required", false);

result.paths = struct();

result.paths.accumulated_source_csv = ...
    string(accumulated_csv);

end


function options = parse_name_value_arguments(arguments)

if mod(numel(arguments), 2) ~= 0
    error( ...
        "reqml:InvalidTestNameValueArguments", ...
        "Expected name-value argument pairs.");
end

options = struct();

for index = 1:2:numel(arguments)
    name = string(arguments{index});
    value = arguments{index + 1};

    options.(name) = value;
end

end


function write_campaign_csv( ...
        path_value, run_ids, condition_ids)

table_value = table();

table_value.run_id = run_ids;
table_value.condition_id = condition_ids;

table_value.sample_file = compose( ...
    "%s.mat", ...
    run_ids);

writetable( ...
    table_value, ...
    path_value, ...
    FileType="text", ...
    Delimiter=",");

end
