function tests = test_materialize_nominal_angular_field
%TEST_MATERIALIZE_NOMINAL_ANGULAR_FIELD Test Dnom materialization.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testReproducesSampledCoverage(testCase)

stream = RandStream("Threefry", Seed=4101);

field = reqml.campaigns.materializeNominalAngularField( ...
    stream, ...
    [0.20 0.40], ...
    MaximumDirectionCount=128);

reconstructed = ...
    (field.direction_count / 128) * ...
    (field.solid_angle_sr / (4*pi));

verifyEqual(testCase, ...
    reconstructed, ...
    field.nominal_angular_coverage, ...
    AbsTol=1e-12);

verifyGreaterThanOrEqual(testCase, ...
    field.nominal_angular_coverage, ...
    0.20);

verifyLessThanOrEqual(testCase, ...
    field.nominal_angular_coverage, ...
    0.40);

verifyGreaterThanOrEqual(testCase, ...
    field.direction_count, ...
    ceil(field.nominal_angular_coverage * 128));

verifyLessThanOrEqual(testCase, ...
    field.solid_angle_sr, ...
    4*pi);

end


function testMaterializationIsReproducible(testCase)

a = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=5201), ...
    [0.05 0.25]);

b = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=5201), ...
    [0.05 0.25]);

verifyEqual(testCase, a, b);

end


function testMaximumCoverageRequiresMaximumConfiguration(testCase)

field = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=6301), ...
    [1 1], ...
    MaximumDirectionCount=128);

verifyEqual(testCase, field.direction_count, 128);
verifyEqual(testCase, field.solid_angle_sr, 4*pi, ...
    AbsTol=1e-12);
verifyEqual(testCase, ...
    field.nominal_angular_coverage, ...
    1, ...
    AbsTol=1e-12);

end


function testAllowsVeryDirectionalFields(testCase)

field = reqml.campaigns.materializeNominalAngularField( ...
    RandStream("Threefry", Seed=7401), ...
    [0 0.01], ...
    MaximumDirectionCount=128, ...
    MinimumSolidAngleSr=0.01);

verifyGreaterThan(testCase, ...
    field.nominal_angular_coverage, ...
    0);

verifyLessThanOrEqual(testCase, ...
    field.nominal_angular_coverage, ...
    0.01);

verifyGreaterThanOrEqual(testCase, ...
    field.solid_angle_sr, ...
    0.01);

end


function testRejectsInvalidRange(testCase)

verifyError(testCase, ...
    @() reqml.campaigns.materializeNominalAngularField( ...
        RandStream("Threefry", Seed=1), ...
        [-0.1 0.5]), ...
    "reqml:InvalidNominalAngularCoverageRange");

end
