function tests = test_req_estimator_map

tests = functiontests(localfunctions);

end


function testExplicitCentersPreserveOrder(test_case)

[wavefield, cfg, feat_cfg] = make_fixture();

centers = [
    17, 17
    33, 25
    49, 41
];

out = reqml.estimators.req_estimator_map( ...
    wavefield, ...
    cfg, ...
    feat_cfg, ...
    "CenterIndices", centers, ...
    "ReturnFeatures", false, ...
    "ReturnFeatureTable", true, ...
    "StoreReqCurves", false);

verifyEqual(test_case, height(out.feature_table), 3);
verifyEqual(test_case, out.feature_table.cx, centers(:, 1));
verifyEqual(test_case, out.feature_table.cz, centers(:, 2));

verifyEqual(test_case, out.x_idx, centers(:, 1));
verifyEqual(test_case, out.z_idx, centers(:, 2));
verifyEqual(test_case, out.center_indices, centers);

verifySize(test_case, out.q_map, [3, 1]);
verifySize(test_case, out.cs_map, [3, 1]);
verifySize(test_case, out.valid_map, [3, 1]);

end


function testExplicitCentersRejectDuplicates(test_case)

[wavefield, cfg, feat_cfg] = make_fixture();

centers = [
    17, 17
    17, 17
];

verifyError(test_case, ...
    @() reqml.estimators.req_estimator_map( ...
        wavefield, ...
        cfg, ...
        feat_cfg, ...
        "CenterIndices", centers, ...
        "ReturnFeatures", false, ...
        "StoreReqCurves", false), ...
    "reqml:DuplicateCenterIndices");

end


function testExplicitCentersRejectOutOfBounds(test_case)

[wavefield, cfg, feat_cfg] = make_fixture();

centers = [
    4, 4
    33, 33
];

verifyError(test_case, ...
    @() reqml.estimators.req_estimator_map( ...
        wavefield, ...
        cfg, ...
        feat_cfg, ...
        "CenterIndices", centers, ...
        "ReturnFeatures", false, ...
        "StoreReqCurves", false), ...
    "reqml:CenterIndicesOutOfBounds");

end


function testExplicitCentersRejectNonIntegerValues(test_case)

[wavefield, cfg, feat_cfg] = make_fixture();

centers = [
    17.5, 17
    33, 33
];

verifyError(test_case, ...
    @() reqml.estimators.req_estimator_map( ...
        wavefield, ...
        cfg, ...
        feat_cfg, ...
        "CenterIndices", centers, ...
        "ReturnFeatures", false, ...
        "StoreReqCurves", false), ...
    "reqml:InvalidCenterIndices");

end


function testDefaultRegularGridStillWorks(test_case)

[wavefield, cfg, feat_cfg] = make_fixture();

out = reqml.estimators.req_estimator_map( ...
    wavefield, ...
    cfg, ...
    feat_cfg, ...
    "StepX", 16, ...
    "StepZ", 16, ...
    "ReturnFeatures", false, ...
    "ReturnFeatureTable", true, ...
    "StoreReqCurves", false);

expected_x = 9:16:57;
expected_z = 9:16:57;

verifyEqual(test_case, out.x_idx, expected_x);
verifyEqual(test_case, out.z_idx, expected_z.');
verifyEqual( ...
    test_case, ...
    height(out.feature_table), ...
    numel(expected_x) * numel(expected_z));

verifySize( ...
    test_case, ...
    out.q_map, ...
    [numel(expected_z), numel(expected_x)]);

end


function [wavefield, cfg, feat_cfg] = make_fixture()

nz = 65;
nx = 65;

dx = 0.5e-3;
dz = 0.5e-3;
frequency_hz = 500;
cs_m_s = 2.0;

[x, z] = meshgrid( ...
    (0:(nx - 1)) * dx, ...
    (0:(nz - 1)) * dz);

wavenumber_rad_m = 2*pi*frequency_hz/cs_m_s;

wavefield = ...
    exp(1i*wavenumber_rad_m*x) + ...
    0.35*exp(1i*wavenumber_rad_m*( ...
        0.6*x + 0.8*z));

cfg = struct();
cfg.dx = dx;
cfg.dz = dz;
cfg.f0 = frequency_hz;
cfg.cs_bg = cs_m_s;
cfg.WaveModel = "unit_test";

feat_cfg = reqml.config.default_feature_config( ...
    "M", 2, ...
    "cs_guess", cs_m_s, ...
    "win_size", 17, ...
    "pad_factor", 1);

end
