function tests = test_run_adaptive_iteration
%TEST_RUN_ADAPTIVE_ITERATION Test accumulated adaptive iteration workflow.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testRejectsMissingCampaignCsv(testCase)

feat_cfg = struct();
campaign_config = struct();

verifyError(testCase, ...
    @() reqml.campaigns.runAdaptiveIteration( ...
        "missing_campaign.csv", ...
        feat_cfg, ...
        campaign_config, ...
        OutputDirectory=string(tempname), ...
        IterationId="iteration_test", ...
        PlannerSeed=1, ...
        PurityEdges=[0.5 1.0], ...
        DiffusivityEdges=[0 1], ...
        SwsEdges=[1.5 4.0], ...
        FrequencyEdges=[199 601]), ...
    "reqml:AdaptiveIterationCampaignCsvNotFound");

end
