function tests = test_final_center_packing
%TEST_FINAL_CENTER_PACKING Test production relationship-aware packing.
tests=functiontests(localfunctions);
end

function setupOnce(~)
root=fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(fullfile(root,"src"));
end

function testPackingAwareCenterUsesTangentialEdge(testCase)
p=reqml.campaigns.computePackingAwareBilayerCenter(55,[.0005 .0005], ...
    InterfaceOrientation="x",DomainPolicyMode="adaptive_for_center_packing");
verifyEqual(testCase,p.selected_domain_size_m,[.05 .05]);
verifyFalse(testCase,p.expansion_required);
verifyEqual(testCase,p.selected_patch_center_indices_xz,[51 28]);
verifyGreaterThanOrEqual(testCase, ...
    p.maximum_geometrically_packable_center_count,2);
end

function testDomainExpandsOnlyWhenRequired(testCase)
large=reqml.campaigns.computePackingAwareBilayerCenter(91,[.0005 .0005], ...
    InterfaceOrientation="x",DomainPolicyMode="adaptive_for_center_packing");
verifyTrue(testCase,large.expansion_required);
verifyEqual(testCase,large.selected_domain_size_m,[.07 .07]);
verifyEqual(testCase,large.selected_patch_center_indices_xz,[71 46]);

without_extra=reqml.campaigns.computePackingAwareBilayerCenter(91, ...
    [.0005 .0005],InterfaceOrientation="x", ...
    DomainPolicyMode="adaptive_for_center_packing", ...
    RequireAdditionalUsefulCenter=false);
verifyFalse(testCase,without_extra.expansion_required);
verifyEqual(testCase,without_extra.selected_domain_size_m,[.05 .05]);
end

function testTangentialTranslationPreservesDiscretePurity(testCase)
center=reqml.campaigns.computeBilayerInterfacePlacement([.9 .98], ...
    [55 55],[.0005 .0005],[51 51],[.05 .05], ...
    InterfaceOrientation="x",DominantMaterialSide="negative");
packed=reqml.campaigns.computeBilayerInterfacePlacement([.9 .98], ...
    [55 55],[.0005 .0005],[51 28],[.05 .05], ...
    InterfaceOrientation="x",DominantMaterialSide="negative");
verifyEqual(testCase,packed.predicted_discrete_purity, ...
    center.predicted_discrete_purity,AbsTol=0);
verifyEqual(testCase,packed.interface_offset_pixels, ...
    center.interface_offset_pixels);
verifyEqual(testCase,packed.interface_position_m, ...
    center.interface_position_m,AbsTol=1e-15);
end

function testRelationshipSpecificSeparations(testCase)
[truth,state,target,edges]=selector_fixture();
r=reqml.datasets.selectDeficitAwareCenters(truth,9,state,target, ...
    PurityEdges=edges.purity,DiffusivityEdges=edges.dnom, ...
    SwsEdges=edges.sws,FrequencyEdges=edges.frequency, ...
    FrequencyHz=220,Dnom=.02,CandidateStepPixels=2, ...
    MaximumCentersPerRun=12,MaximumCentersPerCellPerRun=2, ...
    SeparationPolicy="relationship_aware", ...
    AnalyticToOpportunisticSeparationFraction=.25, ...
    DifferentCellSeparationFraction=.25, ...
    SameCellSeparationFraction=.5,DeterministicSeed=9);
c=r.centers;
for i=2:height(c)
    for j=1:i-1
        distance=hypot(c.cx(i)-c.cx(j),c.cz(i)-c.cz(j));
        if j==1
            required=.25*9;
        elseif c.achieved_cell_key(i)==c.achieved_cell_key(j)
            required=.5*9;
        else
            required=.25*9;
        end
        verifyGreaterThanOrEqual(testCase,distance,required);
    end
end
verifyEqual(testCase,c.center_selection_role(1),"analytic_target");
end

function testExplicitUniformPolicyPreservesV4Default(testCase)
[truth,state,target,edges]=selector_fixture();
defaults=reqml.datasets.selectDeficitAwareCenters(truth,9,state,target, ...
    PurityEdges=edges.purity,DiffusivityEdges=edges.dnom, ...
    SwsEdges=edges.sws,FrequencyEdges=edges.frequency, ...
    FrequencyHz=220,Dnom=.02,CandidateStepPixels=2, ...
    MaximumCentersPerRun=12,MaximumCentersPerCellPerRun=2, ...
    MinimumCenterSeparationFraction=.75,DeterministicSeed=9);
explicit=reqml.datasets.selectDeficitAwareCenters(truth,9,state,target, ...
    PurityEdges=edges.purity,DiffusivityEdges=edges.dnom, ...
    SwsEdges=edges.sws,FrequencyEdges=edges.frequency, ...
    FrequencyHz=220,Dnom=.02,CandidateStepPixels=2, ...
    MaximumCentersPerRun=12,MaximumCentersPerCellPerRun=2, ...
    SeparationPolicy="uniform",MinimumCenterSeparationFraction=.75, ...
    AnalyticToOpportunisticSeparationFraction=.01, ...
    DifferentCellSeparationFraction=.01, ...
    SameCellSeparationFraction=.01,DeterministicSeed=9);
verifyEqual(testCase,explicit.centers,defaults.centers);
end

function [truth,state,target,e]=selector_fixture()
[X,~]=meshgrid(1:41,1:41);
truth.material_id_zx=uint16(X>21);
truth.cs_m_s_zx=1.75*ones(41); truth.cs_m_s_zx(X>21)=2.75;
truth.valid_mask_zx=true(41);
e=struct("purity",[.5 .7 .9 .98 1],"dnom",[0 .01 .05 1], ...
    "sws",[1.5 2 2.5 3],"frequency",[199 300]);
empty=table(zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),VariableNames=[ ...
    "sws_bin","frequency_bin","purity_bin","diffusivity_bin", ...
    "example_count","independent_run_count","independent_condition_count"]);
summary=reqml.coverage.completeCoverageGrid(empty,e.sws,e.frequency, ...
    e.purity,e.dnom);
state=reqml.coverage.findCoverageDeficits(summary,MinimumExamples=4, ...
    MinimumIndependentRuns=2,MinimumIndependentConditions=1,IncludeComplete=true);
target=struct("center_indices_xz",[17 21], ...
    "requested_cell_key","s01_f01_p04_d02", ...
    "predicted_discrete_purity",1);
end
