function tests = test_assign_coverage_bins
%TEST_ASSIGN_COVERAGE_BINS Test patch-level coverage assignment.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testAssignsExpectedBins(testCase)

examples = make_examples();

assigned = reqml.coverage.assignCoverageBins( ...
    examples, ...
    PurityEdges=[0.5 0.7 0.9 1.0], ...
    DiffusivityEdges=[0 0.4 0.7 1.0], ...
    SwsEdges=[1.5 2.5 3.5 4.1], ...
    FrequencyEdges=[199 350 450 601]);

verifyEqual(testCase, ...
    assigned.coverage_purity_bin, ...
    [1; 2; 3; 3]);

verifyEqual(testCase, ...
    assigned.coverage_diffusivity_bin, ...
    [1; 2; 3; 3]);

verifyEqual(testCase, ...
    assigned.coverage_sws_bin, ...
    [1; 1; 2; 3]);

verifyEqual(testCase, ...
    assigned.coverage_frequency_bin, ...
    [1; 2; 3; 3]);

verifyEqual(testCase, ...
    assigned.coverage_cell_key, ...
    compose( ...
        "s%02d_f%02d_p%02d_d%02d", ...
        assigned.coverage_sws_bin, ...
        assigned.coverage_frequency_bin, ...
        assigned.coverage_purity_bin, ...
        assigned.coverage_diffusivity_bin));


verifyTrue(testCase, all(assigned.coverage_valid));

verifyEqual(testCase, ...
    assigned.coverage_purity_label(1), ...
    "[0.5,0.7)");

verifyEqual(testCase, ...
    assigned.coverage_purity_label(4), ...
    "[0.9,1]");

end


function testMarksOutOfRangeExamplesInvalid(testCase)

examples = make_examples();
examples.truth_material_purity(1) = 0.3;

assigned = reqml.coverage.assignCoverageBins( ...
    examples, ...
    PurityEdges=[0.5 0.7 0.9 1.0], ...
    DiffusivityEdges=[0 0.4 0.7 1.0], ...
    SwsEdges=[1.5 2.5 3.5 4.1], ...
    FrequencyEdges=[199 350 450 601]);

verifyEqual(testCase, assigned.coverage_purity_bin(1), 0);
verifyFalse(testCase, assigned.coverage_valid(1));


verifyEqual(testCase, ...
    assigned.coverage_cell_key(1), ...
    "out_of_range");
verifyEqual(testCase, ...
    assigned.coverage_purity_label(1), ...
    "out_of_range");

end


function testRejectsMissingVariable(testCase)

examples = make_examples();
examples.campaign_angular_entropy = [];

verifyError(testCase, ...
    @() reqml.coverage.assignCoverageBins( ...
        examples, ...
        PurityEdges=[0.5 1.0], ...
        DiffusivityEdges=[0 1], ...
        SwsEdges=[1.5 4.1], ...
        FrequencyEdges=[199 601]), ...
    "reqml:MissingCoverageVariable");

end


function testUsesNominalAngularCoverageWhenRequested(testCase)

examples = make_examples();

examples.campaign_direction_count = [1; 16; 32; 128];

examples.campaign_solid_angle_sr = [
    0.01
    pi
    4*pi
    4*pi
    ];

assigned = reqml.coverage.assignCoverageBins( ...
    examples, ...
    FieldCoverageMode="nominal", ...
    PurityEdges=[0.5 0.7 0.9 1.0], ...
    DiffusivityEdges=[0 0.01 0.05 0.20 0.50 1.0], ...
    SwsEdges=[1.5 2.5 3.5 4.5], ...
    FrequencyEdges=[199 350 500 601]);

expected_dnom = [
    (1/128) * (0.01/(4*pi))
    (16/128) * (pi/(4*pi))
    32/128
    1
    ];

verifyEqual(testCase, ...
    assigned.nominal_angular_coverage, ...
    expected_dnom, ...
    AbsTol=1e-12);

verifyEqual(testCase, ...
    assigned.coverage_diffusivity_bin, ...
    [1; 2; 4; 5]);

verifyEqual(testCase, ...
    assigned.coverage_diffusivity_label, ...
    ["[0,0.01)"; ...
     "[0.01,0.05)"; ...
     "[0.2,0.5)"; ...
     "[0.5,1]"]);

end


function examples = make_examples()

examples = table();

examples.truth_material_purity = ...
    [0.55; 0.75; 0.95; 1.00];

examples.campaign_angular_entropy = ...
    [0.20; 0.50; 0.80; 0.95];

examples.truth_cs_center_m_s = ...
    [1.8; 2.2; 3.0; 4.0];

examples.campaign_frequency_hz = ...
    [200; 400; 500; 600];

examples.campaign_run_id = ...
    ["run_1"; "run_1"; "run_2"; "run_3"];

end
