function tests = test_discrete_req_theory
%TEST_DISCRETE_REQ_THEORY Validate active discrete REQ theory models.

tests = functiontests(localfunctions);

end

function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end

function testSingleWaveProducesValidQuantile(testCase)

out = compute_theory("SingleWave");

verifyTrue(testCase, out.valid);
verifyEqual(testCase, out.field_type, "SingleWave");
verifyTrue(testCase, isfinite(out.q_theory_discrete));
verifyGreaterThanOrEqual(testCase, ...
    out.q_theory_discrete, 0);
verifyLessThanOrEqual(testCase, ...
    out.q_theory_discrete, 1);
verifyEqual(testCase, ...
    out.q_single_wave_discrete, ...
    out.q_theory_discrete);
verifyTrue(testCase, ...
    isnan(out.q_diffuse3d_discrete));

end

function testDiffuse3DProducesValidQuantile(testCase)

out = compute_theory("Diffuse3D");

verifyTrue(testCase, out.valid);
verifyEqual(testCase, out.field_type, "Diffuse3D");
verifyTrue(testCase, isfinite(out.q_theory_discrete));
verifyGreaterThanOrEqual(testCase, ...
    out.q_theory_discrete, 0);
verifyLessThanOrEqual(testCase, ...
    out.q_theory_discrete, 1);
verifyEqual(testCase, ...
    out.q_diffuse3d_discrete, ...
    out.q_theory_discrete);
verifyTrue(testCase, ...
    isnan(out.q_single_wave_discrete));

end

function testPartialDiffuseIsMeanOfFundamentalQuantiles(testCase)

single_wave = compute_theory("SingleWave");
diffuse_3d = compute_theory("Diffuse3D");
partial = compute_theory("PartialDiffuse3D");

expected = 0.5 * ( ...
    single_wave.q_theory_discrete + ...
    diffuse_3d.q_theory_discrete);

verifyTrue(testCase, partial.valid);
verifyEqual(testCase, ...
    partial.field_type, ...
    "PartialDiffuse3D");

verifyEqual(testCase, ...
    partial.q_single_wave_discrete, ...
    single_wave.q_theory_discrete, ...
    AbsTol=1e-12);

verifyEqual(testCase, ...
    partial.q_diffuse3d_discrete, ...
    diffuse_3d.q_theory_discrete, ...
    AbsTol=1e-12);

verifyEqual(testCase, ...
    partial.q_theory_discrete, ...
    expected, ...
    AbsTol=1e-12);

verifyEqual(testCase, ...
    partial.q_th, ...
    expected, ...
    AbsTol=1e-12);

end

function testAcceptsNumericNbins(testCase)

out = reqml.theory.q_theory_REQ_discrete_shearUZ( ...
    0.0005, ...
    0.0005, ...
    500, ...
    3.0, ...
    M=2, ...
    Nbins=64, ...
    FieldType="SingleWave", ...
    Plot=false);

verifyTrue(testCase, out.valid);
verifyEqual(testCase, numel(out.k_cent), 64);

end

function testRejectsInvalidNbins(testCase)

verifyError(testCase, ...
    @() reqml.theory.q_theory_REQ_discrete_shearUZ( ...
        0.0005, ...
        0.0005, ...
        500, ...
        3.0, ...
        Nbins="invalid", ...
        Plot=false), ...
    "reqml:InvalidTheoryNbins");

end

function testRejectsUnknownFieldType(testCase)

verifyError(testCase, ...
    @() compute_theory("UnknownField"), ...
    "reqml:InvalidTheoryFieldType");

end

function out = compute_theory(field_type)

out = reqml.theory.q_theory_REQ_discrete_shearUZ( ...
    0.0005, ...
    0.0005, ...
    500, ...
    3.0, ...
    M=2, ...
    Gamma=1, ...
    PadFactor=1, ...
    Nbins="auto", ...
    SmoothSigma=1, ...
    FieldType=field_type, ...
    TheoryMode="S2D", ...
    Plot=false);

end
