function tests = test_req_readiness_framework_equivalence
%TEST_REQ_READINESS_FRAMEWORK_EQUIVALENCE
% Compare REQ-ML readiness with the historical framework implementation.

tests = functiontests(localfunctions);

end

function setupOnce(testCase)

reqml_root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

framework_root = ...
    "/Users/sara/local/shear-wave-simulation-framework";

addpath(fullfile(reqml_root, "src"));

assumeTrue(testCase, ...
    isfolder(fullfile(framework_root, "src")), ...
    "Local simulation framework source was not found.");

addpath(fullfile(framework_root, "src"));

testCase.TestData.framework_src = ...
    fullfile(framework_root, "src");

end

function teardownOnce(testCase)

if isfield(testCase.TestData, "framework_src")
    rmpath(testCase.TestData.framework_src);
end

end

function testReportsMatchExactly(testCase)

data = struct();
data.wavefield_zx = complex(ones(30, 30), 0.25);
data.dx_m = 0.5e-3;
data.dz_m = 0.5e-3;
data.frequency_hz = 500;

legacy_sample = struct();
legacy_sample.wavefield_complex_zx = ...
    data.wavefield_zx;

legacy_sample.axes = struct();
legacy_sample.axes.x_m = ...
    (0:29) * data.dx_m;
legacy_sample.axes.z_m = ...
    (0:29) * data.dz_m;

legacy_sample.spacing = struct();
legacy_sample.spacing.dx_m = data.dx_m;
legacy_sample.spacing.dz_m = data.dz_m;

legacy_sample.frequency_hz = ...
    data.frequency_hz;

current = reqml.readiness.assess_req_readiness( ...
    data, ...
    CsGuessMPerS=3.0, ...
    WindowWavelengths=2.0, ...
    MinimumPlacementsPerAxis=5);

historical = kwsim.req.assessValidationSample( ...
    legacy_sample, ...
    CsGuessMPerS=3.0, ...
    WindowWavelengths=2.0, ...
    MinimumPlacementsPerAxis=5);

verifyEqual(testCase, current.valid, historical.valid);
verifyEqual(testCase, current.checks, historical.checks);
verifyEqual(testCase, current.parameters, historical.parameters);
verifyEqual(testCase, current.frequency_hz, historical.frequency_hz);
verifyEqual(testCase, ...
    current.wavelength_guess_m, ...
    historical.wavelength_guess_m);
verifyEqual(testCase, ...
    current.window_length_m, ...
    historical.window_length_m);
verifyEqual(testCase, ...
    current.window_points_x, ...
    historical.window_points_x);
verifyEqual(testCase, ...
    current.window_points_z, ...
    historical.window_points_z);
verifyEqual(testCase, ...
    current.placements_x, ...
    historical.placements_x);
verifyEqual(testCase, ...
    current.placements_z, ...
    historical.placements_z);
verifyEqual(testCase, ...
    current.field_energy, ...
    historical.field_energy);
verifyEqual(testCase, current.summary, historical.summary);

end
